[Hook: Problem]
Drugs, drugs, bitch I’m on drugs

[Verse 1: Problem]
Molly and the weed tho, that’s all I gotta say
When I put my dicks in this hoes
I hope they high as me
Prolly not, fuck it, taxi all in public
Never wanna use it, prolly don’t
If she let me fuck it
Hella burnt turnt like a car going 'round the corner
Won’t change like the coin machine is fucking out of order
Never ever follow orders I make orders follow me
Riding in the ghost got me hella booze
Halloween, me and that clown, no make up
Red velvet in the sky, my cake’s up
Bitch booty sittin high, her cake’s up
2 words I can’t stand lace front
Ha, I'm playing girl you know you fly
Blow me bitch don’t blow my high, what?

[Hook: Problem]
Drugs, drugs, drugs
Bitch I’m on drugs, huh?
Drugs, drugs, drugs
Bitch I’m on drugs, huh?

[Verse 2: Clyde Carson
Zoner, get owner, all cash pink slip, and a loaner
Need something in your mouth I’m a donor
35 racks in my cup holder
Feels for deals my voice give her the chills
I blow a kiss to molly, then she give me the thrill
It’s like a high, just can’t quit
6 in the morning, a nigga still lit
Tell them that I’m living a life you want in
You can mob, long as you understand this and do your job
Sun coming up man she still wanna ride
I don’t like shit but I still wanna drive
Moving lane to lane I got the coupe 2 stepping
Hop out like a young black Hugh Hefner
Fly, fresher, hella weed, bunch of sour on the dresser, huh?

[Hook: Problem]
Drugs, drugs, drugs
Bitch I’m on drugs, huh?
Drugs, drugs, drugs
Bitch I’m on drugs, huh?

[Verse: Berner]
Wake up in the morning, hit the kesha
Right before I head to the weed spot
I dump all 10 then I recup
My liver too shine, need a detox
Why you clear, you that’s coke and criss
I get her drunk as hell then let her choke on dick
I’m breathing slow, heart beating fast
I got cookie for days, your weed is trash
I used to be at school on the jail tab
I made a quarter mill off a meth lab
I brought a 10 pack on the grey hound
I used to be along with the grey pound
I'm on one, xans and a bottle of gyn
Throw a molly in the glass
Make her suck all my friends
Real talk no time for games
I smoke DMT and now I’m seeing thangs
I’m on drugs
Drugs, drugs, drugs