Young dumb fools Here we come
Dragging what's left of our dirty thoughts
We're feeling young and dumb
Because they come Out of nowehre
And without a warning Good morning
Slide out of bed
It's going to take a million cold showers to wash away this mud
We've been slinging
Hey, everyone gets lonely
Even when we're not alone
It can be very scary
Wearing these earth suits
Alien from Mars And Venus came and made this mess
It's no fault of ours
That we're all unclean
She's unclean He's unclean
Just like our mothers and our fathers
And their mothers and their fathers
And their mothers and their fathers
They all died and Have solied themselves
And it leeches up through the roots
To the flowers
Where the birds abd the bees pollinate
The land with toxic shame
Shame begets shame Guilt and shame
Toxic shame End this strain