[Intro]
Its G Herbo, Big G Herbo
Aye

[Verse 1]
I'm that nigga that grew up in all apartment buildings
With my cousins and the rest of my grandmama children
I was the youngest, this was way before I had a sibling
'Member watchin' water from the rain leak through the ceiling
'Member watchin' roaches, rats run off through the kitchen
And my kitchen eased off chicken, you don't know the feeling
From the fucking up the kitchen, bad bitch doin' dishes
Mama know that I'm that nigga, she see how I'm living
'Member calling police station, she thought I was missing
Told her everything gon' be straight but she thought I was tripping
Cause I was posted on the 8, with Pistol totin' missiles
She say when you end up in prison, niggas ain't gon' miss ya
But we ain't like these pussy niggas, my niggas official
Instead they end up in prison and gave me the whistle
Mally said chill on that hot shit and just keep your pistol
For if a nigga want it with me that mean he don't get you

[Sample]

[Verse 2]
I'm that nigga, been that nigga all my life lil' nigga
I only spit the truth I put that on my mic lil' nigga
The difference between me and you, not nothing slight lil' nigga
You waitin' in line, I'm takin' shit we not nothing alike lil' nigga
Settle for less, that's what you got and what's in sight lil' nigga
I dreamed of riding foreign, I was on a bike lil' nigga
You out here flexing tryna stunt for hoes you like lil' nigga
I was up on Essex servin' hypes, you all on Skype, lil' nigga
You bought that bitch a pair of shoes, I bought a pipe, lil' nigga
Ain't never used one, squeezed that bitch with all my might, lil' nigga
Ain't never used one, it was ball or shoot, lil' nigga choose one
Bought my first tool, stopped going to school, now all I keep is new guns
Bought a five shot .38 and went in with my new one's
Now I keep 40 Glocks on me, wake up and bow a few one's
For G-Fazo, I run through ones
On opps, we ran through guns
Young niggas, we was goin' through some
Wakin' up, just to shoot some