[Intro]
Yea yea yea, Yea yea yea
Yea yea yea, Yea yea yea

[Verse 1]
Never needed me a leash
These niggas need me and that's that
To be a hunnid with the truth
These niggas hoe and I'm already knowin'
That ain't nothin' new
Just don't never get attached
They be right here running back
Better listen when I talk
2015
Niggas is niggas, you know how they are
Gotta keep my number two around
Let his mind wonder when you're gone
And if you let it ring for like a couple of times
He'll be thinkin' bout what got you occupied
This money, money, money
Put no nigga before your money
Money, money, money
And that's what had this nigga holdin' on
His ex bitch ain't really comin' strong
He see me rollin' round on my grown shit
I made it real clear that I owns it
It's no fair
(Fair, fair, fair)
Bitch that nigga ain't goin' nowhere
(Where, where, where)

[Pre-Hook]
I'mma turn this boy into a man
One night only (one night only)
Bet he wanna fuck with me again
One night night only (only)

[Hook]
Never needed me a leash
These niggas need me and that's that
Yea yea yea, Yea yea yea
Never needed me a leash
These niggas need me and that's that
Yea yea yea, Yea yea yea
Yea yea yea, Yea yea yea
Yea yea yea, Yea yea yea

[Bridge]
Boy you know I never needed any help
What you can do for me, I can do for myself
No thank you, right about now it ain't too much that I can't do
I'm out here pushin' keys baby
The money's what I need baby
I don't have the time, to commit
I know all the lies, you come with