[Nicki Minaj]
This is for my niggas that did bids
All of my niggas thats doin time for some shit that they ain't did
This is for my niggas that wild out
All of my niggas that ride out, all my niggas that hide out
This is for my niggas that buy weight
Niggas that leave on Monday, come back on a Friday
This is for my niggas that get high all of my niggas that get by
All my niggas that get fly, this is for my niggas that cop dutches
All of my niggas throwin it up on them bikes and pop clutches
This is for my niggas that don't snitchall uh my niggas that don't bitch
All my niggas that tore fifths, this is for my niggas that don't cry
All of my niggas that dont smileall my niggas that don't lie
This is for my niggas that take care, all of they kids
Order some bids, and take em to daycare
This is for my niggas that dont settle
All of my niggas that push pedals,alll my niggas with gold medals
This is for my niggas that play ball, niggas that wanna get in the game
So they niggas can cake off, this is for my niggas that gave up
All of my niggas that's laid up, and ya mind is made up
This is for the borough of Sean Bell (Rest In Peace)
All of my niggas with strong will, all of my niggas that gone kill
This is for my niggas than stand up, all of my niggas that's gon' fight
All my niggas that man up (C'mon), this is for my niggas with big dreams
All of my niggas in sick jeans, that be spittin' they sixteens
This is for the Tims and this is for the Brims and
This is for the Trims and this is for the rims and
This is for the kings and this is for the bosses
This is for the blings and niggas in the porches
This one's for Malcolm, this one's for Martin
Wish I coulda thanks them, look what they started
This is cuz I'm tired of losin' (Tired of losing)
Even though my music is crack, guess I'm tired of using
It's like I'm tired of rappin it, I ain't even ratchet I'm tired
And I'm askin am I, ready for the rapture?
See, I'm just a little girl, caught in a mixed up world
Shoutout my girls, that be callin me sista girl
A moment of silence, for all of this violence
For all of my men's that's locked in the pens, and trapped in the silence

[Angel De Mar]
I aee you, I see you, I see you, I see you, I seee youu
I see you, I see you, I see you, I see you, I seeee youuu

Keep trying
Kee-eep tryy-yinnn'