(Young Chop on the beat!)

[Verse 1 - Kassa Overall]
C.R.E.A.M. rap - rapping over the, uh, the beat C.R.E.A.M (Cash rules everything around me)
Sprite get dirty behind the counter
Cats get murdered behind the money counter
They never found her
Liquor get thin and the weed get browner
Love the most high, but I need to get a downer
Started from the bottom, even with a founder(?)
Only settle for gold medals, I fold metals with alchemy
Still left a blunt on the balcony
And I still let your main girl talcum me
Keep riding till Farrakhan Malcom me
Seattle hip-hop like Alpha P
You probably wouldn't get the reference
Still pimped out like a golden pheasant
I'm more than pleasant, Justin Bieber but more depressed
You can see in the drink(?) that I'm sort of blessed
In competition but watch for the wrestler(?)
They carrying scripts, American as Bavarian crisps
Apple didn't come from the tree
Kill off the natives when they come from the sea
They ain't fucking with the G

[Verse 2 - Kool A.D.]
Whoa, whoa, whoa
I slap the apple out your Macintosh
I slap the Mac Miller out your Asher Roth
And then I'll walk into the Apple store
And smack the Marshall Mathers out your motherfucking Macklemore
(Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all)
Once again though, I slap the apple out your Macintosh
Then I slap the Mac Miller out your Asher Roth
And then I'll walk into the Apple store
And smack the Marshall Mathers out your motherfucking Macklemore
Kool A.D. is the best white rapper
Who's asking and why you asking for?
I'm rapping awesome, I slap the Bubba Sparxxx out your Action Bronson
Rob 50 Cent and do a Kendrick Lamar diss track
Over the "Benjamins" beat, and then friend him and tweet links to my Bandcamp
Then send him a link to the Homeboy Sandman bandcamp
Or maybe it was Soundcloud
Oops, I don't even... did I even say that out loud?
I'm the best rapper in the world, I give a fuck if you believe me
You probably suck and your ho a breezy
I could probably fuck your ho easy
I don't even know who I'm shitting on specifically
Fuck it, I just mean to say I'm literally
The best rapper, I'm the less black Wiz Khalifa
But fatter and more laughter
Leave them at the freestyle cypher with sore bladders
Get on my level, man you're gonna need more ladders
Either that or just a ladder that's forever
I'm damaging competters, I mean competitors, whatever
Like, I feel like Bennifer from the "Jenny from the Block" video
But more pretty though
How come Drake say he started from the bottom, but, um, he really didn't though?
(Maybach Music!)
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all
Cash rules everything around me, C.R.E.A.M
Get the money, dollar dollar bill y'all

[Verse 3 - Kassa Overall]
Oh wait, more bars! (Maybach Music!)
Vapes in the basement, ace in the spaceship
Face in the facelift, dogs in the spaceship
(?), taste grip, take money, get money
Wall Street journalism, rhythm of the fake money
Penny stack necklaces, five-star breakfastses
Bordeaux in Bordeaux, Gordo in Gordo(?)
Tapping to the porno, laughing when the score low
Rich but I'm so poor though