DJ Unknown & DJ Mekalek ft. Percee P and Rok One - “T.O.N.Y. C.R.E.A.M.”
[Emcee(s): Percee P and Rok One]
[Producer(s) of Instrumental 1: RZA (Original Instrumental from Wu-Tang Clan (ft. Raekwon, Method Man, and Inspectah Deck) - "C.R.E.A.M.")]
[Producer(s) of Instrumental 2: [?]]
[Producer(s) of Instrumental 3: Carlos "Six July" Broady and Nashiem Myrick (Original Instrumental from Capone-N-Noreaga ft. Tragedy Khadafi - "T.O.N.Y. (Top of New York)")]
[DJ Mix: DJ Unknown and DJ Mekalek]
[Scratches: DJ Unknown and DJ Mekalek]

[Intro: Percee P]
Yeah, yeah.  Uh.  It’s The Monarch of the Subterranean, Legendary Lethal Lyricist, The Rhyme Inspector Percee P.  Straight out the BX, y’all.  Representing for my man DJ Unknown and DJ Mek (Uh huh).  A lethal, cerebral verse for the people.  Check it out.  And here’s the sequel.  Uh.  Check it

[Verse 1: Percee P]
What I state’s a blessing.  Can’t make a session?  Tape your lessons
Scrape the best and give ‘em hard times like the Great Depression
Adversaries, bring your crew.  I do bury singers, leave
Every finger broke like guests on Jerry Springer.  What I write
Hits you like ripple, hard like your wife nipple, sharp as i-
-cicles.  Fisher Price fit you when those on the mic switch you
Believe me, you’ll see me up like I'm a graffiti artist
Hot as Tahiti, rob a tail—the streets are Cabrini (Are dimes near?)
I’ll step up like you climb stairs if the sign's clear.  All
Lines here get across East to West like shuttles at Times Square
Turf BX.  Scorn kids, leave their borns with
Birth defects.  Uh, mics fell from my
Delivery of soliloquys.  I’m deadly as killer bees
But more iller, G, got you feeling me like Braille
The ebony one that sever the brain and never need melodies
Cleverly, I’ll drop bombs heavily like I'm Lebanese
Copping dap overseas, shocking Japs.  I'm topping that wack shit you
Popping, black.  Dropping raps/wraps on heads as tight as stocking caps
I’ll hit thighs and rip guys.  Clones bit my styles to get by
Gimmicks limit their thoughts and resort to get hotter than lye
See, what?  You vs. me?  Go first, G.  Disperse
B.  You like Hershey’s mixed with Percee P nuts
Like rat traps, I’ll snap, jack, and backslap all you
Wack acts whose tracks lack and that’s that
Gigolo with the slicker flow, and niggas know, when
It’s the show, whose shit’ll blow and get played like a piccolo
[?].  Still, I get bills
[?] with my hip skills (Lose what?)
I’ll make born-again women wanna sin.  Battles I’m gonna
Win.  I’ll perform and then turn to the cornermen bruised up
Ladies, gentlemen, kin, and friends rush like adren-
-aline to hear next millennium shit from begin to end
My thoughts are catchy.  I’ll sell like a fiend had bought the crack, G.  Those
Supporting rap, B, ought to back me from the Bronx, Fort Apache

[Interlude 1: Percee P and Rok One]
Percee P: Yeah, shout-outs to the Jurassic 5, Lootpack, and everybody at Stones Throw, everybody around the way at Patterson Projects to the rest of the world that respects me and my style of hip hop.  My man Barney Kulok.  Ayyo, Rok One, rip that
Rok One: No doubt Perc’.  Yo, Mek, turn me up.  Uh huh.  Yeah.  Ayyo

[Verse 2: Rok One]
Rappers talk about all the crimes they commit
But their only is all those wack rhymes that they spit.  Man
You claim you keep it gutter and thug.  I asked about you on
The street.  People just looked at each other and shrugged like you ain’t
Busting no slugs or hustling drugs.  Before Jay
Dropped, you ain’t even know what hustling was
You don’t pole bitches up at the club.  Look at your mug, man
You got the type of face only a mother could love, so stop
Fronting and stop lying (Stop it).  You’re not thugging
So stop trying.  You fucks ain’t never cocked iron (Nah)
Ain’t never seen shots flying (Nope) or Glocks firing (Uh uh)
I’ll make brothers duck like when they hear a cop siren (Jeah)
I’ll brandish the heat and spray off on y’all.  My raps
Tear through the air and ricochet off walls or pene-
-trate through flesh and skin.  Your vest is thin
Like a bitch on Dexatrim.  Now let’s begin.  I’ll enter
Through your midsection and switch directions
Rip intestines, disconnect your limbs.  You’re deaded
In a split second for disrespecting
A Smith & Wesson messing up your sweats and Timbs.  I’ll hit
Your next of kin and the man next to him at
Confusion speeds that’ll make your head spin (Whoo!)
I’ll chop cats in half and cross-section men, throw
The noose around your neck and chin and stuff a live hand
Grenade down your throat and eject the pin
And watch your body get torn to shreds from within (Boom!)
Hah.  Blood pouring from your chest to your shins.  You wanna
Contest the best, but I’m destined to win
And your chances are extra slim like finding cheap
Rent on 86th Street and Lexington, so just
Drop the microphone and jet, ‘cause me, Unknown
And Mek’ll give you an ass-whipping you won’t forget
It’s Rok One