[Verse 1]
I can tell you diggin’, diggin’, you diggin’ me
You are – jewelry on, the furniture from Italy
Aw shit, I ate Sicilians in Sicily (I did)
I’m from the block of villans, millions and mysteries
Pounds, unloadin’ it, price low, they throwin’ it
No choice but go in it ’cause everybody pro in it
Flossin’ we showin’ it, Vegas we blowin’ it
Cases, I aced the cleaners, we sawin’ shit
Toughest, remember this: grimy is what grimy does
I thought about it, know who y’all remind me of (who that?)
Pat Ewing, Charles Barkley, Karl Malone, John Stockton…
John Stockton, Chris Webber, Reggie Miller
Homie, you ain’t win a chick never
Sharp cheese – thick cheddar
Turn my back on Lennox? Bitch, never
Had to let ‘em know my ship is unsinkable
Character, who you are?
Reputation, what they think of you?
Everybody like “yo Cam, let me drink with you, link with you”
I don’t stick to you ’cause I ain’t do the clink with you
Shit – and these bullets, you can drink a few
I did links, minks, one wink to get at you
Don’t matter if you a senator, principal, sentinel
New school conventional,hood nigga presentable
Criminal, general, take your vitamins, minerals
All identical, we’ll leave you like you Benadryl
Spend a mill’, make five, intend to kill any real
Nigga wannabe,let me know, ho, I’m on the skills