[Intro]
Yeah, Lord Infamous back in this thang
The scarecrow, Keyser Soze
You know in Memphis, we got this lil saying
When somebody tryna cross then flodgin, high cappin'
We got this lil thing we call OV nigga, that means its over

[Verse 1]
Fuck with this super thug and get drug
Sweep your bodyparts under the rug
Burry this butcher knife deep in yo guts
Make you a nice warm blanket of mud
You fools ain't learned to see the rear burn
Hollowpoint hit you so hard your body turned
You have been advised don't fuck with wise guys
Hypnotize Rydaz 4,5 clips surprise
I know your click is full of wussies
When you walk by you smell like pussies
You niggas ain't killa to fuck with Godzilla
Monsters, Villans for real and cap peelaz
Perpetrate, tough, and get fucked up quick
Whipped like a bitch and shot in the dick
Infamous, And your neck I will Squeeze boy
Come play with me, you'll see its OV, Over

[Hook]
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV

[Verse 2]
So all you niggas join gangs because your weak alone
Catch you by yo self yo ass ol' get gone
Run up in the door high jack you in yo home
Tie your ass up and beat ya wit the phone
You don't wanna feel the force of the tone
Smack ya in the face and crack your jaw bone
Hit this cocaine and do yo ass wrong
Like a 1 in 1, put 2 to yo dome
Glock, Smith and Wessen, Luger and Ruger
Will make sure you have no future
Cock back the hammer and close your pupils
Lord with the sword is very crucial
Hands in the air yo ass best not move
Don't make me walk on yo ass with these boots
Lord of the hood, I got the crossbolt
Bullseye bitch arrow in yo throat

[Hook]
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV

[Verse 3]
Beat, Rob, Break, Murder, Erase
Don't run, there-is-no-escape
Bullets-hit-you right in the face
Im-not-scared-to catch a case
Slugz, hoes, blood- all on yo clothes
Who'll die next
Nobody Knows
Insain- mane -takin a drain
Bitch I-will-empty-yo veins
I -do -not -feel -no- remorse
Blow-your-mammy ass off the porch
Slap-yo-punk-ass-all-around
You-got-2 days-to leave town
Niggas-got-they-dick in the dust
Style-kick-and shot the fuck up
45s, 9s, and the grenades
Blow-yo-bitch-right off the stage

[Hook]
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV
Wanna run up on me its OV
Test the H C to the P its OV
Get these bullets on GP it's on me
Better drop down to your knees its OV

[Outro]
OV Nigga, Over
OV Nigga, Over
OV Nigga, Over
OV Nigga, Over