[Chorus: Danny Boy]
She’s too street for T.V
And the streets know she keeps it true
That she’s a bad girl
But if you can’t keep it gangsta
Then she’s too street for you
And wherever she goes I know
She gon’ handle business but she gon’ lay low
But I’ma be your witness
I get down with a quickness

[Verse 1: Left Eye (N.I.N.A.)]
How many times must I tell ya’ll
The niggas ain’t no fuckin’ for free
Then keep it real and pay my bills
If you want next to me
I got my mind on presiduous missions
So pay attention so pay a visit
I only feel it when a thug hit it
And I’m L-E-F-T to the E-Y-E
And I’m from Tha Row
Mixed with a little T-L-C
So if you ain’t 2 proud 2 beg
Then holler at it
But it ain’t no guarantee
That you gon’ spread these legs
Cuz it’s all about connectin’ dots
Perfectin’ spots
And I ain’t sittin’ on it if your shit ain’t hot
So clear the way and lay the red carpet
Lets get it started
And I’m hotter than 99 percent of all artists
So you don’t have to hate on me
Pretty brown skin intellect and sexy
And in my world I’m the best to me
And I always got love for these gangsta streets

[Chorus: Danny Boy]

[Verse 2: Left Eye (N.I.N.A.)]
Baby I put it down from Compton to Bed Stuy
These skeez contest my flow
But they can’t go
With Lisa Left Eye Lo
You easy give it your best try
No-body can see me
When I’m with Tha West Side Row
They wanna know how long can it last
I oughtta keep my name hotter than volcanic ash
I gotta push weight more copies than Santana
Spot me in Hotlanta
With papi’s in bandanas
And I pull up with televisions and dubs
At the club in front of them jealous pigeons and scrubs
Chickens please kill the drama
Don’t make me pass by
And splash puddles of water on your Prada little mama
See I don’t trip on none of you haters for this reason
Got more hits than Barry Bonds’ best season
Please believe me I’m too street for T.V
And it’s gonna take more than you industry bitches to see me

[Chorus: Danny Boy]

[Verse 3: Left Eye (N.I.N.A.)]
Check it out
I’m too street with two heats
In new feet I’m too sweet
Say you wanna touch
But tell me how much can you eat
Complete from the concrete
Mystery to Bombee
Burn up the sheet
Whenever my pen and my palm meet
Sex symbol nimble makin’ roughnecks tremble
Get clowned if you need a rubber and little like a thimble
I need a born kitty beater
LA city reader
Be the titties on
He’s sprung once I left did he do ’em
But I’ma do him exactly how he’s supposed to be done
Got my roaster in the holster just stay close to me son
T.V. don’t wanna see me cuz I’m way beyond P.G
Freaky still creepin’ Left Eye stay sneaky
In the district where the light’s red
Where the sight spread over these other bitches just now
I’m meetin’ Mr. Nice Bread
Go ahead please remember everything that I said
I’m the best with the burner in the booth or in the bed

[Chorus: Danny Boy]

[Outro: Danny Boy]
She’s too street 4 T.V. (oh)
Too gangsta for most
But just enough for Tha Row (most)
But just enough for Tha Row
Yeah yeah
Mmmm mmmm
Hey baby