(Intro)
Yeah we getting it, man it’s Yamine let’s go!
(yyyyamine with the hook bruh)

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [Fuck with a nigga bitch cummin’ down on her
Lights]{mhmmm} (repeat 2xs)

(Hook)  (background vocals mhmmmm)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT (repeat)

(Verse 1) (background Vocals mhmmmm)
Bitch you know when I’m rollin dice (yeah)
I’m rollin for our life (uh)
The type we have in the night (stars)
Fuck you hard to the light (fuck it, fuck it)
Nobody fucking cares (never)
As long as it’s right (right)
I’m doing it and not being selfish (selfish)
Everything ends up in hell
I call it hellish
All the Heat
The heat that comes with Machines
The ones up in my dreams
Not the ones in the beams
Not all of GTA scenes
Yeah
I got it

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [I’m getting it, I’m getting it, yeah yeah yeah]
{mhmmmm}(repeat 2xs)

(Hook)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT (repeat)[Yamine cummin all over her kitties
Haha let’s go!]

(Verse 2) (background vocals mhmmm)
Walked up to her house right away she sees me (hi!
Sniffs to the snippet alarms are my crickets (chirp chirp)
Bitches loving dicking, then listens to my rock (penis)
Big hard bolder no call it my COCK (shocked)
Museum up awards for the biggest dick (shit)
Shit, I’m up in Hall Of Fame
For how much I stick it in (true)
They get sick to the stomach while they loving on me (man)
All the heat I receive from this room is because of me BITCHES (yeah)

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [hot, cold, heat, bold, get bucked, fucked the
Duck, love it, love the heat.] {mhmmmm}(repeat 2xs)

{interlude: Project Pat Sippin on some Syrup VOCALS)
Sippin on some syrup, sip, sip, sippin' on some syrup (repeat)

(Verse 3) (background vocals mhmmmm)
DH know dat
Just like Kodak (ooh)
Watch Kung Fu Panda
Jack Black (KUwang)
I don’t shoulder bump pussies
I let rookies get no cap (head)
All of these amateurs bringing the heat up my back (hot)
Too hot to have a hat but too cold to have a real dad (sweatin deadbeat)
Left right, left right, all summer no flights
WE CANCELLED
Stuck in the dessert and we living free of cancer (yeah)
Yeah yeah
I be with my niggas to the real life (ooh)
I be with my niggas is real life (wah)
I be with the niggas, my niggas, my niggas, my niggas, my niggas, my niggas
Fucking that pussy call it real tight (yeah)
That’s my right
To do nifes
Shit

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [yeah, yeah, yeah, yeah, yeah. Here we go
Boy] {mhmmmm}(repeat 2xs)

(Hook)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT (repeat)[yeah straight fire again)

(Verse 4)
I got the hammer
It’s so hot call it Hammer
I belong in the slammer
Shut me down like Mc Hammer
I love just my number 7
Love her ass in heaven
Dying at 7 eleven
Not literally
The laughter fully ammo's
Got that shit from the Landlord
Paying my rent with the ammo
She riding my dick like a Camel
From the East the desserts be hot as cammo
Army rangers using hammers
Fucking bitches in the slammers (yeah)

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [oooh, left, right, left, right, on site
Yeah]{mhmmmm} (repeat 2xs)

(Hook)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT (repeat)[big boy pun puns)

(Verse 5)
Pour it up, Pour it up (pour it)
Got a lot drank in my cup (drank)
So hot I need to sip it up (sip it)
Pour about 4 more for the double slut (slut)
Fuck it, (fuck her), fight, (fight), In the (You know), light (light)
I got all this cash so you know these hoes reply (HOES)
Momma got mad at my decision so I got her company (yeah)
2 gym bodybuilders go fuck her in the front seat (fuck it)
While I have my time with my bitches in the damn heat (it’s hot)
It’s so sweaty in this bitch I need hole deep breath (breathing)

(Bridge)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT, [we, getting it, From the AC, in the Heat Yeah
Bro]{mhmmmm} (repeat 2xs)

(Hook)
HEAT, HEAT HEAT, HEAT, HEAT, HEAT, HEAT (repeat)[yeah hoe]

(Verse 6)
I’m like an Addict (Yeah Hoe)
When it’s the night (Yeah Hoe)
Fucking these bitches (Yeah Hoe)
I have a right (Yeah Hoe)
I want the check first I gotta earn stripes (you know it)
I’ve been through hell feel like I did it twice (Heat)
She got it bustin like I’m the new pipe (yeah)
Fuck her at once, don’t care being nice (Yamine)
I’m in the Jungle (Jumanji)
Where bitches and hate be (you know it)
From the F.W. (Fort-Wayne kid)
Where my dad don’ saved me (Yeah Hoe)
I want the friends (Yeah Bro)
Nobody can be me (Yeah Bro)
Now there’s something about this heat
Turn on the AC (turn it)
I have my own Back
In the Hood I need that
Can’t trust nobody
I carry a whole bat
I got them 4s, like a backpack
I’m in prayer (Uh huh)
On a huge (mat)
And it’s so hot I fuck her in the…

(Outro)
HEAT HEAT HEAT HEAT HEAT