[Intro: Gee Watts]
One for the money, two for my bros
Three for the city, now everybody knows

[Verse 1: Gee Watts]
Watts up, no faking – one shot taken
My life was enticed with mayhem, just praying to God I'd make it
City hot as Jamaicans, laying naked with Satan
Just a kid, but what I did would probably leave Jesus shaking
For real – it get real in the field, they kill for pills
And sling packs to dingbats, hoping they’ll cop ‘em some wheels
Niggas start hating, that pistol start clapping
Rat-tat-tat-tat-tatting, no yapping, dapping
Fake fashions? That’ll never happen
We really with this shit – you clowns jiggy rapping
Gee like if Biggie happened to splice with Pac and get it cracking
I take action on acting, I ain’t playing with you
Real whales gave me game, soaked like kiddie pistols
K.Dot gave me respect, the homie like “you crazy blessed”
We finna blow like C4 with no bull in that text
Yes – Mike Jack wouldn’t make it in this thriller
Watts up, watch everybody get familiar

[Chorus: Gee Watts]
One for the money, two for my bros
Three for the city, now everybody knows
Watts up in this motherfucker
Watts up in this motherfucker

[Verse 2: Kendrick Lamar]
Swallow your pride and then eat a dick, uh
Make the rulers apologize, you ain’t ruling shit, uh
I’m Rick Rubin in ’85 with the beard thick
Thick bitch, type Peruvian, slanted eyes, that’s quench
They tell you that I’m one-up, from sundown to sunup
Son, I son niggas, I probably fucked your mama
With no condom, that’s good pussy
Pussy, tell it to your honor, this drama is Jeffrey Dahmer
It took me through many moons just to set up this new platoon
Get ambushed or kick-pushed with push brooms
Man, look, your man look like Sweet Water
Cornbread that break under pressure if he caught up
Big homie said “I gotta crawl before I walk
And if I ever run my mouth then my legs'll get cut off”
See, I’m just a young boss in the bat cave
Back against the wall, and if I fall, Gee Watts bring it back, bang

[Chorus: Gee Watts]
One for the money, two for my bros
Three for the city, now everybody knows
Watts up in this motherfucker
Watts up in this motherfucker
One for the money, two for my bros
Three for the city, now everybody knows
Watts up in this motherfucker
Watts up in this motherfucker