Intro Young Thug
OOOOOOOUUUUUUUUUU

Hook Jaisenzz
Used to get these photos out the A.T.M
Used to get these photos out the A.T.M
Used to get these photos out the A.T.M (skrrrt)
Used to get these photos out the A.T.M (skrrrt, skrrrt)
Used to get these photos out the A.T.M

Verse 1 JZZ
The same as a car getting hit is an impact
Better save your Best Friend because somebody is about to get smacked
Once you here the impact you know I'm incredible like that
Young Thug Tryna jump on this
And I decided he I should the one I'm about to get pumped with
They all take two shots and you know both of them miss
See Justin your the white one yeah your the only one
You look like a super saiyan yet you aren't one
You are such a fake because that's what I was about to become
Remember I was all the way back tryna defend you from all of the stealers
This new girl you have is not as good as Selena
The Queen that you needed
You ain't got no money so you need the A.T.M
You are shaped like a car payin everything
Come to the A.T.M it will say out of order because you are a Benz
This is that shape lift off the Family
Young Thug on Culture means anything

Hook
Used to get these photos out the A.T.M
Used to get these photos out the A.T.M
Used to get these photos out the A.T.M (skrrrt)
Used to get these photos out the A.T.M (skrrrt, skrrrt)
Used to get these photos out the A.T.M

Verse 2 Young Thug
So what were you callin
At the stage of New Orleans
The dawgs seemed relieved, you fucked them then told him
Father on his Album cover
Pretty weird it's not the same color
When I Diss I'm specific so fuck your new shit looking like you Kid Cudi
All of you could suck my dick it's just me and JZZ
We been friends our whole life so what you mean we crazy
When you pick up the phone
You need your baby to be like "If I love you that makes me crazy"
The two best in the industry
After Tyga and Kanye you would think they would be feelin me
But it's family all day so we wouldn't even really see
The girl bout to reject when Yo Gotti is Down In The DM
Too many people tryna see what Yo Gotti got taking pictures at the A.T.M

Outro JZZ YOUNG THUG
I DONT WANT ZERO PROBLEMS BIG FELLA
I DONT WANT ZERO PROBLEMS LIL FELLA