[Verse]
Too many best-rappers, not enough best-rhymes, though
Guess I'm delusional, used to doing it all the time, so
Maybe I'm just jaded, out of touch and unrelated
Unable to connect greatness based on the person who makes it
Or maybe I just hate it
And that would make me hater
Maybe it is great but that don't mean it's greater
Having your profile raised doesn't make you a raiser
Being ambiguous with assertions, isn't making you safer
What you mean, though?
Line us up, paddling us on the back
Like we steamboat, you president of the frat
You goin' sling toast, like you Ringo
And you think Doc Holliday's
Just goin' tolerate and too sick to let that thing go
It's just a matter of returns
Ashes to ashes, scattered them from the urns
To start a fire shaky to gather them from the burned
And reassemble these ashes, the blackness is something firm
Then moving blackness backwards in the bread of some other shit
Any deep we spreadin' wheat seeds from a bucket shit
McDonald had a farm and he lovin' it
Rolls Royce of the scented voice against the arms of the government
Artist gettin' robbed for their publishing
By dirty Jewish execs that think his alms from the covenant
I'll retire when I'm tired, that's a Firestone death
Easy to say when nobody's there, like a microphone check
They wanna hear what I'm gon' say before the microphone check
Make me sign an NDA before the microphone test
'Less you face that type of faith, institutional opposition
Then with all due respect, you are not my competition
Nah