Time will ask ,time will fly
Time will give you wing like a butterfly
You wanna go for something crazy
I'll take you out of here
Time will be, time has passed
Time will make the first be the last
And it'll shake your mind off your body
So let it go then
I wanna see your face in the morning when you wake up
And when you see my eyes
You will know there's nothing made up
'cause I just wanna get high
'n lose control
Get together and let it all be
Time will eat, time will sleep
Time will stick in your head just like a beat
And it's not gonna wait for you
So may you never wait for it
1 2 3 4 5 6 7 8 9 10 11 12
Monday 8 pm
Tuesday 9 pm
Wednesday 10 pm
Thursday 9 pm
Friday 10 pm
Midnight
Saturday
Happy birthday
Wanna catch night
Catch the sparkles
I just wanna get high
'n lose control
Get together
And let it all be yeah
I just wanna bet high
'n lose control
Get together
And let it all be
I just wanna get high
'n lose control
Get together
And let it all be yeah
I just wanna bet high
'n lose control
Get together
And let it all be
Just let it all be yeah
Let it all be
Let it all be yeah
Let it all be
Let it all be yeah