[Intro: Burna Boy]
Warning (x6)
Liquor aid, dat liquor aid, liquor fall down, liquor fall down
Tell dem fi respect every man
Said the same thing in the Bible and Quran
Tell em it's a no play ting
Them are day dreaming
If them thinking they can violate the A-­Team

(Double up)

[Chorus: Da LES]
All my niggas getting paid
Back seat of the Benzo
North side everyday
Now let me tell you what we here for
We saying
"Where the ladies at?" (x6)

[Verse 1: Da LES]
North side nigga when I roll through
2 seat, hold it down pop the roof
You know it's Sandton drive when I’m coming down
I'm the best never lied nigga hands down
Another cheque, another round another set
A bunch of bitches in the
Motherfuckin' pool getting wet
All white, all night pop the molly on sight
And this Mandela money got me feeling godly, a'ight?
I like my shit tidy and it's from the gate
Throw the money in the air watch it ricochet
I got the baddest foreign chick on the premises
Now won't you drop to the slip when I say andale, (Andale!)
(Woo!) goddamn I’m a problem
North god sitting in the motherfuckin' cockpit
Bompton, snap on all Americana
Armour
Now let's continue with saga

[Chorus: Da LES]

[Verse 2: AKA]
These days I be going so hard through the threshold
Pop a couple shots of the XO
I need a body guard, pockets on cholesterol
Check my dress code, 'bout to do the breast stroke
Threw the money, bitches get nothing from me
World in my hand, in Jan we never worry
Oh this your jam, your jam?
Show me some liquor courage
Rubber band on rubber band, who got the budget?
Coming to you live from the 3rd
Got her ass looking light
Did you lie? Won't you twerk?
It's my California girl, drive by in a Merc
Get me Louis Vuitton tell me what size do you wear
More stamps in my passport
So many awards I need a chess board
You now rocking with the best
Whatchu think I’m fucking with L.E.S for?

[Chorus: Da LES]

[Bridge: Burna Boy]
City to ghetto they know me, they know me
No need to tell them my story, they know me
Strictly my niggas around me, around me
Ain't no fake niggas around me, around me

[Chorus: Da LES]

[Outro: Da LES]
Attention please (x2)
I need everybody report to the dance floor
Lets go
Double up
Yeah
You know who this is
Fresh2Def
Come on baby