[Hook X2]
Yo both you and your crew on some Bullshit(x 3)
Ya'll on some Bullshit, you're straight Bullshit

[Verse:1]
You on some Bullshit, and I can see it your eyes
Looking at me like you want something, feeding me your lies
On some bullshit, you're straight bullshit
But i'm the wrong motherfucker to fool with
Cause i can prove it
I'm not about to listen to your bullshit music
I'm not about to listen to your bullshit excuses
The reasons why you didn't do shit, when your crew split
That talk about you empty out the full clip? bullshit
Insult my intelligence with irrelevant elements
Blatant disrespect in my face talkin' all that bullshit
Man i didn't axe' to be fed your lies
Just cause im hungry that don't mean that i'm blind
Yo thats equivalent to feeding me swine
Smelling just like bullshit in a glass,calling it wine
Witness blood shed and call it divine
It's all mine, it's all bullshit
Just like "It's all in the mind"
Like the pain that's inside of your vain
Like the hollow point next to your spine
You catch wreck with a rhyme
You on some bullshit keep your handshake and your smile
Grinning in my face while the state takin' my child

[Hook X2]

[Verse:2]
Man you ain't bitin' my style now thats some bullshit
Hundred percent bullshit, like the stretch hummer outside
Like im'a run and hide, swallow my pride
Just like you screaming out "Ride till I die"
But you don't know how to drive
Now that's some bullshit
Like the housing tenements you livin' in
The book of genesis, somebody dyin' for my sins
Shit i'm still living in sin
And still waiting for the world to end
For the earthquakes, tidal waves and whirlwinds
Yo thats your girlfriend? bullshit
You're feminine ways
Will only having you swimming in blayze
You got the nerve to serve me bullshit on a visible place
Like I should have recognized the chemical waste, bullshit
I'm not about to conform to bullshit trends
Don't ever axe' me to spit for your bullshit friends
Every time I find truth the bullshit comes in
Unnecessary bullshit concerning you and your man
Tryin' to ruin my plans
Tryin' to tell me that I don't got soul
When you motherfuckers don't have goals
When you motherfuckers don't have flows and no soul
When the bullshit CD you released still ain't sold
Cause it's bullshit, it hurts for me to have to tell you the truth
It's really not about who's better than who
It's really all about the truth, being better than you
So fuck you and your bullshit crew concerning me with all that..