G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang! {Whoooooooooooooooooooooo}
And every nigga 'round here representin' gang! {Kiiiiiiiiiiiiiiiiiiiiiiiiiiiid! }
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - We are!
- Not to be play with!
You know how I do it - I represent the untouchable Unit
The G-G-G- boys man slaughter on music
Look in to my eyes you'll see the fire that's behind em
Then think of a slice diamond - that's kind of how I'm shinin'
Right drive right timin' - relax and recline them
They ask to rewind them - you rap from behind them
The world is a big pussy - my Gat is my condom
Whoooooooooo!
WHATTA F*CK? !
'EY YO Whoo Kid... RUN THAT SHIT BACK!
GOD-... DAMN!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
And every nigga 'round here representin' gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - We are!
{Whooooooooooooooooo! } - Not to be play with!
{Kiiiiiiiiiiiiiiiiiiiiiiiiiid! }
You know how I do it - I represent the untouchable Unit
The G-G-G- boys man slaughter on music
Look in to my eyes you'll see the fire that's behind em
Then think of a slice diamond - that's kind of how I'm shinin'
Right drive right timin' - relax and recline them
They ask 2 rewind them - you rap from behind them
The world is a big pussy - my Gat is my condom
Jet Black, 2-0-7 Lac when they find them
I'm all about my pay roll, so move when I say so
A paybro' I get mouth, when the day come to day go
I get high and stay low. "What up Bank$? " Hey hoe!
You want me now, {Whoooooooooooooooo} but didn't want me in the day though {Kiiiiiiiiiiiiiid! }
Hey Yayo!
- Give it these nigga the Gas face
And if they say somethin' show 'em how the Mag' taste
That'll spin a nigga around like his back breaks
Leave in the drag race in other words fast-paced
Cliffhanger! - That's kind of how I climb
Love and hated to powers that combined
Lil' lady try to play me - f*ckin' with my mind
I took her hit her in the morning and tell the bitch to stop lying!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
And every nigga 'round here representin' gang! ("DJ Whoo Kid! ")
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - Yeah, yeah that's my gang!
G-Unit mayne! - We are!
- Not to be play with!