[Intro]
You don't have very many options
You can, get with the program, or you die
The Unit

[Chorus: 50 Cent]
(T.O.S.) Terminate on sight
You see the muh'fuckers, you get it right
(T.O.S.) Night or daylight
It's hammer time, got your nine, I got mine
(T.O.S.) I carve you up nice
You see my knife, see you in ya next life
(T.O.S.) Terminate on sight
Keep one in the chamber, walk with the burner

[Verse 1: 50 Cent]
I'm on that SSK shit, shoot, stab, kill
Think I won't get busy well nigga I, will
Ain't nothin to talk 'bout, get the tape and the chalk out
When I pull the strap out, I might go the MAC route
Leave your car door and your windows all clapped out
I turn enemies to memories, remember me?
The Hennessy, got my eyes glassy, niggas try to blast me
With the .38 them stray shells flew past me
I'm on 'em, what I'ma do, don't ask me
Understand the Feds'll have yo' ass on the stand B
Sold three to muh'fuckers tryin' to jam me
I'm caked up, so niggas in my hood can't stand me
It's fuck 50, I stay in the drama
He love her, I fuck her, she's his baby's mama
She a freak, she give me the na-na
That nigga try to front, I'll give him the llama, YEAH!

[Chorus: 50 Cent]
(T.O.S.) Terminate on sight
You see the muh'fuckers, you get it right
(T.O.S.) Night or daylight
It's hammer time, got your nine, I got mine
(T.O.S.) I carve you up nice
You see my knife, see you in ya next life
(T.O.S.) Terminate on sight
Keep one in the chamber, walk with the burner

[Verse 2: Lloyd Banks]
Yeah (uhh)
Everything was slow motion, but I think I got the potion
'Cause now that they overdosin' all my doors are back, open
In my Cadillac, totin', nigga play with me I'll smoke him
Murder one one, four three-fours where I'm from, son
I don't need a gimmick, I'm the sickest nigga in it
Get it upside-down or twist it, I could promise you a visit
You're a midget, I'm taller than that nigga playin' ball and
Meanin' everybody know me when I'm walkin through the mall and
I get hot, in the mornin' and right before I'm performin'
I been on it since a young'n
I'm comin and here's your warnin', nigga
Don't be snorin', bein' on point is important
'Cause a coffin'll follow shortly after the white chalk and
Call me what you want nigga but you can't call me broke
Call me crack, call me coke, call me uncut dope (uh)
See my oh-eight gas burnin' and my eighty-somethin' rope
Time's over for you niggas, red line on your throat (terminated)

[Chorus: 50 Cent]
(T.O.S.) Terminate on sight
You see the muh'fuckers, you get it right
(T.O.S.) Night or daylight
It's hammer time, got your nine, I got mine
(T.O.S.) I carve you up nice
You see my knife, see you in ya next life
(T.O.S.) Terminate on sight
Keep one in the chamber, walk with the burner

[Verse 3: Tony Yayo]
Unit! Who, who, who, who, who, who want it?
Who, who, who, who, who, who want it?
Which gangsta want it? (WHAT?) Which rapper want it? (WHAT?)
Which trapper want it? My house is haunted
And I'M GONE!!! The Feds wanna bug me and wrap me
I'm the Gingerbread Man, them boys can't catch me
Two-oh-nine, M-6 stuck in the matrix
BM got a new friend, they finally got a face lift
Yeah, I treat bitches like cars, I drove 'em out
They keep a nice trey-pound from when the wolves is out
Horses, Cavalies with a real-life vest on
I kick game like Pele and Beckham (c'mon)
I got dope head hands, and crackhead fingertips (oh yeah!)
From baggin' up with my Bankhead, Atlanta bitch
Every day is Christ', I live like Santa bitch
I'm a scrambler bitch, the Feds can't stand this shit

[Chorus: 50 Cent]
(T.O.S.) Terminate on sight
You see the muh'fuckers, you get it right
(T.O.S.) Night or daylight
It's hammer time, got your nine, I got mine
(T.O.S.) I carve you up nice
You see my knife, see you in ya next life
(T.O.S.) Terminate on sight
Keep one in the chamber, walk with the burner