Uhu

[Intro: The Notorious B.I.G.]
It's the ones that smoke blunts with ya, see your picture
Now they wanna grab they guns and come and get ya
It's the ones that smoke blunts with ya, see your picture
Now they wanna grab they guns and come and get ya

Shoutout DJ [??], I mean DJ Screw
Kinda quiet right now, Ill turn this shit just for us
Yeah, yeah, yeah

[Verse 1: Jason Eric]
Uh, I'm the one, but ain't Ne Yo
So I don't need to sell, for the home that boost my ego
So much B.A.P.E., I should personally know Nigo
I keep up all my three bows
Yes, I got a trio, oh oh, oh oh
They yell and they
I'm so high and it's hard for me to see below
Up a great mass
So when groupies stop by, I always check the people
But I love it when they stop by, even if to say hi
Cause, I am like high
I get the sense that I can touch the sky
My mind is full is full of art
Like ay, I go to [??]
I just joined the mount high club
But, I owe you some bad moves, baby
But your friend providing me lately
Oh, I mean they driving me crazy
It's gonna take more than a sabbath to save me
We so go double O.D
So much swag in this room, we finna O.D
They can't control me, cause I be on the same high as the kids in the O.C

[Verse 2: Travis Scott]
My presence is a must, pastilles free