How the hunger around the underground in my dungarees
Now don't come to me like I ain't hungry please, I've come to eat
I gotta mention I tremble, I'm anorexic
Listen to my excuses and you see I'm bulemic
I eat up rap to spit out crap
I'm the shit, I don't need that slack, this Wale
I don't play, I quit school cause of recess
Now I carry a cane like your name Mr. Peanut
See I'm being plain no facetious
I know I'm in the [?] I devour to feed this fetus
Jeans all premium, the sneakers undefeated
The boy in the star so it's right my feet's in 'em
No lying, I got no line, don't pump fake when you got no lineman
I'm Coach Schottenheimer, you're Philip Rivers throwing sidearm
Sit the pine when I guide y'all

My name Wale, probably know me from the rap
My name Wale, probably know me from the rap
My name Wale, probably know me from the rap

Cut the beat man, this is motherfucking A.D.D. dawg, I can't stand one beat, switch it up for me

[changes beat]

I'm a Giant like Eli is
A little like Mac, I'm a feline here
See, I'm on cap like a cap on bread
I'm the valedictorian, I don't got class
They say I'm that bad cause they say I'm that asterisk
X sign back slash, yeah I'm backwards
?? Please me, I'm a set fifty
I wear KB breezin' through the madness
This the takeover, I'm flamboyant when my face open
The party's over, this the hangover
Flashy as the wonder be, I got change homie
So get your pics and move your cam like ?? rover
The league's closed since the league opened
Yeah I'm Sandy Koufax, know that boy speak on it
Know me, I be the beast of the beltway
This the fourth quarter and I'm going like Elway
And hell way colder than Wale flowing
I steal from the A&R, gotta stay open
So stay focused like LensCrafters cause I rock like Lenny Kravitz when I pen that

[changes beat]

You know I rap it with perfection, capital connection
Mediocre verse though, I gotta bless the next one
The best to come, they all don't equivalate
The hard turn soft and the soft just disintegrate
This is a tender plate, hip-hop's entree
Heatin' up the pot, they don't even make it on tray
And contrary to popular belief, there's not an MC who is as popular as me
People underneath don't amount to my degree
Cause I mounted on my feet and built a mountain full of beef
My buzz like lava, got enough flow to go around like karma
Y'all don't really want none
I got a plethora of never ending flow
Unsigned at the time but I'm better than the pros
I suppose the veterans are slow
LeBron has arrived, Rob Parish gotta go
The callous on my toes, I can't bear it anymore
Everybody know him like Barry with the flow
I am equipped in the dome, I am juking from the hole
When the line don't block, I can still take it home
Line don't block, I can still take it home
When the line don't block, I can still take it home
Take it home

[changes beat]

Around here, it's official
I'm not Scooby or Mike but y'all about to listen
Y'all about to get into the District who've been given you all the true stories of the warriors I'm talking of
I am the author, better yet the offspring of awesome
Authentic talk, this is gospel
So hallelujah, all praise to the higher power
I am a tower, watch I will devour music
We some DC troopers, indeed we do it so fluid
And y'all can't chew it if you brewing it
You know the style take awhile to understand
We pimp slapped the game like it's powder in our hand
The power of a man is often neglected when there's doubters in his land
And all the A&Rs getting crowded in Atlanta
Howard's niggas planned this
I'm a tell you why they eatin', we don't understand us
We judgmental, plus we all haters
We hate to learn shit and we too opinionative
And truly I'm a native but they think that I'm faking
When rappers be wearing sweats I be stepping in my papers
Young SBs and some color in my babesters
And Jordans very rarely cause they be making fake ones
I hate haters, this the hater hiatus
It'll take them five days, they'll probably hate us all, dick
I'm saying I'm sick, the industry ain't shit
The energy they giving me ain't helping me a bit
So Imma backpack it while selling all my hits
Imma tighten up my grip, meditate and light a spliff
As strifling as it is, sometimes I wanna leave
There's haters where we live, but we're just trying to eat
And we're just trying to see this whole city here shine
But them all breads faking and they would rather see us die
Fuck 'em

This the year '06, 2006 man, this is the year of the hater hiatus
All my local artists, we targets of the criticism
But don't let it get you nigga, hold your head but most importantly hold your bread
Keep your fans close, get appropriate exposure by your culture so as long as we know where we came from, we won't change none
Wale!