Intro:
One day the world will stop moving, but we don't abide by rules
And everything that we're doing, they told us that we couldn't do
Everyone said I was different, than all the only kids at school
I never really could pay attention; all I did was just move

[Verse 1:]
Eighties baby, millennium
My dunks is crazy but never made the team
It's never what it seems like you never wore jeans
And I never ran track but I chase my dreams
So, you should do like so
Luckily I had a bright light bulb
An MP3, my whole CD so they jumped on stream on my tight flow
Fly boy, flight control, that boy's tight, hello
Born in July so I'm shooting for the sky and I might get mad if I don't blow
So, if I don't hear the thing when I bowl this
I'll come out the gutter more focused
Eyes on the pens when I wrote this
And I don't know if you noticed but

[Hook:]
We won't stop like we got A.D.D. (x3)
We won't stop because we can't stop, nah
We won't stop like we got A.D.D. (x3)
We won't stop because we can't stop
So move, so move, so move (like you got A.D.D.) (x4)

[Verse 2:]
This my stop let me get off
Tell them other boys they can get lost
I don't give a damn if they roll with Peter Pan
Man them colors ain't been fly since criss-cross
I'm in the Mid where the bids don't look (look)
Where the kid gets booked
I'm on a plane with a dame that wanna join the fly-high club
Tell the kids don't look (ha)
They tried to say that he won't blow (why)
Cause I'm a nerd but she don't know
Until she come to my home and get on her knees (and what)
And play with G.I. Joes
Cause I'm a nice guy in some mean ass clothes
And flow so cold even freon froze
Sho nuff' I got a Leon flow
So you gotta say yes if you don't know, now

[Hook]

[VERSE 3:]

Look, I know you ain't used to me
And I know what I used to be
And I know that we just met
But baby girl would you move with me?
I mean truthfully, I mean usually
I mean actually, I just happened to be
Just writing to waste time and I happened to see
That all the words rhymed so naturally
So naturally, honey actually
It was rapping to me without rapping to beats
Everybody got a story that's what happened to me
And the very next day I was sagging my jeans
I felt cool, they was laughing at me
Had a veelie skullie and like half of my teeth
Things got ugly when my mom said honey
You trying to be a rapper I ain't happy to see
But I promise Ms. Lagranze, I'mma prove to you if I can
That this is all gonna pay out in the end
And we gon play this loud in the Benz
Tryna lay up in the hills when I'm paid
With a girl named Beverly house is a maze
On the beaches kept chair raised
Sitting back, nigga, when I begged for a raise
Maybe I'll get a girlfriend
Or maybe it's too soon
Maybe she'll think I'm cool
Come over and we can spoon
But I never get comfortable
Cause I always gotta leave
And it's hard to keep my attention
Cause they say I got A.D.D. but

[Hook]