[Verse One: Mickey Factz]
See, I seen so many faces
I've been to many places
So, I get so tired of dating
That, I just get tired of waiting
I met these species of woman
It was nothing to keep me from looking
So I wondered if she was from Brooklyn
Cause she was out of this world
I need some info about this girl
Looking fabulous, pushing a Saturn
I hope she take me to her planet
If she touch me then it'll get ugly
If I'm lucky, she will abduct me
On a spaceship and tell me she want me
I know I got her
Now that's what I call a close encounter
Uhh

[Hook]
They say I'm extraterrestrial
Which means I'm out of this world
Your glow is oh so sexual
So you should phone home to me girl

[Verse Two: Harlem's Cash]
They say I got E.T.'s bling
? spaceship, red or blue pills, now we in the Matrix
Foreign top models, yeah I stay with
An illegal alien chick stuck in immigration
See she from Belize
But just invaded South Beach
Asked to be brought to her leader
They directed her to me
The one who bubble from the bottom like Nikes
Now I'm moon walking niggas in my Y3s
Not in vain/vein though, no IV
Twin baby boys, Siamese Tyrese
So if it ain't about scratch, then no flees
I'm a ? like racist, nigga please
(6, 5, 4, 3, 2, 1)
I'm outta this world Apollo 13
She Mindy I'm Mork around these Earthlings
Champion
? to Earth rings
You a Fo kid, he heard he had wings
Cash, Gordon, Mickey, me

[Hook](x2):
They say I'm extraterrestrial
Which means I'm out of this world
Your glow is oh so sexual
So you should phone home to me girl

[Verse Three: XV]
Working at the Daily Planet, I manage to meet her
Took off my glasses so I could really see her
She said, "I love the Squarian demeanor
So Square in the Circle, put a circle around my finger."
Must of had me confused, my name's Clark Kent
And I landed in Kansas from a star ship
Open up the closet in my apartment
"If you ain't Superman then what do you call this?"
Damn
Now she know my secret
"Now tell me what I gotta do to make you keep it."
"Fly me around the world and buy me Victoria Secret
And I'll be so tight that I could never ever leak it."
"True dat." Should of knew that from jump street
Under the covers and then she comes sleep
Mix Master Ice on the process
The new UTFO, you the newest object
Peace

[Hook](x2)
They say I'm extraterrestrial
Which means I'm out of this world
Your glow is oh so sexual
So you should phone home to me girl