Yeah
Ay, they say they need that real shit back tho'
Storch, what up? It's the Mafia (dolla, dolla, dolla)
Black
We smoke till we numb

[Verse 1]
We smoke til we’re numb, and we worship the sun
This year I pulled 4 tons, and moved every one
We don't play the blame game when this shit go wrong
All my trucks are insured, this the real life mob
I’m with the Vietnamese, we trade work for some handguns
Jewish lawyers on retainer, if the man comes
The feds pulled me off the plane, it wasn’t random
I stay away from the iPhone and Samsung
Remember Rico, and them cats out in chico
With the Cali-o-pheno and the root beer Regal
Nah, not Tone from Mendocino
But the cat, with the packs, I like to call Pellegrino
He’s a snitch, [?] Burry him in Mississippi
And burn all his clothes, lose his teeth in the city
My whole team gets busy, and Greed rules everything around me (really, really)
This a motherfucking cartel, God blessed me, and I play my cards well
Fuck a shark, big killer whale, dipped in water, caught a wave, free Biggavel

[Chorus]
Greed rules everything around me
Yeah, greed rules everything around me
I said, greed rules everything around me
Greed rules everything around me
Dolla, dolla

[Verse 2]
You see that pack ain't show up, your man might fold up
And you was outside and saw the van when it rolled up
We had the south in our hands, wait hold up
The 2x4 behind the door ain't hold up
Best friends burn bridges
And working with your fam' is really bad for business
Don't get caught up with the cut and the bitches
It lonely in the cage, noone comes to visit, noone comes to visit (no one)
Greed rules everything around me
Trust don't get left in the dust, with the losers and the smucks
We into livin' plush plus everything deluxe
I got a bussdown Philipe for me, winnin' is a must
Six trucks in Atlanta on ice
In July I raise the price, got the game from Mr. Nice (RIP)
Harlem Nights, H-Town where you at?
Put Gelato on the map, left town and brought it back
Make an M and throw it in the ground
Then I pull a handful out the pound
We the kings of the underground
That's why I don't leave the house without a 100 rounds

[Chorus]
Greed rules everything around me
Yeah, greed rules everything around me
Dolla, dolla
Yeah, greed rules everything around me
Yeah, greed rules everything around me
I said, greed rules everything around me
Greed rules everything around me
Dolla, dolla, yeah