[Intro]
Yeah, this for the fans
This for the fans, dawg, yeah
Super duper good, super duper good
Look, look

[Verse 1]
So um, let's do it, huh, 'cause we ain't really done it
It's just me and my team tryna figure what it mean
Haters keep feeding us caffeine
Tryna keep us from our dreams
But we stayin' asleep
We don't really care though
We after that paper
Holla [?], see your ass later
We doin' it major, MLB
We way ahead of our league, 2,000 under the sea, boy
And we, are, oh so incredible
Ain't nothing we can't eat, every beat is edible
Everything's paid for, and every dollar's federal
About my green so don't forget my vegetables
Don't forget the, the big bro and sister
Can't forget my other brother say what's up to Mr, Man
Damn, it's been so long
And you've been doing so right you can't do shit wrong
And yo Mitch, I appreciate everything you do
And your friendship that I never want to lose
But all I can give is our vision comin' true
So just know I'm doin' this for you

[Bridge]
This one's for you, yeah
This one's for y'all
This one's for y'all, dawg
I know I talk a lot about the haters and they friends
But this one, nah this one is strictly for the fans
Yeah I'll say it again, I'll say it again, I'll say it
I know I talk a lot about the haters and they friends
But this one, nah this one is strictly for the fans

[Verse 2]
With they hands up screamin'
Throw it all up the crowd is bullimic
On the right path you just chillin' on the scenic
Game need glasses, ain't nobody can see me
Ain't nobody can do it like K.i.D has been doin' it
Killin' these tracks all from spittin' and bombin' fluid
No I ain't ever losing
Winning's all I know how
Colder than a snow cloud
Damn I know Momma's so proud of her little boy
Now doin' big things
I'm traveling light speed and don't know when I'ma slow down
'Cause I don't need to
'Cause I'm doing fine G
Got a mean team and a city behind me
Haters can't find me
Got a fine line between what I do
And what these other rappers try to
So I'm stayin' reliable
From beginning to the end
But this one, nah this one is strictly for the fans

[Outro]
This for the fans, this for the fans
You know what I'm saying, like
Every one of you who ever played one of my songs
And really felt what I was saying
This one's for you
It's been a journey, it really has
But Fully Laced we takin' it over this year
Every one of y'all is Fully Laced, like, um
It's the man, ooh damn, K.i.D, you know me
C Breezy, B Compose, Baggie O, Damie
Jada C, you should know
Yeah, this one is for the fans
I love all of y'all, for real
Yeah, I'm gone