[Verse 1]
Every kid with autism know that my heart with 'em
Rather listen to him than the friends he brought with him
Warrior, not a victim, it's rougher than hard denim
Picture bein' on beat but they call you a off-rhythm
Okay, here come anxiety, scared to step in society
Voice shouldn't be judged if it's used loudly or quietly
Nothin' weird about 'em, it's just a fucked up view
He bleed the way you bleed, and his shit red, too
Okay, picture this
You could be the realest nigga speakin', but ain't nobody even listening
Never bully on a bully, but they always wanna pick up on the innocent
Really not tryna hear it, man, some people really are ignorant and belligerent
But you get the point like a pyramid

[Chorus]
A unique-thinking individual strongly matters
A unique-thinking individual strongly matters

[Verse 2]
I'ma treat you like my own
In my heart, you got a home
You ain't gotta feel alone, I understand your tone
You can talk to me even if I got one percent on my phone
'Cause you brush the wrong kid off, they'll go and stab theyself with a comb
Some might repeat words, it still need to be heard
I'm tryna hear every verb, I care more than a nurse
The negative not welcome, put the sign up, please don't disturb
If they don't accept you for who you is, tell 'em they can swerve like Herb, yeah
You deserve to feel free (Ayy), live life fiercely (Ayy)
Always be leery (Ayy), but have no fear, G (Ayy)
Daily and yearly (Ayy), life can get eerie
But the only voice I can't listen to is that annoying bitch Siri
Okay, no matter what, man, we gotta do better
Stronger as one and we braver together
Cold world, never change your weather
Say what you mean and don't fold under pressure, yeah
Everything gon' be fine
And if Humpty Dumpty fall off the wall
Tell Humpty Dumpty re-climb, ayy

[Chorus]
A unique-thinking individual strongly matters
A unique-thinking individual strongly matters