[Verse 1]
I'm already bigger & better
My name big without capital letters
Try one of my fellas you won't see yo future
Go ask any fortune teller
I don't understand y'all hating ass
But I stay on dirt like I ain't taking baths
For all y'all bitches that's taking jabs, when you see this beam it ain't laser tag
Plots scheming have him screaming
My uppercuts will leave a nigga dreaming
The ruger got a bad vibe to it like it's been possessed by a demon
In yo hood I'm flying through
Pulling strings but not tying shoes
Wonder what my rhymes do get double money like times two
On a mission while I'm on the bike
Smoking niggas but I'm outta hype
Stay strapped up to put a bitch to bed, but I'm not talking like a dyke
My woes with me no OVO you don't wanna go toe for toe
Have your soul in the air like a roller coaster
Bitch I'm too much like a overdose

[Hook]
When I clean niggas out know it's me
Bag that nigga up like groceries
None of the cops notice me
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
I'm a come at where you be
And just clean niggas out OCD
When I clean niggas out know it's me
Bag that nigga up like groceries
None of the cops notice me
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
I'm a come at where you be
And just clean niggas out OCD

[Verse 2]
Everybody claim they know me
Cause I stay with bread like baloney
They say one thing but they phony, so I gotta keep it on me
Nigga run now or run later
All about my money like a fundraiser
Metal wound his tongue ,bitch I'm busting lungs
Choppa got his entire gums flavor
On it, my opponent shorty, think twice you don't want it
Even when I know you dead
One mo to the head shots giving you a bonus
Wack his ass got my shirt messy
Animal dead then my fur ready
I'm a cold bitch that get sweet at times
Damn nigga that's Burberry
If I ever feel like I'm at risk, just split his ass like banana splits
Check him for the cheese, mozzarella swiss
Got him nervous now this goofy got the shits
Fake friends, really don't need those
Only come around when shit hot like mosquitoes
Make him fold up like burritos
Gave him a chip tooth no Tostitos

[Hook]
When I clean niggas out know it's me
Bag that nigga up like groceries
None of the cops notice me
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
I'm a come at where you be
And just clean niggas out OCD
When I clean niggas out know it's me
Bag that nigga up like groceries
None of the cops notice me
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
Cause I cleaned the trigger OCD
I'm a come at where you be
And just clean niggas out OCD