[Intro]
It's like I can't cooperate and stuff
Yes
And I can't seem to do my work
Go on
And I just like laughing at people
Mhm it's interesting
I guess it's just THE

[Hook]
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D

[Verse 1]
Yo, ever since I been in school, teachers found a way to hate me
Now they're saying that I got ADHD
Bitches don't blame me, it's your fault
You teachers are fuckin' boring, that's why I doze off
I hate you fuckin' teachers, you all go for the fastest
When I whip your asses for failing me in all my classes
So get ready! The bad kid is back bitch
And I ain't doing schoolwork, I'm doing rap shit
Hopsin comin' after you, there's no way to stop him
LAUSD don't do nothing but cause problems
If I ever get a chance to rob 'em
I'ma just, fuck it next teacher I see I'll fuckin' sock him
So all you teachers better run for the border
Tryna tell me I got a fuckin' mental disorder
This goes out to every fuckin' teacher, I hate you
I said it once and I'll say it again, I hate school

[Hook]
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D

[Verse 2]
Never in my life, did I think I would get it
Until the other day they told me, I was diagnosed wit' it
Fuck school it fucked up my life, it's time to quit it
And I'll admit it, I never learned shit when I was in it
Let me do whatever the fuck I wanna do
I'll stab you in the head with a pencil, a number two
It's the ADHD, you can't tell what I'ma do
I fuckin' mobbin' the school with straight bomb on you fools
You never answer my questions you pantomime
As a matter of fact bitches, fuck a Stanford-9
Why should I take it man, it's worthless
That's why every time I take it I always fail it on purpose
Like I'ma waste my energy, tryna pass it
Just hand me another test and see don't you get your ass kicked
I'm not Batman, Spider Man or Heat-Man
You can just call me the ADHD man

[Hook]
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D

[Verse 3]
I wonder which one of my teachers even started this?
Tryna put me in the class, with all the retarded kids
And I'm the only nigga up in there, I'm hard to miss
I'm telling you man, one day I'ma just [?]
And shoot it towards the teacher and crack his dome open
Break the locks in the door just so it won't open
Stomp his fuckin' face in until his nose broken
I'm one hundred percent serious, no joking
Fuckin' teachers try to act like they reaching out
Then they gon' talk about my ass in the teachers lounge
I went up in there, went blasting every teacher found
They'll get they head bashed in 'til blood is leaking out
Everything I did bad in class was intended
Send me to the dean bitch, I wanna get suspended
ADHD, bitches I'm a lot smarter
I'm just tryna make your motherfuckin' job harder

[Hook]
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D

ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D
ADHD, ADHD
ADHD, it's ADHD
ADHD, it's taking over me
ADHD-D-D

Haha, yeah
Hopsin, listen
I said it once and I'll say it again man
Ay yo fuck school!