[Intro]
Yeah. Awww man. Look what the wind done blew in dawg. Carl Thomas. Rhymefest. And we gon' tell you a little bit about where we come from. Look

[Verse One]
Now y'all don't know what it took
To make these bullies get shook
To put your face in the stars
And write your name in the book
When your wife is a nag and your boss is a crook
And everyday you go to work and want to jump from the roof
But you light up a square and blow your pains in the air
Ask me how I know so well homie, I used to be there
I used to work on my cough to call in work to get off
Like, "Hello, hello, hello boss? I need to call off."
I gotta tell you what I know
And show you where I'm from
With limit income
We had to get out from
Chicago is out son
And we ain't gon' be outdone
You need mo' platinum plaques than Rhymefest gon' pump out some

[Hook: Carl Thomas]
Cause I'm from the southside
And she's from the westside
He's from the northside
And it's alright
Under the street lights
Of Lake Shore Drive
Baby let's ride

[Verse Two]
What's you know about Harold's Chicken?
And Kenny Ribs?
And Moo & Oink on 74th where I used to live?
There was all kinds of gangs to choose from
GD's, 4 Corner Hustlers and Stones, I was the king of the Neutrons
I admit, I was on me
Cause dawg, I'm my own me
And I didn't need no father bitch, I knew who I was gon' be
These rappers runnin' 'round like they half way, you half fake
You false flaggin' as faggot, you better turn your hat straight
You ain't from the low end
He not from the hundreds
You probably from Schaumburg and talkin' that dumb shit
I ?? Jeffery ?? and Jeffery Manor when I moved in my grandma
And them JMG gangstas they was bananas
They would shoot you like you slice and dice
And even Mexicans were trife
103 Latin King verses Gangster Disciples
This goin' out to everybody from the homicidal side of town
We ain't goin' down, doctor check his vitals

[Hook]