[Intro]
Yeah
Right now I need everybody
Lighters up
Not for me, but for you

[Hook]
I sleep with my bible, say my prayers every morning
Wiping coal out my eyelids while I'm pissin and yawning
Bitches do be wantin try shit, I can tell that she horny
You can tell I work night shifts, when you see me in on it
Boy my eyes are so red now like the strings on bologna
All I see is your head now cause this beam it got focus
And that pistol stay on me if you get wrong it's unloading
And like a kindergarten student I don't tell it I show it

[Verse 1]
I'm the oldest of three
Daddy Corey Momma Tammy
I was a bully at three, my lil sister couldn't stand me
My lil brother was my best friend he ain't sit down that's outstanding
Keep the medicine out they reach cause with no room they'll panic
No broom but they married
No room for that sad shit
It's so soon and he at it
Hoes is what he's attracting
Niggas who can't make the situation better call them niggas average
Cut them niggas off make em call me dad to the nigga with no daddy
Call a young nigga bastard, house in Oakland no Raiders
Car black and white like a pastor, house so big no neighbors
I don't dig what they sayin, I'm just tryna be great
The devil call I don't answer cause I got him on call way

[Hook]
I sleep with my bible, say my prayers every morning
Wiping coal out my eyelids while I'm pissin and yawning
Bitches do be wantin try shit, I can tell that she horny
You can tell I work night shifts, when you see me in on it
Boy my eyes are so red now like the strings on bologna
All I see is your head now cause this beam it got focus
And that pistol stay on me if you get wrong it's unloading
And like a kindergarten student I don't tell it I show it

[Verse 2]
These niggas had one way but I'm versitile with these niggas
Get a Sunday drink if she thirsty can't birth a child with these bitches
Curse the child if he snitchin, Choke the girl with my semi
I'm so ahead of them I gave them medicine cause most of them need it
I shot at the car, hit the driver left him with a slow leak
Was supposed to get married tomorrow
No ice but I done caught cold feet
And Salute me like a Sargent if you don't my nigga I defeat ya
Is y'all the way to water quick thirst my nigga no feet
Ride around we listen to Carter wait... number 3
I get to shipping them orders to lames and wannabes
The game is gonna be a trap so don't trust it
Look at how the devil tryna get me so I bust em


[Hook]
I sleep with my bible, say my prayers every morning
Wiping coal out my eyelids while I'm pissin and yawning
Bitches do be wantin try shit, I can tell that she horny
You can tell I work night shifts, when you see me in on it
Boy my eyes are so red now like the strings on bologna
All I see is your head now cause this beam it got focus
And that pistol stay on me if you get wrong it's unloading
And like a kindergarten student I don't tell it I show it