The show is ready, I know it's ready
Is this so hot, too hot!
Cause we got control! Control of myself...

Yeah, I make music for cool dudes and cool chicks
You talk about true shit
All of my crew sick, they're joking our movements
I'm rocking these...
And watching the Ozzy open
Still on my own buzz
I saw some dudes probably hoping
That I'm gonna fall off
The walls gonna run dry
Fuck your creative vision
I see more with one eye
..in the body of one guy
Can we... the sun shine?
I tell you just one time, and one time only
Fuck anybody thinking, I'mma get cozy, you just don't know me
Not a dummy, I'm not grateful for last year
Not too many people celebrating the past here
It's on to the next for me and the clique
Yesterday's news is today's fish and chips
This is it, I'm a rap kicking...
Perhaps I'm more..ain't pep rapping
Ten square bedroom, walk around with no weapon
And no idea.. sixteen in linen
Would you dare if you would come from where I come from?
I took an opportunity that most would run from
On stage and.. cloud in the...
Rapping... when nobody in the room knows where the fuck it is
No crew, no friends, no fam for replace
No drugs, nuts here still winning...

They're all talking like they know it's something
I'm about to show them something
I'm about to show them something real
Something they could feel!
Something they could feel!
Now she's looking at me like I owe her something
About to show her something, about to show her something real
Something she could feel! Something she could feel! Yeah!