[Intro]
(Young Chop on the beat)
(Turn the music up for me Crip)
We prepared for them hammers, couple guns in the attic (Let em' know Chop!)
We prepared for them hammers, couple guns in the attic (Turn up Chop!)
(Chop Squad)

[Chorus]
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no

[Hook]
We prepared for them hammers, couple guns in the attic
Niggas talking that war shit but don't be really packing
See all my niggas savage, pull up and let you have it
Drum hanging out the cannon, money stashed in the mattress

[Bridge]
I got the bands a long way, run up the check a long way
Fuck up a checks the long way, run up the bands a long way
I got the bands a long way, run up the check a long way
Fuck up a checks the long way, run up the bands a long way

[Verse 1]
All this money I'm getting my nigga I grind for it
Got two crosses on my neck my nigga I gotta' thank God for it
And you talking all this money boy, you counterfeit
We ain't got time for that
We ain't got time for that

[Chorus]
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no

[Bridge]
I got the bands a long way, run up the check a long way
Fuck up a checks the long way, run up the bands a long way
I got the bands a long way, run up the check a long way
Fuck up a checks the long way, run up the bands a long way

[Verse 2]
Fuck what you, fuck what you saying
You need them bricks you gon' call the way
Pablo we shipping them bricks
Fuck it we ship it the next day
I sound like [?] with all this yay
Niggas they capping around my way
Fuck up the second and I got it right back
Fuck up the second and I got it right back

[Hook]
We prepared for them hammers, couple guns in the attic
Niggas talking that war shit but don't be really packing
See all my niggas savage, pull up and let you have it
Drum hanging out the cannon, money stashed in the mattress

[Chorus]
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no
We ain't got time for that
We ain't got time for that
Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah
We ain't got time for that
We ain't got time for that
No, no, no, no, no, no, no, no, no, no, no, no