[Intro]
Wait a minute, wait a minute
Wait a minute, wait a minute
Wait a minute, wait a minute
Wait a minute, wait a minute

[Verse 1: Jeru The Damaja]
Man this sucka niggas stabbed me on some OPP shit
Man this nigga thinking, she drinking my love liquid
Jeru pass the heat, ride the beat
Mic twisted overseas with a breeze
Best believe double fisting please
Cover the ears of your seeds
This shit explicit
To some I'm trouble
Double bubbles call me king's horrific
Load up linguistics, the ruler of rhythmic
The god of rhyme, you know the time
Eastern, Standard, or Pacific
Sinful
My words manipulate your mental
When I chump your style on general principle
Build spiritual
Shorty wobble, doubt make you physical
Put fire to the mic
Till it secrete crazy chemicals
The way I murder mics is criminal
And if you press up dog, you messed up
You gon' need dental work
Agonizing pain, cause the truth hurts
On a plane getting brain
With my hand up her skirt
For that last line
You'll probably think I'm a jerk
But can't deny that I'm fly
On the mic put in work
Drop a bomb make emcees disperse
This shit wicked
Like Klan members bombing a church

[Verse 2: (?)]
Hey yo I'm clean with the slicing
Mean with the dicing
Beans with the rice and
Fiends screaming my shit
Jeru that's live shit
Flyig with a pilot
Private, we first class
Reverse that
(?)
F-R-E-S-H
I'm in the south chiefing
While you in the house sleeping
I'm with your spouse creeping
Waking up to (housekeeping)
That's when I'm out sneaking
Leave her with the mouth leaking
Out semen
Thanks for the wild weekend
I get cash wired
And I blast iron
Through cast iron
Its the vampire
I suck the air out of your flat tire
You look tired
Nigga just retire
(You're fired!)
Before I chop you up like Benihana's
And have you stressed with a gray beard
Like Kenny Rogers
Fucker

[Verse 3: (?)]
I'm all for mathematics
You niggas Lenny Kravitz
Big Jew from New York
They call me Jacob Javitz
You a devil, every cell in me is Asiatic
I'm old school but don't you take me for no geriatric
Never catch me in a skirt wearing a heavy jacket
You fashion forward, I'm a poet slash scary black kid
Scary Jerry, extremely strong and very active
Real niggas know and love me
I'm a crazy bastard
Never hating, yet I'm always getting hated on
I'm too abrasive for the players with the gators
Women love me
They don't say its my amazing charm
They say I'm loving and generous as the day is long
But never pussy
Nigga push me, I'ma break his arm
Counter-punching, every move you make is wrong
Bullied brother uplift and celebrate the strong
Now go get your fucking shine box (?)
Wait

[Outro]
Wait a minute, wait a minute
Wait a minute, wait a minute
Wait a minute, wait a minute
Wait a minute, wait a minute