[Verse 1: Jadakiss (Styles P)]
Chrome thing on me, chrome on the Lotus
I don't trust a motherfucking soul, and you know this
Cause all these niggas be having is ulterior motives
It be the ones closest to you that hit you the lowest
That's why you gotta watch niggas like B.E.T
Little stupid niggas, they ain't got their G.E.D
But they'll do anything for a fee
And damn near anything for a key
Yeah, so I keep em in my rearview
You acting like you ready to die (be prepared to)
They gonna think you had a deal with Nike, I'm air you
Coming through, knocking that Black Rob (I dare you
Yeah), I'll send flowers to your wake
(I'll park a hundred and six bullets in your face)
I got a bunch of Rocsi's and Frees with me
I even gotta watch the niggas that be with me

[Hook: Fabolous]
Gotta watch niggas, B.E.T
You gotta watch niggas, B.E.T
Friends at a distance, enemies close
Sometimes the ones you call friends be who envy the most

[Verse 2: Fabolous]
You gotta watch niggas, B.E.T
You keep your gun every day, I got my G.E.D
Everything's believable, anything's possible
Don't take it from me, ask the niggas in the hospital
You holding up your right hand on the stand
And then you put your right hand in the can
Friends like that, who needs enemies?
I'm fucking successful, it do breed enemies
Talking all that fly shit lead to gunplay
Tear your ass apart, rip the runway
I ain't with none of the sucker shit that they be with
Want you to pick em up all the time, that's baby shit
That's why when I breeze past, I'm with a broad
That reminds you of Free's ass at the Awards
My advice? Get your money, don't let it change you
And don't trust shit -- even the devil was an angel

[Hook: Fabolous]
Gotta watch niggas, B.E.T
You gotta watch niggas, B.E.T
Friends at a distance, enemies close
Sometimes the ones you call friends be who envy the most