[Hook x2]
I gotta watch what I say cause the feds listening
They say they got me on tape playing with them chickens
They say my nigga turned state
Now that nigga snitching
The first offer that they're talking is a life sentence

[Verse 1]
I can't even say my niggas names no more
Cause these niggas dropping names on the low
Got me tired and detectives all asking bout me
I'm just trying to figure out why the asking bout me
These pussy niggas sneak dissing from down the street
But real niggas they mention when they found the heat
I was told to keep quiet and never say shit
But these niggas been running off out the lips
Got the feds tuned in all in my business
Saying I'm the one supplying the hood with them chickens
A lot of niggas coming home and I'm wondering why
Man they can't do time so they dropping dimes

[Hook x2]
I don't gangbang nigga I'm from Seminary
And if you don't tote a pistol you in the cemetery
These niggas working with the feds I've been buying reds
3,000 on the show and I ain't have a clue
Looking out for your nigga when your nigga down
He will throw you in the cross and have a nigga down
50,000 for the lawyer ya I'll put it up
No foreigns in the garage ya I put em up
They trying to put a case on me niggas turning phony
Want me back in Rita going to court eating bologna
Hopping off the blue bus got us shackled up
And shared a cell with my co-d got to split us up

[Hook x2]