[Hook]
I still move work, from the A.M. to the P.M
Niggas got beef, I'mma spray 'em when I see 'em
I'mma spray 'em when I see 'em
I'mma spray 'em when I see 'em

[Verse 1]
I pump on the street from the A.M. to the P.M
A nigga want beef, I'mma spray him when I see him
Lay 'em when I see him, AK 'em when I see him
Hop out the Bronco and O.J. him when I see him
Cut a bone out his skin, fish filet him when I see him
Then wire his grill, Kanye him when I see him
My young'uns on they job, so I pay 'em when I see 'em
Turn Boyz II Men, I'll Wanya 'em when I see 'em
Cause I be on the grind from the P.M. to the A.M
Paint pictures with my rhymes, you can see 'em when I say 'em
My songs like movies you can see 'em when you play them
If a nigga want beef, when I see 'em I'mma spray 'em
For six G's, I could get your whip swiss cheesed
I'm like a red nosed pit, you a mixed breed
Bitch please, all 'em dudes in your crew ass
I'll get you strangled with the strings on your doo-rag

[Hook]

[Verse 2]
I'mma let you niggas talk all stupid, 'til you get hawked all stupid
Sparked all stupid, outlined in chalk all stupid
Dog I bite I don't bark all stupid, it is what it is
I'm in the coupe roof dropped all stupid
Fitted hat cocked all stupid, gettin' top all stupid
My clientele cop all stupid
We make sales on the block all stupid, it is what it is
It's a fact that I rap all stupid
Get your wig pushed back all stupid
We strapped all stupid, I'll get you clapped all stupid
Don't let the pills and the 'yac make you act all stupid
Yeah, I do my thing all stupid, let my chain bling all stupid
My ring all stupid and my earring all stupid
I got them things and I sling all stupid, stupid

[Hook]

[Verse 3]
Yo, my flow'll have you amazed and astonished
I been hot since I copped my first Sega with Sonic
Back in the days, when Shawn Kemp played for the sonics
I rocked the huge jeans and I played the Etonics
You know I blow haze, I be blazing the chronic
It got my mind scrambled like the egg in a omelette
I talk to God every day, and he made me a promise
Me and T like Malcolm and Elijah Muhammad
Me and Swizz like Martin and Jesse
But the fact that I can get assassinated, is starting to stress me
I ain't tryna let the police department arrest me
But I still keep steel tucked under the fresh tee
And I ain't just rapping for my health
So before you diss me, you be betta off clappin' at yourself
Cause I ain't tryna battle on the mic
I have them goons hop out on you like they did Harold at the light

[Hook]