[Sean Price]
Yo, two-two-two, five thirty-two, thirty-eight
Four-four-four, five, increase the murder rate
Great, shit can vertebrae, fuck up your backbone
Snatch ya backpack, nigga, fuck up your wack poems
You can't rap, slap his natch with the black chrome
This whipping was a warning, so take your ass back home
Nigga, see I pop shit with the same kinda guns that T.I. got knocked with
Extra clip carrier, quick to click burry ya
Both talk tough, but bitch, I'mma bit scarier
Uh, Rambo guns, Commando guns
Catch you at the beach, will heat up your sandals, son
Fuck with a vet, best believe you fuck with the best
Put a slug in the revolver that'll fuck up your flesh
Put a slug in the revolver and play Russian Roulette
Fuck it, I try, I do it, fuck if you die
Ruck, is the, luckiest fucker alive
I went from nothing to something a couple of times

[Tek]
I got a gun with a nozzle pump, cock back, we dump
Lift ya, who said white men can't jump
I know, dead men talk cuz niggas get caught
But if ya, body a juror then a killa gon' talk
Do ya biddy bop to the block, goodbye to your tail
Shitty city cops, 50 shots, I am Sean Bell
Semi auto four, leave your head looking real gory
Be a ghost before Halloween, that's true story
That I blink like a transporter moving your order
Quarterback spiral like bullets hit your autora
We ain't here to warn 'em, bring the water trigger, we squeezin'
Twenty minute shootouts, clip empty we leaving
When I jump in the porsche, hop in the charger
Fans can't catch the boy, I'm an artful dodger
You know who in charge, get your whole team washed
Then go in and buy guns with the money from these bars

[Steele]
Yeah, the flow rapper, forties and automatic
Arm tatted, chron' addict, it's on when the God rapping
The dog grabbing, my paws, palming the double action
Pump blasting, punk bastards, slump backwards
Rap mastered, got cash? They all plastic
Since graphics, all of my cons, all savage
Lord of War, Nicholas Cage, sick cannons
Spit talents, til we the last Clik standing
Timbs branded, scuffed up from kicking asses
Bucktown, we shoot first, then ask questions
This is my gun, this is my weapon
This is for fun, this is for sending niggas to heaven
Sing 'em a sermon, I heard somebody needed a reverend
Heard he was telling, the bird, he sent a word to my brethren
Parabellum to the back of your melon
You want the rest? See the news at eleven

[Rock]
It go nine millimeter, mack 10, mack 11, twelve gauge
Have your monkey maggot ass on channel seven
Telling like, they shooting, that just how we making you Duck Down
This go round, what up now? He said, what, now?
You the old mattress bout to get drugged out
Like me, I'm so addictive, I'm the newest drug out
With guns out, ignorant birds, we dumb foul
Run out of shells and you ingrown hairs get plucked out
Get smacked with a cap, I'm Kung Lao
Rock a pocket rocket, put a drop top on Run's house
I ain't talking bout horizons when I say 'sun down'
Son, down! down for the count, it was just for one round
Give me two of those gats that Bruno had
On Pluto now, and only on them who hold gat
Ain't that false advertisement? I should sue those fags
I'm just playing, you know that!
Fuck around these days, these dirty DA's'll do your raps
Not guilty, but I do know gats, think about it like
Seriously... is it true or all raps
When I say I put a hole the size of my boot in your back