[Intro]
Yeah, oh yeah, oh yeah
Got it on smash
Alright cool
OG Parker

[Pre-Chorus]
Jumped in the 'What-the-fuck-is-that'
Took a shot of Henny out the back
Girl you know it's real, I ain't tryna brag
I just wanna take you to the back while you let a nigga

[Chorus]
Bust it, down, bust it, down
Bust it, down, oh yeah
Bust it, down, bust it, down
Bust it, down, oh yeah, yeah

[Verse 1]
Wait, in the trap with the top and the cash, ayy
I won't tolerate a bitch talkin' back, ayy
'Less she lookin' at me, throwin' that shit back, ayy
20 motherfuckin' racks on a bad day
Jumped in the 'What-the-fuck-is-that'
Drunk and there ain't no comin' back
Pussy nigga don't get hit up with the .30
Sendin' bullets lookin' all across the map, ayy
T.O niggas don't know how to act
I fucked up the re-up, got it back
Shooter right beside me with the Curry
You gon' let me ride 'cause I

[Pre-Chorus]
Jumped in the 'What-the fuck-is-that'
Took a shot of Henny out the back
Girl you know it's real, I ain't tryna brag
I just wanna take you to the back while you let a nigga

[Chorus]
Bust it, down, bust it, down
Bust it, down, oh yeah
Bust it, down, bust it, down
Bust it, down, oh yeah, yeah

[Verse 2]
Wait, cracked that Hennessy and now I'm drunk, ayy
We don't know you, you can't smoke the blunt, ayy
Yeah, I see the opps in the front but
I got a Glock in my Louis V draws
Jumped in the 'What-the-fuck-is-that'
Drunk and there ain't no comin' back
I might pull up to her block, 7:30
And fuck her once, I know I'll get attached
She mad I keep pullin' on her tracks
Bought her Uber here but I didn't buy it back
Fuck a 'lac, all of this is facts
She just wanna throw that ass back when I

[Pre-Chorus]
Jumped in the 'What-the-fuck-is-that'
Took a shot of Henny out the back
Girl you know it's real, I ain't tryna brag
I just wanna take you to the back while you let a nigga

[Chorus]
Bust it, down, bust it, down
Bust it, down, oh yeah
Bust it, down, bust it, down
Bust it, down, oh yeah, yeah