[Bridge]
Give me a little bit longer
Give me just a little bit stronger
Give me just a little big longer
Give me just one more try

[Verse 1]
Uh, oh look at how these niggas tryna hoe a young nigga
I came from the bottom of the O
Never had a pot to piss in but I had the stove and got richer
Nigga you know what we doin', I've been hustin' just to get myself a cuban
It was all about the butter, I ain't stutter, ain't no Ruben
I got a lot of money in my Balmain
Mixing with the Zara
Anytime I'd step up on the go dog
Tell me why them niggas always hatin', why I always gotta be the one catch it on the low dog
Nigga down to hit it with the four dog
Got some O dogs, gotta hit em with the road dog
Double Cartier n my floor dog
I can say it under oath dog
Niggas already know been the realest
I'ma stay the realest ill the day I go dog

[Bridge]
Give me a little bit longer
Give me just a little bit stronger
Give me just a little big longer
Give me just one more try

[Hook]
I dropped the stand in the Mulsanne baby
I swear I always wanted one of these baby
Remember when I didn't have a thing baby
I swear man all I had to do was, all I, all I had to do was
Dream baby, dream baby, dream baby
All I had to do was
Dream baby, dream baby, dream baby
All I had to do was

[Verse 2]
Look at the flick of the wrist
I don’t see you niggas getting no bigger than this
I got money and it depicting the pic
Women love to fuck a nigga when he da kid with a hit
Rollie with the black diamond
Got the ties in it
I got a first class ticket to put da pies in it
And got a couple of bitches in king of diamond
Cause shit when a nigga
Ice hit the light it will hypnotize your bitch
Niggas need to get their shit straight
Niggas need to get their motherfucking shit straight
Niggas love to say I’m broke how i was running around 50 thous
With a feature named Bieber on a mixtape
I got a glass wall for the crib stake
I gotta hitta that will make the crib shake
I gotta take advantage of the chance that I'm granted just to see these hating niggas make the sick face, ouh
How you love a nigga?
It's either leave it or pimp it if she be fucking niggas
I keep a oven to open over these suckas
I ain't fucking with these niggas
They hated but they say they love a nigga, no
Ain't no time for cosigns
Niggas wasn't giving it, these niggas was living it up
Dropping the rock
I'm picking it up
Robbing the game
I’m sticking it up
Flow stinging like spilling perox- still in the cut
Still in the cut
For niggas thinking I'm giving a fuck
Not never I'm probably the hottest ever
Years nigga i been on this obscure level
That niggas could never meddle with
We are not the same thats why we could never settle it
Lambo dark gray metal tint its evident
I don’t wanna fuck with niggas I know I'm better than
So I think you niggas better just

[Bridge]
Give me a little bit longer
Give me just a little bit stronger
Give me just a little big longer
Give me just one more try

[Hook]
I dropped the steam in the Mulsanne baby
I swear I always wanted one of these baby
Remember when I didn't have a thing baby
I swear man all I had to do was, all I, all I had to do was
Dream baby, dream baby, dream baby
All I had to do was
Dream baby, dream baby, dream baby
All I had to do was

[Outro]
I said all I wanna do, is
Come up in that coupe
That new Wraith, it got the stars in the roof, ya bitch
All I wanna do, I said all I wanna do
I said all I wanna do, is
Come up in that coupe
That new Wraith, it got the stars in the roof, ya bitch
All I wanna do, I said all I wanna do
I said all I wanna do, is
Come up in that coupe
That new Wraith, it got the stars in the roof, ya bitch
All I wanna do, I said all I wanna do

Rollin', rollin', rollin', rollin', rollin' round town
I've been rollin', cops patrolling, strolling round town
Rollin', rollin', rollin', rollin', rollin' round
I've been rollin', cops patrolling, we keep rollin' down