[Qwel]
I never wanted this...I never...

A stream of fetus-liquid bleeding' victims hate the crucifixions
Patients paying 2 for 1 babyhangin euphemisms
Use your wisdom lock them infants in a grave in your soul
Her bodies hers but not herb? Population control
Let em smash it on the tile, it's your child Crack a smile Eve
Rhymes the spine, find abortion cards in aisle 3
Deny me of my fatherhood, motherhood is a punishment?
Repercussions for fucking the cure funded by the government
Teach your misery to walk in bids of labor
Spread your legs teach your selfishness to talk you didn't name her
Or him Cause everyday hurts scrubbing sins away
Bloody couches vouching for cribs forgetting judgement day
Now run and play but the children can breathe its safe now
From all forms of torment, abortion clinics next to playgrounds
Next to nothing the moontans are Ecstasy to fuck her
I pity you, not the carcass You'll never be a mother
You'll never get your hands dirty changing dirty promises
Drown the vipers in dirty diapers not the other way around
Bought another way to drown its not the doctors kid
I see no options bitch but we didn't make a sound
Good job Smith a great success for the economy
Bank the flesh, build a whore, thank god my mom wanted me
Mercy killing squeeze the gold, Whats the fee cost?
Whispers turn to wishes Miss I'm just admitting we lost

I didn't want this...

[Robust]
The defenses drown now the consensus is pretentious frowns
Crowd around the fences of the town while the defenseless drown
In blood sweat and tears for fears my mom is killing me
Honestly I promise I never wanted responsibility
Pull the plug shes full of drugs and love is just a fantasy
So my skull is mugged shrug and give hugs to all of my family
Consumed in this room I assume soon the blood will spill
From the womb to the tomb in minutes It only cost a couple bills
I guess you loved me enough to kill but still why'd it have to be
Me and why you mad at me and why'd I die a casualty
So﻿ casually its sad to see Cause you could've had your seed
Instead you had em bleed for greed I'm burning sacks of weed
In remembrance Mom is tense and shes confused in sentiments
With illusions using common sense you infuse intelligence
Twisted views irrelevant but who's looking through the telescope?
Tell it to the pope selling hope one day you'll choke n smell the smoke
Tell it in a joke, dead the eggs and throw away the shells
Half way to hell spread your legs and then you made em swell
More birthdays to sell, cast a spell and make him blind
Wait in line for your place in heaven, my mother paid for mine
With chump change the diapers ration from fashioned fast humps
Exchange with wipers ask em for carcasses in trash dumps
Garbage pigs bid on the fetus price I cried in your skin
Mom I'm your Jesus Christ look I died for your sins