[Nelly]
Uh-huh.. uhh, uhh, uhh, listen
The way your Apple Bottom pokin out got me on a mission
I wanna get you in every kind of position
I don't wanna keep my cool baby, I can't keep my distance
Girl I salute you, I'll be at attention
I'm so into you, I just wanna be your lover
On the floor, in the chair, under covers
When I'm kissin you I can't think about another (think about another)
Girl (think-a, think about another) turn the lights on

[Hook: Dirty Money]
You're my pride and joy, you're my baby boy
People ask me how I feel, 'bout you
They ask me if I love you (baby, I want your love)
And if I'm crazy 'bout ya (baby, I want your love)
Kissin you is, all that I've been thinkin of
Kissin you is, ooooh, ooooh
Kissin you is, all that I've been thinkin of
Kissin you is, ooooh, ooooh

[Nelly]
See I'mma kiss you, wan' go up to your body, shawty you will never
Scorpio, girl I was built for pleasure
I'll make your body start rainin, I change the weather
Let it fall on me, I don't need no umbrella
I get it - from the back (from the back) from the front (from the front)
On your side lil' mama, now here it come
Heyyyy, I just wanna be your loverrrrrr {yeahhhhhhh}
Now sing it for me girl {*echoes*}

[Hook] w/ ad libs

[Murphy Lee]
Look, uhh, yo, check it, uhh
I'm in a Lex' bubbly talkin to my text buddy
Said I forgot about her thinkin 'bout my next money
Not only that honey, kissin's what I think of
You got the Wi-Fi, what's the code so we can link up
Kitchen flo', kitchen table, fuck the whole sink up
The best sprinkler, your back open like a pick-up
The mess that you're makin we can blame it on the liquor
If that's not enough then you can blame it on Murph' baby

[Hook] w/ ad libs