[Verse 1]
Cause now you know the reason why I'm private
True friendships, I've been deprived it
It's painful when them knives get
Thrown in your back
By those you run in the pack with
Who's active in making the right tracks shift from under your feet
They fradulent, so it's no wonder you see
It's there whether the outcome is that you wanna defeat
I always felt someone who's true would be loyal to them beneath the soil
That's if you boil ramen noodles or you royal
No need for crying over spoiled milk that's spilt
Cause everybody isn't built to see the error in they guilt
And treat you fairly instead so we not cut from the same cloth
And they hangin' by a very thin thread

[Chorus x2]
I need true friends
Not the one with misleading surprises
Cause that's a fake relationship involving enemies needing disguises
I need true friends
And if you feel the way I feel, put up your two hands
Same n's that you drink with and you blew gans
Be the same n's that'll try to knock you off your path where your shoe lands
And force you to come up with some new plans, damn

[Verse 2]
Man, I don't believe it
Thought he would always have my backbone
Till things got ugly as a scene in Scarface when they wack Ton'
We was supposed to start our black own business
Invest in real estate
Drive cars off the lot with the dealer's plate
We seen each other at our lowest
Rolling that bud bundy speaking on how cool it would be if we could blow this
In a Ferrari or the Lotus
He knew just 'bout my every setback and set off notice
The runners with the law getting sued by the label that fears me
Not being able to stay mentally stable
The friends who were cut off like cans
For stealing on a Iran civilian
That would've ruined my plans a million
Times before I was broken completely
If you discretely feel the same but covered your tracks neatly, then eat me
They say what's in the dark comes to the light, sad
He didn't make it quite bad and so he might had a screw too loose to fit
Once after getting stoned
I thought how he went behind my back and crossed me, that's a crucifix
You know, them abusive sticks they nailed Christ to
Guard our alleyways we shot dice through
Memories of high school parking lot pimping
Attempting to get a number rapping in battle
Never would been out, no doubt
I would've went to war for 'em
Discusses on your block of your form

[Chorus x2]
I need true friends
Not the one with misleading surprises
Cause that's a fake relationship involving enemies needing disguises
I need true friends
And if you feel the way I feel, put up your two hands
Same n's that you drink with and you blew gans
Be the same n's that'll try to knock you off your path where your shoe lands
And force you to come up with some new plans, damn