[Intro]
P.S. (x2)

[Hook]
They say I keep it too real
How do you feel?
What you prefer red pill, blue pill? (x3)
They say I keep it too real
Well, how do you feel?
What you prefer red pill, blue pill?
Red pill, blue pill

[Verse 1]
Last year wasn't a good year
It brought thoughts of a past
I want to forget
In a future I could fear
Used to write out of love
Now it's for therapy
From doing terribly
But God blew air in me and
If a lump of coal can produce a diamond
I can jump and touch the sky
And wouldn't need a boost to climb it
I always beat myself up
Like a producer rhyming
So I barely sleep as much as night owls on rooster timing
And wondering why my mind's wondering
So much it drifted on a memory
And him and we are different
To see what's naive
That thought me to keep a trick up my sleeve
For every day that I breathe
And I was barely on it
Now I think about myself in the future
Thinking bout what I was thinking bout in this very moment
You know how many times there was rent due
And I ain’t have a cent to
My name is that the same stint you went through
And if so, I'll be your guy for the drive
The devil's on my head
But God's on my side
And from up there
I know he see his son trying to follow his footsteps
Without his sneakers untying
And tripping over the little things
That lack meaning
But you know that sometimes poisons
A place you find vaccine in
Writing verses in my mobile with the crack screen
And parked in front of Whitney's
On the mack
While sitting back leaning
Spending hours on a bar
Until they measure up
With the one before
And if I don't  I drop the line like a underscore
Who said these battles would be worth it
If I  won a war
Got love off the album and begun the tour
So as the thunder roar, rain fall and lightning flashes
I walk by faith
I can't trust my sight and glasses
I never said that I was perfect
But if you get to know me
And be friendly, it be worth it

[Outro]
They say I keep it too real
How do you feel?
What you prefer red pill, blue pill? (x3)
They say I keep it too real
How do you feel?
What you prefer...
Yeah
P.S. (x5)