Came up livin tough
Tanked in a basement of uppercuts
Mommy was a soldier
Got beat up in the name or relationshion-shutup bitch before I give you something to cry about
Crying out crying out crying out crying out
I got a name I came to make
Take a number, flock of lepers who'll
Dive off a bridge if I mentioned living under
Never safe
Memory’s burdens blacked out to clean slate
Underestimated, under sold
Under now, u don’t know
Gagaga rah rah rah
Speaking gibberish blah blah
Call the cops? Is that a threat well do it
Already proved what I came here to do with it
Law, lazy, last in line, loud, loser
Lost in lime light lies
Temper, trashy tactless
Tough, tried too hard, teased a ton
Talked way too much
Tainted tongues tapered on tall tanned
Ties
Take a teaspoon of talcum
10 tears to trigger trials

C.U.LT

Constantly undermining large trains of thought
I’m a girl from NY, also spent time on a farm
Got my break in a city where the angels came with the fury of gods


Never broke with the weight of my start
But took the pieces they left of me to make a name for my art
Watch pay attention sometimes
Cause when you force it upon them what’s theirs is mine

Some of you can tell that I happened to make this up
Got some kids to believe and then booked my own cuts
Livin is tough when you weren’t raised to survive
But I was and this is why

C.U.L.T