[HOOK]

I can't believe I got so high
Smoke clouds,my God,the sun so high
I'm so high, I forgot that line
I can't forget about Riverside (The side)
But on a road they say all I do is role up (Yeah I smoke)
They mad cause keeping up so hard
Keepin' up so hard (2X)
Pass that Kush
It got the girls in the cars
Looking so hard
They can't catch me though
Cause keepin' up so hard

[VERSE 1: T.Mills]

Welcome to my room that high room
Double X's kill zone
Double up and extendo there
Make sure that it's real long
I'm smoking on that Schwarzenegger
That Iron man, I'm still gone
Basically what I'm saying is
I've been smoking on this real strong
Keeping up is so hard, life is moving so fast
Yesterday in my rear view, and life's full on the gas
We used to be in the same position so I get just why you mad
You run a 60 in less than 10 in a row I'm speeding of in that ass

I'm elevated, levitated, elevated I'm high
Elevated, levitated, elevated I'm high
Elevating, levitated, elevated I'm high
I'm elevated, levitated, elevated I'm high

[HOOK]

I can't believe I got so high
Smoke clouds,my God,the sun so high
I'm so high, I forgot that line
I can't forget about Riverside (The side)
But on a road they say all I do is role up (Yeah I smoke)
They mad cause keeping up so hard
Keepin' up so hard (2X)
Pass that Kush
It got the girls in the cars
Looking so hard
They can't catch me though
Cause keepin' up so hard

[VERSE 2: Smoke DZA]

Ride, let me put you on something only I know
When the chief and me are are hauling
I have sold it cause I smoke
I love bud even my shane's smoking
See that fucking gray clouds like the rain coming
Yeah my rain coming,watch me fly pass
To the top way higher than my high ass
Uh, these OG's in east LA
So loud wish I had this on beats by Dre's
I'm a rock star, fucking Pot star
Light up anywhere cause I'm not sure
I'm the kush God fuck with you dawg
Know when I come do make sure you disabled them alarms
Cause I'm burnin' down your dorms, stair cases, back allies
And get schooled rolling up at your pap rallies
Tryin' to cop a sack then get at me
Got some shit sure to make you happy

I'm elevated, levitated, elevated I'm high
Elevated, levitated, elevated I'm high
Elevating, levitated, elevated I'm high
I'm elevated, levitated, elevated I'm high

[HOOK]

I can't believe I got so high
Smoke clouds,my God,the sun so high
I'm so high, I forgot that line
I can't forget about Riverside (The side)
But on a road they say all I do is role up (Yeah I smoke)
They mad cause keeping up so hard
Keepin' up so hard (2X)
Pass that kush
It got the girls in the cars
Looking so hard
They can't catch me though
Cause keepin' up so hard

[VERSE 3 :T.Mills]

I like blue drain, blueberry
At the house watching Halle Berry
Movies with groupies in Jacuzzis
They blow me when they smoking up on that "Ou wee!"
Blasting off in that Oh Yeah
Your girlfriend, your ex chick and your next chick
They all here
One year, that's 12 months, 12 girls I hit once
2 girls I hit twice and they both arrived on the same night
Same time and their names rhyme
Slam dunk I got hang time
One blunt, smoked an 8th of weed
And you still blowing that same dime

I'm elevated, levitated, elevated I'm high
Elevated, levitated, elevated I'm high
Elevating, levitated, elevated I'm high
I'm elevated, levitated, elevated I'm high

[HOOK]

I can't believe I got so high
Smoke clouds,my God,the sun so high
I'm so high, I forgot that line
I can't forget about Riverside (The side)
But on a road they say all I do is role up (Yeah I smoke)
They mad cause keeping up so hard
Keepin' up so hard (2X)
Pass that kush
It got the girls in the cars
Looking so hard
They can't catch me though
Cause keepin' up so hard