Really
Uh

[Intro]
Masters of the universe
Rulers of the world (world, world)
World touring me some bad yellow bitches I prefer
One more time
(x2)

[Verse 1]
Dancing to my own beats
Laughing at my own jokes
This nigga must be crazy
Like what the fuck you on yo
I got (?)
Sour and the OG combo
Convos about long dough
How about bomb pussy pronto
I twitch, homie I flip
Niggas always talk free, never buy shit
Use logic, I ride with
Zips up in the glove up in my shit
Uh
I'm psycho, I might go
Light a couple bombs under the Eiffel
Dance with the devil to the maestro
Maestro
On moonrock, I moonwalk like Michael
Eyes low
Shit i fuck around and go viral
Kushed God'll (?) the world like the Bible
Uh
Nigga high as a kite though
You never know my cycle
Move weight like lipo
Its light though

[Outro]
As I sit here and gloat
I ask myself what're you doing right now
(?)
Its not a tribute
Its a farewell party
(Laughter)
And I'm the one who caused it
I'm the one who has ended Hulkamania
Why?
Because I rule the world