[Intro]
"Realistically speaking"
"Comin' from Queens"
"Realistically speaking"
"Son, you know how it go"
"Realistically speaking"
"Comin' from Queens"
"Realistically speaking"

[Verse One: Twin Gambino]
It's the B-I-G T-W-I-N-S
And Queensbridge is where we rep
For holding Tecs, Mack-9s, Four-pounds and shotties
You don't want to get bodied so fix your face
Before I air that ass out
Go to court and beat the case
It's real like that
I have no feelings inside
Maybe cause my twin brother died in front of my eyes
And it hurts to this day like a pain in my chest
That's why I stay vexed
In the hood, sipping on Beck's
Wishing I could get a check instead of robbing something all the time
It's about crime, but we gotta give it up
Before they put me behind bars with no parole
I love Old Gold too much, I gotta stay home
Plus the orgies, the shorties be blessing me all day
Even at a mov-ay, they do what I say
We gonna start from the ground till we rise to the top
If not, dun, we gonna run up in these banks with the Glocks
And pop anybody jump in my way
Cause Gambino don't play when it comes to the cakes

[Hook: Twin Gambino]
It's the B-I-G T-W-I-N-S
And Queensbridge is where we rep
For holding Tecs, Mack-9s, Four-pounds and shotties
"Comin' from Queens..." Kid you know how it goes
It's the B-I-G T-W-I-N-S
And Queensbridge is where we rep
For holding Tecs, Mack-9s, Four-pounds and shotties
You don't want to get bodied so fix your face

[Verse Two]
Fuck life: that's how I feel when a nigga try to front
Get laid down with the double-barrel pump
And chump, serve lumps, what you want? I'm right here
I'm a grimy-ass nigga that love to drink beers
For years, I've been trying to wipe the tears
Take one step at a time to the top of the stairs
Ya'll niggas scared
Cause the grimy one always come prepared
With two guns blazing, no matter the year
Chill at your mom's funeral and body you there
We don't care: my goal is to get the chair
I did so much shit, I'm surprised I'm here
We don't fear, we don't care, we right here

[Hook]
It's the B-I-G T-W-I-N-S
And Queensbridge is where we rep
For holding Tecs, Mack-9s, Four-pounds and shotties
"Comin' from Queens..." Kid you know how it goes
It's the B-I-G T-W-I-N-S
And Queensbridge is where we rep
For holding Tecs, Mack-9s, Four-pounds and shotties
"Comin' from Queens..."