[Refrão]

O dinheiro arruinou tudo ao meu redor 3x
Dolla Dolla Bill Y'all 2x
2x

[Verso]

A vida é uma dádiva e a gente duvida
Dedico o meu tempo tentando entendê-la
Eu vejo as pessoas tentando estendê-la
Vivendo rápido demais até pra despedidas

Nas voltas desse mundo queremos prendê-la
Sem passagens de volta, só temos a ida
Partindo corações, é a nossa partida
Perdemos a jogada tentando vencê-la

Eles querem vendê-la, eu só quero amá-la
- Amor, faça as malas. Vamos fugir daqui!
Alguns ganham no grito, outros perdem a fala
E os que falam demais nunca vão distinguir

Genuíno ou falso? É uma farsa legítima
E as mentiras tão íntimas são verdades pro réu
A realeza é dos reis, mas as pessoas reais
Não precisam dos reais pra comprar vagas no céu

...no céu 4x

[Refrão]

O dinheiro arruinou tudo ao meu redor 3x
Dolla Dolla Bill Y'all 2x
2x