Big bank in my pocket
Naw nigga you trippin
Ace been off that bullshit
Like Michael Jordan and Pippen
I be riding round with bout 50
Moving and Whippin in that Bentley
Soak your mind like Yo Samity
Get more money my remedy
Lookin at a real nigga with big dough
Neck lookin like that disco
Swag unidentified Joe Doe
Doing this shit with my eyes closed
But I don't like that babababa brain cold
Hots and I'm dippin in that light slow
Talkin bout paper nigga 10 4
Moving and I'm chillin with them bad hoes
Shitting on them niggas like a asshole
Beating up the beat like car pull
Yessir Messir
My pussy ask her
Hit it then I send it back home to you
Getting to stepping Kappa
9 to 5 with my top gone
Nickname Casper
So what the fuck ya'll mad at me for
Sippin and I'm chillin with a deep throat
Thick bitch trench coat
Had to reintroduce her to the strepthroat
No hands straight jaws
Golf balls
Let go
Got theses niggas out here petro
5 when I slide in the place ho
Any nigga beat beat death row
Flip the marder that debt flow
Why the fuck ya'll hatin on me for
Fuck you niggas I'm beast mode
Fuck you niggas who sleep holmes
Hard as a motherfucker can go
Kiss my ass besos