[Intro]
Big booty ho
(I need that)
Big booty, big booty ho
(On my lap)
Big booty, big booty ho
Big booty, big booty ho
Big booty, big booty ho
(I need that)
Big booty, big booty ho
(On my lap)
Big booty, big booty ho
Big booty, big booty hoes
Hump with it

[Verse 1: B Mac the Queen]
Keep it on the low, that's something you gotta know
If them two chicks had a name, it must be Duece Bigalow
It must be too official, you used to gettin' your way with niggas you know
(In the Booty club its snowing , in the booty club its snowing ohh Lord)
I'm rippin' my tab, I'm yellin' it loud, that's how we get down
They breakin' it down, all that dough on the ground, got us shakin' it now
They know we around, just me and my rounds, I be makin' my rounds
Get game from a stripper I know all about it
Stuck in the them bands they don't fit in no wallet
They mad at her, this fantastic, I'm mad happy, she poppin'
She poppin', hell yeah she poppin'
She kill her cheese before she leave, them bands ain't no for no college
For them dollas, how much you wanna bet that she givin' up knowledge
Drop it

[Hook : Hit-Boy]
She got ass, she got ass
I need that, on my lap
Run it quick, I might let you hold me stacks
And it go like that, you better know that stack

Quick fast, never slow, bust it open for the realest clique you know
You ain't fast, never slow, bust it open for the realest clique you know
Quick fast, never slow, bust it open for the realest clique you know
Quick fast, never slow, bust it open

[Verse 2: Oktane]
A fresh nigga just walked in, act like it, act like it, yeah yeah, act like it
A fresh nigga just walked in, act like it
It's time to relieve how stressed I am
I ain't gon' talk about how West I am
I ain't gon' talk about how fresh I am
Fuck am I kiddin' nigga, yes I am
Nigga that's the reason she shakin'
Friends tryin' to guess how much money I'm makin'
Dreads on my back now she think I'm Jamaican
Whatever, whenever, just do it naked
White girls they love me
Step up in this thing like fuck it
Ain't worried about no budgets
Just throw as soon as you touch it
And whenever she shake it I smack it and laugh
Then leave hella drunk out the back of the cab
Higher, higher, dab after dab
And swipin' our cards on the crack of that ass

[Verse 3: Price]
How you fit that in that denim?
I must say that I love lookin' from the outside but lord knows that I want to be in 'em
That ass is too fat to a personal tailor in London is right where you send 'em, huh
To get stitched and sew'd girl u winnin'
Commitin' adultry in my mind now I'm sinnin'
Hold up gimme a minute, start a nigga from the beginnin'
So I can say to the whole world I love big booty bitches
Animal cruelity how I do that kitten, I'm a grown ass man bitch who you kiddin'?
I'm screamin' out B Mac (B Mac)
Once we beat 'em they will never get a rematch
Throw me the cat, a nigga need that feedback
On my lap bitch, that's right where I need that

[Hook + Intro]

[Outro (2X)]
Small waist, ass fat
Look at you with the back tat
Let a real nigga tap that