[Verse 1]
Ms. Big-Booty-With-The-Spandex
Yes, what it do, where your man at?
I'm trynna converse
Most likely to be the first
Nigga to spit this much game til you threw a verse
Beside E-40
We both know
They won't know
What they can't see
Cause they can't go
It's just me and you
We them niggas with clean money
I need a freaky bitch to keep the pussy clean for me
Old enough to make her own decisions
If you're living on your own, well, take a nigga home
I'm only getting ratchet with a bitch
She threw her pussy at my face so I slapped her with the dick
Rapping while she's doing little tongue action tricks
I'm just having fun, running with the shit
If she want the dick, nasty bitch that don't like to spit
I might let her taste the flavors
But first I need a favor

[Hook]
Ladies scream if you gon' let a nigga hit
Take a dip and hit the pussy real quick
Bounce them titties for a nigga
If you came to the club just to show love (then what?)
Then bounce them titties for a nigga
If your bad behavior got you shaking what your mama gave ya (then what?)
Then bounce them titties for a nigga
If your nigga ain't shit and that nigga acting bitch-made (then what?)
Then bounce them titties for a nigga
I ain't shit but my shit probably help you get your rent paid
Bounce them titties for a nigga
Bounce them titties for a nigga

[Verse 2]
Hide your wives, trying to get inside them thighs
High forever, yeah we're getting high tonight
Roll with me, young nigga roaming the streets
Baby I could have you moaning for weeks
I swear I'm feeling like the man, dog
Booty big, I couldn't keep my hands off
Baby make it jiggle with your pants off
Cause playing with my balls ain't enough no more
Tonight you better get that pussy up for show
Hoes be scheming, late night creep and they get a piece
Of the beast
Under the sheets
That's under my briefs
I know they feeling thick when they be bouncing on it
Probably hit the pussy, wasn't counting on it
8:35, gotta hit the stage by 9
Make my day
Take it out and take your time
It's alright
If you trying to kick cause you tripping it
In order to leave how we know you with the business

[Hook]