[Hook]
Real c-l-u-bs that's where we go
Drop raw b-e-a-ts live at the show
Real E-m-c-e-es we spit tha flow
Its KRS-o-n-e somebody say

[Verse 1]
Anytime you want the raw b-e-a-t I bring it crazy
No if, and, buts, or maybes
The whole spots hazy but ain't nobody lazy
Blaze me
I'm expressing the talent that God gave me
Divinity
The devil on every level is jittery
No I'm not the average emcee, I'm the epitomy
Think not, come to my spot see my delivery
Then count back thirty years, lyric artillery
People tried to get rid of me, diss me and belittle me
But look a where these people were going
Nowhere quickly
So back to my delivery
I mastered the enemy
When I mastered the inner-me
So what are you telling me
I spit positive energy, the light is sent to me
I will glow and grow into the next century
Enter the dragon, enter the naga, enter the centre-me
KRS is the realest emcee you'll ever see

[Hook]
Real c-l-u-bs that's where we go
Drop raw b-e-a-ts live at the show
Real E-m-c-e-es we spit tha flow
Its KRS-o-n-e somebody say

Welcome to the boom bap, yo who's that over the two track
I'm hungry for the boom bap, you knew that shit so I dos that
The hood is where I grew at, enlightenment I pursue that
That boom-bap I renew that and microphone check one-two that
That writing emcee and grafitti DJ and we does that
Yo move back
I rock the city but I ain't no new jack
I prove that
Your rhyme get batter with time yo who that
Gimme the mic
Beat loud with a crowd well Imma move that
Cats don't do it like this no more
But KRS will spit the raw
You ain't with it, get the door quickly
We ain't playing around with this sound
We breaking it down
And the real streets the block
And the hood is standing with me
So miss me
Mi-mi-mix me like hickory dickory dock, hip-hop
Yo hold up hold up hold up
That shit is raw
Imma go to a higher level on it
Right now
Yo gimme that track right there yeah
That one