[Intro: B.G. & Baby]
Cash Money slangin nine nigga
(Off top playboy)
H.B's and The B.G.'s
(What's happing little B.G. bring it to these niggas)

[Verse 1: B.G.]
When I got that iron in my hand I'm goin' to slang it
When I got that drama on my mind I'm goin' to bring it
I ain't backin' down from no nigga that's nathan'
If the nigga say I ain't bout my business look here he hatin'

[Verse 2: Baby]
Coming uptown playboy we gonna slang it
If I catch down nigga bad we gonna leave ya stankin'
Fucking wit my H.B's nigga I'm gonna bring it
Rollin' uptown stay strap and keep thinkin'

[Verse 3: B.G.]
Cause a nigga get stolen
Better yet get takin'
Paper is burn
They come fast, ya can't shake it
Picture this my brother Cash Money done went nation
That come's from seven hard years of dedication

[Verse 4: Baby]
Fuckin' with B.G. nigga
I'm puttin' on your face and I'm a kill me a nigga
That's believin' worth six figures we call hard hitters
We uptown riders and we real with this nigga, nigga

[Verse 5: B.G.]
Police can investigate but they ain't gonna find shit
But a hundred bullet shells without a fucking fingerprint
This Hot Boy click laid back and spy on niggas
We see them workin' on somethin' look here we riders
Ain't like workin' niggas
Any block with a flussy
That goes for the boss too
We ain't got no picks to choose it
We get cha if we gotta
Wig split cha if we gotta
I know you ain't got word that B.G.'s a rider
So keep it on the D.L
If you got keys don't serve nobody but off V.L
Cause they play for keeps
A one way ticket to hizell
Six feet deep
It's a filthy dirty rizell
On the U.P.T
I was raised in the streets
But I put it on my mind
By the time I was nine
I was pushin' nigga
I was slangin' that nine

[Verse 6: Lil Wayne]
Na, Na, Na, Na
Now them them don't want us
They know me and Turk don't fuss in the corners
They already know that we brothers, Blood
Or whatever you wanna call it
Click up wit my dog we get crazy like alcoholics
Plus we ballers
So whatever we spin the Lex or Benz
Its gonna be on twenny, twen, twens

[Verse 7: Turk]
Get off the block when we come nigga (nigga)
To the lane
Shots that close shop when the bullets start spraying
Run your mouth too much, better watch what cha sayin'
Like a nigga on the sideline, nigga we ain't playin'

[Interlude: Lil Wayne]
Na, Na, Na, Na
Now why O why Lord
The nigga wanna try and die Lord

[Interlude: Turk]
Niggas wanna learn hard way
Give it to 'em like that
Make 'em suffer
Put that bitch wit a bag

[Verse 8: Juvenile]
I guess you probably standin' there sayin, "Who's the muthafucka?"
Nigga Juv's the muthafucka, that'll bruise a muthafucka
Either there's been a lot of cross-firin' in the bricks
And I'm gonna kill me a nigga
If they put me in that shit
Look I'm gonna tell ya like I tell my folks
Play with me if you want but Cash Money goin' broke
Even if it means creepin' up slow
Bustin' out shots out my black Volvo
Fo sho, cause ain't nobody gonna run me
I don't want nobody going to tell my mama when somebody done me
She ain't bring me in the world for that
She ain't raise no ho's
She could have had a girl for that
I been realized, I'm all in
Surrounded by the camouflage, in ballin'
Make a nigga recognize, I'm starvin'
Go in and do a homicide, you fallin', stop callin'
Cause ain't no peace treaties whodie
You better not leave that forty-five at your house cause you gonna need it whodie
I told you boy, I'm a soljah boy
U.T.P up on my stomach from the 'Nolia boy

[Outro: B.G.]
Slangin' nine
Fo sho nigga
That's how we layin' it down for the ninety-eight all the way to the ninety-nine
Worldwide
Slangin' nine
All you bus pass niggas better recognize

[Outro: Juvenile]
This on here bezzeled out, ya heard me?
Ask my nigga Prime nigga
Ask my nigga Lac nigga
Ask my nigga B Dog nigga
Ask Manny
Ask Ruckus
Ask my thug Corey
Ask B.Geezy nigga
Ask Soulja Slim

[Outro: B.G.]
You ain't got no muthafuckin' heart
Got the butcher knife killin' in the back, ya heard me?
Slicing throats we doin' it like that, nigga
Ah ha, Ah ha
How you love that, nigga?
What's up now nigga?
Talk that shit now
What, What's up
I thought we was what kind of boys
Nigga what, nigga who what, nigga ha

[Outro: Juvenile]
I know yall gonna hear me all over the nation
So this is for the East Coast, the South Coast, the West Coast, over
The world
Nigga ain't no beef nigga
It's bout money
Nigga if you ain't making no money I can't talk

[Outro: B.G.]
Shut the fuck up
Nigga ain't got no words for ya
It's all about the fetti