[Intro]
You know, it’s been a while since I felt like this
The last time was high school
But this feeling I think he’s so cute
I want to tell him so bad-but I can’t
C.R.U.S.H
Yeah I got one really bad
This is how he makes me feel

[Verse 1]
He puts the beat in my heart
Every time I see him, thoughts are getting deeper
And I knew from the start yeah, from the “Hi” and “Nice to meet ya”
I was blinded by he’s features
Girls said You're wrong”
But I said la, la, la, la, la-la, la, la, la, la
She said “Ci you're in love”
But I said na, a, a, a, a-na, a, a, a, a

[Hook]
C is for your confidence-Boy I love the cool in you
R is for rumors they make-I wish that they were true
U, you put a smile on my face - you're unforgettable
S is for your sexiness
H I gotta have it
I gotta crush on you-I love me some you
A big crush on you-I love me some you
A big crush

[Verse 2]
He knows the right things to say hey
I can’t help but pay attention to everything he says
He says he has fun with me
It’s been a while since he could do this, tell me what does it mean?
My girls say "you're gone”
But I said la, la, la, la, la-la, la, la, la, la
They say “Ci your in love”
But I say na, a, a, a, a-na, a, a, a, a

[Hook]

[Verse 3]
I can’t control how I'm feeling inside-I'm off the meter
He’s always on my mind-been a while since I felt this way-ay-ay
I don't know what to say-ay-ay, when I see him
I get the chills when I look in his eyes-he’s so beautiful
He’s everything and more-when I see him every day
Hoping he feels the same, am, am-he’s a keeper

[Hook]