[Hook]
I got my R.E.S.P.E.C.T
각자의 자리에서 끊임 없이
Grinding하는 모두에게 경례
상관이 없어, 후배, 선배. You got respect from me
R.E.S.P.E.C.T
각자의 자리에서 끊임 없이
Grinding하는 모두에게 salute
상관이 없어, 후배, 선배. If you're keeping it true

[Verse]
R.E.S.P.E.C.T
Even for the rappers that used to beef with me
'세련된 문장, 고급스러운 skill로 내
적을 발라버리자' 이런 거 물론 필요해
Competition이란 이 문화를 여기까지
이끌어온 힘이니까. 하지만 어디까지
즐길 수 있는걸까? Sade, Marvin Gaye
Bob Marley fan인 내가 디스전의 결과
뒤집어썼네. 기술만 따지는 놈이란 누명
Reunion, The Grind, One Way 그리고 Drunk
등등 전부 무시하고 내 가사는
잘난 체 뿐이래. 귀는 장식품이냐고, huh?
이번엔 확실히 말해야겠어, 여기서
난 진실이 담긴 음악하는 모든 뮤지션
존중한다고 오해말라고, 이제
물론 사기꾼들에겐 I got no respect

[Hook]