[Shawnna]
Shawnna, kick hot shit for bitches, that got they baby daddies locked in the pen gone, fittin' to rot, cause he did wrong
Run up on the cops, and he hit 'em with the Glock, left his wig home, sellin' rock on the big phone
In the projects, niggas run up on your set with the tech' out, leave you wet with your chest out
Killer niggas, realer niggas, have a nigga feel a never realer nigga, drill a nigga, fuckin' with a villain, never spill a nigga
Fuck that! Nigga bust back, we in the 'Llac, me and my bitches all strapped
Puffin the sack, and we be sippin on 'gnac,fittin to react, and pop a nigga for them stacks (OOH-OOOH!)
Niggas I'm with, they put the fifth to your whole melon, I'm with the murderers and known felons
I gotta pop a nigga, drop a nigga, rock a nigga, shock a nigga, lock a nigga, fuck a nigga, cop the floppin' nigga
Roll for my bitches, that be droppin' in the strip clubs, tryin' get 'em a lil' somethin'
If you gotta take it off, take it off like a boss, for the big ones, then you get you a big gun
Motherfuckers in the Chi', like to put it yo' eye, if it's on bitch, put it straight to you, don't miss
Now you fuckin' with them gangsters, ballers, hoes, hustlers, bangers, niggas that with them real motherfuckers, like whoa!

[Hook 2X: Ludacris]
It's real real - on the block I been up for days
I gotta keep the steel steel - in case a nigga wanna get in the way
So now what's the deal deal?  On the street you got nothin to say
So when I see him I'ma get him (WHAT!) drill him (WHAT!)
Fill him fill him (WHAT WHAT!)

[Twista]
Twista kick hot shit for hoes and thugs
In ghettoes and clubs that get crunk; for my homies locked down
To whoever hurtin in the hood and ballers with 22's on big trucks
To my thugs that call over to they mob
And to the hustlers that be servin hydro and cocaine
To my niggas that ain't hoes; if they have to
They will steal a nigga touch a nigga check a nigga cut a nigga
Pull the trigger bust a nigga, yellow motherfucker nigga
Ready to fill and spill a drink, I'm drunk go and weed it up
And I'm talkin about go like I'm smokin the bone
Full of some shit that damn sho' wouldn't seed it up
Got you feelin the holy ghost through your body
Probably reanimated with all my Legit Ballaz rollin up
Up the streets stuffed the beats
So you see them Navigators, Escalades, Benzes
Beamers, Excursions - bumpin systems TV's and them 20's spinnin
Mob for them niggas that done came up off them hard times
K-Town, West side, South side
Murder us for the money that's why I'm known to kick a hard rhyme
Whatever set you represent throw it up
If you buck or crunk then take yo' motherfuckin shirt off
Dealers get your work off; you wanna party
Full of hustle niggas killer niggas gangsta niggas chill niggas
Baller niggas thug niggas player haters real niggas

[Hook]

[Shawnna]
I'ma kick hot shit for bitches up in the industry tryin to compete me
I'm from the hood South side, West side
Where niggas'll put a motherfuckin slug in my enemy
Motown, Pucketown, do or die
The difference between a motherfuckin thug and a gangsta
One's thug in a chamber
Get a nigga stick a nigga put him in a ditch and then forget a nigga
Hit a nigga pop a nigga little with the rocket nigga
Puff pass say you love that
We in the 'Llac and put the lemon in the 'gnac
Remy and sacks that got me scummy in the back
Puffin the raps that got me layin out slacks
And it's speakin like, "Wow, that, blunt let me hit the weed"
Cause I been feelin like
Fuck a nigga bust a nigga Shawnna never love a nigga
Chi about to show the motherfuckers how to rush a nigga
Crush that put it on momma
On everything I got a thang for the drama, puff marijuana
To things Shawnna gonna throw it on ya
Flows leave you froze in a comma
We so relentless, you know Chi gone bring the business
Blows to yo' dome in an instance
Home of them Folks and the Mo's and the King's and the Fo's
And the BD's and lows and the fiends and the hoes and God!

[Hook] - repeat 2X