[Intro: Pack Strong]
Everywhere I go I got the four fifth on me
Smoking on the loud, got a lot of [?]
Hood rich nigga, so you can’t shit on me
Hood rich nigga, so you can’t get on me
Guns On Deck, I believe in G.O.D
Go against us, that’s against the odds
A hundred shot plus that’ll tear you apart
Got my young niggas with me, better get out of dodge
When you got choppers, you don’t need no aim
Left, right, left, right, hit everything

[Verse One: Pack Strong]
All my young niggas ain’t in no gang
But all my young niggas that are sure gonna bang
Crip niggas to my left
Blood niggas to my right
Everybody see green, so we [?]
You all bark, no bite
Stop playing with your life
Stop talking, killer, you ain’t got no bodies
Don’t nobody know you, nigga, you a nobody
Stop talking work, nigga, you ain’t Yo Gotti
To tell the truth, pussy, what you really know about it?
I said, I trap or die like Jeezy, nigga
‘Cause that rap shit too easy, nigga

[Hook: Pack Strong]
Guns On Deck, I believe in G.O.D
Go against us, that’s against the odds
A hundred shot plus that’ll tear ‘em apart
Got my young niggas with me, better get out of dodge
When you got choppers, you don’t need no aim
Left, right, left, right, hit everything
When you got choppers, you don’t need no aim
Left, right, left, right, hit everything
Guns On Deck, I believe in G.O.D
Go against us, that’s against the odds
A hundred shot plus that’ll tear ‘em apart
Got my young niggas with me, better get out of dodge
When you got choppers, you don’t need no aim
Left, right, left, right, hit everything
When you got choppers, you don’t need no aim
Left, right, left, right, hit everything

[Verse Two: Soulja Boy]
I’m chilling with killers, we posted in trenches
My niggas, they swerving and [?] Bentleys
Gucci and Louis my [?]
I shoot you in your kidney with the semi ‘till it’s empty
Money on me, I got plenty
[?] through Memphis, the city
We swerve in the Bentley
It’s me and Pack Strong ‘bout to get it
Nigga talking, he gonna get the hollow to his fitted
All of my niggas, they with it
We up on a mission
We come in, stacking, packing chickens
I wrap it, pack it, then I ship it
My niggas, they stacking, packing, gotta get it
Niggas talking, they ain’t on a mission
Look at my diamonds, you know how they glisten
AK-47, I keep the pistol
Diamonds on my neck, you know they official
Diamonds from China, diamonds from Africa
Whipping that dope, whipping up like a spatula
Niggas, they talking, they don’t get no money
Pull on the block and I spray with the Tommy
All of my niggas, they toting ‘em for me
Automatics, and they shooting ‘em for me
They killing shit for Soulja
I’m pulling up in that Rover

[Hook]

[Verse Three: Pack Strong]

Who the fuck called these niggas hitters?
How the fuck you niggas hitters when you niggas missing?
[?] getting money now
Me and my niggas about to go and cause [?]
You niggas say you shooting shit down
Why the fuck ain't nobody ever came up missing
You niggas little boys, I'm a mister
I fuck your bitch fast, like a twister
I fuck her friend, then I fuck her sister
I keep the loud, yeah, I keep the
You niggas tweet, so we call you sugar
My niggas lurking on your ass on the instagram
Know some niggas in the can and they going ham
Put the bands on they ass, they don't give a damn
Marching with the damn drum, cause I got the bands
Give a fuck what you say, just don't [?] hands
Homie, I don't fuck with phonies
Watch what you say, though, like Rich Homie
I ain't got to wait cause I got it all on me
Generation four Glock 40
Nigga, I'm an animal, [?] dog
[?] gorilla, trap jumping like a frog
Love to see my nigga eat, never been a hog
And guns on deck getting money over broads

[Hook]

[Outro]