1500 or nothin
Yeah, yeah, yo, yo

[Verse 1]
This one's for the people
All the bees that'll bleed and they sleep and they eat
Shit, breathe, I thought we all equal
Ain't a man on the God's green be underneath any other
I don't wanna play preacher
But, but I swear they turn a ear, when we talk about peace and love
Sometimes might need a hug, yeah we all wanna come on up above
But this ain't about Jesus
No way, no Abe, no Ike, Moses or Muhammad, yeah it's all about believin
Full steam ahead because I know the worst times are behind me
I don't wanna sound cheesy but, but, but, it's just I really mean it eh, eh
Yeah I'm tellin' I can feel it, eh, eh, it's the reason I don't sleep
I be way too geeked tonight

[Hook]
This one's for all of y'all, I'm the same as all of y'all, I'm on my shit
I work real hard and all, for every little bit that I get
But this is all I need, so sing this song with me, it goes like

So it sound like this, everybody start clappin hands, it's like, it's like
(IIIIII, I've been on my griiiiind
I can only grind-ind-ind-ind, for so long)
Go, go, go, go, go, go
Said (IIIII, I've been on my griiiiind
I can only grind-ind-ind-ind, for so long)

[Verse 2]
Yeah, about time to change a few things, we a slave to the bank
And we only wanna buy new shoes, the way that we think
We can do anything that we really wanna put our minds to
The American dream, dream, is a pyramid scheme, scheme
And it feels out of reach, when it's hard and the times are tough
But change starts with us, so yep, yep
We all want freedom
Yeah, to be who we be
I don't wanna be afraid when I speak, to say what I'm feelin
Yeah, together we're strong but divided never been so weak
It's time we get even, yeah, yeah
And really what I mean is, is, is, this change I can feel it
Yeah, yeah, Mr. President, think it's all gonna be okay

[Hook]
This one's for all of y'all, I'm the same as all of y'all, I'm on my shit
I work real hard and all, for every little bit that I get
But this is all I need, so sing this song with me, it goes like

So it sound like this, everybody start clappin hands, it's like, it's like
(IIIIII, I've been on my griiiiind
I can only grind-ind-ind-ind, for so long)
Go, go, go, go, go, go
Said (IIIII, I've been on my griiiiind
I can only grind-ind-ind-ind, for so long)

[Outro]
So, it's not about, fame and, and fortune
It's about believing and believing in yourself
And understanding that, that this life is, it's life
It's, it's liberty and, the pursuit of happiness
And, happiness isn't about getting what you want all the time
It's, it's about loving what you have
So Get Ready, It's a New Day

(IIIIII, I've been on my griiiiind
I can only grind-ind-ind-ind, for so long)