[Intro: Wooh Da Kid]
They say they looking for a gangsta, well that's me
Trigger finger's an addict, I think it OD'd
They say they looking for a gangsta, well that's me
Trigger finger's an addict, I think it OD'd
Fuck a dub's at? I need a OZ
And I don't puff-puff-pass cause I smoke weed

[Hook: Wooh Da Kid]
North Jamaica, south Jamaica, south Atlanta, north Atlanta
West Atlanta, east Atlanta, that's my homies
Waka Flock make you hop, Capp peel 'em, make you rock
Wooh Da Kid Just went crazy, he done OD'd
Smoking marijuana, we just OD
Blowing on the ganja, we just OD
Southside on the track, he just OD
Gucci Gucci want a pack, that's my homie

[Verse 1: Wooh Da Kid]
They say they looking for a gangsta, well that's me
Trigger finger's an addict, I think it OD'd
Fuck a dub's at? I need a OZ
And I don't puff-puff-pass cause I smoke weed
Anybody wishing death, I hope I stay alive
Ink drops on the paper, make it come alive
You niggas salute me or just shoot me
Or I'ma have to send a hundred slugs through ya hooptie
Black Brick Squad chain, I just OD'd
Heroin thoughts like Elvis' [?]
Wooh Da Kid, Capp, Flock left it lonely
And we gon' wake the game up cause they still asleep

[Hook: Wooh Da Kid]

[Verse 2: Lil Capp]
I done OD'd, bottle so deep
Pop one, pop two, naw, pop three
Get out of line and I'ma let Nina burn ya
Have you rolling down the river like Tina Turner
I'm biting down, me and Wooh Da Kid
Split a 10-pack cause we do this shit
I'm geeking like a nerd, you can call me Screech
But I done OD'd and I can't sleep
My PO tripping so I can't smoke the green
I got a ounce of lean, mix it with the beans
I'ma bet that you can't hang, you got to show me
He done passed out, he just OD'd

[Hook: Wooh Da Kid]

[Verse 3: Waka Flocka Flame]
I'm fucked up on Grey Goose, Patron and Hennessy
X pills and marijuana, Lord, I love that purple weed
Y'all niggas not fucked up, we live life wasted, nigga!
Quarter pound of kush [Aye, whatchu do, Flocka!?] (Waka! Waka! Waka!)
OG, them OZ's, catch me on Grove Street
Southside track, well, it cost about 10 G's (Sizzle)
I'm a ball-a-holic, I'ma OD on Louis
OD on Gucci, OD on True jeans
FLOCKA! FLOCKA! FLOCKA! WAKA! YUH!
Make the club go ham!
Mix the gram and white (Boy, you crazy) I don't give no damn!
Taxing all my verses, you can call me Uncle Flocka Sam! (2x)

[Hook: Wooh Da Kid]