Dt-Dt-Dt On your mobile phone
Dt-Dt-Dt On your mobile phone
You fuck my man and wreck my home
I'll get my bro to rob your phone [x4]
You big dummy

Now could it be that me and he
Are tighter than J-Lo in her jeans
And could it be that me and he
Are tighter than R. Kelly in his teens
You fucking with my man
And you text him all the time
You might've had him once
But I got him all the time

Dt-Dt-Dt On your mobile phone
Dt-Dt-Dt On your mobile phone
You fuck my man and wreck my home
I'll get my bro to rob your phone [x2]

U R A Q T
Is your Dad a dealer cause you're dope to me
You throw them balls across the country
You win gold medals for when you're with me
You big dummy

Right then, it's on [x8]

He ain't no word for Scrabble
You don't get points for doubles
Menage trois Lalalalala
I'll bill you for your droudles
You done lost your marble
Like a ball I'll make you dribble
Your the shrapnels in the rubble
I'm a raging bull, a rebel

It's all about the low-blow brown girl
The no blood, no love hot girl
The juking juking jumping off the decks girl
The juking juking jumping off the rocks girl
You big dummy

U R A Q T
Is your Dad a dealer cause you're dope to me
You throw them balls across the country
You win gold medals for when you're with me
You big dummy

Right then, It's on [x16]
You Big Dummy