[Intro: Memphis Bleek]
Yeah, motherfuckers
That's what y'all want right
That ol' gangsta, that ol' gangsta
Check it out now yo, yo
All I need, bomb ass freak, nigga
Hold me down, nigga
Hold my heat shit
Stash a brick, blast the clip
Gangsta shit, yo

[Verse 1: Memphis Bleek]
I need me a straight down girl, get dow, girl
One to hold me down, one I can count on
I'll even teach her how to load the Glocks
Sophisticated school girl
Be on my block
Rocking bracelets, anklets the basics
Petite nice body, skin and face sick
One I could shop with
Go uptown and cop with
She not a thug girl but my down chick
She know how to roll the weed but don't smoke
She know how to cook the coke and bag dope
Screen my calls
Flip on me when I'm wrong
Talk shit through the night
Throw it on me on the morn'
She like it from the back
With my fingers in her hair
I love it in any position
Ma, I don't care
She like when I shine up them jewels that blind her
And drive by the projects while a nigga hollar

[Chorus: JAY-Z & Memphis Bleek]
(Yeah, yeah, yeah)
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
My pretty young thing
Yeah, she's my gangsta bitch
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
She's my pretty young thing
Yeah, she's my down ass bitch

[Verse 2: Memphis Bleek]
Yo, you know how I do
Dillinger duece duece
One in the sleeve, one in the construction boots
My shorty, tote two, that's what she do
One in her purse and one in her Gucci goose
I keep her Prada down
Bitches wanna hollar now
She back out the step
When yo niggers crowd around
That's my road dog
And you know I unload for her
She hold me down anytime I call for her
Like at the time when I crashed the Jag
She brought the Yukon 2000 black
Through a screen and a DVD
Twenites on the truck that'll piss you off
In return I sent her on a tour thru Sacks
With ten grand shopping spree to get back
I brought her a five that look nice when she drive
Put a Glock on the dash, nigga
Watch the stash, nigga

[Chorus: JAY-Z & Memphis Bleek]
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
My pretty young thing
Yeah, she's my gangsta bitch
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
She's my pretty young thing
Yeah, she's my down ass bitch

[Verse 3: Memphis Bleek & Amil]
Ayo I ride for my lady
Die for my lady
Hold my 380 baby
This what the game made me
I'm a hustler, love it or not
I be thuggin;, huggin' the block
Glock bustin' running from cops
Uh, I'm right beside
Pull the gat out of my Prada purse
Clock 'em, clock 'em
That's gotta hurt
I'm your down bitch, your accomplice
Ride for you, baby and that's a promise
I got your back, nigga
I'm the one you trust to count on your stacks, nigga
Cook your cracks, nigga
I park the Pinsky right off the pounds
Let off hollow rounds if shit goes down
I'm with the robberies, holdin' banks up
This pretty young thing gonna keep it gangsta what?
Uh-huh, yeah, Amil-lion wha-what?
Amil-lion, Memph man what? uh

[Chorus: JAY-Z & Memphis Bleek]
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
My pretty young thing
Yeah, she's my gangsta bitch
I let her drive the V
She's my pretty young thing
I let her ride with me
She's my pretty young thing
Rap or robbery
She's my pretty young thing
Yeah, she's my down ass bitch

[Outro: JAY-Z & Memphis Bleek]
Ride with me my pretty young thing
Let her, my pretty young thing
Let her, my pretty young thing
My down ass bitch