[Hook]
Are we sinners in the hands of an angry God?
Or is God being judged by a sinning mob?
If God ain't good, I must've missed something
If God ain't good, I must've missed something
He been good to me
You been good to me
Are we made in the image of God?
Or is it God that's mimicking us?
If I'm what's good, I must've missed something
If I'm what's good, I must've missed something
He been good to me
He been good to me

[Verse 1]
I used to be scared of the Holy Ghost
Now I'm just scared of them holy folks
Should we disagree with God or should we change Him?
If I'm made in His image, then why do we feel like strangers?
Is He a battery that's charged by my faith?
Who's at fault when I race but then I fall on my face?
Is God to blame for our intentions?
Like scientists didn't bless the world with eugenics
Like media ain't teachin' a new religion
Every time I watch the news, I'm gettin' a baptism
Should I prophesy or should I proselytize?
Is it culture engagement or compromise?
When I keep the doors closed, I'm gettin' ostracized
But when I open up the doors, I'm gettin' colonized
Everything is straight when you have no moral compass
Everything is new when you thinkin' like Christopher Columbus
Is everything just a social construct?
Who's allowed to judge our moral conduct?
I was an insecure boy who just thought he was a genius
But always pissed off, that's because I thought with my penis
It's all strategic, I'm just asking us the reason
Share my faith on the track, I'm just exorcising demons
Yeah, never told a lie
Uh uh, never told a lie

[Hook]
Are we sinners in the hands of an angry God?
Or is God being judged by a sinning mob?
If God ain't good, I must've missed something
If God ain't good, I must've missed something
He been good to me
He been good to me
Are we made in the image of God?
Or is it God that's mimicking us?
If I'm what's good, I must've missed something
If I'm what's good, I must've missed something
Yeah, He been good to me
Okay, let me preach

[Verse 2]
The rich man wants more
The poor man wants your's
The oppressed want a peace of mind
The thief want a piece of mine
The doubter needs a little faith
It ain't cliché to say "let us pray"
Who gon' call the fouls if everyone balls out?
So open-minded that your brain falls out
G.K. said it best, nothing fails like success
And being consumed with it is much worse than death
They killin' you with money, they just bought your silence
You can't worship in a land full of pirates
The more booty, I promise the more scary
Success can be a drag, you can ask Tyler Perry
We sell sex then get mad that we have rapists
We promote greed then get mad that we have haters
I hated the police until a brother got robbed
I hated welfare until a brother lost his job
When I'm at work, I watch my pockets for them corporate thugs
When I'm at home, I watch my back for those crips and bloods
If my words bring conviction, let's call in context
I'm realizin' life is pretty complex
Thoughts of abortion taught me sanctity of life
A divorced man and woman taught me how to love my wife
A poor man sat me down and taught me about dignity
A blind man's vision taught me all about imagery
It'll leave you broke, that's why it's called the record industry
I forgot who I am trying to get them to remember me
We adapt and evolve, the problems just revolve
Industry creates the very problems that they try to solve
I know I trace my image way back to the beginning
We done lost so much, we don't know when we winning
I'm hated, I'm loved, I'm both, I'm a challenge
I'm clean, I'm redeemed, I'm a recovering addict
I have baggage, I am damaged, I am unequally balanced
I'm a servant, but I have a room in the palace
Uh, never told a lie
Uh, never told a lie

He been good to me
He been good to me
Alright, let me preach

[Sample]
When I think of the goodness and all He has done for me
My soul cries out "Hallelujah!"