[Hook]
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me

[Verse 1]
You won't believe if I told you
JME thinks he's a road yout
Talking about punch in the face with the house keys
When him and his bredrens roll through
He'll get a box in the durag if man ever try bring shit my way
I saw man rolling around on some electric skateboard ting last Friday
Neek, Xbox freak, he ain't got girls, man don't beat
He could never go bar-for-bar with me
You're mad, fatality
Man's really out here, cuz
JME's riding his likkle buzz
Real recognize real, rah
I swear that's Jme
(Ayo, ay, Jme, ayo bruv)

[Hook]
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me

[Verse 2: JME]
Wagwan bruv
(You good?)
Yeah, alright
(Can I get a pic? Get a pic?)
Love
But have you got my album, bruv? (What?)
I just had to dismiss some youts back there
Cause they thought man was Skeppy
Asked man for a pic just cause they saw man taking a pic already
Moving bready
(Blud, that's not me, that's them)
Sick
Asked man for a pic, now you wanna switch
It's too late for all of that, bitch
Your cover's blown, fix up quick
Make up your mind
Some full time idiot
But some badman part time

[Hook]
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me
I heard they wanna war on the streets with me
I heard they wanna war on the beats with me