[Verse 1: Kardinal Offishall]
They go, they go
Came from the hood ain't never sold blow (no)
Get it so fast that it look slo-mo
Even though I'm on your telly I ain't doing it for show (uh uh)
Here I is, here I is
Shooters put the Glock down, you know what it is
Take your trap money, throw parties for the kids
Spread a little love, give them a reason to live (ey)
Look momma we made it, she said no you blessed but the man dem still sell dope
This a win-lose, double-edged sword thing
Damned if you do, damned when you get more things
Damned if you don't, damned even if you try
So I give a damn but I put a finger to the sky
Lured to the left, lured to the right
Add another finger hold that bitch to the light

[Chorus]
All I ever wanted, was to get that money
And now that I got it (got it)
The whole world look funny, oh well
I just pour a little liquor for the homies who ain't here tonight
Two shots, one love for my people tryna get it right

[Bridge]
On me, got a lot problems
Nothin' that one shot of liquor can't solve man
On me, got a lot problems
Nothin' that one shot of liquor can't solve them
Man, COD, COD, COD
I need to get that COD, COD, COD
I need to get that

[Verse 2: Kardinal Offishall]
I don't care, I don't care
I hear all the fuckery but keep it over there
Cameras off, still a rude boy I swear
Rappers getting in trouble with chicks in their ear
Man get hype start to feel themselves
Tell people keep it real, them then real themselves
You can see them try to live a bad man life
When they go to jail they become a bad man wife
Bad man keeper keep, bad man friends, if you want a bad man, sell til bad man ends
Me? I ain't study in the bad man trends but a bad man asks you a why you [?]

[Chorus]

[Bridge]

[Verse 3: Kardinal Offishall]
I hear them talk, I hear them talk
I ain't really studying how waste man walk
Loading up the clip because I need another shot
Black cat, 9 lives, one love, 2Pac
Biggie lookin' down tryna see who in his spot
You can hear him laughing with Jesus on the block
You selling you soul trying to make another knot
You the man right now but you temporary hot
Fire works bust when the squad gets working'
Chicks spend money when the broads get twerkin'
Rude boy Kardinal still the same person
Power to the people till jock close the curtains

[Chorus]
(Raybans on and I'm lurking)

[Bridge]