[Verse 1: Kardinal Offishall]
Offishall (right)
Nappy heads true to the words aristocrate (true)
Brother function with an automatic slang
Yang makes the ying, we slang rhyme banging off the walls
Like Brooklyn Smalls, yo we Biggie
Yo must trust bust, though it's my time to bust too
Hustle you I must, cause your crew might get dust too
Frustration, cause I can't make a mil
Without Jully burst, follow a my burst, try burst
Makes my niggas crackhurst, and dispersed in the realm
My timing is perfect like synchronized rewinding
Of my lining (style), moving (style)
Like keys we the freshest, believe it or not like Ripley's
Yo, them G's ain't really heard about my (flow)
Cause they too hardcore to (know)
That I am the flow (pro), my bro pocket stretch like Armstrong
Yo my niggas got it going on, it's right where I belong
On top, never will we be stuck at number ten
Number one is where start and number one is where we end up
And up friend up, niggas fronting jewels (lets do this)
Cause my crew will bring the real ting

[Chorus: Kardinal Offishall]
We always look like we have a million
We gets down yo, regardless of what we feeling
(Say what?)
Real niggas make moves by the hundreds
We straight up or you blunted, yo this is how we run kid
We always look like we have a million
We gets down yo, regardless of what we feeling
(Say what?)
Real niggas make moves by the hundreds
We straight up or you blunted, yo this is how we run kid

[Interlude: Kardinal Offishall]
Yo babes, what's up?
Nothing much, what's up with you?
Yo you ever hear this nigga named Afrolistics?
No, who's that?
Yo check this shit out, aight!

[Verse 2: Afrolistics]
I consume the hydro weed, for hyper speed
Afro and Kardinal, two officials making the new breed
Circle productive, poetic structure
Always intent to blow you out the frame
We tied you down, I contain
Paranormal and F.O.S. are out for the platinum, that be framed
We scoped out the terrain, to find niggas that was slain
Serving 25 to lifers, for they weren't sufficient writers
I be pulling all nighters, to increase my penmanship abilities
With no trace of leakage, my CPU
Fully programmed, while yours suffers from (glitches)
You love to chat, no you getting popped from the hinges
You entered the game you couldn't handle, now you shitting
Cause you got disqualified from your mission
Now listen, Aftrolistic only operates on precision
Hibernates only with those that have ambition
Never ass kissing, unless it is my wifey
Rocking beats with ease, like Saukrates
It's all about the connect of the two families
The scholars with the entities collecting the cheese
Equal ways, 3-60 degrees
Our anthem is, vandalous marvelous
Pass the trees, it's all about the will
And this is how we chill, with our players on Capitol Hill

[Chorus: Kardinal Offishall]
We always look like we have a million
We gets down yo, regardless of what we feeling
(Say what?)
Real niggas make moves by the hundreds
We straight up or you blunted, yo this is how we run kid
We always look like we have a million
We gets down yo, regardless of what we feeling
(Say what?)
Real niggas make moves by the hundreds
We straight up or you blunted, yo this is how we run kid

[Outro: Kardinal Offishall & Afrolistics]
Yeah
Yeah yeah
Kardinal Offishall
Afrolistics
F.O.S. Crew
Paranormal
This is how we do
The Circle
Don't stop baby, KC and Thomas
Choclair
BJ Supreme
Lock Jaw
Bucktooth
This is how we do
This is how we do this
For real
Nigs from outta town
Yeah