[Intro]
Swag,Swag

[Verse 1: Slim Thug]
Swag
Bitch I'm fresh up out the bag
Every time you see me I be fresh up off a tag
I keep a do fifty, keep them hoes on dick
I keep a fly ride to keep them saying it’s the shit
Stay clean I'm a O.C.D nigga
Don't get it twisted cause I kick it, I’m a G nigga
Say you fly, you ain't G6, that's me, nigga
Belt a stack and the shoes two g's nigga
See, nigga? My swag got ya budging
And you ain't gotta like it but your bitch sure love it
It's nothing, it's nothing, it's nothing when you’re hustling
I stay O.C.D so stay the fuck away from me (haan!)

[Hook: Killa Kyleon & Slim Thug]
X’s [?] for the stacks, dubs for the women
All on dick, g's how I’m living I'm a street nigga
With a lotta cream
Stupid with a bunch of guap that mean I got swag
Bitch we turnt up
These niggas cut down
Oh that's your main ho?
She's just a bust down
I’m a street nigga, with a lot of cream
Stupid with a bunch of guap that mean I got swag

[Verse 2: Killa Kyleon]
Real nigga, one hunnid
99 ain't adding up
Chase the paper I'm speeding, nigga
Looking back when I pass you up
Now pass the cup I'm leaning
Two zips I'm dreaming
With a bad bitch, your last bitch
She mine now cause I cash-get
I'm talking money, you talking slow
They all ears, I'm talking more
Your pockets quiet, they speechless
What the fuck are you talking for?
Fresh like I hopped out plastic
Stuck on the ground like velcro
Pedal to the floor, I'm mashing
And that red coupe look like Elmo
Street nigga not no sesame
Money-making my recipe
Garlic weed and that french toast [?????]
Making bread my specialty
All I do is count like Dracula
Get more, get more, stack it up
Money make her come, she freaking
Reverse, reverse, back it up
She wine fine, Moscato bottle
My neck, my wrist like Colorado
Rocky nigga, I'm Stallone
Syrup my soda, kush my cologne
T-E-X-A-S, nigga, run that bitch like Jay do [??]
Money my main, your ex-bitch
Running that bitch like [??]

[Hook}

[Verse 3: Le$]
Brim low, let fly
Bitch you know I'm that guy
Candy drippin wet, my whip look like it just got baptised
Beatin out the trunk, you niggas hear me when I pass by
I'm super tight, don't ask why
Three blunts' smell, I'm mad high
Gucci belt on my dickies, bitches saying I'm pretty
Fat ass and them titties, got her coming outta her Vickie's
Bitches be coming and bitches be going
They loving the way that a nigga be flowing
I'm spitting the game and it's getting them hoping to
Put my peninsula up in her ocean
Hoping I don't blow, so lame
Bitch I'm swanging in your lane
Mad because they screaming L-E-Dollar and not your name
My money growing, no rogaine
Them stones whiter than cocaine
We showing naked [???]

[Hook]