[Hook]
Men, all should be
C.U.T.T.H.O.A.T

[Verse 1: Mac Dre]
Some of these niggas is gay, they switching
Bite my style everyday I switch it
Fruity ass niggas sweeter than the exit
Get slapped and cussed out like a bitch get
A Cutthoat girl, just ain't simplistic
Knew about the war when I enlisted
Fought hard for the gravy that's on my biscuit
Now I eat crab and grilled beef brisket
Can't deny this salvia on my dick tip
Or the lipstick, Backwoods got me lifted
I'm gifted, every show I ripped it
Stayed on course while you others drifted
Or rims put them on a Benz and dipped it
Or the studio with Coolio Da Cryptic
This thizz I eat got my teeth clinching
Starting player while you niggas is benching

[Hook]
Men, all should be
C.U.T.T.H.O.A.T
Men, all should be
C.U.T.T.H.O.A.T

[Verse 2: Dubee]
I'm hollering yo ho ho
Steady blowing hydro
Waving a black flag, y'all see the skull and cross bones
I knock domes, get shitty with the Committee or all alone
Gets me all up in my zone, trying to bubble up like foam
A turf gator, me any niggas lock blocks with capers
I'mma knock, knock and rock ya Amadeus
I'm the greatest, Cassius Clay this track
I'm hollering Cutthoat Camp
Nigga ain't nothing on that
Go put your bucks on that
We get down, I get down, let's get down
If she gonna get down, I get down and sit down
Boy I'm all in it
Represent it and spit it just to get it
Feel it when I spit it
If I done it then I did it
Keep it all heave ho
Addicted to squeezeo's
Boy it's all on a Beezo for me though
Chippers like it's Reno
The hustlematic addict, spiller savage
Keep it Cutthoatish, [?] till these niggas understand it

[Interlude: PSD Tha Drivah]
A nigga groovy like a black movie
With nigga in it
[?]

[Verse 3: PSD Tha Drivah]
That Remy green bout, I'm spillin' it with Furley and Dubee
I holler Cutthoat [?] 'til they bury into me
Fuck a thought if it ain't beneficiary
Experience be the teacher here
Niggas queers, bitches that's scary
I'm in a hurry trying to scrape up a treaty
Wreaking havoc on your building
I'll duct tape your girl and your children
Get the cash and a whole half a bird I'mma steal it
If lord willing [?] no killing
I'mma leave no feelings for these bleezy's
I ain't [?] shiesty and pricey
Show them, have my way
A nice little black bitch with ass and some [?]
I'm likely trying to toss dick and back her face
No chase, straight laced, from the gates we silent
And no haste and straight waste if it ain't paps or profit
These street corner cats want it, can't wait to cop it
It's Turf dough, Cutthoat we can't wait to knock it