[Verse 1: Twisted Insane]
Friday, the 13th nigga that's monster shit
Great big nigga like Frankenstein, hop in the whip with a monster bitch
Slice through hoes like Freddy Kruger, wait for you niggas like Doctor Satan
I had to come harder than your favorite rapper, that's why I kept all you people waiting

[Brief Jeopardy-styled music]

Friday, the 13th Pamela Voorhees shit
Lead motherfuckers straight to they death, call me the black Jack Kevorkian
I'm like a werewolf Michael Jackson thriller, on the full moon you can test your luck
I hunt motherfuckers deep in the woods, I even give a head start buddy best of luck
Yeah, I be in the corner like a nigga who was bout to murder you was sick
Until he get and catch a nigga slippin' he grew up in this shit and I ain't leave until the homie got a fist full of Motorola, pissed getting naked with this bitch, black man and I'ma sign up for a full-meal ticket
Got this foo' wipe out a blade so I'm knowing anything a nigga say shit he'll deal with it
Yeah, I be off of cop shit, wild shit eating everybody, crocodile wit
Get up in the morning and a nigga run a mile we can play a little game but a sin is never childish
Flow so dos know i'm too wicked, punch you in the face and make yo' ho go out and get it
Shitted on all the motherfucking competition and I look em in the face and tell em I did it, nigga


[Hook]
Night time x16
Night time shit x16

[Verse 2]
Octo-ber 31st, that's Halloween
Nigga I'm the real life Michael Myers, look you dead in the eye while I eat your spleen
Shout out to Wes Craven, Stephen King, Clive Barker and the rest that do horror themes
I be leaving motherfuckers whole body numb, when I spit you would think you on morphine, nigga
Brainsick, Muzik but homie that's all I know
Spend my time doing this rapping shit, if I didn't have this I'd be kicking doors
If I didn't have this I'd be pimping hoes put em on the block, tell em get to work
What the fuck you mean you ain't got no money? Pull out your titties bitch lift your skirt
Yeah, acting like a phantom I be at 'em in the parking lot and ready for the killin', I am like a supervillian
When I open up and drill 'em, better know who you was dealin' with, a nigga finna peel 'em, I get deep inside your mental if your money to the ceiling
Chainsaw brains raw I get ignant, fuck a nigga talkin' bout the peace shit catch em in the streets quick and it gets vindictive
Every time I catch them in the street they be cheesy at the cheeks with the peace shit
Speak with hella respect but on the phone check he was acting like a nigga with the G shit
He so wit' yo switch yo bitch ass niggas ain't fucking with me and my kind
I'm sitting in the dark room during broad daylight if you lookin' for me you can find me in the


[Hook]


[Outro]
Help me get this motherfucker out the trunk, nigga
C'mon, ttake him back here, nigga, back here homie
Shit, back over here in the dark
Ain't nobody back here, nigga. (Gunshot)