We was born in sin, we supposed to sin
Repenting, get close to Him, we supposed to win
We started this the year this shit was supposed to end
2000 and counting now I'm counting with an accountance
Several lassic albums, swear this music shit was worth it then
Now I am a boss, never forget, I used to work for them
Shout out to the music mogul dudes who let me earn for them
More important than the dough is reach back that we earn for them
Kill these rappers with this flow, somebody fine a urn for them
We burning them, we scorching them
They pass me the torch and then I'll f*cking put the torch to them
In other words, we torching them
I feel like Marcus Garvey, Martin Luther, as we fought for them
They still may recognize all this real shit that be bought to them
F.O.S, F.O.S
Freedom of speech, F.O.S
F.O.S, F.O.S
Freedom of speech, F-O-S
F.O.S, F.O.S
Freedom of speech, F.O.S
Them people f*ck with Free
I had 'em people screaming S.O.S
I say what I want, bitch
Say what you want, bitch
Do what you don't, you can guarantee we won't bitch
I say what I want, bitch
Say what you want, bitch
Do what you don't, you can guarantee we won't bitch
Bitter rapper, I broke the mold
Played the game right, never broke the code
O.J Simpson, yeah, I had that white on a open road
Alphabet soup, nigga, o's and o's
Ripping in the kitchen better hold your nose
Got a five year goal
Y'all perks better hope that we stick to the goal
Remoting food control
No illuminati, never sold my soul
No Buggati, still boo hotties
All over my body
Rocksmith all over my body
Over my shotty
Get them kicks from sole control
Grew around G's like
But you been knew that before I told you so
They pray five times, so heaven is where my soldiers go
I'm an open sinner, so I pray that's where my soul'll go
And no, I am not a hater so I pray that's where you all'll go