Starlito & Don Trip
I'm not into cuffin', homie you can keep her
I just wanna fuck her, ion wanna feed her
Say she really love me, na i don't believe her
Ion want her, ion want her, ion want her neither!

Starlito
Thats right i'm hard on these hoes, especially petty hoes
I need a broad with some goals 800-credit score
If you been scarred or heartbroke its hard to let shit go
So i start charging these hoes, its better than selling dope!

Don Trip
Ion want her neither! least not 'til i need her!
If she can get me jordans 'fore they drop then shes a keeper
Imma simple man swangin through this bitch like derek jeter..
Major league ballin-wouldn't buy a bitch a slice of pizza!
Oh you love me damn i'm sorry darling why ain't you say that at first???
I could give you everything you want but that shit never works!
I'm gone fuck yo' friends before you know it wish i could say i'm ashamed
I'm so into meeting faces i'm so bad with learning names..
Might make an exception maybe for lashontae heckard
Boy i hope that gal ain't crazy, if she do i still accept her
I will marry her and prolly knock her up at the reception
She don't know me but she love me i swear we got a connection (godspeed!)

Starlito
Thats right i'm hard on these hoes, especially petty hoes
I need a broad with some goals 800credit score
If you been scarred or heartbroke its hard to let shit go
So i start charging these hoes its better, than selling dope

Don Trip
I say i'm hard on these hoes especially messy hoes
I need a broad with a job car and a home
I might use a bitch heart as a stepping stone
And if a hearts a house for love ian never home bitch i'm gone

Starlito
Got turnt out by the pimp game she came thru when the rent came
Fuckin' up the rap game and still break bread hoe ain't shit changed
Get a bitch, break a bitch, thats my type relationship
Tell you bout my favorite, a sheisty bitch, no shaky bitch
She gangsta with it, prey on ballplayers, yeah she bait 'em in
Better have rich sex with her.. or she might take ya shit
Cook and clean for me, pour the lean for me, weigh the mid..
Walk a mile for me, just like child support.. she pay the kid
I grind for it, she'll sign for it, i'm in the latest shit
I can't even lie i think i love her, i just won't say the shit
Ain't nothing worse than an ole worrisome ass thirsty hoe..
Except a lazy ass crazy bitch

Starlito
Thats right i'm hard on these hoes especially petty hoes
I need a broad with some goals 800credit score
If you been scarred or heartbroke its hard to let shit go
So i start charging these hoes its better than selling dope

Don Trip
I say i'm hard on these hoes, especially messy hoes
I need a broad with a job, car, and a home
I might use a bitch heart as a stepping stone
And if a hearts a house for love ian never home, bitch i'm gone

Starlito & Don Trip
I'm not into cuffin' homie you can keep her
I just wanna fuck her, ion wanna feed her
Say she really love me na i don't believe her
Ion want her ion want her ion want her neither