Do the D.A.N.C.E
1, 2, 3, 4 Fight!
Stick to the B.E.A.T
Get ready to ignite
You were such a P.Y.T
Catching all the lights
Just easy as A.B.C
That's how you make it right!

Do the D.A.N.C.E
E E E E E E E
...

[Verse] x3
Do the D.A.N.C.E
1, 2, 3, 4 Fight!
Stick to the B.E.A.T
Get ready to ignite
You were such a P.Y.T
Catching all the lights
Just easy as A.B.C
That's how you make it right!

Do the D.A.N.C.E
Stick to the B.E.A.T
Just easy as A.B.C
Do the dance, do the dance
The way you move is a mystery
Do the dance
You're always there for music and me
Do the dance
The way you move is a mystery
Do the dance
You're always there for music and me

Under the spotlight
Neither black nor white
It doesn't matter
Do the dance, do the dance
As strong as you might
Working day and night
Whatever happens
Do the dance, do the dance
Under the spotlight
Neither black nor white
It doesn't matter
Do the dance, do the dance
As strong as you might
Working day and night
Whatever happens

Do the dance, do the dance
The way you move is a mystery
Do the dance
You're always there for music and me
Do the dance
The way you move is a mystery
Do the dance
You're always there for music and me

Do the dance, do the dance
Under the spotlight
Neither black nor white
It doesn't matter
Do the dance, do the dance
As strong as you might
Working day and night
Whatever happens
Do the dance, do the dance
Under the spotlight
Neither black nor white
It doesn't matter
Do the dance, do the dance
As strong as you might
Working day and night
Whatever happens

Do the dance, do the dance