[Hook]
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando

[Part 1]
Schon wieder viertel nach Acht, ich hab' ihn wirklich verpasst
Also aufs Ohr gehau'n, weil der Sandmann mich im Würgegriff hat
Dann steh' ich mittags auf, vor dem Frühstück wird noch gepafft
Und dreh' die Anlage auf, bis jeder Halswirbel knackt
Die Nachbarn fucken mich ab, aber, ey, ich lache sie an
Denn letzte Nacht hat ihre Tochter an der Stange getanzt
Ich komm' von Sitzen bleiben zu bis ich reich bin
Okay, ich fick' nich' alle, doch ich fick' die meisten
Bademantel von Hi Kids, Badeschlappen von Hi Kids
Bulle klopft, doch ich entscheid', wann diese Party vorbei ist
Das der Fick-dich-Status, Lick-Dick-Status
Krieg' den Arsch so oft geküsst, hab' Lippenstift auf meinem Anus
Mama weiß heut, was ich damals meinte
Als ich sagte, dass ich für die Schule keine Zeit hab'
Bus verpasst, doch 'nen Masi gekauft
Und wenn die Snobs mich abfucken, kommt der Asi halt raus, ah

[Hook]
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando

[Part 2]
Mit roten Augen in den Spa-Bereich
Werden wie Aliens behandelt, denn die Straße bleibt
Ich lass' die Pizza auf die Suite liefern
Und ruf' den Techniker, damit ich PS4 spiel'n kann
Werd' öfter abgeschleppt als jede Bitch
Aber Hauptsache ist, ich parke direkt vorm Ritz
Krieg' nur noch gelbe Post von Inkasso und Gericht
Aber Fick-dich-Status heißt, ich mache weiter nix
Keine Cashfrage oder Geschlechtsfrage
Du brauchst nur Eier in der Größe einer S-Klasse
Bin am ball'n und dem Lord grad so nah wie noch nie zuvor
Denn ich steig' öfter in den Flieger als Serena scored
Aufm Court, Sikk und ich an Bord, fra, ich hab's geschwor'n
Zwei Finger an den Kopf und ich beginn 'n Mord
Ich trag' mein'n Schmuck auch nachts
Damit ich weiß, es ist wahr, wenn ich im Traum aufwach', ah

[Hook]
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando
Bleibe weiter rich, ich hab' den Fick-dich-Status
Mach' keinen Finger krumm, auch nach der dritten Mahnung
Von schwarz im Bus zu 'nem schwarzen Lambo
Lass' Packets laufen, so wie Lieferando