[Verse 1]
Yeah, my creator gave me the gift to create
In this mind of mine apply to our escape
In an atmosphere that wouldn't hold our weight
If I leave from here, I'll call when I'm safe
Knocking on the door, hoping someone answers
Yeah, I call that faith
This mouth of mine has turned down water for wine
I still recall that taste of bittersweet
Like when I realize you'll never be as perfect as the one that invented me
And a world full of temptations can make you feel so incomplete
Grew up to better than me, go farther than I can go
See farther than I can see
When my days draw to a close, breathe longer than I can breathe
And I'm fine with that
In the event I decide to move forward what you've done
They can rewind it back
And I'm a proud parent now as I was a proud parent then
I saw you grow up to become the kind of king that I knew you'd always been
Indeed, there's a finish line for me, but for you, there's no end
So, perhaps all that work that has been done was a win
And although my intentions were for good, it still brung us to a sin
But I'll pay for your mistakes as long as this world continues to spin
As this vessel of mine breaks down, I know you have never been
I'm sure as Multi is your home, hard times will come again
I set aside a book of rhymes that'll pave the way for now and then
I know forever is a mighty long time—so where should we begin?

[Verse 2]
—On the Southside 'cause I'm a country bumpkin, bumpin' out the system, fuck if they don't listen
We done came a long way from niggas throwing CDs out the window like I made a frisbee
Better than veteran rapper's favorite rappers
Conscious or trappers and I'm Mississippi
Dirty Southern mothafucka kicking
Like a red bucket with white top chitlins
Shittin' on niggas, my rhyme flow
Hands-'hind-back, eyes blind fold
Mind, body, and soul connected to the Most High
Even when times got low
Uhh, look how they hate me, but copy me
Possibly I was the one with components and properties
To be the greatest of all time, but you won geography lottery
So I keep kicking, flipping tables, chosen and favored
Fuck being major when giant is greater
Fortune and fame but you fuck for the label
Truth is what made me
Settle down, settle down, I was angry but I'm better now
Niggas talking raising bars, mine amongst the stars
Give it time to level out
If you worried about the flow, I'll make a beat
Write you a hook that you repeat
Even go as far to drop a mixtape that you re-do
Never credit me, separately sold
Slick as the Giuseppe on slippery floors
Mop by the buckets that I used to hold
While dreaming of plaques and selling out shows
Multi-alumni forever the fours