[Verse 1]
I feel again anytime for me to rewind like you were my life
I did you so much, I feel like your mama
My friends are my family then I'll be fine
So I met a guy, his name was white
He loved me and I put him back for his sake
Cause he was so good at being so bad
He drove me crazy like being a cab
He went outta town
Told me that I was the only girl that he want in his life
And I was naive and yes I believe
All the B.S that he was telling to me
Taken without but I was wrong
He didn't know what he had till I was gone
I hope she was worth it, he had me cursing
And when I see cupid I tell him in person
(haha) like this

[Chorus]
Love is so S.T.U.P.I.D
Oh love is so S.T.U.P.I.D
Oh love is so stupid
Cupid, what's the matter with your aim at my heart
Just a game to you
Love is so stupid
Keep on missing every shot you take of my heart
And just break it in two
Love is so stupid

[Verse 2]
I'm so afraid now to fall for him
This new one is a good guy, yeah
I already feel like we're best friends
Why am I not closing my eyes cause I'm still messed up
From the aftermath
Of what the wrong one did to me, wish I felt better
All the fear I have I know he's so right for me
Love is so (damn)

[Chorus]
Love is so S.T.U.P.I.D
Oh love is so S.T.U.P.I.D
Oh love is so stupid
Cupid, what's the matter with your aim at my heart
Just a game to you
Love is so stupid
Keep on missing every shot you take of my heart
And just break it in two
Love is so stupid

[Bridge]
Just the thought about being alone
Another valentine ain't nobody calling my phone, well
I'd rather be with my family and friends
Then let my poor heart get shattered again

[Chorus]
Love is so S.T.U.P.I.D
Oh love is so S.T.U.P.I.D
Oh love is so stupid
Cupid, what's the matter with your aim at my heart
Just a game to you
Love is so stupid
Keep on missing every shot you take of my heart
And just break it in two
Love is so stupid
Love is so stupid
Love is so stupid
(Just the thought about being alone
Another valentine ain't nobody calling my phone)
Love is so stupid