[Intro: Denzel Curry]
Yeah, ayy LoRd Lu C N
There's time's way back man
When we used to smoke kush and just chill man
In the Cadillac Seville man
Just thinkin' about the cosmos man
You know astrology is where the knowledge be, you know?

[Verse 1: Denzel Curry]
Ayy, my 8-track stay slap
Way before I had a Cadillac with hub caps
Way before a nigga ever rocked a wave cap
Way before a nigga ever had to stay strapped
'Cause these niggas still tripping, Cadillac's dipping
Still pistol gripping, foes still tip in
Got hoes in the hotel just like the Tipton
Making money off of square niggas that's attempting
To get in the box but they watching out for cops
"Yo I hear the sirens, shh, stop!"
Whoa, still, my 8-track still slaps
Runnin' through the city like a goddamn Mac
Kaleidoscope colors in a brand new lac
My goons in the back do not wear all black
They wear white suits, it's time for me to shoot
It's time that I get my bullets in time to recoup
Regroup, I go back to the club with my troops
With a bad bitch that's on my side lookin' like hoops
Who, I'm in the club, who, rollin' a dub, who?
Who got the flavor lookin' like flavor of love, who?
Who got the model? Who, who got the bottle? Who?
Who got the truth that's looking and willing to follow, who?
It's Zeltron the hell spawn, you know this, uh
It seems that I'm flying like lotus, uh
I'm fly like a bird catching locusts, uh
My 8-track stays on Black Moses, yeah

[Bridge: Denzel Curry & Anna Wise]
Way before wavy
Yeah, you know the Isaac Hayes shit
Way before wavy (leggo)

[Verse 2: Denzel Curry]
My 8-track still slaps
Way before a nigga ever had to write raps
Way before a nigga ever had to peel caps
Way before a nigga ever let the guns...
Way before, way before, way before wavy
Way before '84, '94 baby
Way before many more you were born maybe
Way before, way before O.J was crazy
Driving Miss Daisy but I'm driving the Cadillac
Two girls in the lac, hair braided to the back
Sipping on some Similac, telling me to just relax
One is kissing on my neck, the others on my nutsack
She hide the dick, so where my nuts at?
So deep inside, like where her guts at?
Like Obi-Wan I had to cut that
I bust my nut and then I cut back
Drop them off, now it's back to the mission
Let me show you how we do it, High Definition
Let the money talk, what the quarter said
Chilling in my water bed
Thinking 'bout the money, how to make the bread
For instance, a lucrative business
These niggas took the spot now I'm back with a vengeance
Then I pay off the cops, putting stacks in they pension
Look at the newspaper it's not even worth mentioning
The tabloid, I'm back boy
The 8-track slaps in my lac boy

[Outro: Anna Wise]
Way before wavy
Calm yourself
That'll make you move
[?]
Way before wavy
Way before wavy
Calm yourself
Way before wavy
Way before wavy