[Verse 1]
On everything I love, I'ma knock that pussy out
When we leave this club, ain't no talkin', I'ma be up in your mouth
You've been sayin' that I look like I know what I'm doin'
You don't seem like the shook type, it's time to show and prove it

[Pre-Chorus]
Ain't no nice way of sayin' this
Ain't no nice way of sayin'
Ain't no nice way of sayin' this, girl
Ain't no nice way of sayin', sayin'

[Chorus]
Suck a nigga's dick or somethin'
Suck a nigga's dick or somethin', forreal
Cause we're both horny and you know you want to
Promise me you'll do it, girl
I'ma put it on you
Go head and suck a nigga's dick or somethin'

[Verse 2]
Ridin' to that UGK, bass rattlin'
Watchin' how your booty sway, back and forth
My other chick, she moved away, ain't that a bitch?
So I'm rollin' with you today, fuck with your boy
Chopper on me, I ain't talkin' gun though
Dita shades cost me nine hundo
Already bust but I need me one more
Have a nigga screamin', "bailando"

[Pre-Chorus]
Ain't no nice way of sayin' this
Ain't no nice way of sayin'
Ain't no nice way of sayin' this, girl
Ain't no nice way of sayin', sayin'

[Chorus]
Suck a nigga's dick or somethin'
Suck a nigga's dick or somethin', forreal
Cause we're both horny and you know you want to
Promise me you'll do it, girl
I'ma put it on you
Go head and suck a nigga's dick or somethin'

[Interlude]
I know some cool shit we can do
Let's go to the club tonight
You go with your girls, I'll go with my niggas
And I'ma act like it's my first time meeting you
And I wanna say the most vulgar shit to you
That would normally offend you if a stranger said it
But I want you to just be turnt on by that shit
You with it? Alright I'll see you later
Turn the lights on

[Outro]
Suck a nigga's dick or somethin'
Suck a nigga's dick
Suck a nigga's dick or somethin'
Suck a nigga's dick or somethin'
Suck a nigga's dick
Suck a nigga's dick or somethin'