[Verse 1: Vado]
Yo, on square floors I serve butter to get a step
On my second call from Gudda, got six minutes left
Can't talk long, fuck it, told me he was the best
Told him on the make up, I got it covered, ya nigga blessed
We alright, yacht parties in all white
Shaking three small dice
Glass tables, the boss life
Cigar light, with a broad you call wife
Loafers on spice, when I ball, I score lite
Room Suite at the Ritz, low for business
Reservations at down, frescos, or Flemings
Hesitating the shit blow to some gremlins
Pulling up in two M's showing the emblem
With foreigner plates, your daughter is safe
Just send me a quarter mill, we could call it a day
Four acres on the hill, bridge crossing the lake
Kingpins coming to chill, grill tossing them steaks

[Hook: Troy Ave]
I don't be playing, I be cooking up the base and heading out the dooor
Niggas stay patient, get a little, get complacent, not me I need mooore
Steady paper chasin, in the fast lane racing, got to get this dough
If your real like me, then you feel like me, on your mark get set, lets gooooo

[Verse 2: Vado]
Look, Killa made some fresh cut, keep it caught
It's not you I don't trust, it's your secret thoughts
I don't fuss, save that for peoples' court
Reggie Hammond, I pop the clutch in that beetle porsche
Simply the off, the cliff, I lead you off
Bullets will lead you off, snitching like he the boss
Cut your meter off, no time for BS
Rol shine in VS, ghost-ride with GS
Slime you see us, Hamptons for the week
Partying every day, big Mansion by the beach
A glass of chardonnay, chicks standing in Celines
Two cars away from expanding once a dream
Plans, got several, my mans in federal
Hoping for five, they got checks, grams and revenue
Fam, Im telling you, need cash to live
Like the rock notch of caliber, Dame Dash and BIG

[Hook]

[Verse 3: Jadakiss]
Uh, yo, top down on to the next hood
Hop out, everything Vivian Westwood
Clearly ten steps ahead of whats going on
All they do is whisper and point when I throw it on, Corleone
Keep em coming, you know Im on my job
If it's under a hundred, it can't go in my garage
At the hearing, feel it, before you seen it on a vlog
Not the head of a gang, niggas know I'm in the mob
Do your research, Gaudier t-shirts
Stop telling on niggas, that's police work
Eye open, CBS, the spots 24 hour CVS
Im in the crib that dont show up on the GPS
I could kill you, but that'd be a easy death
Yes, I'm gonna to get it forever cuz
Money ain't one of my problems, and it never was

[Hook]