[Hook]
난 The Q-U-I-E double T
I never Q-U-I to the double T
I never QUITT. 난 E 빠진 놈이 아니니까
Never QUITT. 난 E 빠진 놈이 아니니까

[Verse 2]
Party people. 헤이, 다들 준비됐어?
모인 playa들을 휘어잡아버릴 special joint
네 번째 LP, 하지만 아직 young poet
이젠 어린 애들이 내 자리를 넘 보네
놈들에게 보여줄 건 베테랑다운 classiness
또 언제나 신인 같은 freshness
예, 이 것은 형님들의 music
약빨 떨어진 것들에게 휴식기를 주지
난 무지막지한 heavy weight rhyme을 때리지
The Q와 Jake One, 완벽한 chemistry
이 것은 일종의 톱니바퀴네
듣고 있는 숙녀들의 몸이 막 튀네
That's bounce. 이 랩 판 위의 best다운
랩 카운트 펀칠 후려쳐 like Chris Brown
Never QUITT. Realize who you rockin' with
This is The Q & Jake Uno. We got you quick, yeah

[Hook]

[Verse 2]
내 머리 위엔 항상 빛나는 스포트라이트
Like an angel. 신이 주신 리듬 감각
말하자면 내 재능은 기름값과 같지
항상 올라가니깐. 네 탑 5
리스트에 Q가 없다면 문제가 있어
그렇다고 해도 난 너의 다섯 손가락
MC들의 numero uno producer
넌 모른 척하지. 다 알면서
하하, 감히 날 부정하려 하지마
어찌 손바닥으로 태양을 가리나
넌 땀이나. 내가 너무 핫하니까
오, 지구온난화의 주범은 바로 나인가?
난 빙하처럼 녹여, 네 몸이나 마음이나
그것이 Q의 초자연적 rap phenomenon
어, 난 SC의 representer
키는 작지만 한국 힙합의 센터

[Hook]

[Outro]
난 절대 멈출 수 없어. 절대 관둘 수 없어
내 목소리가 들린다면 know that I'm the best
Never QUITT, baby (Never Quitt, baby)
I never QUITT, baby (I never Quitt, baby )