[Intro]
What does Chicago mean to me?
I mean, that's my city so it means a lot. You know
That's where I'm from, you know what I'm sayin'
That's one of the best cities in the world to me
You know, and I'm just...
It's an honor to be able to say that I'm from Chicago
You know what I'm sayin', I'm from Chicago, you know
In the mothafuckin' south side, mid-west south side
You know, it is the mid-west
But I'm from the south side of the mid-west
You know what I'm sayin'
South side, 064 061 you know that shit. You know what I'm sayin'
Lamron, front street, you know, but um yeah
Chicago means everything to me. You know what I'm sayin'
I mean my teams there, The Bulls, the Cubs, the Sox
I mean no mater what, win or lose
I mean that's my city and I love 'em
You know what I'm sayin', everybody
They hate us, they love us, I love 'em all man
You know what I'm sayin'. And make sure...
And make everybody straighten out fly right
You know what I'm sayin'. Gang shit

[Hook]
What would you do if I get in my coupe
What would you do if I win and you lose
What would you do if I woke up and you snooze
What would you do, I came through with two tools
What would you do, what would you do
What would you do
What would Jesus do, what would you do

[Verse 1]
Pull up, they like Sosa that's you, it's true
And I got on my damn True's with a few
Bands in my pants, these booled up
Tru'd up, Glo'd up, you know it and poled up
So what, nigga, Glo up, get mo bucks
No Slow bucks, Glo bucks, O bucks
Green bucks, blue bucks
Come through,Ku Klux
What would you do
If I came through with rugers

[Hook]

[Bridge]
What would you do [x17]

[Verse 2]
If ya grandma house was a two bedroom
What would you do
If you left yo toolie knowing you snooze
What would you do
If you making big moves and the cops behind you
What would you do
Take a step in my shoes, I do not snooze, I do not lose
Bitch I got gwap, what about her, what about you
What would you do if I F'd these rose, throw them at you
I'm walking with my tool in a bad mood, what would you do
Pull up on an opp and let that bitch rip like duru-duh-duh
Scooterska-scooterska-scooterska duh-duh-duh-duh
Scooterska-duh-duh, scooterska-duh-duh, scooterska-scooterska
Pull up on an opp and that bitch rip like
Duh-duh-duh-duh-duh-duh
What would you do if you was still in the hood
Pull up where the gwap at, nigga I am about that
You ain't talking 'bout that
Boy you better get that, before I let six shots at your six pack
I been coolin' where the gwap at you ain't talking 'bout that
Go where ya sky's at
What would you do
If I came through in a drop top knock ya top back