[Hook: Troy Ave & Avon Blocksdale]
New York, nigga we on that bullshit
Grip the semi and spray nigga
We pull quick
Putting holes through the heads of our rivals
Brap, brap
We leave 'em dead on arrival
New York, nigga we on that bullshit
Grip the semi and spray nigga
We pull quick
Putting holes in the heads of our rivals
Brap, brap
We leave 'em dead on arrival, nigga

[Verse 1: Troy Ave]
Troy Ave, dope boy swag
To the max with a Mac in my bitch bag
And she in that Maxim, bitch bad
Page 32, Emilio Pu ad
Fly shit, Jet Blue on 'em
Stay buying bricks
I set 2 on 'em
After 3, so we both in the air
Scott Pippen for the coke
No bullshit here, yeah
Trailblazing, weed amazing
Loud Pack flow full of freebasing
You could say that the band's all here
Hit the horn, pull strings
Got a drummer with hair
Barrels, I'll send 'em to ya'll
Play if you want, the barrels send 'em to God
Half religious, my other half is vicious
That's how I hold it down and be handling business, nigga
Fortune, no 500
CLS 550, straight stunting
10 grand in my pocket, straight fund
BSB Murder Team ?

[Verse 2: Mr. Muthafuckin' eXquire]
My college hoes say they want to ingest my semen
My hood bitches say "nigga, just bust on my face"
Timbs with loose laces
Shooters with no cases
Broke nigga, how he so bossy with no paper? Wow
Major labels clocking me, but they can get the cocky
Turned down the same deal they gave A$AP Rocky
Got my dick sucked just before I got in this booth
Ave replied Uneek I swear that shit is the truth
Ask me, son a grown man like Benjamin Button
Jump the shit out of niggas, we too deep for tussling
Knock a nigga ass out like Robitussin
A pet hyena with a gold muzzle, fuck it
Gucci dashiki's, halal from Rafiki
Easy on the white sauce, don't want it on my cheek, B
Franz Kafka novels in the projects
Ramen Noodle rap for my niggas who ain't got shit
Adderall got a nigga like Limitless
I stay fucked up, ya'll can have the gimmick shit
Huzzah, Huzzah, Huzzah, Huzzah
Troy Ave told me to put that in a verse
Is it good now?
A lot of niggas rapping
But they ain't this
I just bodied this verse
And I ain't say shit
Fuck it

[Midtro: Action Bronson]
Swerving on the fucking Jackie right now
Queens, Queens to BK
Yo

[Verse 3: Action Bronson]
I'm like a young Dino Bravo
Tan loaf press the Beamer throttle
Out the sunroof, throw a fiend a bottle
Terry shot me now I'm seen with European models
At the Riviera, I'm on my Queens shit
Pop Rocks on top of scallops, we adventurous
Fly shit, I reinvented it with sentences
Fuck a censorship
I'm in a rental with the hard white
Packed inside some gum like a dental click
How you think I'm living?
My girl a Chino in Luxembourg
Way to blow the dust right off the vino
Shoot dice but never roll for less than C-Notes
And plus we fly
Never see me in a cheap coat
Squeeze the lime in the soup to brighten it up
Clash of the Titans and I see you tightening up
Mash on the turnpike
Getting sucked by a firm dyke
Snake the hash so it burn right
It's me

[Verse 4: Maffew Ragazino]
Greg Louganis, Rich Kuklinski
Rims on a hooptie, pegs on a 10 speed
Gallon of Georgi
Lemonade simply
My true blue tre's is crispy, it's me
Talking that 90's shit, my nigga, miss me
Mobbing with them dirty ass Brownsville niggas with me
Like I don't respect niggas, I disrespect niggas
I'll 21 Mercer niggas, you know
Check niggas
Check please, roof Cris
Del Frisco, mixing Vodka with Cisco and sip slow
Niggas know
The lyrical molesting is taking place
Fucking with Ragazino ain't safe
Temporary plates on a bullshit vehicle
Hopping out with Foamposites over the pedicure
It's Senior, the entrepreneur
5-0-1 Denim sag
Fly coffin couture, nigga

[Hook]