[Verse 1: Cormega]
Even the hardest rhymers know I got desire and heart
Like John Starks when "The Dunk" had the Garden
Wilding, triumph was short-lived
But the moment is timeless
Words hold weight like consignment, never break your silence
If you face indictment, take it like a man
A thousand deaths is a lot of sweat
Satan's fire rages like the 80's
Tyson blazin souls of those that say we came from science
Ain't as wise as they like us to believe, think about it
What made us conscious?
A greater power gave us all the gift of life
Be grateful for it before the creator calls you
Witnessing a great performance, I ain't conforming
I crush those who want it then weigh the powder of they persona
On the highest scale of rhyming they've encountered
A peak harder to reach than Himalayan mountains
People say I'm calmer, I consider it evolving
I'm sick of facing charges And my mental game is stronger

[Verse 2: Action Bronson]
As rain falls on my executive trench
With the waist belt
Base dealt make your face melt
Toast to fortune, diamonds in the coffin
Pinky extended, getting twisted like a blender
Grown man rap, grown man pockets
Never catch a statutory, eating cacciatore
You like a scungill', peel when you see steel
Me, I'll squeeze it til it's empty, then I refill
We sitting, playing gin rummy
Chips of hash like the Rock of Gibraltar
Cop my pops a Porsche
Gun metal with the rocket launcher
You getting wetter when I pop it off
I got bitches making salsa sauce with they blouses off
Shorty shoot the gun soft like a mouse's cough
Four hundred dollars what it cost for an ounce of broth
Collect the paper, then I'm bouncing off
That's me

[Verse 3 - Roc Marciano]
As I mastermind, craft rhymes made of heroin
Head nod, lines on a higher echelon
With fly epilogue, Gore-tex belt checker
Bought three Hecklers, the sun gleam on my complexion
Completion, eclectic in fleeces
Expensive oils and greases, slacks with the creases
Black Jesus in Moncler geeses, sample cheeses
Antique hammer squeezing
My grammar like ham, shit is seasoned
Bitches from Greek to Polynesian
Wallabeein' out in Sweden
While I be out for green like a vegan
Stay thorough, decorated in metal
Chain yellow, grape flavor cigarellos
Days are mellow, Good fellows put change on your sombrero
Slugs out the gun bellow, hit the falsetto
I twist chickens in the six-inch stilettos

[Verse 4 - Saigon]
Use the elbow to split your wig
Male chauvinistic pig
Fuck a nigga bitch like ol' Kells did to Mr. Bigg
But I don't keep it on the low, I blow the shit up
If he show up at my crib, that old fucker get cut
Nigga, I throw a left hook at your grandpop
While Chef Action Bronson cook up them lamb chop
After that, we gonna eat a rapper for dessert
Mega got the blood of emcees on a napkin in his shirt
You're acting like you're berserk
Nigga, that'll get you hurt
Dragged all over the floor, be a tragedy for sure
They thought I might have fell off, so I had to get to work
Show em how it goes down
When I put the pronouns and them adjectives to work
Ah, niggas get murked
The perk? I think I'm blessed cause I'm eye-seeing them
Roc Mars said it's cause I got bars and I'm nicer than them
They all right, I ain't as biased as him
Nah, I'm lying; them niggas drier than psoriasis skin
Lyrically, I'm a messiah to them
Sing em a rockabye
It's gonna be Mega Action happening when you Roc with Sai
That's M.A.R.S., motherfucker, and I'm not gone lie
Hip-Hop is something we came to occupy
Tell em why