[Intro/Hook]
Yea, motherfucker's in this Paper! Buck!
But it better be no bullshit
On the real, i dont fuck with them nigga's
I be doing I dont know what's up with these nigga's
I got brick's all in my kichen, pounds up in the livingroom
Bitch i got work and right now im about to get it

[Hook]
I know, it better be no bullshit
Better be no bullshit (x 2)
I ain't with the bullshit
Better be no bullshit (x 3)
Bitch you can keep the bullshit

[Verse 1]
On the real I'm [-]
Ballin' at the [-] (Legga!)