[Intro]

(Movie Dialogue)

[Verse 1: Roc Marciano]

Check it
I learned from the old heads
Invest the overhead
Don't let what was said
Go over your head
Don't go and bet the whole loaf of bread
So many soldiers bled
It left the ocean red
Open your head
Brain matter fell on the Pro-Keds
Broker deals with the cokeheads
It came when the culture was dead
I shocked the game
Rose rose from the bed
Frankenstein with the bolts in the neck
I'm approaching the home stretch
I only took a break to give the stove a rest
I'm back in the kitchen
I'm scratching the itch
?What's on his wrist?
?Half a chicken?
It's already clicking
Nit-picking
Good shit
Like listening to some air conditioning
This is frigid
So many niggas switch
It's slim pickins
?You better had to flip?
To get a different template
I'm hot tempered
To get away from pigs as children
We hopped the fences
To the project benches
The blocks was hot
We was sprintin
Could've tried out for the Olympics, but I didn't
Took a hit, got knocked, but pops was ?dented?
Locked in prison on the block
Where White Suprem'ists rock swastikas
Even though the odds was against us
God was with us
This a dirty job
To wash the garbage niggas
I'm a target hitta
You a mark
Just like them old Seagal pictures
Just for talking shit
I'm taking all your bitches

[Interlude]

[Verse 2: Roc Marciano]
187's, felons, cain sellers
Back when 'caine was selling
Had the big chain with the name embedded
Made some bread and
My ladies aided and abetted
The Mercedes ain't rented
Bitch I was saving up to get it
This some bucket list shit
[?] just run a couple tickets
Cut some denim to tuck the stick in
Niggas putting shit out with nothing stickin
I'm by the oven
I'll have my youngins butter your biscuit
Banana clips to end your monkey bidness
[?] iron deficient
Bitch if I ain't the flyest
Then I'm lying to the mirror
Raise the bar in the game
Shit was dying
I had to make a higher ceiling
Faggot niggas out here acting like I didn't

[Outro]