[Verse 1]
It's 1:52 AM, looking at my watch
Staring at her house from this vacant parking lot
It's right across the street and the street light's blinking
I'm sinking deeper into all this crazy shit I'm thinking
Like I never want another man to touch her like I touched her
Cause I'll find the motherfucker and I'll make 'em both suffer
Maybe suffocate him, fuck I hate him, feels like they mocking me
I'll shoot her, take her purse, and make it look like a robbery
Oh shit! A car passes by slow
But I ducked, did they see me? Fuck I really don't know
I jump out, close the car door, jog up to her house
Loaded .38, duct tape for her mouth

[Verse 2]
It's 1:52 AM and I'm staring at my clock
Did I lock my front door? I better double check the lock
Cause this crazy motherfucker doesn't understand no
Showing up, blowing up my phone, calling me a ho
I'm looking out my window, the street lights are flickering
It's creeping me the fuck out, I swear I keep listening
For any little sound, God I wish I could sleep
He got it twisted over something that was never that deep
I text message who I'm dating, said my ex got me paranoid
Jumping and investigating every time I hear a noise
LOL, hope I make it through the night
Come and see me if you're up, make sure I'm alright

[Verse 3]
It's 1:52 AM and I just got a text
From my girl all upset cause of her psycho ex
When I pull up to the house and notice the broken glass
I open up the front door and see this bright flash
Heard a loud blast, holy fuck I'm shot!
Looked down, see my stomach leaking and my body drops
Girl starts screaming, didn't know it was me
She had a gun her father gave her in case of emergencies
This other dude never even made it in
He broke the glass and she thought I was him
I'm passing out, can't believe I'm shot
I see this car pulling out the parking lot

[Samples from The Pharcyde's 'Passin' Me By']
"I'm shooting for her heart, got my finger on the trigger"
"Finger on the trigger"
"Hope she gets the picture"
"I'm shooting for her heart, got my finger"
"I'm shooting for her heart, got my finger on the trigger"
"Finger on the trigger"
"Hope she gets the picture"
"I'm shooting for her heart, got my finger on the trigger"