[Produced by Thelonious Martin]

[Intro: Curren$y]
Drive In Theatre
Turn it up some for me

[Verse 1: Curren$y]
Fresh paint on the park bench
Shining in the sunlight of the morning
Under the shade of the trees, taking it all in
In the courtyard of my homegirl's apartments
Scared to play, how could you ever win?
Make a mistake, then a revision
Make them see that shit the way you did
Some of these fools will never get it
But I still give a hundred percent, just
Consideration for the listeners
Appreciation for the livers, lifers
Henny swiggers, weed smokers, Chevy drivers
Switches hitting, steady dipping, banging oldies
Throw the set up out the window, hit my horn at the homies
Just vibing, bitch, you can't kill it
Immortals chilling, portals to dimensions
Where everybody keep it realer
On this side, we don't feel you
On this side, one of these youngins might steal you
On this side, for looking too unfamiliar
Too much like a squealer, dice shooter
Debt dealers, grocery store looters, all the same, nigga
Put into a bad position, back the coolest cat in the corner
Transform into a junkyard bulldog on them
Posers, imposters, opponents, I throw them all in one-size-fits-all boxes
Coaching, while smoking notice, a weakness in your defense
We bust it open, fitting to run it like a quarterback option
These niggas not sharks, they just flounders, goonies in training
Surround them, then drown them, Scuba Steve blood hounding
Never found them, started from the bottom
Then I got rich, never dipped
Cause I'm so at one with my surroundings, bitch

[Hook: Curren$y]
You far away from your home, you's an alien, alien
You far away from your home, you an alien, alien
You far away from your home, you's an alien, alien
You far away from your home

[Verse 2: B-Real]
As I'm pulling trees out the grow room
Phone blowing up, man, how'd they know so soon?
All these ladies looking right, hydro bloom
Got these rookies fucking faded, singing show tunes
You get it from the doctor, it's a bomb sack
And if you sitting too close, catch a contact
If you want my territory, combat
I don't be losing cool, doctor is a calm cat
Every ninety days, around the way, the ladies pay me
Crazy how they make me paper, I appreciate it greatly
One day I'll retire, give some peace to those who hate me
But you're saying to the doctor, listen no one else can save me
But every now and then, someone stepping out of pocket
People want my green and my rivals try to block it
This is unacceptable, I don't see the logic
To put your life at risk, cause I'll put one through your locket
I don't beef for bullshit, I just want to treat my patients
It's a cold life, Alaska, Sarah Palin
When I give you knowledge, take it like a revelation
When the people want the best, they know that I'm the destination
Any other source will get you high, you'll feel amazing
But it's just a duplication of the fire that I'm blazing
When you're far away from home and you don't have no sources
I will dab you out if I can just find where my torch is

[Hook: Curren$y]

[Verse 3: Curren$y]
Uh, she came first, I came last
Shiesty bitch'll put arsenic in your glass, and
Propose a toast to the fact that you been smoked
You a dead man walking, sucker, you ain't even know
Never let my eyes close around these hoes
But she quick to put us down on the score
That's for sure
Tryna work her way in
Mafia ties
Helicopter ride
Business meetings in the sky
Drug dealers in disguise, this is I
Day in, day out
Dazed in the Days Inn
Letting this work play out
They download and demand more
When I put a tape out
But I'm the manufacturer
So there will never be a drought
As a matter fact, girl
You need to peep your boy out
I been considering
Assembling
A batch of bad bitches, my
Hired assassins
Looks could kill cause I just
Handed Looks a Magnum
We called her Look cause
Fuck, man, look at her
She got them looks, man
Model, singer slash actress
Dillinger's in the mattress
Gloves and ski masks
Dissipate the static
Chase away the madness
Chase bank deposits
Bitch I always got it, I just tell you I don't have it
Cause too many people was looking at me when you asked me
Hundred percent averaging
Highness, your majesty
I am this savagely

[Hook: Curren$y]

[Outro: The Godfather]
Clemenza: Looks like a fortress around here. What's with all the new faces?
Tessio: We'll need 'em now. After the hospital thing, Sonny got mad. We hit Bruno Tattaglia four o'clock this morning
Clemenza: Jesus Christ