[Intro: Fonzworth Bentley]
This is what we call, the movin' sidewalk (let's see)
Movin' sidewalk, movin'-movin' sidewalk (what am I gon' wear today?)
This is what we call, the movin' sidewalk (gimme them Cedar gloves)
Movin' sidewalk, movin'-movin' sidewalk (I'm goin' into my cashmere closet)
This is what we call, the movin' sidewalk (I got mo' cashmere than y'all)
Movin' sidewalk, movin'-movin' sidewalk (where my trousers?)
This is what we call, the movin' sidewalk (cream brown and 3 inch cuffs)
Movin' sidewalk, movin'-movin' sidewalk (where my sneakers?)
(I don't wear sneakers, I wear slippers)

[Verse 1: Fonzworth Bentley]
The rumor, of me in the Isuzu Trooper, fooled ya
It was a Porsche, a super duper
Charger, it wasn't Bankhead it was Boulevardin'
Wasn't Shawty it was comedian not it (uh-uh)
That wasn't my car, I was walkin', in velvet slippers
Know ya talkin' but before you do you need to know that
That's the type of brother got a castle wit' the cognac river
For a moat, I'll tell you what floats my boat
Purple silk linin', in, all of my coats
What you want? You want cashmere in the winter?
Really wanna know my worth? Wanna know my splendor?
Before, I deliver, gonna warn ya, may offend ya
Tesh and Kina this thang while you just a Simba
Watch the beak on this penguin his raps are sicker
I can weave in this lane, halogens I flicker
Foreign somethin' sittin' in the back wit' drivin' gloves and wavin' lazy

[Hook]
We gon' paint the town tonight
They gon' faint and fall in line (yeah)
Faded cause we're out of sight
Cool Outrageous Lovers Of Uniquely Raw Style
We gon' paint the town tonight
They gon' faint and fall in line (yeah)
Faded cause we're out of sight
Cool Outrageous Lovers Of Uniquely Raw Style

[Verse 2: Pimp C]
Pimp mode, meat good like pie a la mode
On parole, still keep me a calico ('co)
Never them gym clothes, cut Hilfiger ('figer)
Polo horses on my bed, pillow and spread
That girl want a wild bull between her legs
Too much game for them squares and them lames
I'm in a wet car (car) candy thang (thang)
Cologne smell good taste like a candy cane
Lane to lane (lane) brain to brain (brain)
I wrecked the Spur (Spur), it really ain't no thang
I'm in red, brand new, hoggin' the game
I got the Phantom, car's tuned true, just bought a Range
At press time hadn't dropped the album yet
Chinese girls love me long time on the G4 jet
Unh, ya hear that noise in my closet?
That's the gator tryna talk to this chinchilla tryin' to
Touch the ostrich

[Hook]

[Verse 3: Lil Wayne]
Umm... microphone check twelve or just one two
I am me, who are, fuck you
And I'm one too, high, you should look, up to me
My French girls love it when we smoke the oohwee (translate)
Um bellan France, I don't when we smoke the oohwee
I do me, she feel me comin' like new teeth(ow!)
I got paper like loose leaf
Come over here and maybe you can get a few sheets
My body's unique like the Sistine chapel
Fresh, likesix green apples
I should cut myself to see, if my blood's red
Baby I brainstorm, call me Floodhead
Married to the money, and if she leaves me bury me money
And when you're not good then ya arrogance is funny
And when you're really rich, then asparagus is yummy
Weezy F. Baby

[Outro]
C-O-L-O-U-R-S
What's that spell?
Cool Outrageous Lovers Of Uniquely Raw Style
C-O-L-O-U-R-S
What's that spell?
Cool Outrageous Lovers Of Uniquely Raw Style