[Intro]
Scrizzy, scrizzy S.C.R.A.M

[Verse 1]
Threw on a white T and 501 jeans
Jammed everything I can in my pockets, car keys
With a box of backwoods, weed, card, and my visa
I would never leave the crib without these, bruh
Made my way out my building full of crackheads
Picked an eighth up from the rasta with the fat dreads
Couple daps now I'm 'bout to go and stack bread
Cause a closed mouth don't get fed, that's what dad said
With that said, met up with the homie Breezy
Grabbed breakfast, got my eggs over-easy
Started plotting 'bout the next few months
Got a tour and an album so we gotta move, son

[Hook]
They out to chit-chat til the sky pitch black
But I'm busy, S.C.R.A.M
Holla back

Scrizzy S.C.R.A.M
Going heavy on the man
I'm going heavy on the man
Scrizzy, scrizzy, scram, scrizzy
Scrizzy, scrizzy, scram
Scrizzy scram
Crooked letter C ram
I'm going heavy on the man
Scrizzy, scrizzy, scram, scrizzy
Scrizzy, scrizzy, scram

[Verse 2]
Headed to my whip, give the valet man a tip
When I see a group of kids and they asking for a flick
So I pose, they get close, but they taking hella minutes though
Let me guess, camera setting was on video
Traffic on the 10, get a call from my friend
While I'm talking on the phone, get pulled over by a pig
Like a dick he wrote a ticket, but I ain't losing time at all
S.C.R.A.M, middle finger while I'm driving off
To the studio, put him in a rap
Put his first, middle, last name, number on his badge
That's a wrap, mix it down, then release the fucking track
[Scrizzy S.C.R.A.M] don't tell me to relax

[Hook]

[Verse 3]
Okay, we vibing off the demo
I'm mobbing with my kin folk
I made a left on Pico
To swoop this little nympho
We headed to the function
I love this bitch's steelo
I took her to the key club
We cut a gang of people
Easy access, homie I'm that good
Trees and capsules, liquor with handles
She's an actress, little miss Hollywood
Scenes on my mattress, iPhone classics
Damn, isn't S.C.R.A.M life fantastic
I said damn, don't we got a flight to catch
In the morning, drop the the chick off, then I dips off
I'd rather listen to my hit song

[Hook]