(Intro)

Baby...

We know how to spend that money
Woooahh

[Hook]
Here I go
Here I am
Who I am?
Nigga, I'm that
Nigga, I'm that
I'm that Bitch

Here I am
Who I am?
Nigga, I'm that
Nigga, I'm that
I'm that Bitch

[Verse 1: Briana Perry]

Tom ford on my feet on my feet
Rolex on my wrist
Nigga what you know
Bout this?
I look like, I smell like, just like money
You stunt right, and you chase like
P**sy taste just like honey

[Pre-hook]
Keep it 100, I do me
Don't need no nigga for nothing
What you see, baby that's me
And I don't do no fronting
And all my bitches, they
Know how to get that money
One time for my niggas
That know how to spend
That money

[Hook]
Here I go
Here I am
Who I am?
Nigga, I'm that
Nigga, I'm that
Here I go
Here I am
Who I am?
Nigga, I'm that
Nigga, I'm that
I'm that Bitch

Nigga I'm that
Nigga,  I'm that bitch

Nigga, I'm that
I'm that bitch

I'm that
Nigga I'm that bitch

Checkin' all that..

[Verse 2]
I'm feeling free
Every nigga wanna make me
His lady, all these drinks
Getting faded, and she know
How to make him chase it
All these niggas keep falling
That's it, the money is calling
Wanna give me all that doe
Don't want them to know

[Pre-hook]
Keep it 100, I do me
Don't need no nigga for nothing
What you see, baby that's me
And I don't do no fronting
And all my bitches, they
Know how to get that money
One time for my niggas
That know how to spend
That money

[Hook]

[Verse 3: Brianna Perry]
Broke bitches don't fuck with them
Broke niggas don't fuck with them
Real niggas, my partner them
Them new J's , we copping them

Fuck niggas, don't fuck with them
Fuck bitches, don't fuck with them
Real niggas, my partner them
Them new J's, we copping them

Outshine!

(repeat hook)