[Hook] [XV]:
I'm G. double O.D
I'm G. double O.D
I'm good, good, good
I'm feeling G. double O.D
And the girls on me look good, good, good
I show up to the club and the owner show me love and say I'm good, good, good
Yep, and all around the globe, everybody bout to know that he's good, good, good

[Verse One] [XV]:
I'm G. double O.D
I hope you O.D. off of this rhyme
Cause I'm about to change minds like cold feet
In store for a meal, groceries
But they be like, "It mostly don't come over night...mostly"
Go and get your rosaries cause I'm about to kill this, no Halo like Sony
And if your girl a little horse like a pony?
Uh hmmm, well of course start pointing
Fly boy club, well course I'm soaring
So my logo gonna always be in the air like Jordan
And they always gonna stare, just ignore them
Cause now you're with the X-Man, I'm gonna call your Storm
I'm touring, say goodbye to that hood and ummm
It's foreign enough under that hood and ummm
I feel like a dude this fly, dope and cool should feel
So I guess I feel good

[Hook] [XV]:
I'm G. double O.D
I'm G. double O.D
I'm good, good, good
I'm feeling G. double O.D
And the girls on me look good, good, good
I show up to the club and the owner show me love and say I'm good, good, good
Yep, and all around the globe, everybody bout to know that he's good, good, good

[Verse Two] [Really Doe]:
Jesus piece official and Yeezy's check
We was running shit last time I check
If I'm in the building, best believe its a check
Involved, cause we ball
She say, "My throat clear now Doe. Thanks for the Halls."
I say, "I love giving back." Baby, down for the cause
Cage us up like animals who stop at the mall
Found the spotlight at the end of the fog
They say I party too much, T.O. up in the endzone
But back when I was broke, they didn't even have a show room
Now I walk up they go, "There go Doe, mooooove."
To the sounds of C hugs and pounds
Different weight class like sumo
I'm out like UNO if you're trying to get knocked up like Juno
Unfortunately, sent you off
But you know, if Doe killing these niggas, go start the promo

[Hook] [XV]:
I'm G. double O.D
I'm G. double O.D
I'm good, good, good
I'm feeling G. double O.D
And the girls on me look good, good, good
I show up to the club and the owner show me love and say I'm good, good, good
Yep, and all around the globe, everybody bout to know that he's good, good, good