[Rapper Big Pooh]
Uh, yeah, it's Rapper
I need some more money nigga
Some of them tens or them twenties or them fifties, y'know?

[Hook]
C.O.D. Cash on delivery
V.I.P. We see it all vividly
R.A.P. You know you gon' remember me, uh
You gon' remember me, uh, you gon' remember me, uh

[Rapper Big Pooh]
You gon' remember the name
So let me tell y'all why the fuck I came
Just tryna get paid, you can keep the fame
Embarrass a couple niggas that's staking the claim
They the best thing living, respect ain't giving
Put your bifocals on, inspect my vision
Inspect my kitchen, always make the grade
Intimidated by the flow so they try and throw shame
My song's being played, I don't care how you got it
If I see you at a show you putting money in my pocket
Blowing out sockets, me and Mickey Freezy
Got niggas thinking that this shit is so easy
No you don't see me, I'm not in the public
Grew my hair out cause I knew them hoes would love it
They love it! But I let 'em know "You can't touch it"
Them tell 'em it's +Hammertime+ cause we both on a budget
Right now!

[Hook: 2X]

[Rapper Big Pooh]
Cause I'mma do what I do
You wanna talk politics? I can do that too
Wanna speak about a clique? H.O.J.'s the crew
And since I put +Sleepers+ out I been a bit brand new
But you knew, you kinda see how it grew
Make it back for round two is just a limited few
Only know what's on the tube, you got a limited view
I ain't mad, I understand how your judgement is skewed
How you preach from a pew, how you teach from a desk
When them chicks grow up it's called leaving the nest
Watch 'em spread they wings, then fly away
And hopefully I see my child do the same one day
It's a shame I say in this game I play
Seems one too many people done lost they way
Done lost they pay then lost they mind
Once your mind start to go it's kind of hard to find

[Hook: 2X]

[Big Dho]
Yeeeah! You gon' remember us nigga
You gon' remember me nigga
It's Big Dho staring the commissioner nigga
Like I said...
9th! What up son?
H.O.J.'s in this motherfucker, man you know we happy man
Pun intended motherfucker
What up Rapper Big Pooh? My nigga, what's up?
What up Jozeemo? What up L.E.G.?
What up Away Team? What's going on Sean Boog?
Khrysis what's good?
Foreign Exchange what up? What up 'Te?
What up Chaundon? What up Scudda?
What's going on D-Brock? What's popping baby?
Y'knahmsayin? Bizness where you at? Where St. Louis at nigga?
It's all good though, E. Jones, Jersey, what's good?
That's what we do y'all, you gon' remember that
I guarantee it nigga, Mickey Free!
Be more nigga, better be more careful