[Intro: {Sample}]
{Breathe}
Uh huh
Cause I'm a human grease horse of course
That's nasty bro
Ayo Jay I love everything but the haters
Listen man
Okay

[Verse 1]
I show you how to train a pet dragon
And babies with a flamethrower
But don't crush the kids cause you ain't Yoda
And these pens ain't sabers
[Steal?] for juice like [?] in the streets of Grenada
Letting it off on the roof with ya layer
Eights on the set
With 21 razors on cue
Lies playa
Invoke flavor - Outkast
[We?] collect [?] like [?] in elevators
Organic you don't think space is raw
You sun boxer
What you think all the rays is for
Sneaker face
These souls will lace your drawers
We trace your flaws
To live like a patient frog
'Til you croak
No joke what you waiting for
Debating score keep your head in the game
Maintain the course
One more thing don't talk bread with birds
And keep your ideas close 'til heads is served

[Hook] x4
Chalks already near all I do is trace your body in
{Scratched} Do whatever it takes

[Verse 2]
In the the house I be picking up
And I be getting my ...
Something terrible cause I am a king
When I workout the theme is 300
No time for fronting in my mind
I am [a bench?]
In the streets please respect the curb
Or get chalked out quickly
Expect the worst
Jets in seconds
Cavemen first
So if I betray the verse and raise a curse with a brazer verse
Why thank you
Crazy raisin smirk
Taking no shorts
And I'm raising skirts
Pulling bra straps
And if my baby burst
I'm putting insane work in
It's crazy work
That's ten
Daddy get money and win
I sound like the Biggie hook on Wu-Tang
Again and again
Don't quit your day job (get it)
Waging war
I'm a constellation
Real stars stay with the [?]
And it was verbatim
The way he could bait 'em with verbs
At point blank range would make the cadence occur
This is that one shot video with no scene changes
We both thought the beat was hot so I cremated it
When I'm [banging?]
Can't hang in
Couldn't be fly with sky practice
This guy's Baptist
He wouldn't cross himself
Flame retardant
With each freak the beast targets
The 3's hardened cause C don't leak jargon
King joggin'
I'm running the track hobgoblin
Halloween pumps glow in the dark and spark margins
Just like acting dumb is not showing you smart with art
I beg your pardon
That fake shit ain't real
I expose in the dark
Non-fluorescent each bulb an idea from the heart
Trying to curb my fly shit like a bat leash in the park
Non-fluorescent each bulb an idea from the heart

[Outro: {scratched samples}]
{Do whatever it takes takes
The fakes I could never relate
Recognize
We could settle the score
Your shit is wack
What I think about you rappers
I won't get to that part part part part}

I only get two tracks right

{Do whatever it takes takes - the fakes I could never relate}