I was walking in the park, in the noon
When I saw her, she was beautiful
Like a flower in the summer, what a bummer
I wish I could talk to her, I got my nerve up
And then I started to walk to her
I said, "hello", she said, "hi"
I said, "You're so beautiful, won't you be mine?"
She was beautiful, she was beautiful
She was beautiful, oh she was beautiful
Now we're in my house, I took the pants off the wench
The fuckin' bitch had syphilis, I cracked her in the face with a wrench
Now she's on the floor, like a dirty whore, reaching for the door
I bashed her in the face some more, you fuckin' cunt
I'll teach you to disease people
She laughed at me and said, "Yo, their ain't no skeez equal, to me"
Fantasia taught me everything, I'm a pro
I told her, "You won't blow no more"
She tried to get live, I tied her up, I put eight condoms on my dick
Attach razors to it, and slide right up and rip the crabs out the crack
Lubricate my cock with strychnine, just in case gonorrhea attacks
This bitch giggled as I snuffed her
She said, "You can find me everywhere, my name is STD, I'll be your lover"
I went to Rome and got some Roman armor and some blacksmiths
Gave 'em rubber and make something elastic
A metal condom for my cock, now STD is beaten for now but she'll be back up

Just a little fuckin' warning, for all you fuckin' sluts
That try to be fuckin' look beautiful, but deep down
You got a fuckin' stinkbox, a nasty stinkbox
Don't do it, don't do it
If you look beautiful, be beautiful everywhere
Don't be dirty under there
Cause this is two-thirds of the schizo, and shit could get evil like the beat