[Intro]
Hahahahahahahahaha!

[Verse 1: Freddie Foxxx]
Ha, check it out!
It's Bumpy Knuckles baby, also known as Freddie Foxxx
That's right, and I came to check my niggas De La Soul
See y'all niggas don't really wanna bust dat shit huh
Yaknahmsayin?  So I'ma show you niggas
The super-laser-gamma-ultra-killa-nigga special
You niggas ain't no killers
You motherfuckers ain't gonna hurt nobody nigga
You better keep rhymin' nigga
'fore I smack the shit outta you, you little fuckin' sissy
You niggas ain't real; that's right
It's De La Soul baby, and Bumpy motherfuckin' Knuckles baby
Alright, c'mon on!

[Verse 2: Maseo [?]]
Check my stats, entire, apparat'
Even from the days when I had to roll strapped
Wonderin' if I gotta go back to that
Zest to rub records from rap and kick facts
To tracks and stack, one [?] got kayed
Yeah some got paid, some waved in the fades
Fact of the matter my style will never fade
Managin' to keep it all A-grade
So you can stay nourish and flourish with the truth
[?] some niggas I know
If I need a mayday
Bust some fuckin niggas tryin' to play me cra-zay
Causin' interruptions to my big pay-day
Playin with them guns make them fuckin' lea-ry
But if it's clear-ly
Merely and surely and, how it's gotta be
I got some thorough niggas that's ridin' me
So witcha bullshit I'm not buyin' it B
Don't come around thinkin' you can try it with me
'Cause uh

[Chorus]
You don't wanna bust dat shit (uh-uhh)
You don't wanna bust dat shit (no no)
You don't wanna bust dat shit (uh-uhh)
You don't wanna bust dat shit (no no!)
You don't wanna bust dat shit (uh-uhh!)
You don't wanna bust dat shit (NO NO!)
You don't wanna bust dat shit (UH-UHH!)
You don't wanna bust dat shit!!

[Verse 3: Maseo [?]]
Shick shick, CLIK-A-CLIK
This is where my people headin' at
Innocent people are carryin' gats
Now what the fuck is all that?
Is it cause times is live like a wire
Gettin shock treated by the crossfire
Ha-siyahh, burn bare well prepared
To make my decision for my livin'
I ain't the one Robin, I'm the one Given
Hip-hop driven, and willin' to die for it
When Scott LaRock died man I cried and shit
Then some cats got rich callin' a woman a bitch
But ain't no woman like the one I got
And if you call her a bitch well you might get (*BLAM*)
And I know the feelings is mutual
It's uncivilized and unsuitable
Crips and Bloods are recruitable

[Chorus]
You don't wanna bust dat shit (uh-uhh)
You don't wanna bust dat shit (no no)
You don't wanna bust dat shit (uh-uhh)
You don't wanna bust dat shit (no no!)
You don't wanna bust dat shit (uh-uhh!)
You don't wanna bust dat shit (NO NO!)
You don't wanna bust dat shit (UH-UHH!)
You don't wanna bust dat shit!!

[Verse 3: Freddie Foxxx]
Ha ha, yeah you get the motherfuckin' point, HUH?
You niggas get the motherfuckin' point, HUH?
That's right so while you niggas is sittin' up in central booking
Crying like bitches, HUH?
I'm in the motherfuckin' holdin' block
Waitin for your sweet pussy punk ass
And I'ma whoop the shit out of you
For gettin' on a fuckin record, actin like you a fuckin' killer
I'ma show you niggas what a motherfuckin' killer's all about, HUH?
You niggas ain't no motherfucking gangsters
You don't wanna bust that motherfuckin' shit punk
I'll punch your whole chest cavity out faggot
You ain't no real nigga, nigga
I'll smack the shit out of you
'Cause you ain't a fuckin live nigga
You sittin' in central booking, cryin' like a bitch
Waitin for your father, to come bail you out
And Freddie Foxxx don't play that shit nigga
That's right, Bumpy Knuckles motherfucker
And if you don't know, now you motherfuckin' know
And yo De La, check it out, it's your motherfuckin' man
And if anyone of them niggas get sidewindin' with you nigga
Let me know, and I will send them niggas hot ones
Like I'm a motherfuckin' Mexican, feel me on that one HUH?
'Cause them niggas know me nigga
Believe me nigga they know me
The motherfuckin' troublemaker, that's right
And De La Soul, is rollin' with Bump' Knux' nigga
So WHAT?!?!!  Tell me, WHAT?!?!?!