A.M., P.M, all night long
Turn your radio up cause we are on
Ready or not, here we come
We got so much juice, you can all get some

Now to all ya ladies who want to know
Well, who are the kids that'll make ya go
Well, who are the guys that the girls adore
Well, who are the men that the girls prefer
Who are the kids with the most finesse?
Who are the guys that never fess?
Who are the fellas on the golden mic
That's gonna say all the rhymes that ya like?
Well if you do not know of me
Well baby doll you sure can play the game
Well we're sittin' in the limousine right outside
That's right, it's Dr. Jeckyll & Mr. Hyde
So Mr. H-Y-D-E
Why don't you bust a funky rap for me?
Yes I'm a fresh kid and I'm makin' my bid
I go to Paris in the spring time, Bahamas in the fall
That's right, huh, I'm doin' it all
And I got a little something for you sweetheart
So listen close cause I'm about to start
I want to hug ya, squeeze ya, freak ya out
I want to love ya down girl until ya start to shout
So when the morning light comes and I leave your side
You say, "Don't go, Mr. Hyde"
I like my sirloin steaks done just right
I like to wine and dine and candlelights
And to rock the mic to the broad daylight
So all the young ladies can bite, bite, bite
So come on homeboys, you can all get some
While I bust this break on my LinnDrum

So my man (Uh huh), Fresh Doc (That's me)
Just get on the mic and start to rock
Now I've toured all around the USA
And when it comes to MCing there's one thing to say
I'm the top of the list when it comes to this
And when I rock the microphone I cannot miss
I just put the microphone to my lips
I move my body and dip my hips
And when I feel the beat (Hah), I shake my feet
And that's when I rock you out your seat
You'll scream and shout when I'm bustin' you ou
Cause baby doll that's all I be about it
Now tell me, how could you ever resist? (Hah)
A kid that rocks as hard as this
I'm Dr. J-E-C-K-Y double L
And baby doll I got that clientele!

Whoo!
Ahh!
A-yo! A-yo!

A-yo man you know I went to the store
And you know what record they were selling?
Jekyll and Hyde's! (You know it homeboy!)

And when I was that party and there was 100,000 girls dancing and screaming
You know who they was calling for? (Who?)
Dr. Jekyll!

Now [?] you about ready to rock the house?
Well check this out
Here we go!

Hit it doc!

Now I'm feeling though it's been 100 years
Since I got on the mic and I rocked up here
We still rock the house just as much (Huh)
Cause everybody knows we still got the touch
I can't lose it (We can't lose it!)
Cause you know we know how to use it
Now we feel as though we got something to say
It just comes out in the usual way
So in a few years, you will see
A Dr. Jeckyll, Mr. Hyde university
With mixing as a minor and rapping as a major
Be on your best behavior
No C's, only A's and B's
Cause you gotta be def if you wanna MC
You graduate at the top
(Ha ha) If you really wanna rock the spot
And then placement trips for the very best
Profile, Motown and CBS
But don't think you're the best, you'll be petrified
If you ever have to battle Jeckyll & Hyde
So bust it, bust it, bust it!

Yo, remember how we used to rock at 110th St and Clinton Center?
Remember those fresh rhymes?
(Ahh they were def)
Yo, bust that shark joint on me
(You sure you want it?)
Bust it right now!
(Ok)

Well I was swimming in the water of the ocean
When all of a sudden, I dropped the potion
So I held my breath and dropped my head
Cause in 13 minutes I'll be dead
So I went on down and it started getting dark
And 200 feet (What you saw?), I saw a shark
Well the shark was big, around 20 feet long
It had big green eyes and was very strong
I said "Mr. Shark, you live in the ocean
You help me find that magic potion"
The shark looked at me and said with a sigh
"Well I don't know but I'll surely try"
So I held his tail and gave him a hit
We went down so far we couldn't see shit
When he finally got there, he gave me a notion
And there it was, my magic potion
I turned around and it was plain to see
That other sharks had followed me
I said "Stand back sharks, cause don't you know
That I'm powerful, like a stereo"
They said "Mr. Hyde, well you may be good
And you can rock it like an MC should
But if you can, huh, beat me
I'll let you go, hey, I'll set ya free"
Well I looked at him and then I checked the tide
And then I came out with a vicious rhyme
I said "pop-pop, fizz - fizz"
Tell me shark what it really is
Mirror, mirror in the see
Can these sharks deal with me?
I said, c'mon sharks take it in stride
Cause you cannot mess with Jeckyll & Hyde