[Intro]
There are many things you can do
You're unexceptional
You were born on ten-twenty
Roman numeral X:XX
A divine knowledge
Woo!
Uh
Woah!
To my world
Uh
Yeah

[Verse 1]
It's protocol to protect your neck and protect the set
Ridiculous and driven, never short of losin' breath
When I was 8 years old, I told my mom I'd have an early death
She rolled her eyes and said, "You better grind until there's nothing left"
Write, write, note pads and iPhone's
Up late, cause my chicks in different time zones
Facetime me, 3:30 am, them freak hours
She miss that so bad, I call that D-power
My right soldier always got the weed rolled
My left soldier never let the team fold
Rep that, RAD to the T
So dudes know what I mean
When I say that "we blazin', smokin' that G's all'
These hoes be blinded by weed smoke
Think you gon' get cupped because you got double D's yo?
Told her to cut the chat, let me tap it right in the V
Roll me a joint, we smoke, then I kindly ask her to breeze

[Interlude]
Yo, my nigga, eh
You want some shit?
What you want?
Chill my nigga, chill
Got no chill, man
That old school shit

[Verse 2]
Got that old school flow, like I'm Kool Mo Dee
Pass that toad, know I got that tree
No days off, gotta get that cream
Recognize the traits of a true O-G
Steal that rock like some new jack, swing
Bring a couple goons, and we got that O-D
Just another day, C-O-O-P
Never mad homie, I stay R-A-D

[Verse 3]
Aye yo
Uh
Who got the papers, got the papers?
I'm a wise guy, when I rhyme, I'm vicious
They say I'm wise beyond my times, so rock with politicians
Unless it's Clinton
And we rollin' up a joint, sippin' Henny, out with a couple bitches
Good fella, know it's Brooklyn baby
So don't forget the motto, still: fuck you, pay me
(Yo, bro I got this crack that we could-) Fuck you, pay me
(I could put you on if you just-) Fuck you, pay me

[Outro]
Oh shit!
Stand still
Uh
*Bullets firing*
Come here
Ah
Did I get him?
Nope
Ah, dang
Can't nobody touch the Dark Night