[Chorus]
Call me at 3 a.m., tellin' me that I could be the one, oh, yeah
Maybe I was in love from the outside, guess I ain't what you want no more
If you got someone else inside of your life, yeah, that's good for you, I'm happy
You got someone that makes you smile more than I ever did, yeah, that's great

[Verse 1]
Listen, why they always tryna hurt me?
Why they always tryna burn me?
I swear to God, shoulda never even happened in the first place
Only time you hit me's on my birthday
Wish that I could tell you that I got a lot of love for you
Wish that I could tell you I got trust for you
Once you put some money in the bank you understand that the money ain't enough for you
Yeah, look what it's done to you
Everyone's your friend when the music start buzzin'
I'm closer to the people that were there when I was nothin'
Tryna talk about the past but you always changin' subject
I ain't good at shakin' hands but I'm good at holdin' grudges
Why you always frontin', huh? Always tryna play wit' me (woo)
Yeah, whatchu gotta say to me?
I am not a slave to the people writin' checks to me
This is destiny, they ain't never had respect for me, ah!

[Chorus]
Call me at 3 a.m., tellin' me that I could be the one, oh, yeah
Maybe I was in love from the outside, guess I ain't what you want no more
If you got someone else inside of your life, yeah, that's good for you, I'm happy
You got someone that makes you smile more than I ever did, yeah, that's great

[Post Chorus]
I don't like that!
I don't like that, no! (I'm really sorry)
I don't like that!
Why you actin' shady on me?
Why you always tryna-
Why you always tryna play, I ain't got a clue right now
Everything I ever wanted was someone, I'm watching them go

[Verse 2]
Yeah, you said I'm scared for you
Lemme say a prayer for you
Hope you never make it to the top just to find out there ain't nothing there for you
And now the people tryna tell you that they care for you, never cared for you
First time that you ever told me that you loved me, I know that was probably weird for you
'Cause I didn't say it back, I'm so caught up in the past, and I know I wasn't fair to you, woo!
Maybe I don't see the world like I'm s'posed to
Maybe I'm just living in a nightmare
Maybe all the people that I thought that I was close to
Wouldn't be around if it wasn't for my career
Yeah, this third record doesn't pop off, how many people 'bout to drop off?
I know how it works, if the record doesn't work, then it's my fault
I'm in a room full of fans singin' my thoughts, my God, woo!

[Chorus]
Call me at 3 a.m., tellin' me that I could be the one, oh, yeah
Maybe I was in love from the outside, guess I ain't what you want no more
If you got someone else inside of your life, yeah, that's good for you, I'm happy
You got someone that makes you smile more than I ever did, yeah, that's great

[Post Chorus]
I don't like that!
I don't like that, no! (I'm really sorry)
I don't like that!
Why you actin' shady on me?
Why you always tryna-
Why you always tryna play, I ain't gotta clue right now
Everything I ever wanted was someone, I'm watching them go

[Outro]
Yeah, yeah, I'm done with that
Reminiscing 'bout all we had
We got nowhere to go, you got all the things you wanted
Got everything that you wanted
Yeah