[Strophe I:]
Die Passion, ich starte die Mission
Lang genug war ich der Versager der Nation
Ich fragte mich: Wie kommt man als Straßenkind da hoch?
Ich geb nicht auf! Das ist wie mein Vater mich erzog
Mein Schiff drohte wirklich fast zu kentern
Jetzt hab ich die Segel neu gespannt, ich muss irgendwas verändern
Damals war ich jung, ich war 17 und hab ich nichts verdient
Nüchtern bin ich Superman, Whisky ist mein Kryptonit
Das ist mein "Wunder Punkt" ich brauche Disziplin
Ich möchte runterkomm' und rauch ein bisschen Weed
Vergiss die Klunker und auch das ganze drumherum
Ich lunger rum und verschlafe den Gerichtstermin
Niemand ist perfekt, draußen herrscht Hysterie
Würd diese Flasche liegen lassen, wenn ich wüsste wie
Du würdest gerne mit mir tauschen um ein Star zu sein
Ich würde gerne mit dir tauschen um normal zu sein

[Refrain - Scratches:]
Die Passion Whisky
"Need weed to calm down, need money to live life"

[Strophe II:]
Die Passion, noch immer unterwegs
Ich hatte Angst, dass ich in den Trümmern untergeh
Yeah, ich mach es war - die Flaschen sind zerbrochen
Mama hat gesagt: "Sohn, du hast es mir verprochen!"
Hände voller Scherben, jahrelang vom Pech verfolgt
Kämpf mit Stolz, doch es endet im Verderben
Heute fick ich jeden, die Banger sind die ersten
Ticke die Kristalle wie ein Händler in Antwerpen
Ich bin Berliner, mein Gegend ist versüfft
Ich räum' mit allem auf, krieg mein Leben in den Griff
Manche meiner Wege führn' versehentlich zurück
Doch ich seh es nur als Vorbereitung für den nächsten Schritt
Du musst bereit sein, üb' an deinen Waffen
Wenn es dunkel wird springst du über deinen Schatten
Du würdest gerne mit mir tauschen um ein Star zu sein
Ich würde gerne mit dir tauschen um normal zu sein

[Refrain - Scratches]

Yeah, die Passion, Audio-Alkoholiker
Ich halt mein' Körper fit, fick auf Anaboliker
Ich scheiß auf Codein-Fake gib mir nur ein Beefsteak
Live on stage, ich ex' den Protein-Shake
Bin schon wieder in den Trends
Steige aus dem tiefgelegten Benz, physische Präsenz
Rapper wolln' kein Battle mehr mit Silla oder Frank
Weil ich Feuer spucken kann auf deine Lyrics bis sie brenn'
Damals als ich anfing hat niemand mich erkannt
Jetzt bin ich erleuchtet wie ein Diamant
Heut' bin ich entspannt, roll das Weed in einen Blunt
Du spielst Gameboy, ich hab das Spiel in meiner Hand
Drogen sind normal, doch diese Harten sind nicht gut für euch
Du bist am Arsch wenn du'n Tag in meinen Schuhen läufst
Du würdest gerne mit mir tauschen um ein Star zu sein
Ich würde gerne mit dir tauschen um normal zu sein

[Refrain - Scratches]

-Folg RapGeniusDeutschland!