[Verse 1]
Du bist der Meinung, mein Rap ist zu einfach?
Rap ist zu einfach für mich, aber du scheiterst
Wenn du mal Zeit hast, setz dich hin und übe
Wenn ich mal Zeit hab, komm ich und es setzt Prügel
Ich scheiß auf Regeln, ich mach kein auf Gangbang
Aber auf dem Beat, schlag ich dich um längen, Kind
Es ist besser, besser wenn du wegrennst
Zeig mir einen, der wie God auf dem Track brennt
Du rappst ätzend, du hast leider Pech
Was du machst ist viel, aber sicherlich kein Rap
Nichts, du bist ein Strich in der Landschaft
Ich puste dich um, wenn du nicht von dir aus Platz machst
Das du Angst hast, seh ich dir an
Ich zieh den Stift aus der Granate, du fängst und *BAM*
Ich bring die Beats und Raps als Bombe verpackt
Wo jetzt ein Loch ist, war früher deine Stadt

(Scratches)

[Verse 2]
Ich merk schon nach nur einem Satz von dir
Dass du scheiße bist - mit wem willst du konkurrieren
Konzentrier die weiter, auch wenn ich langsam rappe
Deine Karriere neigt sich langsam dem Ende
Das sind keine Zustände mehr, dreh dich um
Guck mich genau an, du sollst wissen, wer dich bumst
Wissen wer hier pumpt, du willst wissen wer dich kalt stellt?
Es ist Silla der Killa, der dich peinigt
Perfekt im Timing, du besitzt kein Sachverstand
Hol mir irgendjemanden, der irgendetwas machen kann
In einem Affenzahn, leg ich Tempo vor
Dein Affenclan und du, ihr gehört in den Zoo
Schweig und hör zu, ich bin das Tier aus deinem Albtraum
Ich bin ein Angeber, für mich bist du Abschaum
Du kriegst keinen Part, das Game ist hart zu dir
Godsilla & Orgasmus - rappen bis du es kapierst

(Scratches)