[Verse 1: Monoxide]
Fuck you!
Well I'm screaming, "Fuck you!"
Middle finger in the air
And all I want to hear is you
Screaming, "Fuck you too!"
I'm out of the stratosphere
And a brand newt loon, new atmosphere
I wanna blow a chute till the cap is clear
Cause I never thought I would've made it out of here alive
From the land where the people put the eve in evil, the night ride
You'll never see an equal to my kind
So blind to anything, the line to life and mine is right now
Looking for another mind to fight foul
Bringing everything that you can bring down to the ground
Like a hundred and fifty pounds of C-4
Looking for keyboard thugs
Well I'mma need more slug
Cause I wanna see more blood
You ain't never seen gore like us
They don't want to make 'em anymore like us
Put 'em on tour with the paint on
Hoping that anybody'll know your little lame song
Fuck right, I'mma stay wrong
Blackout with a ray gun
Looking for anybody in make up
Motherfuckers, we need you to wake up

[Hook: Monoxide]
When you realize
There's nothing really you can say
That's ever gonna change my mind
I'm on some fuck that shit today
Just say fuck it, I don't care
Middle fingers in the air
Only killers up in here, only killers up in here
Just say fuck it, I don't care
Middle fingers in the air
Only killers up in here, only killers up in here

[Verse 2: Jamie Madrox]
Fuck this!
I said, "Fuck this shit!"
I was born a son of a bitch
And always talked a whole gang of shit
Even though that I win the worst spit
Now tether the game up faster
Whole world revel in the wake of my dad's disaster
Had to talk to a pastor
Told me sit down, handle my shit
And tried to figure out what the fuck's really the matter
Hating animosity, only the guy wicked
It's the last, the victim, from your offer to the premises
I never know peace cause the nemesis there
'Fore I cover up all the scars and all my blemishes
Needing that x, another interest
Nothing form and I manage to myself with a run-on sentence
And I hang out of shape, put my bat head down
Got my eyes closed, watch as I swing for the fences
Home run, even a base hit'll get the job done
Me and my brother both 2nd 2no 1
We the ones who come for your young
In the depths, and at midnight, to free them from (bullshit!)
That they call the world, that's right
Hold tight till your reality swirls
And it curls to the audio medicine
There's never been a better prescription
Than the one that your listening

Fuck you! {x7}

[Hook] {x2}

Fuck you!