[Hook: Sleepy Brown]
All day I dream about
All day I dream about sex
The way you move your sexy groove
I've got my mind all over you
All day I dream about
All day I dream about sex
You say you were so sick of it
I'm tired of jacking off cause you ain't there

[Verse 1: Big Boi]
'65 Chevrolet Impala peachy cream
Cruising down the street like two fingers
Cause the ivory is clean
Talking bout meeting at the MC room
On the inside of the ship
Not a honey dip to hunt on
Cause she mobile than a grip
Or the Blue Man Group
Caught out on the Vegas Strip
Tell em a good game, juju pimping
Give em to my nigga Dime Legit
Boss lips, legs, arms, necks
Hip dips, hair net, mo' stretch
It's a camel toe and thats fo' sho
My brain is on one track
Like Mary Mary toss for crackle like a rock star does for smack
None of that but the female genatalia's where it's at
I'm a man and I demand a WO-man for that act
Personal preference cause I use the law of nature as a reference
No I don't ever recall seein' a man turn up pregnant
But that's just me
From them female fantasies frolic freely
In my cock pit, every 30 some seconds I can't stop it

[Hook]

[Verse 2: Killer Mike]
Killer Kill from Adamsville and in a Bonneville I chill
Heffers call me Black-N-Decker, I don't screw them hoes I drill
I've been cuttin' Cuban coochies since before the record deal
Catch me daydreamin' 'bout them, thick, medium, or slim
Doctors call the thing vagina, in the hood we call it trim
White boys call it snatch, Puerto Ricans call it chocha
Nathaniel likes his white, I like mine dark as cola
It's the first thing on my mind in the morn' when I roll over
All men young or old in the end it's what we after
Even my grandpappy's happy, he got prescribed Viagra

Grandaddy, grandaddy what's happenin'
What's up, what's up this me
Hey let me get about three of them blue diamonds
I promise I got you tomorrow

[Hook]

[Verse 3: Killer Mike]
When I drill, I don't spill, even if she's on the pill
Keep my weapon covered, concealed, and in a shield
Cause I don't need that A.I.D.S
A D. and an A. missin' out my Adidas
PLUS, We don't need no DNA mixin' between us
We just need to keep this thing friendly and hush hush
On the down low, like R. Kelly and youngsters
But over eighteen only cause baby I'm no perv
From the tour bus to the lobby, elevator to the room
We can jump each others bones but there's no jumping brooms

[Verse 4: Big Boi]
Buffoon you are too consumed in the womb
It is too early for you to jump the broom, boom

[Hook]