[Intro]
Ouais ma gueule ça dit quoi ?
Wesh l'ancien
Tu m'manques, enfoiré
Putain (ouais c'est ça)
Bye bye, check
B-Biface, longue histoire gars

[Couplet unique]
On a parcouru des épreuves, on a pleuré des rivières
J't'ai vu sourire, j't'ai vu parfois dériver
J't'ai vu nous dire qu'c'était la fin des dix frères
Elles sont étranges nos peines
[?] j'te taillais sur le 310, tu m'taillais sur la grange [?]
Mais allons-y, viens on déballe nos peurs, on est des gars moqueurs
Une fois qu'faut parler vrai c'est difficile car on écrase nos coeurs
J'emmerde la rue, j'emmerde les stups car tu t'es caché sous cette bannière
Tu sais, ensemble on aurait franchi toutes les barrières
Arrivé au studio, tu m'dis qu'il faut qu'on parle
Et tu dis : "Wesh les frères, j'suis désolé, il faut qu'je parte
Dans l'équipe j'ai pas ma place, entre nous c'est plus trop ça"
Mais pour moi c'est plutôt sale, il faut pas que j'me bute au sky
Et j'peux pas oublier les moments où j'riais quand on a tout pillé
Les bombes se sont dégoupillées, le micro on l'a bousillé
Arrivé poussière, j'repartirai poussière
Mais j'ai décidé d'changer c'est pour ça qu'tu m'as vu pousser hier
Je n'peux pas tout gagner mais j'n'ai pas perdu tant d'choses
On n'était pas si proche mais pourtant on a vécu tant d'choses
Ouais depuis Kyubi, le feat avec 1spire "J'veux respirer"
Attends, j'ai encore plein d'choses à expier
LTF tu connais l'éthique, fallait tout baiser en équipe
Mais t'as choisi ton équipe donc on peut pas dire qu'on est quitte
T'as fait ton choix, vis-à-vis d'toi j'pense avoir jamais commis d'faute
Vingt minutes après ton discours, ouais j'ai pleuré comme une fiotte
J'm'en remets pas, tu m'as pris dans tes bras, tu m'as dit : "Qu'est-ce qu'il t'arrive ?"
J't'ai dit que j'perds un frère et l'supporter c'est pas si facile
T'as fait ton choix, tu n'veux pas revenir, je n'peux pas t'retenir
Plus j'avance et plus j'comprends mieux tout c'que la vie veut m'dire
Les gens sont éphémères, à croire que tout c'que j'ai fait merde
Mais c'est comme ça mais j'y peux rien même si ça m'véner
J'comprends ton choix, plus d'une fois j'ai failli faire pareil
Mais j'ai réfléchi et, en fin d'compte, j'me dis que j'perds la tête

[Pont 1] x2
On voulait l'succès, l'impression qu'la malchance nous succède
Ça s'ra plus jamais pareil sur scène
Ça va nous changer, tu l'admets, j'en ai un aperçu amer
Entre nous, c'est plus la même, autant dire que ça pue la merde

[Pont 2] x2
Tu m'as pris dans tes bras
Quand j'ai pleuré, tu m'as dit : "N't'en fais pas
Y'a des blessures qui par le temps s'effacent"
J'te tends une feuille blanche mais j'ai écrit mes récits dans ces drames
J'écris en trempant ma plume dans mes larmes

[Outro]
Ouais ouais, hein hein, fini d'pleurer
Ouais, c'est ça
Han, vas-y essaye de faire la même, B-Biface