Yo
I'm having trouble at the crib
I'm going at it with my baby mother where I live
While the soldiers bleed, the economy recede
And all she want to watch is reality TV
Well for us real life is Strange Love
Some behavior, I couldn't figure the flavor
Dropped out of Charm School when she fell in love with New York
And love money
That's what I'm not made of
I bought a membership to the Celebrity Fit Club
To see if I could stand a real chance with this love
It don't make sense, the way she try to turn a G to a Gent
Don't need tough love, don't get it mixed up

I was one of them Wildboyz, Shootin for Sizemore
She was a little live jawn watching The Osbournes
The Best Week Ever had her goin for broke like Eddie Griffin
Or Danny Bonaduce, but no he never listened
When I drop a Super Sweet 16
Daydreamin of becoming Miss Rap Supreme
Or maybe Making a Band but bring your guns out
Sing your lungs out
Move out like Daddy's Girls out of Run's House
But that's against all odds
Pick apart this mic, come try to Pimp Your Ride
Real as Real Housewives of Atlanta
Yeah it's real outside
And it's like an episode of College Hill outside
Whether it be for the love of the payday
Or for the love of trying to have a baby for Ray J
The most modest model on Project Runway
She wanna be Kimora livin Life in the Fab Lane
And change her last name, and since Gotti's Way was passé
She watched Salt N Pepa and Celeb Rehab day
That's all she talk about at the café
I swear to God it drove me to drink about a half a carafe, hey
My head's so spinning
I'm so through with women
Who watch reruns of The Real World with dinner
And Kim Kardashian, moms and Bruce Jenner
And Three 6 Mafia show, and Jerry Springer
Scott Baio, 46 and Knocked Up
I'd rather see The First 48 or Locked Up
Instead it's just a Nanny 911, I'm Trading Spouses
Extreme Makeover, she rearranged the couches
Now she keep changing outfits
I'm about to get a Doctor Phil to do something about this
The house not fresh, she not Top Chef
I tell her Viva la Bam, she tell me not yet
Watching Cribs lookin at shit she never gon' get
America's best dance move she tryin to do the step
'Bout to do her like Beyonce and tell her to the left
Truth be told, she's bout to television me to death
YO!