6. Young Nigga, Old Soul

Engineer: Jonathan Isaiah
Producer: J Dilla (RIP)
Writer: Jonathan Isaiah

(Verse)
They hate when you aspiring
Never lacking confidence

Do you feel titanous will
Inside of all yo human skin?

Maybe
We young GODS that sent

Cause lately in my dreaming
All these demons tryna haunt the kid

So you see why escaping
The next thing I got in my plans

It's crazy
Taking brains
From out my reigning
Imma need these fans

Playing with words
Sharp as swords
Stuck in the matrix

Fillin spaces
Plugging chords
Like samples playing

I'm congregating
Masses stating
That dominating
Times we placed in

The way to break it
This segregation
Hip-hop spittin
Rappers fakin

So Imma take it
Monster's foot when
I'm kicking open doors
To find my footing

Get by with goodness
New highs that I been cookin
Climbing out the box

Everybody claim that they a rapper
Man, I kid you not

But hop up in the booth
Can't spit they truth
Nowhere near hot as Jon

You skipping old school instrumentals, so I know you ain't with GOD

This here is timeless
I know you vibing
I know I'm shining
Please don't remind me

Cause I got

Way too much stuff on my plate

And I got
Way too much love in my hate

And I spot
Way too much ties that turned fake

And I'm not
With all that dumb shit they say

That's why
That's why
That's why
That's why

(Hook)
Cause I'm a young nigga with an old soul
A young nigga with an old soul(x2)

(Verse 2)
Masterfully crafting these
Rhythms and patterning
Getting niggas flipping
From tracks the way acrobatics be

Vision clearer than binoculars
Hoping to make impressions
On the ones coming right after us

I stand for generations
Every Sunday to Sunday
Pacifist activist
Droppin bombs
While y'all preach gunplay

When really that isn't tight

Killing each other ain't right

If you ain't willing to make a new life
My nigga then you done lost sight
Of any moral understanding

You really ain't about that shit

You do drugs cause they rappin
Bout it

I gave up, so I could face the madness

I raise up, into a place and pass it

Escape the grip fellow vibration addicts

Homeostasis back in
On the go, making magic

Indigos say I'm that kid

If you relate then back it

Don't just go praise my actions

Take all these words and add it

Inside of yo mental mappings

Till negativity' s lacking

If you
(hook)
A young nigga with an old soul(x4)

(Verse 3)
And honestly
I hate a lot of things
I hate these little niggas
That want me on they team

I hate the fact that if you rap
They think you can't succeed without it

Been up every single night
Reaching to my dreams no doubt
It's harder than ever

Niggas out here dropping bars so they can keep the shit level

You need to lower down ya bass
So we can see what ya treble
Been talking bout

Cause every fucking song sound the same

And Everybody knows that you'z a lame

I'm tryna build and get up out the south

You just tryna do it for the fame

You just tryna ride a nigga wave

I ain't got the time to let it waste

You can have the burner on ya waist

But you ain't cooking shit
Nah you ain't pulling shit

A nigga ain't a nigga
Till he out here speaking ignorance

My mind been on my grind
While y'all children get belligerent

I know Im still gone shine
Even when they get to dimmin shit
'Cause

(Hook)
I'm a young nigga with an old soul
A young nigga with an old soul(x2)