[Produced by Larry Fisherman]

[Intro: Mac Miller]
Yeah, yeah
I just wanna let you know you are so beautiful (oh, me, me)
I just wanna let you know you are so beautiful (oh, to me, me)

[Hook: Asaad]
Heading to the bank with a heartbreak
Highs, the lows, the 808’s
I prayed to be great
I need more God in my life
The ills they overtook me
I get so high so they can’t overlook me
Try to sage ‘em out me
But its stuck within me
But its stuck within me
Heading to the bank with a heartbreak
Highs, the lows, the 808’s
I prayed to be great
I need more God in my life
The ills they overtook me
I get so high so they can’t overlook me
Try to sage it out me
But its stuck within me
But its stuck within me

[Verse 1: Asaad]
Double entendre or a triple whammy
The three wise men it run in my family
Blood nine run thick that’s my kinsfolk
[?] fuck an invoice
I'll speak my inner being nigga invoke
20 days in the shower with the 10 soak
Organic only cause I'm the most dope
Smoke the most dope no I won’t choke
Hydrogen water luxury ice cubes
Architecture the culture construct the right moves
I’m zoned out before im zoned in
Completely unaware of my movement
Everything I ever wanted in life it could fit in this song
It came true all along my brother was there all along
Flowing like fuck a first aid
My mistakes paved the way go after what pays

[Bridge 1: Asaad]
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back
White light yeah hiphop is back

[Verse 2: Asaad]
I’m excited to work with my heros
I mean worship the weirdos
Hermes’ pages I smear on
Left handed like the Bic I flare on
Windows down with the air on
New ideas airborne
Invoke it out me so I can get it out me
Permanent out of bodies [?] than me catching hommie
Was once like the hobby ‘til I rolled in them johnnies
Movin backwards that’s for hommie
Need the mil for mommy
44 minute flow
Kevlar strap over my Visvims though
Corridor cut with the movin’ metal
I felt the vibe I was feeling special

[Bridge 2: Asaad]
Hip hop is back
White light yeah hip hop is back
White light yeah hip hop is back
Hip hop is back, just me n Mac
White light yeah hip hop is back
White light yeah hip hop is back
White light yeah hip hop is back
White light , Just me n mac
Hip hop is back hip hop is back
Hip hop is back just me n mac

[Hook: Asaad]
Heading to the bank with a heartbreak
Highs, the lows, the 808’s
I prayed to be great
I need more God in my life
The ills they overtook me
I get so high so they can’t overlook me
Try to sage it out me
But its stuck within me
But its stuck within me
Heading to the bank with a heartbreak
Highs, the lows, the 808’s
I prayed to be great
I need more God in my life
The ills they overtook me
I get so high so they can’t overlook me
But its stuck within me

[Outro: Mac Miller]
Yeah, yeah
It ain’t shit if it ain’t me
Say cheese let ‘em hate me
Keep a bakery full of pastries
A lotta money in the bank see
The money changed me
It made me angry
Soul got cold as the AC