I'm a little Nipsey Hussle plus a little pixie dust
I piss all on your bike, I like to see your fixie rust
I'm in the pile of fly-lo wanna be followers
Send me photos in allover print nylons
Nylon magazine saying I hold the mic wrong
Smile all glad like I wanna be in your nikons
Viewfinder god, I'm white ball in
The corner pocket, I scratch the bumps my skin
Stress Rash Rules Everything Around Me (RREAM)
Getting drowsy, Bena-Benadryl, y'all
Rash Rules Everything Around Me (RREAM)
Getting drowsy, Bena-Benadryl, y'all

I grew up on the shy side, the free wi-fi side
The O.C.D. side you know it's me, Pryde
But I don't really have much of that so
I'm blushing while I'm running the show
I don't want to take a flick and I never take photos
I never say yolo, I never say cheese
I don't wanna pose cuz I don't want em to see
The anxiety rash I'm hiding under my sleeves
It looks weak, to get all red and
Itchy when I'm barely upset but
It's bad enough to make em call a medic
I could be in cali or connecticut
I'm loud and always yelling and
I'm kinda like a pelican, cuz my mouth
Is way bigger than my belly and
I like to keep some feathers on my skeleton
I'm not a bird but I pretend I am when I shit on your head
Outside your residence, without my medicine I'm stressing cuz
Rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl

I'm a little nipsey hussle plus a little pixie dust
I piss all on your bike, I like to see your fixie rust
I'm in the pile of fly-lo wanna bees
Prank callin me all the time
I just wanna grind, I just wanna flex
I don't really mind all the politics and stress
I like to be the trending topic, the pound key
Even though my hives break out when they hound me

And rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl
Rash rules everything around me
Getting drowsy, bena benadryl yawl