[Verse 1: brandUn DeShay]
I catch a lot of girls looking now
I guess the catch isn't fire because I'm sicker now
Been looking around for awhile, now I found you
Love T.K.O., but now it's round two
You were different much from the last two
Good look, good height, great smile, and I'd smash, too
But I don't wanna put it past you
Because, uh... you're still different from the last two
It's only right that you get a fair chance
I'm going in circles, can I have this square dance?
And you can say you had a song
It's sad and all, but I'm begging for change like a [?]
And I just wanna get it from you
I know how you feel, but I wanna hear it from you
I wanna hear it from you
I need to hear it from you
This is kind of like a poker game
Got to know the deal first before I play my hand
But if it's like you're saying, then it might be
Any sort of blackjack can trust me, I don't ever hit on nineteen
I don't need another green just to see that I'm on the right side
But on the bright side, I got a nice ride
And it seems like you don't care much
But even still, I don't dare trust
This paranoia again
Small percentage of doubt, it's annoying again
Shoot down memory lane, now I'm going again
Tears of fears, looks like I'm sewing again
I don't what it is that you want
Tell me whatever it is that you, gone
Tell me just what it is that you, don't
Lie to me because I know that the truth won't

[Verse 2: HiCLAS!]
Making all the right moves like One Republic
Like [?] on me, I won't be disrupted
No slipping when you're moving in the eye of the public
Because good can turn bad like girls who switch subjects
Speaking of these girls, I got yours on my right, so my team
I hope to give your girls self-esteem
And once I got them, yo, I got them doing anything
If she fit, stays clean, and how you bought the fling
A lot of chicks ain't worth the time
I'm a dreamcatcher nigga, all they do is interfere with the grind
But I heard you got a new man, oh that's cool
Even better, I heard that he went to my school
Oh shit, girls just trying to put me in the bubble
Adding stress to my everyday life and my struggle
But that's okay, because I was born to be a fighter
Looking for the wifey type, not a one-nighter
All the girls in my past, yes, you know who you are
Asking me in the future how I made it this far
I plan on being bigger than your biggest dreams
Sold-out concerts, mansions, and limousines
It's hard finding a girl worth time and commitment
Because when you find a hotter one, the further you get shifted
And I predicted all my past relationships
Side chicks telling me to move on, they don't give a shit
Frustrated without is and niggas stepping in
I knew I saw her coming, let the games begin
Because all these girls really wanna do is play games
I was flying high on my jet, I fell out my plane
On some X-V shit, but it won't get the best of me
Emotions flow out like bees
Stressing, P, I'm looking for the girl of my dreams, they got the recipe
Sat back patiently, I know that he's been 'sessing me
From the B.S. I did with lately
Would never let a chick make or break me
But real talk, if I gave you a shot
You did me bogus, the other you're not
No one for me, so I guess I'll keep it moving
Because my jewelry was sevens, while my [?] time grooving
We're moving irrelevant girls out of my life
This is HiCLAS!, homie, signing off, good night
Yeah