Yeah, put your bottles of Adderall in the air
This to everybody with A.D.D
You know you got it, ha, listen, listen

[Verse 1]
I got Attention Deficit Disorder, I ain’t kiddin' em'
Don’t know where I’d be without the Adderall and Ritalin
Poppin’ them shits three at a time in heavy dosages
And go back to the doctor like, I still can’t focus bitch
That’s right, It’s the A.D.D
Got officially tested in upstate CT
And after I did my part
The dude went to my parents and was like
Hmm, where do I start
His levels are off the charts
This shit is killin’ me, but still I rap it skillfully
Even with a certified mental disability
I know ya'll feelin’ me, it’s drivin' me mad
Got A.D.D so bad, I can’t even add

[Hook]
I can’t pay attention to nothing, end of discussion
I just got that A.D.D, A.D.D, A.D.D
I just got that A.D.D
And teacher I know that I can’t focus
Whatcha gotta know it’s just that A.D.D
A.D.D, A.D.D, I just got that A.D.D

[Verse 2]
I day dream more than Lupe, sing a different tune
Space out, eye fuckin' that biddy across the room
It’s true I’m not messin', this shit would get you stressin’
Teachers callin’ on me I’m like, uh, could you repeat the question
I don’t pay attention, I miss out on every lesson
Get lost cause I wasn’t listenin' when I got the directions
Start typing in my phone, and then forget who I was textin'
Zone out during sex and lose my fuckin' erection
I really hate this, constantly misplace shit
Losin' my wallet, phone, or keys, on a day to day basis
It’d probably help If every night I didn’t get wasted
And high enough to be a passenger aboard a space ship
But since I do, then fuck it
Even though losing my scholarship is not within my budget
Cause son I’m not playin’
I, uh, shit, I forgot what I was sayin’

[Hook]

[Verse 3]
My brain just doesn’t work cause of all the drugs I’ve done
Plus the A.D.D. to the point that thinkin' even hurts
Teachers try to talk to me as if I am gonna hear it
All I do is crack jokes, space out, and write lyrics
My brain’s unraveled over time like a rope does
Lost my mind like the change in your sofas
But I don’t gotta take my meds to spit it dope cause
All they do is give me dry mouth and a coke buzz
So what? I can’t focus but it’s straight
At least I got a good excuse when all of my work is late
Maybe can’t pay attention, but there is still a place
In my brain that allows me to murder a mixtape
Wait, maybe it ain’t even so bad after all
Fuck all the doctors, I don’t need to pop an Adderall
I’ll just be a rapper and such to make bucks
But if that doesn’t work, uhh, I guess I’m fucked

[Hook]