Ha ha ha
Tokin on my indo..
Smokin on a indo..
Lookin through your window.. (chi-chi, blaow!)
Doin what I win doe, ha ha, ha.. it goes
Who that tokin on my indo? Pow!

Fragile niggas get mashed out
(Who dat?) The Funk D-O-C Spock hash mouth rhymer
The Prime Timer, sharper than barber shop liners
Look at my chin - ninety degree bent
When I spit I make devils come out Yves Saint Laurent (Djinn)
I spend so much money on chalk and the indo
My weed supplier need to build a drive through window
My form of art rock, jewels with Clarks
When my bass sparks for fiends it disturbs the NARCs
Freak pattern after pattern to leave Angeles Los
The roughest rapper a DJ needle came across
Knock it in your Hummer; if it's too hot dial 9-1-1
Hook off on you like I Know What You Did Last Summer
Your dog is my dog, we dogs when it's thug time
When the fuckin hoes keep that drow in your bloodline

Yo, I send this to all my DOG
To my real niggas that are true DOG
Niggas who will bust guns for they DOG
Niggas who will spit ones for they DOG
Niggas who be rollin deep with they DOG
Niggas who blaze blunts with they DOG
Niggas who would do time for they DOG
Niggas who would diss a bitch for they DOG

Yo I'm a dog
I piss on the wall in airport bathroom stalls
Grab the intercom and yell, "Fuck you!" in the mall
I drop it with the holocaust force, I got balls
I get my pants fitted twelve inches bigger than y'alls
I went to college, rockin' Taiwan velour outfits
Dropped out, but stuck my friends for college deposits
Nigga, get a country nigga gun bustin
Like they saw 2Pac with two Glocks still thuggin
Fuckin with a dog like me, I call your name out
While you pussy niggas Call ID, when I blaze
You step life your wifee got a baby on the way
The way I flex son you think I'm made out of clay
I'm illin, my lyrics on the blocks make the killings
I string your moms out until DYFS take the chillen'
I don't like to toot my own horn but I'm the shit
And if you hearin me I see you paid that twelve cent

So peace to homey $hort DOG
Peace to that funky nigga Snoop DOG
Peace to that old nigga Dirt DOG
Pour some beer out on the curb for your dead DOG

...

You can call a female a dog too (true)
You can feed they stinkin ass u-canu-bu, DOG
They fuck your enemies and bring the beef to you
You got me, I left a couple in your Fubu
A real raw dog never get jealous
They keep they shit cocked if niggas try to dead em
So ask 'Face, keep your mind on your money
I keep the stinkin ass hoes doin laundry DOG

Cause I'm a dog