[Verse One: Sy Scott]
Yo, I'm a tic-tac-toe tactical wit it tactician
Tit for tat, three bombs on me, we all ticking
Schizophrenic, up in the kitchen
With a black fifth up against my head, just, click, click, clickin' it
Recheck the barrel and start respinnin' it
We I start, medics, start sowing and restitching them
My constituents and scorpions poisonous stingers filled with opium
Stay grippin' 'em
I got a venomous heart, filled with vigilance
That will shatter seven continents and ten peninsulas
Envision the vengefulness, visualize the vindictiveness
I rhyme with Sid Vicious viciousness
You be kiddin?
You soft like kittens
My grills are pit bulls they will kill when I say sick'em
Restrain me, restrict me
I'm arresting, resisting
I'm a rest when resisting, can't be apprehended
Nigga

[Hook]
If you got a problem with E
And you got a problem, come and holla at me
And if you want it, we can get it started
Plus I got the whole Squad siding with me

[Verse Two: Icarus]
Let the gatty spray and wet up the matinee
Smack niggas with both hands like patty-cake
Violate and I will retaliate
I don't battle fake niggas, I'm heavyweight nigga
GMG, fam, we gladly hotta
Ic' hold the sorcerer's stone like Harry Potter
And I'm like harry potta, we scary riders
Can't get near the dadda
I swear to God I'll come find where you hidin'
Have my high ninas, firing ninas from Beamers
And leave the area shot up, you hearing me patna?
I'm a fucking five star general, to drive cars into you
Ic' dodge interviews
One flip of the mac, take all ten of you
This message intended to, who's ever offended duke
Yeah you my nigga, but you could still get it too
So don't test me, I don't wanna do this shit to you

[Hook]

[Verse Three: Red Cafe]
Live from the NY state
And I gots one question, guess what's in my waist?
Ya'll got me pisted off slick talk
To get that Jacob watch, I'll cut your wrist off
I'm in the limo too long to turn
And this motherfuckin' dutch taking long to burn
I'm impatient
This is a song you learn
Make money, take money, and I'm hear to confirm my occupation
The new boss of course, the new Porsche
I pull up just to murder you niggas and move off
You too soft, Red Cafe from New York
I tell a bitch quick, I'm hot can't cool off
I twist lesbos, and and guzzling out X.O
My firearms stick to my waste like Velcro
It's R.C. nothing phony about me
With E double the O.G. you know me

[Hook]

[Verse Four: Erick Sermon]
Yeah I know, you never expect me to anchor
I bring it to them so called pranksters and them gangsters
I run DMCs, from rappers that's petter piper
I am the big apple, ain't nobody riper man
I'm not M.J. I'm a lover and a fighter
That's why I'm in D.C. now, looking for the sniper
I came in the game with hoodies and timberlands
Hard since Cypress Hill been wanting to kill a man
I did time, a thirteen year bid
I'm gutter E, I'm hanging on the side of crib
I'm a fan, but I hate what you're doing
Whenever you performing shows it's me booing
Ya as soft as your bid-die
You punk now, and you gonna be a punk at sixty
Dawg, ya need more team to get me
I'm a G, and my Unit come through like Fifty

[Hook] - repeat 2X