[Intro]
Yung Snapp made another hit

[Strofa 1: Lele Blade]
Pigliano 'o tavl' pe' tutte part!
In giro a Napl' pe tutt part è prenotat
Che se ne fanno 'e chisti piezz' 'e carta? 'E danno fuoco
Comm' si vennesseno 'e piezzi 'e crack, 'e piezz 'e coca
N'to locale n'e veco, n'e ceco
N'to locale n'e veco, n'e ceco
Vonno fa a gara,ma che mij nun se pass..
Dincell' 'o cameriere ca se caricass,a genta dice :"Bella vita si durass"
A facc' bere na' butteglia 'e "Caritas", tu a' bé dinc' o guaglione tuoj ca' nun se ne incaricass
Fiumi e Clicquot,fumo a go go ,semp co' gas!
Pure si o' tizio 'a ritto: "Ca' nun se fum", ce ne pass po' cazz
Me sciacquo e rient' cu stu champagne "Frank Titas"
Chist nun aveno idea pe' sord che spennimmo aró stamm e cas..
Sanno ca nun simmo figli e famiglia, ce guardano e cagneno strada;
Semp' tutt apparicchiat, semp buon' ammanigliat!
Si 'a nott porta cunsigl', a nuje c'è cunsegn' denar' ammappat..
Spennimm comm' si foss l'urdma nuttat primm e i a fernì carcerat

[Bridge: Lele Blade]
'Sti guaglione vonn vevere
Nujo 'e 'nfunnimmo 'e capill
'Sti candel 'e sti butteglie
Continuano a fa scintille
Se fa luce 'ndó privè pare juorno 'ndo locale chesta genta
N'av idea ca' cu nujo
Se fanno male

[Ritornello: Vale Lambo]
10 Moet
E cumpagnij s' vevn 10 Moet
20 Moet
S chiavn ncap chiu e 20 Moet
'O tavolo Esposito
Arrivn a 30 Moet
C vonn sti sciem
O'Lè stappam 50 Moet
E brindam 'nfaccij
V brindamm nfaccij
Cu Alfons e Gennar
Ve brindammo 'n faccia
Ve brindammo 'n faccia
Skkkrt
'n faccia, 'n faccia
Ve brindammo nfaccia
Cu Nicol e Pasqal ve brindammo nfaccia

[Strofa 2 : Vale Lambo]
10 Moet
20 Moet
E cumpagnij loc stann cu me
Puort nata Moet
Napl 'e notte se 'nfonn 'e Moet
Sapev sul 4 Pal
Chill re bas
Ma cà dint a guaglion fa' e dann' abball co palo so chiav
Jamm o local
Jamm a Dubai
Piglio tutt o local
Vestit tutt'altolocat'
O'Lè nuij che tut' ra cas
'A nennella vò nata Moet
S'arap o' privé stamm bell
Nun te movr vag addu chell
Verimm si c'esc na pell
Tutt'è venerdì a rot e Clicquot
A' Cristal è nobil qualità oro
Comm'è o' caffè Moet & Chandon
'O Mast va a Don Perignon e nun è capodann
È 'o compleann ro frat 'e Totore
Chist' apparten è o frat 'e Totore
O sabato e sera
Geeno s' ferm adde nere
Corrad che femmn' o' per
'A squadra mia e chella manier
Clement p' ngopp e divan
Lelluccij e' tatuaggij chicani
O' Lè mo 'nfunnimmcij e man
Damm a bevr pur' è cani

[Bridge: Lele Blade]
Sti guaglion vonn vevr
Nuij e' 'nfunnim e capill
Sti candel e sti butteglij
Continuano a fa scintill
Se fa luce ndó privè par journ ndo local chest a gent
N'av idea ca' cu nuij
Se fann 'mal

[Ritornello: Vale Lambo]
10 Moet
E cumpagnij s' vevn 10 Moet
20 Moet
S chiavn ncap chiu e 20 Moet
O tavolo Esposito
Arrivn a 30 Moet
C vonn sti sciem
O'Lè stappam 50 Moet
E brindam 'nfaccij
V brindamm nfaccij
Cu Alfons e Gennar
V' brindamm 'nfaccij
V' brindam 'nfaccij
Skkk 'nfaccij "x2"
V' brindamm nfaccij
Cu Nicol e Pasqal vm brindam nfaccij