[Produced by DJ L]

[Bridge: KD Young Cocky]
They say them people after me
They say them people after me
I ain't worried, boy, I'm from the streets
I ain't worried, boy, I'm from the streets
A bunch of real niggas, they come for me
A bunch of real niggas, they come for me
I done seen shit that you wouldn't believe
I done seen shit that you wouldn't believe

[Hook: KD Young Cocky] x2
I'm my City God, I'm my City God
I'm my City God, I'm my City God
I pray you niggas get money and praise the City God

[Verse 1: King Louie]
Numbers so I'm stackin'
Niggas wanna whack me so I'm packin'
They just rappin', I'mma whack 'em
Show 'em Tony 'bout that action
My pockets fat, your pockets plasma (yeah, baby)
Walk up and shoot 'em in his visor
She needa fix my dick, Macgyver
Them folks that I be with some travelers
No Limit shit, shout out to mo'nem
Tony, B.O.N, shout out to fo'nem
We don't just buy pistols, we blow them
Bitch I go hard for packing dro'nem
I load 30's and reload them
Use your brain, no we ain't slow'nem

[Hook + Bridge]

[Verse 2: King Louie]
Youngest one with it, nigga died, I know who did it
I'll die before I tell it
My dick dope bitch, I should sell it
My dope loud, bitch, you can smell it
Kill a nigga and celebrate
Get the yellow and the red tape
Drop a nigga like a mixtape
And we plan it, premeditate (yeah, baby)
AK's chop shit, call 'em sensei
Pop a fuck nigga and then pray
God forgive me for my sins please
Exit bigger than the entry
I won't stop till my clip empty

[Hook + Bridge]

[Verse 3: Fetty Wap]
Zooville, aye, yeah, baby
Aye, come take a ride through my city, baby
Aye, come take a ride through my city, baby
Aye, Zoo Gods, we run the city baby
Aye, bitch I'm the god of my city baby
Aye, I keep the 40's or the 50's, baby
Aye, you call me Wap, I don't want it, baby
Aye, fuck out my face if you don't know me
Aye, you not my friend, you not my homie
Aye, you catch this 40 like you owe me
Aye, and I don't think you wanna owe me

[Hook + Bridge: KD Young Cocky & Fetty Wap]

[Outro: Fetty Wap]
King Louie, Fetty Wap, 1738
Chiraq to Jersey