Part 1: The President
[Verse: Rapsody & backup]
God please watch out for my bae
He out in these streets in these woop-woops going crazy
We just tryna eat, no receipt cause they ain't pay me
Tell me mind my business, well then maybe I could do that
If you let me muthafuckas Hey
If you let me muthafuckas Hey
I could do that for my brothers Hey
You can do that for my brothers? Hey
Well let me see you muthafuckas
They don't know what we gonna do
And they don't show what we gonna do
And they don't care what we gonna do
Whoa
Well let me see you muthafuckas
They don't know what we gonna do
And they don't show what we gonna do
And they don't care what we gonna do
Whoa

Part 2: O.L.M.S
[Verse 1]
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
Feet up on the sofa so I always got a leg up
I was born with the force now you'll never never catch us
Mind on the money, watch doors open like Teslas
I walk in the White House with a strut like George Jefferson
Looking at George and Jefferson, look at us now
Having round tables, these power moves you don't see around
It's just us talking justice, the POTUS been down
Making history, the union representing for the south now nigga
I'm still southbound, ain't a noun could describe me
A pill they could prescribe me, appeal like I'm Cosby
Caught up by the higher ups, they all wanna hire us
My appeal is astounding
9th Wonder found me in a little white house
And a little school crew by way of a little white dude
I paid my ten years of dues
Ain't paid a dime on the loan I took to get into school nigga
Wolf pack remember who was woofing at me back then

[Verse 2]
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
Your acclaim temporary, In the bible even Joseph
Know you know he ain't nothin' without Mary
Know some niggas who won't rap with Rap cause Rap is too scary
I fit the stereotype of radio, one don't hear me
Now back to Mary tell the story of the wise men
9th, Jay, Gu they all know that I'm a godsend
Call them all sandman
Tell em bring a dream back
Shout to Spanish Ran, account ran when I whipped my P's
Down in Jo'burg
I'm tough as ten leathers nigga, four furs
Ain't gotta save up four words
Obama like my shit
I made my whole career off unusual politics
In a game full of politicians
I was never scared of risk
Cold cold world my rise was in my blitzens
They yellin' me the reindeer, never cut the rude off
I'mma talk shit, can't help you niggas built so soft
So soft, yea

[Verse 3]
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
Back again this the incredible
You ain't eligible to speak my name
Gotta put respect on it, I ain't playing with you man
This ain't Michael Keaton nigga, Birdman, Birdman
Chris Anderson mohawk been praying on everyone
Who been praying on my fall
I told you I'm more hawk, be Tony get on board
Either way you swimming with the sharks
I went to your crib and turned all your power off nigga

[Verse 4]
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
I got my guard up, 30 on my back
Looking back on my twenties and they all turning black
I put 50 tubs on it, where my real G's at?
This ain't child's play got you crying over silverbacks
Oh, no I won't change up nigga less is uniform
I address 'em enough they'd rather see my jeans torn
Family too strong I don't ever write a wrong
You should always right your wrongs and never leave me alone

[Verse 5]
This shit is so Swayze, Swayze, Swayze, Sway, Sway, Sway
Average listeners will never comprehend this
Like the real reason Draymond Green was suspended
I stand by my words mama told me don't amend shit
Been running for a long time a nigga still ain't winded
But I'm blowing up either way y'all still blowing it