[Intro]
Taj Money
I'm a 38 baby
Fuck...
Yeah, yeah, yeah, yeah
Taj on the beat

[Chorus]
I grew around it, so you know I'm 'bout it (know I'm 'bout it)
I came from nothin', now young nigga got a whole lotta (whole lotta)
Won't stress myself 'bout nothin', I'ma find my way up out it (find my way up out it)
I'm goin' in, with everybody who behind me
I was gettin' it, now I'm in it and it's perfect timin'
Everything that you said, I ain't forget about it (I ain't forget about it)
I'm a real nigga 'til the end, you gon' hear about me
I'm a real nigga 'til the end, you gon' hear about me

[Verse 1]
I'ma run that sack up and buy all my niggas time pieces
In my hotel, been abused by some bad bitches
Ever since I was way younger I've been had this vision
Now I'm in Cali, stuntin', flexin', kickin' shit with Beanin
I'm only 16, it's always been my dream
But I do this shit for my lil' boy
No I don't give a damn what it take for to get
I walk in this booth and go hard
I won't stop, I'ma shoot for the stars
Where I'm from, gotta stay with that rod
Bet' not put your trust up in these broads
Over 400 shots in that car (brra)
Juvenile in a foreign (skrrt)
If they call, I don't answer, ignore it
State to state, but I ain't tourin'
Straight to that bag where I'm goin'
They don't like the way that I get to it
Nigga go get in my way, I'ma do him
They don't like the way that I get to it
Nigga get in my way, I'ma do him
I was on confinement in that cell, was just paper and pen
I exit every time I hit the dro, I smelled it in the wind
Lil' Tim went home on Valentine's Day, they shot him dead
Crazy how they bled, I keep one in the head

[Chorus]
I grew around it, so you know I'm 'bout it (know I'm 'bout it)
I came from nothin', now young nigga got a whole lotta (whole lotta)
Won't stress myself 'bout nothin', I'ma find my way up out it (find my way up out it)
I'm goin' in, with everybody who behind me
I was gettin' it, now I'm in it and it's perfect timin'
Everything that you said, I ain't forget about it (I ain't forget about it)
I'm a real nigga 'til the end, you gon' hear about me
I'm a real nigga 'til the end, you gon' hear about me

[Verse 2]
You ever slept on me? You gon' hear about me
You ever betrayed me? You gon' hear about me
You don't believe me? Yeah, you gon' hear about me
Believe that, I'm goin' in, you gon' hear about me
Chasin' that money, been a long day
Now I feel it's safe to say we came a long way
I swear that it's a dirty shame the way they did Lil' Dave
No, we ain't stoppin' 'til we make them bitches feel our pain
I was blowin' sell to see how bad I fuckin' stunted
I wish my grandma was here to see how much that I accomplished
I just stopped by my lil' brother and gave him a hundred
You know I'm steady hustlin', so you won't run from nothin'
Straight out the gutta, came out runnin', I ain't lookin' back
Ridin' with KD in that Camaro, with 'bout four straps
Me and Dino, we 'bout our business we gon' handle that
No I ain't gotta sell really, B gon' cancel 'em

[Chorus]
I grew around it, so you know I'm 'bout it (know I'm 'bout it)
I came from nothin', now young nigga got a whole lotta (whole lotta)
Won't stress myself 'bout nothin', I'ma find my way up out it (find my way up out it)
I'm goin' in, with everybody who behind me
I was gettin' it, now I'm in it and it's perfect timin'
Everything that you said, I ain't forget about it (I ain't forget about it)
I'm a real nigga 'til the end, you gon' hear about me
I'm a real nigga 'til the end, you gon' hear about me