[Verse 1:  Canibus]
Now God's big coins in the glove box
Blood clot comma ice zones
Some Mozilla Fox
My poon shot tight like teenage tube sox
You ain't looser than a old lady's loose frock
With wet spot underarms
I storm pawn shops like what up
Let me see that lawn rifle boss
My Cuban link faster than computer can think
Liquid nitrogen, I keep my computer in the sink
Great computer nitrogen cooler
Fight a nigga over a rumor
Butt your face off with the ruger
Looking for Mr. Nice Guy, this ain't the right time
My Broadway play is Iron Mike in his prime
Or Bishop Don Juan dressed in lime
With two pit bulls, dyed them a color
Don't cross the line
Folks stand behind the barricade cryin'
Martial law line, lock your ass up for tryin'
Infinite unemployment nigga stop applyin'
Tryin' to get firearms, get shot for buyin'
F-A-M DHS is like "When?"
Firearms'll murder all over again

[Hook]

Fa Fam, F for the Fire and the A for arms and you know the M for murder

[Verse 2: Bronze Nazareth]
Yeah, let's go, yeah
Aight
Hey yo Shoddy Rice shot gun the face scanner
Let me walk you buckshot man its
These murders in my day planner
The hit granter
The Roz Swan tie gas pipe man stripe yellow wick in Atlanta
Danny Green burials East Cleveland manner
Pro Borrow on his lance takes Steve from the camera
Duct tape table beneath for hidden hammers
Co-defendants nailing their fingers to the family
Block slanted assailant, witness recanting
Hit list for Ulysses S. Grant financin'
Goliath add you to the sky plus minus
Gone before you sought beyond the Sunland bias
Goons and guns forever silenced
Idaho potato compression all the violence
Pristine sixteen Cadavers in the [?]
Operating a business, my destination science

[Hook]

[Verse 3: M-Eighty]
Oh yeah, yeah, oh yeah, yeah
Wu Tang, la familiar, get on the [?]
Constantly we killing 'em or draining em for [?]
Often imitated, never duplicated
Always celebrated forever made it
We the greatest, get the the picture
We know that you know that the crew's back
Heavy balls slash intact, combat the track
And Martyr drop the eighty on the daily maybe
Just to show em Brew what Ricky Rubin
Keep it slick like Rick the Ruger
Do it, however you make you done it partner run it
Keep it comin' while we gunnin
Top slot. it's always somethin'
Hands grimey, nose dotty, mouthpiece shoddy
No need for Paparazzi
With the crew shootin' beside me
Pain in that ass while I'm ripping the track
Tell the select to bring it back
Ask Nino with The Carter
Who gonna circle this remarkable timing
Risk cause a mind shining
Be the sign of the times
You rap remind em, We! We! We!

[Hook]
[Verse 4: Nino Graye]
Murk! Murk!
Any enemies askin' for beef
Get the machete hackin' 'em deep
Pedigree better be master
Fella relaxin'
Never reactin' quick enough
To get at me back with pleasantly passive lines
Mind cleverly crafted
Claim you're heat you're in the training league
I'm Fuego Faithfully
Your body was just mentally fascist
Mentally massive, penalties actions
Death squad assembly blastin'
All pretend to be bastards
Hey yo I stay true to find the course
While you heathens fled from a god
To try and  pray to a higher source
Flowin' off very honest depths
You stuck in a pontoon gazing upon
The current Mariana's Trench
Rap's a restaurant, Caskey true
Spittin' ABC raps written on napkins with drool
Shoutin' they the best
DJ Khaled in the booth
More like Em and D12
What ya'll lackin' is the proof
(Proof) (Proof) (Proof) (Proof)