[Intro]
Yea
The super-gross is back
Traumah, you a fool for this beat though
Yea, let's do it
Check, one-two
Yea, yo

[Verse 1: Greydon]
I don't care I'll put my life in a song
I tell you twice as a pawn just to see which building the sniper is on
I'll probably be the next to get a mic on his arm
Cause I love hip-hop, and my rhymin' is strong
Ain't nobody askin' me what side of science I'm on
How the bright idea of one god divided 'em all
Technologically we should be a lot further along
But we squandered it all with cold wars and bombs
The dark ages, those are seven-hundred years of tech
And I don't know about you, but I'm here to collect
Just have the Catholic church write me a check
And I'll divide it up amongst all the poor people on earth that's left
Should've had the star system colonized already
Bases on the moon and Mars headed for alpha centauri
Aids and cancer should've been a thing of the past
'Stead of dropping a bomb to spend money we build in Japan
Humanity has scars like an abused harlot
Circling up all the gases of moving target
Peace is the hardest due to current though process
We embrace superstition and reject logic
I got a message for the next prophet:
"How 'bout a fresh option?
More understanding and less doctrine?"
Just one of many in the ocean of space
With existence the focal point of debate
You know that it's Grey
Last I checked this was for the species
But when it comes to human rights they treat it more like feces
What does it matter if gay people wanna get married
When you sittin' over-eval how you wanna be buried
Like it's more important, to say it's decreed by external forces
Not knowing the earliest idea were of female origins
You need to do some more reading of quantum physics and explore reason
Cause we need more heathens

[Verse 2: Syqnys]
When I look up at the sky
I see the difference between you and I
I see the universe, near perfect in fact
You wanna make up a god and start worshipping that
I say "there's so much in this universe"
You say "there must be more", don't even search it first
You rather be amazed by a virgin birth
There's no church on earth that is worth the dirt
It's built on the [field on?], the hands of those
That believe it's disgusting; the cancer grows
See I don't care about no angelic wings
I'd rather know is there really one-dimensional strings?
When they sing do they make up the fabric of things?
Is that too much to fathom for a rational being?
Like, nymphs physics isn't yo cup of tea?
That's gravy baby, there's so much to see
There's so much to learn, there's so much to love
Instead of reading about "such and such" above
Yea, whatever; are you really amazed
By the books? Page, after sillier page?
Cause the Koran and the Bible are exactly the same
Moronic and vile means attacking your brain
Yea, you need to do more reading
On anything and explore reason, cause we need more heathens

[Verse 3: Task Rok]
Or even more seasoned agnostics
Those still working on the reasoning process
I believe in my conscience; people of all tense
Fighting over all this deity nonsense?
We could all be friends if we squash this
Constant bickering and sickening nonsense
This is for my nuns out livin' in the convents
To my thugs with the guns still sittin' in the projects
To the honest little children only buildin' up a complex
From the bible belt to a village of Islamics
This shit is real, you can feel it in the Cosmics
We'll revealing all the prophets and we're killing 'em with logic
My honest opinion? God and religion
Is often a prison designed for your thoughts and decisions
I followed my wisdom and it led me to skepticism
Took the spirit out of me; undoubtedly an exorcism
Yes there isn't a god, but don't stress it
Your heaven's right here on the planet, so go get it
Stop givin' this life no credit; had to make an afterlife?
Well, I don't get it. Roll credits and the audience exits
Life leaves too, and your body is breathless
You need to do some more reading
Just to ensure we can even the score when you're speakin'