[Intro]
[Trick Daddy]
We gettin dollas
(dollas, dollas, dollas, dollas)
Yours Truly, I know y'all been
Waitin' for it
And it's about time, ain't it?
What I'm a need y'all to do
Cause I got what you want
I want all the bitches to report to the dance floor
Right Now

[Verse 1]
I need a bitch to make that ass up
Make it clap, tune it up and shake it a lil' faster
One cheek at a time, left cheek, right cheek, do it all to the beat
It's easier on ya g-string, and you can free ball
Bitch and you ain't gotta wear draws
How low can you go?
Look back at it, and make it jump like a jack rabbit
Take it down down to the flo'
Shake ya booty break it down get low and low
Work the flo' like a runway
Now vogue wit it, point a nigga out and tell him come get it
Boom boom skeet skeet goddamn
Now grind on it, bitch bounce up and down on it
Let him hit it from the back
Put a arch in ya back and let him hit it like that

[Hook]
Now to the beat just jump on the dick
[Khia] Don't eat, sucka suck on the clit
[TD] That's right just jump on the dick

[Khia] all night sucka suck on the clit
[TD] just jump on the dick
[Khia] sucka suck on the clit
[TD] just jump on the dick
[Khia] sucka suck on the clit
[TD] just jump on the dick [x2]
[Khia] sucka suck on the clit [x2]

[Verse 2] (Khia)
Hush, Shut up don't say nothin
When I'm ridin in, slippin slidin in
And the more you in it the better it gets
And it's it to you how wet it get
And it's up to you how many nuts ya get
My nigga you don't know who you fuckin wit
Who you suckin up, who you love to fuck
You see a bitch like me I neva stop
I like to take it from the bike and ride on top
All night, all day I'll be on my way
When you call, if ya call all you to say
(Jump on the dick)
Bitch do yo thang
And I'mma get fucked up and suck ya up
So what you think about that, you wanna give it to me?
Then baby show me what you got and give it to me cuz

[Hook]

[Verse 3] (Tampa Tony)
I'm ma playa; well know dick layer
Talk out a bitch out her pussy don't pay her
Hey(hey) what you say? Good pussy bitch slang it this way
You don't like niggas hold you gay
Keep ya mouth open bitch and turn this way
Lemme stick somethin it you in it you like
You can spit and slob but don't bite
You like when rap hits a mic, so spit a lil somethin that a nigga like
Turn ya ass ova and tho in bike, cuz dick and pussy they love to fight
If a notha pussy jump in it's on tonight
No child support bills, so swallow my kids ho

[Hook]

[Trick Daddy]
We gettin dollas

[Khia]
Don't say nothin