[Vers 1: Pede B]
Pede B typen der forsvarer sig, jeg klarer mig
Ny 100 kilos banger siden L.O.C. han tabte sig
Men før jeg ramte tre cifre på min badevægt
Og blev en bred knægt var jeg et langt barn med hagesmæk
Jeg følte midtfirserne i en yuppie tid
Hvor nogen pressede citronen og nogen var ude og skide
Hvor en hver direktør hørte Sanne og sku' suge den hvide
Og besættere fik borgerne til at ringe til politiet
Om statsministeren var superstupid må guderne vide
Men nogen sir' idag han ik' duede til en skid
Før shawarma bar var jeg på grillen med min gamle far
Et par ristede med brød og lille Peter ku' klare sig
Fastfood, du ved det værste hø du ku' finde
For mor var ude på sygehuset, vi vil' gerne besøge hende
Hun fik det bedre og kom hjem igen
Det var dengang en Amiga var en teenagers bedste ven
Vi blev afhængige af TV og moviebox
Og Hollywood og alt hjernedødt vi ku' suge til os
Underholdning svines i en periode
Hvor masseproduceret bras gjorde ungdommen sær i hovedet
Sir' ik' vi alle sammen er sære, nej
Hey yo men tegneserier lærte mig at afstumpet at være sej
Ville være som dem og bladre frem på siderne
Det jeg mener når jeg siger jeg' et barn af tiderne

[Omkvæd: Pede B]
Jeg' et barn af tiderne, jeg et firserbarn
Den slags medierne ofte viser frem
Som et hidsigt skarn, eller et bittert barn
Hvis du ligesom mig homie lav lidt mere larm
Jeg' et barn af tiderne, jeg et firserbarn
Den slags medierne ofte viser frem
Som et hidsigt skarn, eller et bittert barn
Hvis du ligesom mig homie la' mig se din arm

[Vers 2: Pede B]
Jeg ik' ude på at pege fingre som en anden Uncle Sam
Tror ik' vi blir' crazy af at spille atomic bomberman
Tror ik' at vi allesammen er offer for nogen
Og jeg tror ik' underholdning kan skabe en tosset person
Så lad mig bar' forklar hvad begrebet dækker over
Du et barn af tiderne hvis du ik' er den bedste borger
Drikker lidt for meget fordi det ganske enkelt er sjover'
Og helst bare vil være en ægte bawler med kæmpe kogler
Vil egentlig ændre os, men tør det ik'
For uden stimulanser blir' du sikkert skør af det shit
Og hvilket billede tror du egentlig dine børn de fik
Når i sku' hygge stod den på øller og lørdags slik
Lidt mere fedt i blodet, lidt mere sprit i hovedet
Og kaffe så du kører og ik' behøver sænk' niveauet
Sorry jeg ik' ude på at gi' nogen skylden
Jeg vil ik' sætte generation før os op på lortehylden
Vi vant til folk brækker sig, vi vant til vold i byen
Vant til blå øjne, skæve tænder og dobbeltsyn
Til gengæld er vi ambitiøse og vil frem i rampelyset
Selvom chancen for det cirka er som af bli' ramt af lynet
For selvom tiden gør os lettere tåget
Så gir' det os en mentalitet der gør at folk de vil kæmpe for noget
Til trods for en bjørnebryg og en fernet
Det har sløvet og bedøvet et større styk' af min hjerne

[Omkvæd: Pede B]
Jeg' et barn af tiderne, jeg et firserbarn
Den slags medierne ofte viser frem
Som et hidsigt skarn, eller et bittert barn
Hvis du ligesom mig homie lav lidt mere larm
Jeg' et barn af tiderne, jeg et firserbarn
Den slags medierne ofte viser frem
Som et hidsigt skarn, eller et bittert barn
Hvis du ligesom mig homie la' mig se din arm

[Bro: Pede B]
Generationen efter generation X
Hvor alle er efter store checks or Rolex
Forstår ik' hvorfor det forarger en hver
Når de siger ungdommen er anti-autoritær
Jeg mener, pædagoger lærte os helt tilbage ved børneleg
At vi skulle tro på noget blindt, men stille spørgsmåltegn
Sæt det sammen med politiet på vores fristad
Der daglig pisser hele byen af men virker ligeglad
Forventer de så vi skal bak' tilbage
Og slappe af, derhjemme med lidt kaf-og-kage - næh
Folk de blir' vrede og vil slås
Så de blir' til vores billede af at regeringen hader os
Faktum er at de gør større skade
Ligesom de spør' efter ballade når de gør alle gadens børn vrede
Har det som Clemens på sin første plade
Hr. Betjent hvis du slappede af ville det sgu gøre mig glad