[Intro]
And I’m willing to borrow your grass
But I specialize in eating MC's
In the immortal words of LL Cool J
As he would say: "I'm a G.O.A.T.!"
And for those of y'all who don't know what a G.O.A.T. is
It means the Greatest Of All Time
And I consider myself one of those
So thank you very much, here it goes

[Verse 1]
This is the part I was worried about
Everyone thinks that my career is down the tubes
And I'm in some dusty garage
Inhalin' them carbon monoxide fumes
And everyone's tellin' me what I should do
And how I should come out and what to rap about
And I know I got a lot up
In my medulla oblongata that I gotta get out
And I'm not sure how this is gonna come off
They're probably gonna think that I'm comin' off as cocky
Like I just started givin' a fuck what you really think about me
See, the thing about me
Is you don't really know a thing about me
Everyone's makin' a stink about me
Like there's some kind of an aura of that of the king around me
Surround me with nothin' but gangsters
Killers and bangers and the most dangerous criminals
And I feel like I'm more comfortable around them
Than I do my own motherfuckin' neighbors
But, see, my dream is to be remembered
As one of the best when I leave; why does it seem like I'm not even put up in the same category as other MC's?
So when Weezy says that he's better than Jay Z
Please be that just subliminally
Means he thinks Jigga's the best
And that he's the only one up in that league, see
And it's easy just to consider me
One of the greatest white rappers there is
Knowin' goddamn well that I'm one of the best motherfuckin' rappers who ever lived, period

[Hook]
I'm a G.O.A.T. and I don't mean to gloat
But I know what I know and I know what you think
And these magazines'll never put it in ink
Because how would it look
If they considered me as a G.O.A.T.?
And for those of y'all who don't know what a G.O.A.T. is
It means the Greatest Of All Time
And I consider myself one of those
So thank you very much, here it goes

[Verse 2]
Maybe they figure that I'm on my way out the game
So they gotta go try to find 'em
A new Eminem or a new Shady
If they think it's gonna happen, man, I thought I was crazy
Or maybe I could be takin' it wrong
And they're tryna pay homage to me in a strange way
So let me pay homage to my fellow white competitors
Almost in the same way
See, you hardly ever do hear anyone even bringin' up that Paul Wall's white, ‘cause lyrically he doesn't pose a threat to anyone, see, he's just aight
And Bubba Sparxxx, he just won't write
Because he's so caught up in that snow white
That Timbaland can't even get him in the studio
He's so gone off that coke, right?
And it's so sad, ‘cause he's dope, right?
America's next great white hope, right?
So now they feel like they gotta come up with
Some corny-ass White Rapper Show, right?
And which I'm still havin' mixed feelings about
They said it'd be real, I'm just spillin' it out
There's somethin' about a white boy talking black
And runnin' around with a damn grill in his mouth
And I love when the say that Tiger Woods shit
"Isn't it ironic that the best rapper's white
And the best golfer's black?"
And I'm the one who's gotta catch all the flack off of that
But these are the people who
Never had heard of an Eminem until 8 Mile had came out
But I had already hit middle America
Parents had all got to likin' me now
When suddenly I wasn't such a bad guy
All of the hatred for me must've died
Thought I committed career suicide
So I had to turn back into the bad guy
So faggoty faggoty faggoty gays
Anatomy God made Raggedy Ann and Andy
Not Raggedy Andy and Andy and Andy
And Angelina Jolie is just another ho, and Brad is a sucka
Because once I fuck her, she wants to go to Somalia to adopt another baby; you know what I say? "No."
You better save some of them kids from Madonna
She needs all the publicity she can get
You wanted Shady, well
You got it, man, I ain't apologizin' for shit

[Hook]
I'm a G.O.A.T. and I don't mean to gloat
But I know what I know and I know what you think
And these magazines'll never put it in ink
Because how would it look
If they considered me as a G.O.A.T.?
And for those of y'all who don't know what a G.O.A.T. is
It means the Greatest Of All Time
And I consider myself one of those
So thank you very much, here it goes

[Outro]
Man, I'm takin' my ball and goin' home
Man, shit is too easy
Nobody even wants to pass me the ball
‘Cause I'm a G.O.A.T
So don't worry, I'm out the motherfuckin' game
And y'all can sit and argue about who's the motherfuckin' best
But y'all know that  I'm a G.O.A.T
And like I said, I'm one of the motherfuckin' best
Before you get your panties in a motherfuckin' bunch
But before I go, I'd like to say fuck you very much
To everybody who wasn't there from the start
And thank you very much to everybody who was
And y'all ain't gotta say it, just think it
‘Cause I know that you know that I know
That you know that I know that you know that I'm a G.O.A.T
I'm out, y'all, it's been real, peace