[Verse 1]
You'll never make me stay so take your head off of me
I know your every move, so won't you please let me be
I've been here times before but I was too blind to see
That you seduce every man, this time you won't seduce me
She's saying that's ok, hey baby do what you please
I have the stuff that you want, I am the thing that you need
She looked me deep in the eyes, she's touchin' me so to start
She says there's no turnin' back, she trapped me in her heart

[Hook]
Dirty Diana, no, Dirty Diana, no
Dirty Diana, no, Dirty Diana, let me be!
Oh no... Oh no... Oh no...

[Verse 2]
She likes the boys in the band, she knows when they come to town
Every musician's fan after the, curtain comes down
She waits at backstage doors for those who have prestige
Who promise fortune and fame, a life that's so carefree
She's saying that's ok, hey baby do what you want
I'll be your night lovin' thing, I'll be the freak you can taunt
And I don't care what you say, I want to go too far
I'll be your everything if you make me a star

[Hook]
Dirty Diana, no, Dirty Diana, no
Dirty Diana, no, Dirty Diana, let me be!
Oh no... Oh no... Oh no...

[Verse 3]
She said I have to go home cause I'm real tired you see
But I hate sleepin' alone, why don't you come with me
I said my baby's at home, she's probably worried tonight
I didn't call on the phone to say that I'm alright
Diana walked up to me, she said I'm all yours tonight
At that I ran to the phone sayin' baby I'm alright
I said but unlock the door because I forgot the key
She said he's not coming back because he's sleeping with me

[Hook]
Dirty Diana, no, Dirty Diana, no
Dirty Diana, no, Dirty Diana, let me be!
Oh no... Oh no... Oh no...