[Produced by Thelonious Martin]

[Verse 1: Joey Bada$$]
Yo, yo
My days numbered to infinity, when I close my eyes
I see the trinity, mind, body, & soul holds the energy
But they dont know the inner g, I try to keep serenity
But enemies, always try to end me and my entity
But eventually we all gotta go someday
And I ain't shine as a star if it ain't on a sunday
But I know you see my rising son, cause when I do your ho rising too
The beast coast we deeper than verizon crew, in all our eyes is hues of blue and indigo
If you dont plan on controlling your soul, than what you in it fo? it's intricate tho
To be this intrinsical, it may seem like we occult but we ain't mystical
You missed the show
So put ya weapons or whatever your collecting
Word to my brethren conception, STEEZ I knew it swept us
They believe in false projections of the evil essence/lessons
So sleep on the progressive and wake up in the Medieval section

[Hook: Joey Badass]
When we Kings most praise to the most high
When we Kings be afraid dont apporach I
When we kings, and we conquer the Earth, been on my conscious from birth
Dont dishonor the work just honor the perks

[Verse 2: Capital STEEZ]
Like I ain't notice we corrupting ourself
I lost too much for the belt, and now Im up on cloud 1 hundred and 12th
I'm too high on my own supply of false egos
We flyer than bald eagles, still incognito
Like I think we lost Steelo, vibe as I tune in
I just lost one, now I'm walkin like a new man
Never wake the student in the words of Confucius
It's confusing if you snoozing and you trying to pay your tutor
Ya'll losers get smacked by the rulers
Got dunce caps and lunch bags waiting when I school ya
Class is in session, we the masters of progression G-shit
This is passion, but cash had to be second
They blinded by fears, we the new light bearers
In your area, open your ears you might hear
Came from the underground but I ain't climb a flight of stairs
And everything I thought that I needed was right there

[Hook x2]