[Intro: Celph Titled]
{"You know in the good ole' days
We'd have a smart punk like you fitted for a pair of cement pajamas
For a long sleep at the bottom of the river"}
Yeah, Celph Titled AKA Jesus Ice
Shinin' the chrome for all you horseless headman motherfuckers

[Verse 1: Celph Titled]
You hear the sound of ricochet you better duck to Hell
Appetite for destruction
After the lead releases I suck the shells
Chrome Depot culinary art form
It's magnifique
I need a female with Kelly Price physique
I'm sick in the noggin'
This ain't for the squeamish
I stay givin' it to pussies whether I use my knife or I use my penis
It's a full moon and my K-9's came with grey nines
Now you speechless, with your hands up like a gay mime
I heard Satan talkin' shit and had to pistol whip the bitch
Put a crack in his horns
Became John Malkovitch
In my casket with a poker face
I'm dead serious
Ricky Ricardo on some conspiracy theory shit
I'm goin' Hollywood in three seconds flat
Detonate the nuke?
You'll need a chin strap for that fitted cap
No special effects, these are real torpedoes
Catch my snuff film live on MTV Making The Video

[Hook]
Y'all wanna see a show for free?
"You can suck my dick" - Ol' Dirty Bastard 'Brooklyn Zoo'
You broke and want a beat from me?
"You can suck my dick"
All you fags that get offended
"You can suck my dick"
Conscious rapper tryin' to talk shit
"You can suck my dick"
Bitches think they doin' favors
"You can suck my dick"
All you critics and player haters
"You can suck my dick"
If you don't have my money on hand
"Now which part of 'Suck my dick' don't you understand" - Show & AG

[Verse 2: Celph Titled]
I really love it when these bitches start cursin' at me
It's like they swearin' to God, don't take it personally
Come at me sideways and get twisted backwards
Hollow points move forwards in all directions the outcomes disastrous
You better call the psych hot line and find out if my Glock nine
Will leave you bleedin' in a shirt that says "Stop Crime"
Chain down to my feet rockin' an Iceberg scarf
Out from Con Edison's ? in Central Park
Caped Crusada with a baked potato
Stuck in the nozzle so the gun blast sounds like space invader phases
Homo rap cats, y'all some undercover brothers
You photo shoot look like a Tevin Campbell album cover
Chillin' in Tampa Bay, 100 degrees with a ski mask
A dirty desperado type of nigga (believe dat)
My man J-Zone made a track for me to spit to
And show these motherfuckers what a crazy spic will do

[Hook]
Y'all don't like battle rhymes
"You can suck my dick"
You don't wanna see me shine
"You can suck my dick"
Think I won't use my Beretta
"You can suck my dick"
You're jealous and think you're better
"You can suck my dick"
Want me to hear you demo tape
"You can suck my dick"
Don't wanna say it to my face
"You can suck my dick"
You think I fear another man
"Now which part of 'suck my dick' don't you understand?"

"Who are you?"
"The man with a gun. Pow. How bout you?"
"Suck my dick"
"Suck my..."
"With my nuts on your tonsil" - Snoop Dogg 'Dre Day'

[Verse 3: Celph Titled]
Excuse me
What's all this rap shit about?
Fuckin' with me, the only thing comin' off your dome is ya scalp
You probably think I fantasize of blastin' a tech
I'd rather punch your teeth till they poke out the back of your neck
Whilin' out
Knockin' out jake, breakin' his jaw
Now that's what the fuck I call, layin' down the law
World renown king of punchlines
Grimy rap, gangsta shit
Spit harder than a nervous gun with anxious clips
This twelve inch will destruct when I'm dead
And you'll be wonderin', "You think he went to Hell for all that shit he said?"
I'm formin' a group with real criminals
Chi Ali, Steady-B, Cool C, rappers with real rap sheets
And nasty tracks with beats
Put more crack in the streets
When 808 bass kicks, breaks shit
My earthquake hits...
Way beyond the San Andreas
Remain Godly
With Elvis and 2Pac at my record release party

[Hook]
You're an ugly ho but still
"You can suck my dick"
You don't think this track is ill
"You can suck my dick"
You don't like my choice of words
"You can suck my dick"
Think you could spit a better verse?
"You can suck my dick"
You think you got the nicest crew?
"You can suck my dick"
And act hard in interviews
"You can suck my dick"
You ain't a Celph Titled fan
"Now which part of 'Suck my dick' don't you understand?"
"Suck my dick"
"Suck my dick"
"Suck my..."
"You can suck my...."