[Intro]
Freeverse (RND)

                                       Não convence

[Verso 1]
Quebro as leis, busco nisso redenção
Alguns nomes vem e vão, o resto é sangue e canção
Os dias que passam em passos que pregam mais peças que um falso sermão
Sem dia propicio, é o inicio e o indicio da raiva em um dia de cão
Televisões e faróis num transe, o trânsito para e eu esqueci o que vi
A valsa de Banshee e o tédio, o sexo ainda é remédio
Sem céu, só sacadas de prédios
Os homens e seus sonhos médios
Tudo isso num relato débil desse que vos fala e ama ser ébrio
Em Abril o rápido apego de Dezembro some
Aquele que é soberbo mente em seu nome
Aquele que é humilde se apega a fome
De ter o que não teve e ser um novo homem
A vida atropela o que bom pra seguir as regras do ponteiro do tempo
E eu busco uma forma sensata de entender a vida e seus desacertos, e campos
Fim do ano da serpente, cruzes, calibres e pentes
Meus olhos atentos ao enferrujado elo que segura as correntes
As colunas de São Paulo, Eclesiastes
Eu sou um tolo ou um sábio?

[Ponte]
E eu...
Eu sou um tolo ou um sábio?
Eu sou um tolo ou um sábio?
Eu sou um tolo ou um sábio?
Tolo ou um sábio?
Tolo ou um sábio?
Eu sou um tolo ou um sábio?
Eu sou um tolo ou um sábio?

[Verso 2]
E não convence, todo sacrifício que te faz perder o senso
Te transforma em maquina dentro de um mundo imenso
Faz da sua rotina apenas um grilhão que...
E não convence, todo sacrifício que engole o que tu pense
Te transforma em gado dentro de um ciclo intenso
Faz da sua rotina (apenas) uma passagem que não...


                                             P.D.M

[Verso]
Eu falo o necessário, calo esses otários
Não vendo a mentira, ando nas bordas do pário
Foda-se sua integridade, desintegro a maldade
Você não tem mais idade pra esse tipo de levantamento
Eu corro com o tempo, eu fodo seu rap
O nome do vento, em nome do vento
Mentiras e mais mentiras contadas, armadas, montadas
Passadas com bons odores, mas vocês falsos atores
Conquistando corações em oratórias de dores, não prestam
Sem tapa e sem topo, não topo, não engulo, não acato
Vocês esqueceram de dizer que além do rap, a hipocrisia de vocês
é um fato
Sem tapa e sem topo, vocês vão se engasgar com meu vômito
Cômico, trágico, cegar os moleques em idéias retrogradas é cômodo
Incomodo, eu e Deus, o Outro e a Terra
Tudo válido, sua tolice é invalida, pálida, lapida
Cérebros que preferem éticas mentirosas do que sinceras animalidades
VOLTEI, A.L.M.A, sangue, vida, choro, esforço, verdade
Maldade, intriga, ressaca, tédio, tirania e saudade
Tudo já foi dito, esqueceram da fragilidade
Uma parte vivi, ainda me falta metade
Ainda me falta metade, mais da metade da meta de vocês apago com ira
Quem dirá, que vira, a pira, de dar o escuro e dizer que essa porra é luz?
Quem conduz? Quem disse pra você que você conduz?
Anos luz a frente desse papo fodido de Fake Progress, é um regresso
Eu detesto, eu impeço, eu não meço esforços, remorsos
Ei Moços, acordem! Já e tarde, tão tarde
Eu odeio acordar cedo e já é tão tarde!