[Intro: Stract]
Seeking to reveal all components of truth
Seeking to reveal all components of truth

[Verse 1: Stract]
Another day another dollar, another dollar another day
And with the words I am a scholar
Knowledge lodged within my brain
Your skull is hollower than clay pots, oughta brought a lot of shame
I know that's kinda hard to swallow like a taco that has aged
It's an intolerable taste, I know it's bothersome to say
But you just fall into a phase and started following for fame
You're simply hopping on the train but you ain't got a lot to say
How many rappers am I gonna end up slaughtering today?
Take the revolver out the case, and bars, I'll launch them if I may
To planet Mars and bring you back when you're recalling of the name
The name is Stract, if you forgot the proper way to say it
Problem solved, now watch as I evolve before your face cause it's the
Critic killer, quick-witted spitter
The sinister slick riddler, legitimate big figure
A mastermind just passing time and rhyming 'til I'm fit to
Leave the scene as soon as these lyrics have been delivered
I'm spitting the killer flows and ripping a hole right through most
Emcees want a piece of me, I'm flipping them like it's judo
Make them freeze, my steeze is zero degrees, I'm dripping with snow, I'm too cold
When I'm deceased, the second my spirit's released, it's written upon the tombstone

[Refrain: Stract]
Seeking to reveal all components of truth
Seeking to reveal all components of truth

[Verse 2: Stract]
Ha, sicker than your average, Stract twist cabbage off instinct
Bandages are recommended for the damage
I'm headed straight for the win with no challenge
Steal it then I vanish, feeling like a savage
Mastering the craft like an addict
Consistent practicing 'til my raps are the baddest
Damn it, most want it but can't have it
I'll rap 'til I collapse and then perhaps it will be granted
I'll rap 'til I collapse and then perhaps it will be granted