[Chorus: Perrie]
All day I dream about shh with you
All day I dream about shh with you
They say that it's overrated, well they ain't doing it right
All day I dream about shh with you

[Verse 1: Jesy]
Since I met you I been thinking all day
I been Googling ways to keep you entertained
It's been three weeks since we started to play
Now it's serious babe cause what you do is crazy

[Pre-Chorus: Perrie]
I never had somebody who could do them things
Make me say ooh ooh ooh
So come on baby baby, come on pretty baby
You're gonna get it tonight

[Chorus: Jesy, with Jade]
All day I dream about shh with you
All day I dream about shh with you
They say that it's overrated, well they ain't doing it right
All day I dream about shh with you

[Verse 2: Jade]
Slaving in the kitchen, iced you a cake
Then I served you a plate, but that ain't what you ate, no
We been busy doing all Fifty Shades
While we listen to Drake, we on that hot love and emotion

[Pre-Chorus: Leigh-Anne]
I never had somebody who could do them things
Make me say ooh ooh ooh
So come on baby baby, come on pretty baby
You're gonna get it tonight

[Chorus: Jade]
All day I dream about shh with you
All day I dream about shh with you
They say that it's overrated, well they ain't doing it right
All day I dream about shh with you

[Bridge: Jesy & Jade & Perrie & (Leigh-Anne)]
You got that goodie goodie and I'm addicted
I'm on that kissy kissy, bang bang delicious
All day I dream about it, baby so how's about it
You know I'm all about that
(All day I dream about, wait, all day I dream about, wait
All day I dream about, shh with you)

[Verse 3: Leigh-Anne]
Excuse me, do me or lose me
Get me to the bedroom, do your duty
Milkshake milkshake
Bet you like some of that strawberry
Like a wave gonna come tsunami
Wanna take this ride better hurry
Cause me one, you there's a million
And they all wanna huh my Brazillian

[Chorus: Leigh Anne]
They say that it's overrated, well they ain't doing it right
All day I dream about shh with you