(Bridge)
Every day I’m all about that dollar bill hoe
That R E S P E C T I kill for
Lost a hundred grand, made a hundred mill though
My money long, your money short, back out so stand up

(Hook)
I’m lookin good, I roll the block
I’m all about that GDOD, hoe, get dough or die
Say I ain’t getting it, who told done told the lie?
I’m all about that GDOD, hoe, get dough or die

(Verse)
Say girl stand, stakin, I can hit a mill
Playin hay, getting on my ass, I don’t give a fuck
We talkin paper, hood is up, we get them figures up
The order I’m payin for, I hit them niggas up
Triple OG, they can sit around
Slurp green like nigga you a sitting duck
I park a drive, you suck a dick then I’m still bonified
GDOD, you know me homie, know I’m gonna ride
My reputation all I got
Some say I’m snitchin, pussy nigga, who you talkin bout?
Fuck nigga, we can have a paper work party
But she ain’t got no patience, Shawty do that work for me

(Bridge)
Every day I’m all about that dollar bill hoe
That R E S P E C T I kill for
Lost a hundred grand, made a hundred mill though
My money long, your money short, back out so stand up

(Hook)
I’m lookin good, I roll the block
I’m all about that GDOD, hoe, get dough or die
Say I ain’t getting it, who told done told the lie?
I’m all about that GDOD, hoe, get dough or die

(Verse)
I’m about that paper, I’mma get that til I die
I’m not understanding you, we’ll see when we can lie
I’m ridin round solo with some titties in my right
They say we ain’t getting money, they don’t motherfuckin lie
I’m like shittin rich, we getting karats by the pound
We ain’t countin that so we gonna be countin for a while
Cut through it when I shoot
Now they through it in the top
‘Cause everybody came through
Shawty take they ball
Get dough or die, they where you need it ho
Though how the streets talkin you a dead man walkin
And I just bought a Louie belt to hold that 40
If you play emotion to the death with that big ol 40
For real, I’m preachin out in Ogeeda
Don’t talk about yo real, boy I’m walkin on the real
Any boogers in my ear cost me brick fair
All white BBS’s look like fish scale

(Bridge)
Every day I’m all about that dollar bill hoe
That R E S P E C T I kill for
Lost a hundred grand, made a hundred mill though
My money long, your money short, back out so stand up

(Hook)
I’m lookin good, I roll the block
I’m all about that GDOD, hoe, get dough or die
Say I ain’t getting it, who told done told the lie?
I’m all about that GDOD, hoe, get dough or die

(Verse)
I’m all about my paper, bustin for my cheddar
The reason why you broke ‘cause you don’t know no better
You not talkin money I can’t see yo visions
All I do is getting money, that my true religion
I will bust it down, pass when you were washin dishes
You was workin for the man, now we’re still up in it
We ain’t ghosts in the ghost, nothing is rented
I don’t even know the price, bitch I just spin it
You see them Forgiato bitch, I pull em on the curb
If she’s not a bad bitch she getting no swerve
Can’t even swing a rack, no sir
I’m a selling digit nigga, like a phone long bird

(Bridge)
Every day I’m all about that dollar bill hoe
That R E S P E C T I kill for
Lost a hundred grand, made a hundred mill though
My money long, your money short, back out so stand up

(Hook)
I’m lookin good, I roll the block
I’m all about that GDOD, hoe, get dough or die
Say I ain’t getting it, who told done told the lie?
I’m all about that GDOD, hoe, get dough or die