[Chorus: Caskey & Famous Dex]
I'm lit, ayy ayy (I'm lit)
My bitch is thick, she roll with sticks
I'm lit, ayy ayy
I'm dressed in wick, I'm too legit
Ayy ayy (ayy ayy)
I'm lit, I'm lit, I'm lit, I'm lit
Hey, Caskey, what up, bro?
Ayy ayy (ayy ayy)
My bitch is thick, I roll with sticks, ayy ayy
Ah Dexter! Ah what?

[Verse 1: Famous Dex]
I'm lit, I'm lit, huh
Run up on him with a stick, cocked
Your bitch a bitch
Fuckin' on his lil bitch, ooh, huh
Swear to God, bitch, you a lame lil hoe
Fuckin' lil bitch, give me brain, lil hoe
I don't do it for the fame, lil hoe
Run up on him with the banger, hoe
Bang! Bang! Bang!
Run up on him, blow his brain, brain, brain, brain
What, huh? Yeah, go and shoot him, snatch his chain
Ooh, what? Yeah, ooh, smokin' on poo
Fuck on your boo, huh
I get the money, I swear that these blues, yeah, Dexter

[Verse 2: Caskey]
I'm lit, I'm lit, huh, yeah
No one could tell me I owe 'em shit
I'm lit, I'm lit, yeah
What's on your hip? That's some Rick Owens shit
I bought a zip, she up in my whip
Ayy, shorty, I got a ownership
She won't give me lip, she hopin' the tip
Is what I got sittin' up on her
My bitch too hot, had to freeze her
She know I don't need her, I'm sippin' out the new two liter
Weed like the [?]
Perk, sittin' in the vert with a eater
Damn, shorty got her friends
But we sittin' inside the two seater
Yeah, so I just had to swap out that coupe for a beamer

[Chorus: Caskey]
I'm lit, ayy ayy (I'm lit)
My bitch is thick, she roll with sticks
I'm lit, ayy ayy
I'm dressed in wick, I'm too legit
Ayy ayy (ayy ayy)
I'm lit, I'm lit, I'm lit, I'm lit
Ayy ayy (ayy ayy)
My bitch is thick, I roll with sticks, ayy ayy