[Verse 1]
Fuck the police
I'm sick of internet scams
And these cigarette brands
Call Parliament
I'm so non partisan
But still a part of sin
Drunk in my apartment, woah
When it so darkening
I can never get a break dog
Feel like i always gotta start again
I wanna shake it off, Parkinson's
Rock shades with a darker lense
Sick of minimum wage and my awful French
I wanna look upon days with a softer bench
I wanna prosper
But it's like every week rollin' with the coppers
What they want with the kid
Try'na turn this 'lil Honda Civic to a helicopter

[Chorus]
Watch for the P.I.G.S
(keep yo eyes open for these police man, mother fuckers don't give a fuck about you. They don't give a fuck about me. They not here for us, they here for the state.)
Watch for the police, peace
Ridin' 'round with yo' piece
Watch for the police
Ya, keep the peace
Ridin' 'round with yo' piece

[Verse 2]
Just want po' promethazine
I get ghost, go get the cream
My big bro know Medellín
He serve coke, know better things
I been on the list for a minute
I'm on X tour, I'm infinite
She want sex too, and I'm chillin'
Nah, really i don't got jade
But i do gotttt feelings
Don't talk to twelve about nothin'
I don't want fetti
(fuck all that shit)
Only thing i be suckin' up is some titties
So fuck the police
Tell them boys to come get me
I don't give a fuck about'cha, got it with me

[Chorus]
Fuck the police
Mother fuckers out here playing for keeps
Ridin' 'round in these streets
Try'na eat, but chy'all boy sleep
Watch for the police, peace
Ridin' 'round with yo' piece
Watch for the police
Ya, keep the peace
Ridin' 'round with yo' piece
Watch for the police (x4)

[Verse 3]
Bangin' numbers on the hall
Last time i got stopped
I was on the Harley drinkin' alcohol
Time before that i had the strap
I done been caught with Ecstasy
Police tellin' me to strip naked, lookin' sexually
Fuck outta here
Feel like someone try'na stop my career
Feel like the badge say one thing about'cha
'ey treat you like intimidation, i never fear
Sippin' lean inside the house
I done quit it in a year
They gave me enough for a life
Did it all in a year
Shout out to everyone who got a beer

[Chorus]
Fuck the police
Only time i'm finna' do is on these beats
Runnin' 'round in these streets
Ya, try'na eat
I couldn't even be an asshole for free

Fuck the police, ya, peace
Ridin' 'round with yo' piece
Watch for the police
Ya, keep the peace
Ridin' 'round with the piece
Fuck the police (x3)