Hella gang signs and shit
Ho-o-o-o-ly sh..

[Chorus: Yhung T.O.]
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' it, if you wit' it, I'm wit' it, I'm wit' cha, girl
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' cha, if you wit' it, I'm wit', I'm wit' cha, girl

[Verse 1: Yhung T.O.]
You know I’m with it, bounce out, 30 shots get to trippin' yeah
Let me hit it, young nigga, young nigga, worth a million, yeah
And I'm wit' all that shit, how much I made last month?
I couldn't call that shit, and she know I'm rich
She say she love you, but I still wouldn't trust that bitch
And we go way back on that throwback shit
Know I run up a check and I blow that shit
It ain't nothin' to a boss, when you on that shit
Bounce out that big Benz wit' that long ass stick

[Chorus: Yhung T.O.]
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' it, if you wit' it, I'm wit' it, I'm wit' cha, girl
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' cha, if you wit' it, I'm wit', I'm wit' cha, girl

[Verse 2: Yhung T.O.]
And I still made time
'Cause I know they don't make 'em like mine
Girl I got a lot of money, I'm fine
I can take care of you and your moms
I'm a young rich nigga and I'm still wit' the shit
I can't trust a broke nigga who be stealin' and shit
In that big body Benz, get to kissin' some shit
Ex nigga hit her phone, in his feelings and shit
Aye, I don't trust that nigga
If he look the wrong way, I might bust that nigga
She said she stuck with a nigga
Only take one time to fall in love with a nigga

[Chorus: Yhung T.O.]
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' it, if you wit' it, I'm wit' it, I'm wit' cha, girl
Young nigga, fall wit' it, fall wit', young nigga, yeah
And I'm wit' cha, if you wit' it, I'm wit', I'm wit' cha, girl