[Intro]
On the east side (yeah, yeah)
On the west side (huh)
You know how we ride
Yeah

[Chorus]
I get love on the east side (yeah)
I get love on the west side (yeah)
I get love on the north side (yeah)
I get love on the south side (yeah)
Thirty deep, you know how we ride (yeah)
Oh my god, she is not my type (yeah)
I just get her wet like Slip 'N Slide (yeah)
Shawty, I could really change your life (yeah)

[Verse 1]
Shawty wetter than a forest, she gorgeous
Back it up, that thing enormous, I'm on it
I can never say it's not mine, she too fine
Shawty always let me wine and dine, like every time
Hit the mall, we buyin' Gucci, she boujee
Chain colder than a smoothie, like ouuiee
Me and shawty off that good gas, grade A
Every day it's fuckin' pay day, can I say
I been flexin' on my old hoes, it feels good
I just had to set some new goals so I could
Stunt harder than I ever have, it's so sad
Pussy niggas out here getting mad, I'm getting cash
Look at life, I'm workin' hard now, hands down
Feels good makin' my mom proud and see her smile
Boy, I'm aimin' for the stars now, no lookin' down
Since I'm up, they wanna come around, I shut 'em down

[Chorus]
I get love on the east side (yeah)
I get love on the west side (yeah)
I get love on the north side (yeah)
I get love on the south side
Thirty deep, you know how we ride (yeah)
Oh my god, she is not my type (yeah)
I just get her wet like Slip 'N Slide (yeah)
Shawty, I could really change your life (yeah, yeah, yeah)

[Verse 2]
I had to go get a check, yuh
That why these hoes gimme neck, yuh
All of my bitches finesse, yuh
In the game like the ref, yuh
Me embody, shawty clean, ayy
She gon' do it for the team, ayy
Shawty loyal to her dreams, ayy
Like she Martin Luther King, ayy
Margiela on the feet, ayy
Shawty style too elite, ayy
She my beauty, I'm the beast, whoa
We gon' eat like a feast, whoa
Better yet, think again, ayy
Joker and Harley Quinn, ayy
Screamin', "Fuck fake friends," ayy
Me and shawty need a Benz, ayy
And it's alright
Watch my friends turn fake as they see me on the rise
I remember being broke, used to have to sacrifice
Now I'm always on my vibe even through my hard times
I know niggas ain't real
I know bitches ain't real
I can never ever lack, I just had to bring it back
We was runnin' after rags, dodgin' cops, sellin' pack

[Chorus]
On the east side (yeah)
I get love on the west side (yeah)
I get love on the north side (yeah)
I get love on the south side (yeah)
Thirty deep, you know how we ride (yeah)
Oh my god, she is not my type (yeah)
I just get her wet like Slip 'N Slide (yeah)
Shawty, I could really change your life (yeah, yeah, yeah)