[Verse 1: Andy Mineo]
This is all out of my control, really
I got one job, make the flow silly
Serve one God, it's my sole mission
When I'm out of here, man, I won't miss it
How that man went and sold fifty?
Not one blogger even noticed him
But they don't diss them, they just don't listen
Oh I get it, they don't get it
At the shows some blow sticky
Some ladies even throw Vickie's
But he stay pure, that's so Disney
Shout Soulection, my bro's in it
Out the rappers in this whole city
Not one of y'all was ever gon' pick me
So I picked the locks then came through the back doors
Sold out shows and still got my soul with me, woo!
Stranger things have happened
And a white boy like me blackin'
On a track I'm going bad again
Got a baddie and she going Randy Savage (oh, yeah!)
All I know is that family matters
All I know when I came in rappin'
If you jack somebody else flow and style
Then you gon get a black eye like "Panda"
Put up or shut up, so what up, I'm here?
I don't got nothing to fear
I don't go one up my peers, I just been pushing myself
I don't like cussin', but this one I swear
When I start bustin' they shouldn't be near
They never been accustomed to hearin' this custom-made flow
They just copy the stuff that they hear
Man, they always come up short
I'm a sneaker connoisseur
I been readin' Art of War
Don't they see I got some more? (what else)
Loop the beat up for your boy
I'ma need another four
Before I leave it at the morgue
Yeah, we winnin', but who keepin' score?

[Chorus: Andy Mineo]
I'ma run up the score (run it up)
Yeah, run up the score (run it up)
I'ma run up the score
I'ma need a few more
I ain't talkin' 'bout twenty five, twenty five, twenty five, ayy
Thirty five, thirty five, thirty five, ayy
Can't stop, can't stop, gotta be great
Ain't nobody safe
I'ma run up the score (run it up)
I'ma run up the score (run it up)
Yeah, run up the score (tell 'em)
I'ma need a few more
I ain't talkin' 'bout twenty five, twenty five, twenty five, ayy
Thirty five, thirty five, thirty five, ayy
Can't stop, can't stop, gotta be great, ayy
Ain't nobody safe

[Verse 2: Wordsplayed]
I'ma run up the score (who runnin'?)
I'ma run up the hills (who runnin'?)
Yeah, in Hollywood (skeesh)
Still kept it real (okay)
That's how you feel? (true story)
Oh, that's how you feel? (true story)
We out there in the field like Holyfield
MJ, Magic Johnson
Michael Jordan, Michael Johnson
Run the track, walk the score up
Minor League, chart the border
Where the tour? South of Florida
Son of Mary, all glory
Hail Mary on the fourth of forty
After parties at the forty forty
All the teachers wanna told my momma that boy too slow (sorry)
So I came back around and hit them with the bacon, egg and cheese flow (true story)
Harlem River, drive all the way back my seat go (skrrt)
Take the field, won't take a knee
Ah, yeah you know

[Chorus: Andy Mineo]
I'ma run up the score (run it up)
Yeah, run up the score (run it up)
I'ma run up the score
I'ma need a few more
I ain't talkin' 'bout twenty five, twenty five, twenty five, ayy
Thirty five, thirty five, thirty five, ayy
Can't stop, can't stop, let it be great, ayy
Ain't nobody safe
I'ma run up the score (run it up)
I'ma run up the score (run it up)
Yeah run up the score
I'ma need a few more
I ain't talkin' 'bout twenty five, twenty five, twenty five, ayy
Thirty five, thirty five, thirty five, ayy
Can't stop, can't stop, gotta be great, ayy
Ain't nobody safe
Might run up the score

[Outro]
That was embarrassing
No mercy
He really ran the score up on that one
Beam did it again
Too much sauce!