[Verse]
Tire marks, tire marks, finish line with the fire marks
When the relay starts I’m a runaway slave-master
Shittin’ on the past gotta spit it like a pastor
After, bash her, did it like doe like dasher, faster-motorbike faster
Iggy gotta get a bitch watch for my rapture
White bitch go, ’bout to blow like the wind
Penthouse too, roof top at the Wynn
When I win, when I win I win
No when I wid ’em they good like shin
Got hoes on call, got hoes on call
To come through take a pro-to-call
Just damagin’ that’s my protocol
Dismantle ya, Australians on Slauson
No camera, I don’t care who you are
No condom rap gotta give it to you raw
Pitchfork point, better pass me the joint
Gotta twist this beat I’ma sprain my joint
Straight crack rock, ball till I pop, pop
Pull my trigger, Rap City, no Tigga
Yeah shorty do it illa’ I’m raw no Digga’
What’s my muthafuckin’ name it’s Iggy not Jigga
Don’t compare me to her, throw the bitch in the ditch
Ruff ruff ho, kill the bitch I'm Vick
Sewed the game up stapled up in a stitch
Click-click pow D.R.U.G.S. gang, my clique
Look at my heels LV on it, ignorant art, everybody on it
Everybody want it, 666 got a three-car garage
Driveway be The Omen, boss like Cohen
Hate me, Chordz 3D can’t see me
Pockets better than a H3, I don’t see you like mace-me, ugh
D.R.U.G.S - click oh and we on - hater
On these hoes hairs no activator
Whores fuck up when he activate-her
Cuz I’m goin’ out with my hand raised
’Bout to smack, smack, smack till my hand cave
On the bitch-made, honey I’m paid
I’ma get laid fuck yer man cave
Ya act like ya real, be real, son
Kinda spaced-out you bitches be duckin’
Better than ya girl, than the best, make the competition rest
Unless it’s sex, no less, I’ma fuck the whole game, I’m best
With my strap on, my vibrator, ’bout to bust a rhyme, no violator
Course no, I’ma feel myself
I’m a masturbator like "uh uh uh uh, fuck me, fuck me"
Now I’m off beat, my head hurts, I murk shit, I gets paper
Wash my mouth, I curse like a sailor - bitch!

[Outro: YG]
It's YG 4 Hunnid!
Drug money, fuck with a nigga
Pushin' it like we up in this bitch! Ayy!
Iggy spitting, y'all bitches better get y'all bars up in this bitch
For real though
For real though, for real though
I show y'all, mmm, snapping up
Man, what the fuck?
What the fuck is she doing on Slauson? Somebody tell me
What the fuck is she doing on Slauson?
Ha-ha!
Pussy flavor!
D.R.U.G.S!