Hangul

Stay away from around me
난 네 가르침 따윈 안 따르니
가득 따라
Grab my feet
That’s where you supposed to be Yeah
꼰대 님들아 팔짱 끼고 잘 봐라
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

They be talkin’ s*it
But they never know
I like it I cop it I got it for sure
I don’t drink at all but pour it all up
We don’t f*ck with no petty a*s h*es
꼭지를 돌려 버튼을 눌러
건조한 지폐는 그녀를 놀려
겨울에도 필요 없지 보일러
고온 다습해 I live like a boss

난 검은색은 다 찢어
밤에는 개처럼 짖어
토요일 까지도 미쳐
주일엔 Worship Jesus
난 어쩔 수 가 없는 Sinner
But burn it up make her thinner
이제 시작해 운동회
아침이 올 때까지 운동해

She says She says
She ain’t that kind of woman
What’s That What’s That
You’d better stop pretendin’
우리 만난 지 이젠 꽤 되었지
이제 너도 익숙 해졌지
I be touchin’ 옷이 헤졌지
고갤 숙여 해줘 Yee

Stay away from around me
난 네 가르침 따윈 안 따르니
가득 따라
Grab my feet
That’s where you supposed to be Yeah
꼰대 님들아 팔짱 끼고 잘 봐라
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

난 언제든지 느껴지네 날 향한
그 무의미한 질투와 시기
그건 절대로 안 사라지지 그래
그건 어쩌면 다 나를 위한 지지
난 그저 내 속도를 올리지
더 빠르게 in a new york minute
I gotta grind harder for gettin’
Pool houses and them
Chicks with bikinis

F*ck whoever judge myself
Ain’t nobody got my taste
절대 말 못해 나한텐
Jesus got my back
Money is comin’ to me tho
그녀들이 손을 내 밀어
천천히 움직이지 내 위로
Callin’ me papi
Callin’ me daddy
정신 없이 움직이지 Like merry go

집게사장 난 돈이 좋아
전부 모아서 내게 가지고 와
흥청망청 내 모토 제일 좋아
또 샀지 또 샀지
엄마가 말하길 돈을 좀 모아

Stay away from around me
난 네 가르침 따윈 안 따르니
가득 따라
Grab my feet
That’s where you supposed to be Yeah
꼰대 님들아 팔짱 끼고 잘 봐라
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

Eybody know I’ve been bossin’
Straight rick rossin’
Adidas mix it up with rick owens
I’mma keep goin’
Gettin big dough and spit
Sick flow that s*it flamboyant
Rest in heaven to the legend big L
I see u when i get there tho
뭐를 하던 어딜 가든 나는
야들 과는 사뭇 다른 태도로 임해

Motha f*ckin boss
Im the motha f*ckin’ king
Ridin motha f*ckin’ ghost
Kiss my motha f*ckin’ ring
I got the motha f*ckin’ sauce
Yammo and motha f*ckin’ Dean
F*ck the motha f*ckin’ Lost
We gon’ motha f*ckin’ Win

B o double s 그래 뭐 돈만
마니 번다고 바로 쉽게
되는 것은 아니지
다들 보스보스 거려 똘마니들
여럿 거느리며 고개 위로
치켜들고 다니지
나는 누가 알아봐주길 바라면서
살지 않아 그게 너와 내
쉬운 차이지
We hustle we grind
We puttin’ in work
잠은 죽어서나 자야지

Stay away from around me
난 네 가르침 따윈 안 따르니
가득 따라
Grab my feet
That’s where you supposed to be Yeah
꼰대 님들아 팔짱 끼고 잘 봐라
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

Romanization

Stay away from around me
Nan ne gareuchim ttawin an ttareuni
Gadeuk ttara
Grab my feet
That’s where you supposed to be Yeah
Kkondae nimdeura paljjang kkigo jal bwara
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

They be talkin’ s*it
But they never know
I like it I cop it I got it for sure
I don’t drink at all but pour it all up
We don’t f*ck with no petty a*s h*es
Kkokjireul dollyeo beoteuneul nulleo
Geonjohan jipyeneun geunyeoreul nollyeo
Gyeouredo piryo eopsji boilleo
Goon daseuphae I live like a boss

Nan geomeunsaegeun da jjijeo
Bameneun gaecheoreom jijeo
Toyoil kkajido michyeo
Juiren Worship Jesus
Nan eojjeol su ga eopsneun Sinner
But burn it up make her thinner
Ije sijakhae undonghoe
Achimi ol ttaekkaji undonghae

She says She says
She ain’t that kind of woman
What’s That What’s That
You’d better stop pretendin’
Uri mannan ji ijen kkwae doeeossji
Ije neodo iksuk haejyeossji
I be touchin’ osi hejyeossji
Gogael sugyeo haejwo Yee

Stay away from around me
Nan ne gareuchim ttawin an ttareuni
Gadeuk ttara
Grab my feet
That’s where you supposed to be Yeah
Kkondae nimdeura paljjang kkigo jal bwara
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

Nan eonjedeunji neukkyeojine nal hyanghan
Geu muuimihan jiltuwa sigi
Geugeon jeoldaero an sarajiji geurae
Geugeon eojjeomyeon da nareul wihan jiji
Nan geujeo nae sokdoreul olliji
Deo ppareuge in a new york minute
I gotta grind harder for gettin’
Pool houses and them
Chicks with bikinis

F*ck whoever judge myself
Ain’t nobody got my taste
Jeoldae mal moshae nahanten
Jesus got my back
Money is comin’ to me tho
Geunyeodeuri soneul nae mireo
Cheoncheonhi umjigiji nae wiro
Callin’ me papi
Callin’ me daddy
Jeongsin eopsi umjigiji Like merry go

Jipgesajang nan doni joha
Jeonbu moaseo naege gajigo wa
Heungcheongmangcheong nae moto jeil joha
Tto sassji tto sassji
Eommaga malhagil doneul jom moa

Stay away from around me
Nan ne gareuchim ttawin an ttareuni
Gadeuk ttara
Grab my feet
That’s where you supposed to be Yeah
Kkondae nimdeura paljjang kkigo jal bwara
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss

Eybody know I’ve been bossin’
Straight rick rossin’
Adidas mix it up with rick owens
I’mma keep goin’
Gettin big dough and spit
Sick flow that s*it flamboyant
Rest in heaven to the legend big L
I see u when i get there tho
Mworeul hadeon eodil gadeun naneun
Yadeul gwaneun samut dareun taedoro imhae

Motha f*ckin boss
Im the motha f*ckin’ king
Ridin motha f*ckin’ ghost
Kiss my motha f*ckin’ ring
I got the motha f*ckin’ sauce
Yammo and motha f*ckin’ Dean
F*ck the motha f*ckin’ Lost
We gon’ motha f*ckin’ Win

B o double s geurae mwo donman
Mani beondago baro swipge
Doeneun geoseun aniji
Dadeul boseuboseu georyeo ttolmanideul
Yeoreot geoneurimyeo gogae wiro
Chikyeodeulgo daniji
Naneun nuga arabwajugil baramyeonseo
Salji anha geuge neowa nae
Swiun chaiji
We hustle we grind
We puttin’ in work
Jameun jugeoseona jayaji

Stay away from around me
Nan ne gareuchim ttawin an ttareuni
Gadeuk ttara
Grab my feet
That’s where you supposed to be Yeah
Kkondae nimdeura paljjang kkigo jal bwara
Everybody

Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Act like a boss
Talk like a boss
Like a boss
I never know
But we here mo’f*cker
Boss