[Intro]
Tino

[Chorus: YFN Lucci]
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah

[Verse 1: Dreezy]
It's my first time in your city
Know you gotta show me round like a tourist
Pull up on you with that NyQuil
Know you tired from your tourin' shit
Show me somethin' I ain't used to
All these niggas be too full
Feelin' on all your new coupes
So I hope you paid your insurance, yeah
That's loose chains
Diamonds dancin' like blue flame
Did a show with my old nigga
Got me ridin' with you in that new thing, yeah
Tity boy but I'm a bad bitch
So he went and bought the kid 2 Chainz, yeah
Bitches try to get this flock on they two planes
Like you really comin' (Hey show me somethin')
You been [?] now show me somethin'
Bring me out to your block
Show me how they rockin' with you so I know you runnin'
Hit up Lenox mall, I spend it all
Cop the new Chanel, could've paid the bills
All this money, we just steady stuntin'
Ride foreigns all through summer hills

[Chorus: YFN Lucci]
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah

[Verse 2: YFN Lucci]
Her all, you know we young and wild
Yeah, grew up runnin' wild, they tried gun me down
Yeah, grew up movin' pounds, now me blowin' pounds
Yeah, got your bitch in town, 30 pointers on me now
I need a bitch gon' hold me down when I'm feelin' down
Yeah, put on some fly shit, you know we be flyin' private
Put some Cartier over her eyelids
Let her drop the top, let her know we ain't gotta hide shit
Yeah, 10 AM in the A, I put a AB on my bae
D&G every day, rose gold Cartier
She a boss, I relate, huh, yeah
I'm a boss in and outta state, I told you I run the A

[Chorus: YFN Lucci]
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah
10 AM in Atlanta, fly a bitch to Atlanta
Fly your bitch to Atlanta, let her ride in my Phantom
Know we runnin' Atlanta, yeah
Let me show you round Atlanta, yeah, yeah