[Crystal Watson]
Enter Everready

[Big Sean]
So we rolling, just left Billings, Montana, did a dope ass show
We in a 15 passenger van, heading to Spokane, Washington
We driving along the interstate, we go over this bridge, hit a patch of ice, all of a sudden the van starts fishtailing
We're going back and forth, I'm like "Woah!" Krizz says...

[Krizz Kaliko]
"You got it Sean you got it! I think you got it man"
But we went sliding further and further towards and back then BOOM we hit
We flipped like 5 times, all the windows start breaking out in the van
I'm like "Oh god, oh god!" while we flipping, and finally we stop I'm looking around the van to see if everybody is alright
First person I looked at was Big Nick 'cause I see him jumping out first
He runs to the doors 'cause they crushed in and he starts grabbing trying to rip them open like (Grunting noises)

[Big Nick]
I yank the doors open and I'm yelling out "Tech! Tech! Are you alright man? Kutt! Kutt! Are you alright?"
Kutt raises up and I see he's drenched from all the bottles of alcohol we had in the van from last night; and I say "Kutt man, are you cool?" and he says

[Kutt Calhoun]
"Yeah I'm cool man, I'm cool"
So I'm wiping my face, I'm thinking I'm bleeding
I look at my hands, it ain't nothing but the liquor
So I look around, everybody up and moving
Tech's still on the floor and I'm like, "Tech! Tech, you alright?"
He ain't saying nothing, I'm like "Aw man... Tech, you alright?!"
He said something like "Kutt,"

[Tech N9ne]
"I'm fine man.. I'm fine man, I'm fine, I'm fine." I asked him, I said uh, "anything wrong with my face? Anything on my face?"
And Kutt was like "Nah" So I'm like, I'm listening, and I touch my teeth and I see blood in my mouth, but I'm smiling 'cause I'm hearing Krizz Kaliko saying "Thank you Jesus, thank you Jesus,"
And it felt good to be in God's graces
The ambulance, the people that came, they said that we were all blessed
Ya know what I'm saying, to still be alive after flipping 5 times man
So ever since then, we been celebrating life baby Kickin' it hard Every day's a party baby