[Verse 1]
I see your face when I'm scrolling through my instagram
Hoping that you love me and hoping I be your fucking man
Seeing how you act I'm sure you got a different plan
I know that I should stop trying but I don't think I can I see your smile and it does something to me
It's like I'm starstruck and I'm your bud and your rudy
Fuck it you my ruby, a gemnist never seen
Attention is what I'm wishing but it's like I never seem to
Find a way for you to mention my name
Not even talking about the sheets, or am i'm saying in vein
I'm just hoping one day you'll see all of my pain
And know the times I'm up laying you running my brain
There's more fish in the sea, well that's the saying
But you're always stuck in my head, there's not a fucking day
When you not on my mind and I promise I ain't lying
I couldn't make up a story like this if i tried
I rolled threw when we smoked outside
I mean I didn't want you too, but you said you'd be fine
Then the L hit your lips, took a puff then another
Soon your eyes were as low as the temp when it snows
You slept over I wanted to Casanova
Feelings ain't seem the same so I slept on the sofa
For me to get you Imma need a green clover
When I'm with you in my dreams I get mad when their over
And I wish that we would talk a little more
You say that you're afraid I'm wondering what for
I only want the best and I'm sure you know I do
You gave me a chance but even Biggie was given two
It's true I'm stuck on you, I'm stuck like glue, no one time screw
But you got a different view
It's like I think we never say it to you
That's why I'm hoping that you know that this is your elegant tune. NEHRU

Who that who that who that girl? I say who that? that girl(x5)