[Intro]
Shinoda, that's right, Ryu
Celph Titled, Demigodz
Dipset, Juelz Santana
And of course Fort Minor
Let's go

[Hook: Mike Shinoda, Ryu, Juelz Santana, Celph Titled]
It's like oh, oh, oh
F.M. D.E.M.I.G.O.D.Z's, it's like
It's like oh, oh, oh
D.I.P.S.E.T. S.O.B. G's, it's like

[Verse 1: Ryu]
I came from pumping 60K out the trunk, switchblades
Ziggy stuff, nicknames, itchy braids, bitchmade
Faggots, but shit's changed, my cabbage is picked man
Rolling twenties up like Snoop Doggy Dogg's Crip game

But I'm out for the crown
Housing 'em, bucking 'em down
Dousing and dunking these fucking punks
In a bucket and bounce

When I get up in the game, beware
Put a pimp on a hope and then say your prayers
Got a potion so damn potent, player
Put you on the floor like a broken chair

You know it's a movement, like crack for the gods and goons
We back, you talk about gats but don't actually use 'em
But I'm happy to do it, 'cause this is Demigodz
Celph Titled, Ryu with Tak, Apathy stupid

[Verse 2: Juelz Santana]
From bottom to top (I rose), chopping them rocks ([?])
Cocking the Glock and blow, no more of that
Now, I just hop in the drop and go
To the most popular spots with hoes, and they know they go

I went from pumping that white stuff
To being up in them white clubs
Like hey, I got dubs still pumping that white stuff
Plus I fuck with the white boys, skaters and bike boys
We may act different, but the struggles alike, boy

Shinoda, know that if there's a problem I'm coming over, yo
Quick fast in a hurry, and I be near to overdose
And I mean that, just call if you need that
The best of both different worlds, not often they see that

[Hook: Mike, Ryu, Juelz, Celph]
It's like oh, oh, oh
F.M. D.E.M.I.G.O.D.Z's, it's like
It's like oh, oh, oh
D.I.P.S.E.T. S.O.B. G's, it's like

[Verse 3: Celph Titled]
We not just rappers here that you have to fear
We smacking queers, murder, extortion, hustling
Nothing stopping this movement
I swear we getting to the top, this year

Got your ears, all eyes on me
Old school 80's guy, that's me, hip hop head
Female rappers give me dome
And that's just that hip hop head

I flip off the feds, it's been said
I'm out my mind to the fullest
Alone in the crib, bugging
Fucking with Russian roulette with six bullets

Won't never free my guns
But fo' sho' we letting them triggers go
Sparking the weapon
You's a thousand miles from me, you far from perfection

And that's just room for thought
I'm moving the bar, rap entrepreneur, I'm rap lord
Come to the hood, I'll bring you in through that trap door

It's Demigodz and it's Dipset
It's Doe Rakers and it's Bird Gang
That's Ryu, Celph, and Santana
The best rap singers you ever heard sang

[Hook: Mike Shinoda, Ryu, Juelz Santana, Celph Titled]
It's like oh, oh, oh
F.M. D.E.M.I.G.O.D.Z's, it's like
It's like oh, oh, oh
D.I.P.S.E.T. S.O.B. G's, it's like

[Outro: Celph Titled]
Demigodz, Celph Titled the Rubik's Cuban
Ryu the Beast, Shinoda the Cobra Holder
You a fool for this beat, Santana the Great
This has been a Demigodz Dipset feature presentation
We'll slap the beeswax right out your grill

And when my situation ain't improving
I'm trying to murder everything moving
And when my situation ain't improving
I'm trying to murder everything moving