Verse

I got Loyalty and royalty inside my DNA
No destroyin me, got noisy dreams that’s from my DNA!
I got devils and rebels that hate inside and disobey
I just pray, Everyday, they Escape the disarray
Father forgive for my sins they want that verse they gotta pay!
I just make my daily bread, make sure it’s stuffed with that fillet!
Call my bae, she say its all you can eat, that’s my buffett
They should call me Father Time cuz I never got delayed
Im the realest, know you feel this cuz this from my DNA!
Dream Or Die we in the building, knockin down what’s on display
Realist out, without a doubt we about what you potray
Talkin down all on you clowns, don’t make a sound, see I don’t play
I just win again, then win again, like Jordan 23rd
Yeah that’s him again,  don’t mention when I rapped this on the curb
I was walking miles in the cold I never had a car
Baby played her part, and and took off her bra
When I told her
I was Cumin, Cumin, Cumin Cumin, talkin bout them spices
Baby whippin up a pie, I ain’t givin out no slices
Everybody wonder why I done broaden my horizons
Cuz I looked her in her eyes and could tell that she’s my Isis
I came from that underworld, that’s my girl, yeah that’s my world
She the reason I flow sick, every verse I make you hurl
Give her pearls, give her gold, everything that she deserves
Found my heart, found my soul, when I die it’s all for her
Beloved, chiyea, chiyea, chiyea, chiyea, soldiers DNA
Born in Ninety Trey, seventh  grade they gave an empty tray
Extended day, still at school, cuz I ain’t have no where to stay
But It’s okay, 12 years later I came up, and now we straight
Now every plate, come with steak
Gimmie that cream gimmie that cake
Gimmie that house up on that lake
With that gate that’s for the fakes
Stay away, stay away
Pray I see em fade away
While I go and meditate
Thats all That’s all for toda
(Beloved Chiyeaaa....)