[Skit: Rocky Balboa & Adonis Creed]
Why do you wanna fight?
What you talking about, I just told you why
No you didn't Donnie
Why do you wanna fight?
I get why they wanna fight you, I know what they're fighting for, what about you?
Listen to me, you got everything to lose, he's got nothing to lose
When a fighter ain't got nothing to lose, he's dangerous!

[Chorus: Eearz]
Fight, fight, fight, fight, fight, fight, fight, fight, fight
Fight, fight, fight, fight, fight, fight, fight, fight, fight
Give a fuck what my nigga did
Run 'em down, work 'em, that rumble
Give a fuck what my nigga did
Run 'em down, work 'em, that rumble
All of you stuck in the projects, nigga I'm goin' off site
All of you stuck in the projects, nigga I'm goin' off site
(Fight, fight, fight, fight, fight, fight, fight, fight, fight
Fight, fight, Fight, fight, fight, fight, fight, fight, fight
Fight, fight, fight, fight, fight, fight, fight, fight, fight
Fight, fight, fight)

[Verse 1: Eearz & Juicy J]
Who got my back? Ain't nobody holdin' me back
I'm out here fighting for my life, no tellin' what come with it right?
My momma needed bills and lights
I'm prayin' for some better days
I can't go havin' sleepless nights (Shit)
But nigga that's life, when you tryna do right like Spike
But the licks be lookin' enticing
This shits such a roll of the dice, police wanna read me rights
I got no time to relax, when the wall up against my back
My vice reach on a ten, nigga I'll knock out your lights
Mike Will saved my life, this life will hit you like Mike, Tyson
We steady then go on strike (Boom)
Fuck these niggas mean? Nigga I grew up mean
Nigga I came up in scenes that these niggas never seen
Everyday I got to-

[Chorus: Eearz & Gucci Mane]
Fight, fight, (Ayy), fight (Yeah), fight (Mike Will)
Fight (Bitch), fight, fight, fight
Fight (Evil Genius), fight, fight, fight
Fight, fight, fight, fight

[Verse 2: Gucci Mane]
My bitch went through my phone last night when I was sleep
Woke up startin' a fight, 'bout a quarter passed three
"Who is Diane, Gucci who is Monique"
I said "I'm the dope man, everybody know me" (It's Gucci)
Chillin' in the club, in the V.I.P
Nigga hand frigid and all the hoes dig it
There's always one young nigga, wanna be brave
Like we gon' put his ass on the fuckin' front page
Put your hands on your knees, that's a R.I.P
Well it's hum like a hummingbird, sting like a bee
Put the drum in the bitch, make her mute, make it kick
She so sprung on the dick, she just swung on the bitch

[Chorus: Eearz]
Fight, fight, fight (Huh), fight
Fight, fight, fight, fight
Fight, fight, fight, fight
Fight, fight, fight, fight

[Interlude: Project Pat]
We gon' rumble in this ho
All you weak ass niggas get yo' ass off the floor
We gon' rumble in this ho
We gon' rumble in this ho
All you weak ass niggas get yo' ass off the floor
We gon'-

[Verse 3: YG]
Kick a nigga in the head with the hard bottoms
Your homies is dying, I don't give no fuck, that's your problem
Tryna catch yo' ass when your homies around ya
I ain't tryna talk, I'm gon' beat the ho up out ya
Hit your ass with that left right, left right, hit him in the chest right
Knock his as out out, hope he lived his best life
I be in his ear sayin' gang like, gang like
I be on a jet niggas still better think twice
I be on with the homies on the block, they ain't livin' right
I be on with the homies on the block, that're killer type
I be with the homies, with the homies, with the homies
With the homies, with the homies, with the homies, yeah gorilla type
YG stole that, no nigga hold that, fuck your party, spark me up, throw that
Niggas know the program, the program, the program
Spit in a niggas face, pipe a nigga ho down
Take a nigga chain, take a nigga chain
Take a nigga chain then sell it back to him
Now everybody knew, everybody knew you a ho
And so YG do em'

[Chorus: Eearz]
Fight, fight, fight, fight
Fight, fight, fight, fight (And so YG do em')
Fight, fight, fight, fight
Fight, fight, fight, fight

[Verse 4: Trouble]
Fighting like all of my life, know I'm real right and the streets call me "Zilla"
Leanin' up there, that what you like, heard you been talkin' up under your pillows
I get it poppin' on sight, not just with Mike, get you beat like I'm Mike Will
That drum hangin' under the TEC, kill, the drummer like Eearz and Dipset
Give a fuck about a nigga height, I still put you lil' babies on ice
You can be same way that I be, get hit with they car he sounding like
Pump it up for a nigga then, tell 'em come let the gorillas in
They don't wanna let the gorillas in
It's okay I been knockin' doors off the hinge
Get the gloves if you 'bout it
In your zone homocide get you watered, know the Scoob get you watered
You can fuck with me? Seriously doubt it, your trick got rerouted
Now tell me what the fuck is your problem?
You gotta be ready fool, don't tell me you ain't hear the announcement

[Chorus: Eearz & Trouble]
Fight, fight, fight, fight
Fight, fight, fight, fight (Don't tell me you ain't hear the announcement)
Fight, fight, fight (Hey), fight (Hey)
Fight (Hey), fight (Hey), fight (Hey), fight (Hey)

[Verse 5: Quavo]
Yeah, knuckle up, knuckle up
Nigga got hit with the upper cut
He got a cut on his eye, damn now he can't see it done closed up (Damn)
Fuck it (Fuck it), fight (Fight)
Get your stripes (Stripes, bow! Bow! Bow!)
Hit him knockin' out your lights (Hit him)
Look at my arm, my knuckle, my knuckle, now he lay down in front of me (Hold me up)
My momma would told pipe 'em up, pipe 'em up, while she was sittin' in the front seat (Momma)
It be like, I coulda used combos, but I hit him with a one piece (Combos)
It be like, I coulda just told you, I rather you one me (One up)
It be like, he hit the canvas, whole crowd a be like (Oh)
You went out the saddest, whole crowd a be like (Woo)
I can imagine, view from the ground, it be like (Damn)
Wanna rematch it? Hit my phone and be like-

[Chorus: Eearz & Juicy J]
Fight (Hey), fight (Hey), fight (Hey), fight (Hit 'em)
Fight (Hit 'em), fight (Hit 'em), fight (Hit 'em), fight (Hit 'em)
Fight (Left), fight (Right), fight (Left), fight (Right)
Fight (Hit 'em), fight (Hit 'em), fight, fight
(Shut da fuc up)

[Verse 6: Juicy J]
Mama didn't have it (Yeah hoe), so they cut off the lights (Yeah hoe)
Now I'm drippin' in ice (Yeah hoe), and we don't need no lights (Yeah hoe)
You want that check first you gotta earn stripes
I've been through hell, feel like i did it twice
I got it bussin' like I got the pipe
Came up from nothin', I'm uppin' the price
I'm from the jungle (Jumanji), where gorillas and apes be (Yeah hoe)
You don't wanna rumble  (Yeah hoe), these niggas can't take me (Yeah hoe)
Niggas said that they love me (Yeah hoe), but they show me they hate me (Yeah hoe)
It's a cold, cold world, no need for AC (Yeah hoe)
Nigga I have my own bag, rich nigga I own that
Nigga I'm from the projects, got a house where the Combs at
I ain't tryna kick it, no air in the ball, that mothafucker on flat
I cannot lose like Floyd when this on the line, it's no match
Tried to take it and you gotta-

[Outro]
Fight, fight, fight