Aw, man! Do you see my man Uncle Luke?
Yeah, yeah yeah on CNN? Yeah, from Japan?
He’s all that
A T and T
All this and that
That’s right
Did you see what honey did?
Yeah yeah
She did the L.L.O.L.M
You know what that mean?
Lip lock on love muscle

[Luke] You found the dick!
Now just- what are you gonna do with the dick now?
(Laughs)
You just can’t hold it there with your cold hands
Your hands are cold, sweetheart. You gotta warm them up
Suck it
[Ho] Back up some
[Luke] She fixing to suck it
[Ho 2] Oh, shit
[Luke] You a good girl
Jump on it
Hold on- let me put the microphone closer now
[Ho] Tastes so good
[Luke]  Oh, yes this feels good too
You gonna suck it next?
[Laughter]
[Ho 2] What?
[Unknown] Hey, man, you still gonna do the record after this?
[Luke] Hold on, we- time out. We on pause here. Mute the damn thing