[Intro: T-Pain]
Woah, ah
Yeah, ah
Woah, ah
Yeah, ah

[Pre-Chorus: T-Pain]
Oh, I think I found the one
Yeah, my baby girl gon' give me a son
I found the girl that can do both
She balling with the crew
And she just like me 'cause all she wanna do

[Chorus: T-Pain]
Fuck bitches, get money
Fuck bitches, get money
All she wanna do is fuck bitches, get money
Fuck bitches, get money
All she wanna do is

[Verse 1: T-Pain]
I'm stupid, she funny
She keep the tooly, I get the money
She watch the trap for me
And any time of the day, she gon' have fun
Then get right back on her cake 'cause she ruthless, some Eazy E shit
When she hit the strip clubs, she straight ball on your bitch ass
She can talk the drawers off your bitch ass
And bring 'em back to me and we gon' dog-fuck your bitch fast

[Pre-Chorus: T-Pain]
I'm like oh, I think I found the one
Yeah, my baby girl gon' give me a son
I found the girl that can do both
She balling with the crew
And she just like me 'cause all she wanna do

[Chorus: T-Pain]
Fuck bitches, get money
Fuck bitches, get money
All she wanna do is fuck bitches, get money
Fuck bitches, get money
All she wanna do is

[Verse 2: T-Pain]
Fuck snitches, hit 'em in the stomach
You know I'm stupid, she on that dumb shit
She make me cum quick, we fuck like three times a day
Suck me unconscious, I give her 300K
And then she move it, across the border
I'm her Weezy F baby, she my Carter
She on that cool shit, she know what to do
Man, you say it's fuck me, no it's motherfuck you

[Pre-Chorus: T-Pain]
And she make me say oh, I think I found the one
Yeah, my baby girl gon' give me a son
I found the girl that can do both
She balling with the crew
And she just like me 'cause all she wanna do

[Chorus: T-Pain]
Fuck bitches, get money
Fuck bitches, get money
All she wanna do is fuck bitches, get money
Fuck bitches, get money
All she wanna do is

[Verse 3: Young M.A]
See I got this lil' jawn, we ain't together but we fuck around
Told her, "Listen, shawty, you ain't messin' with no suckers now"
And she 'bout that life, she see a opp and she run it down
And I gotta make her cum every time she come around
Pour a cup of brown and we freakin', we freakin'
Hustle on the week days, freakin' on the weekends
And she get her own checks, she don't give me no stress
She ridin' like a road test and she stick with me like a drum and

[Pre-Chorus: T-Pain]
Oh, I think I found the one
Yeah, my baby girl gon' give me a son
I found the girl that can do both
She balling with the crew
And she just like me 'cause all she wanna do

[Chorus: T-Pain]
Fuck bitches, get money
Fuck bitches, get money
All she wanna do is fuck bitches, get money
Fuck bitches, get money
All she wanna do is