[Verse 1: Big Henry]
I'm from the G-dot-A-dot-D
Pocket full of money, getting live in the streets
With a bottle of that Henny V.S.O.P
Country mahfucka, mouth full of gold teeth
So bust down the blunt, wrap the THC
That's 24 chrome on that Classic Caprice
What you know about me? Not a goddamn thang
Fatboy Mac, I let my nuts hang
I do it how I do 'cause it's just my thang
You can hate if you want but I ain't gon' change
How you gon' explain when I leave pop your brains
Leave it on a curb till their washed off by rain
When I'm in a booth man I'm high octane
So tell Dr. Dre did it ain't no game
'Cause this documentary
Y'all gon remember me
Hail to my enemies and fuck what they tellin' me
Till god take my energy
It's always Henry

[Yelawolf]
Getting into some shit
[?] the clique I have to deal with
But when you all in your friend will come 'gain
Next thing you know you got gold in your grill

[Bridge: Yelawolf]
Shawty Fatt! Could you bring the hook to the line?
Put a fish in a trap from the cast of your mind
Bake for the state AL to divine, specifically don't say it, abbreviate

[Hook: Shawty Fatt]
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?

[Verse 2: Yelawolf]
Nada
Non other than a brainiac on a track
Perspirating thugs, stained hat
A new era of painted 'Lacs
Rolling through the sentiment attrac-
Tion, a ton of some of the biggest gunners will aim and snap
My trained head
Too many kaboose riders, man
And I want my pennies back
My dollars and my fanny sack
You holla for real and complain 'cause you got it
You want your pennies back?
There is no bitch in me
Unless ya mean South America on the coast nude
With a sandy crack
How could ever there be a dude with a handy pack
That swings the pinpoint shot when I'm in attack
Easy if you had practice how to lame an ass-hole
'Cause all my life I would [?] back
Train 'em how to act
Their trainers on the track (choo-choo)
But what is too true, ain't it bad?
Annie Amy's brother and the son of a tainted dad
With his pants hanging low
Well, can he sack?
In America as an old chief, ass take rooted
4000 years ago, chief
Wayne, it's sad how you dissed me
You owe me! Respect me! I'm godly!
Like a black [?] with a tombstone
You will get faded
And I ain't talking 'bout a [?]

[Hook: Shawty Fatt]
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?

[Verse 3: Shawty Fatt]
Say momma: "There goes that man
Sitting in a Caprice on twenty douce fans"
Gun in my hand looking like a hundred grand
A hundred and one fans on a band wa-gon
I kill it like I started
Them first bars were retarded
Don't get me started
Hardest, stay in a booth
When I speak be the truth
Alabama coming through
Yelawolf, let me loose
So I can tell it like the T.I
Ills 'cause he got skills
Pushing up on a mill
Mouth like "ill"
South like trill
One more time what it is?

[Bridge: Yelawolf]
Shawty Fatt! Could you bring the hook to the line?
Put a fish in a trap from the cast of your mind
Bake for the state AL to divine, specifically don't say it, abbreviate

[Hook: Shawty Fatt]
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?
I'm from the G-dot-A-dot-D
Pocket full of money, mouth full of gold teeth
24 inches on that Classic Caprice
Sea seat low, what you know about me?