[Verse]
Ayo, it’s Weezy motherfuckin', easy with the hatin'
Bitch, I’m in the buildin', you just decoratin'
I’m just detonatin', then I get blatant
More dangerous than Internet datin'
Scoob got the cameras on, so I got to show off
I'll put your sister on, I'll knock your bro off
Weezy spit snowballs, catch it in your face bitch
Good game, Wayne, man, I deserve a Naismith
Cocaine gang flow, dope in the vein flow
I'll only be smoking the purple out the rainbow
Stronger than Drano, your boyfriend a lame-o
And if you stay with him, then y’all in the same boat
Deepwater Carter, fishing for a dollar
You can join the salad, I’m splitting your tomata
Ball 'cause I gotta, you’ll love me in the morning
I told her I'm a King, them other niggas Prince Charming
She love to rock my mic, she say there's nothing like performing
Man, I'm in love with her grill, George Foreman
Forewarning, Young Money’s armed
And we can shoot it out, I got the money drawn
Yeah, take that to the bank wit' ya
I rock my hat to the side like I paint pictures
Smoke weed, talk shit like Lane Kiffin
Whole country in recession, but Wayne different
And I’m a Maybach rider
Haven’t drove it one time, I got a cool black driver
Can't walk around with guns, I got a dude that got 'em
Don’t worry if I'm shootin' as long as you don't get shot
And I'm a beast, I'm a pit bull
I get my ass kissed, I get my dick pulled
I'm a beast, I'm a big bull
I got my money right, I got my clip full
Yeah, it’s like seven in the morning, nigga
I’m up for whoever the opponent, nigga
Stop the track, let me relish in the moment, nigga
Now bring that motherfucker back, 'cause I’m goin' in, nigga
I go hard like Rafael Nadal
And if the bitches worth having then I bet we have 'em all
And man, I'm so high, it's like an everlasting fall
And I’m charging these hoes like women basketball
Uh, I bet that chopper get his mind right
Leave a hole in his chest like a lion bite
Superhero car, like I crime fight
I see big cheese, you niggas' blind mice
Uh, T-Streets still roll with me
Still sticking to the script, like Nicole Kidman
Need the man hit? We are those hitmen
He stopped running, the bullet holes didn’t
Uh, basically, I’m still a monster
'Til the fat lady sing, I come to kill a opera
Y'all too plain, I'm a helicopter
My words keep going, like a teleprompter
I’m a asshole, wipe me down, bitch
I get big checks, Niketown, bitch
Yeah, mean mug, Bobby Brown shit
And the flag red, like clown lips
Uh, T, I can't stop goin'
Drop my best shit, like the Cowboys dropped Owens
I’m the best to ever do it, motherfucker, I know it
No Ceilings, goddammit, now the fuckin' sky’s showin', uh