We are the Halluci Nation
Our DNA is of earth and sky

Bismillah
True and living by the G Code
What the fuck is fleek though?
Don't ask them, what do he know?
What I forgot is better than whatever they remember
Never mind, I'm off it, it’s quiet for 'em
Time to put the temper tantrums to the quiet corner
"HUSH! That’s enough," said the ruler, no suckas allowed to break bread or asunder
The daylight, lightning, and the thunder
Sun, moon, and stars and the hunger
Abundance in bundles, lessons and troubles
Towers and tunnels, views and valleys, waves
And peaks
What streets you from, son? Planet Earth
And ain't scared of no Mars Attack, what type of bars is that?
Stay off my jack
Out their corny riot garments, top 5 Dylan-in’ on ‘em
Superfly Snuka top rope, eagle-divin' on 'em
You why you lyin', homie? You won't play with my emotions, Smokey
Big Chief, heart rate, big beat, B-E-Y Yasiin
Straight jacket come clean
B.I.G. said it was a dream, now it's a living thing
We true and living kings
Ameen and Ameen

Ameen and Ameen
Yasiin and Yassin and the R.E.D
Ameen and Ameen
Original nation, Ameen
Ameen and Ameen
Straight jacket come clean
Yasiin and Yassin in the R.E.D
Original nation
True and living, you know we're true and living

R.E.D, A Tribe Called Red
R.E.D, A Tribe Called Red
R.E.D, A Tribe Called Red
R.E.D, A Tribe Called Red

Illuminarcy, emergency on planet Earth
The currency is murder, you a man of worth?
They say the day is coming, drumming that you can’t reverse
Watch the banner burn, before the cannons burst!
Don’t chase an illusion, the Nation Halluci
Hallelujah!
Taste of the future, the people, the shower, the pistol, the coward that’s racing to shoot ya'
Lonely martyrs
Magic carpets, dirty blankets, coca-cola, soul controller, holy waters
Middle East mode, sandglorious
Cheat code in Babylonian, the orient
My superhero got the people power
Yasiin and Yassin, you should heed the hour

We true and living kings
Ameen and Ameen
Ameen and Ameen
Yasiin and Yassin and the R.E.D
Ameen and Ameen
Original nation, Ameen
Ameen and Ameen
Straight Jacket Come Clean
Yasiin and Yassin in the R.E.D

Original Nation
True and living