(Mr. Man verse)
S.O.S
Breaker breaker 1-9 maydey
Surviving off of pennies until my next payday
All I ever wanted was a real nice lady
A clean pair of socks
And some fish for my gravy
But all I get is rice
Which will have to suffice
Coz I always used to think I didn't need no advice
So I never ever really tried to heed no advice
But in the end we all pay the price
So let's get to the point (point point)
Of the whole situation
So many obstacles
So many confronations
But still I'm focused on reaching every station
Coz destiny is my destination
I came to make it happen
Instead of wasting time I don't got
The time is now
Coz I only got one shot
Navigating through the schemes
And the intricate plots
Coz you and I is all we got
Lets make it happen

S.O.S
Breaker breaker 1-9 maydey
Surviving off of pennies until my next payday
All I ever wanted was a real nice lady
A clean pair of socks
And some fish for my gravy

(Lee Majors verse)
Why
Why is the world round
Why do the suckas bite
Why do the freaks come out at night
Why they paint Jesus white
I sit and wonder why
We breakin hip hop laws
Doing videos in houses that we know ain't yours
Representing projects
Man them shits ain't yours (check your lease)
What I release I'll make you shit in your draws

Well then
Hear what I say (OK)
Your begin for an easy way
Well I don't know (well I dont know)
Oh yes I don't know

Yo light
Let me let these niggas know
Its like all I ever wanted was a girl with
Respect and a 3rd eye
DKNY ain't what makes you fly
Lights in my face
Government in my pocket
Its hard to be a prophet and still make a profit

S.O.S
Breaker breaker 1-9 maydey
Surviving off of pennies until my next payday
All I ever wanted was a real nice lady
A clean pair of socks
And some fish for my gravy

(Mos Def)
I swing with phat cats to smack tracks over phat raps
It's all of that we tread the BK back road (brooklyn)
'96 about to put it on
Hey baby palm
Put a quarter upon the needle head
To hold it still while I lace up the verbal threat
Now watch me sew shit up
Mos def in your spot about to blow shit up
See i've been rhyming since when I was growing up
That's why I say that shit that
Make the party open up
Like the sky
Plus my voice is fly
I roll with dave mase
And wonder why
I rock it from Medina green on to the strong i-i
Land on my feet coz im a cool cat
Make the kids around my way say
How you do that
Be careful what you say coz ain't no takebacks
And if you makin' moves
Don't fake jacks
Perhaps that's the sound when you smack the drum skin
Whenever yall want to jump in
Man I don't want the landlord kicking my door in
You tired of getting high but you
Never know when
And fuck around and get low again
But you can always be certain my friend
How your low tide is always gonna come in
It's like that
So check it on out yall

S.O.S
Breaker breaker 1-9 maydey
Surviving off of pennies until my next payday
All I ever wanted was a real nice lady

(Lee Majors)
(It's like right about now you're probably sitting on
Your couch thinking, damn what is son doing
I dont understand
You try to front but its like you can't son
Its music
You gotta appreciate music
Take a listen
Yeah, yall dont understand
Before you a mc
You a artist
You make music
So make that music
Listen to this, yeah, I feel it
I see your heads..)