[Verse 1: Yonni]
Many even stressing
Riding through the city, motherfuckers asking questions like
Can I make it make sense?
Been to school my whole life, my best teacher was experience
So what me can't tell y'all niggas nothing
I can show you how I move
You can watch the way I run it, bust it
And far from a newjack, so many bad bitches with me
It's like orange is the new black
Watch me shine on 'em
Got me feeling like the kids, so wait me grind on 'em
[?]
But you're a stupid when the nigga he was blind on it
Man trying to be your shit [?]
Fuckin'' Parasuco jeans and [?]
Sippin' on that Hennessy, no Chaser
Mateen gon' hot, like the eightfive make, 'cause I ain't bullshittin'

[Hook: Yonni]
Nigga ten toes in the dirt, I be puttin' in work, I ain't bullshittin'
Hittin' on me ain't gon' work, fuck around and get hurt, I ain't bullshittin'
Nigga ten toes in the dirt, I be puttin' in work, I ain't bullshittin'
Hittin' on me ain't gon' work, fuck around and get hurt, I ain't bullshittin'
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no, body, fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no, body, fuckin' with me

[Verse 2: The Game]
Creesha, nice to meet ya
I like your body, I like your features
I can't afford to fuck with you, but I'll leash ya
Heard you had trouble with them curve, I'll teach ya
Teach you how to ride it like the Raingler
Didn't your momma tell you not to fuck with strangers
The clit strangler, too late, you're in danger
The rain maker, you climax when I switch fingers
Ain't no body fuckin' wit' you, huh?
Wait 'til I slide in, put the whole nine in
Ain't no body fuckin' wit' you (ahh)
It's the weekend, we got a party next door, come!

[Hook: Yonni]
Nigga ten toes in the dirt, I be puttin' in work, I ain't bullshittin'
Hittin' on me ain't gon' work, fuck around and get hurt, I ain't bullshittin'
Nigga ten toes in the dirt, I be puttin' in work, I ain't bullshittin'
Hittin' on me ain't gon' work, fuck around and get hurt, I ain't bullshittin'
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no, body, fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me
Ain't no body fuckin' with me (fuckin' with me)
Ain't no body fuckin' with me (fuckin' with me)
Ain't no, body, fuckin' with me