[Lil' Wayne]
Hustle fa sq - hustle fa sq
Wobble fa sq
Hustle fa sq - hustle fa sq
Ykno them hoes love weezy im a dog with it
And if ya bitch scream sqad we can all hit it
I make her work it from behind and catch a wall with it
And then she rock rock tha boat
And walk with it - walk tha - walk with it
I run it in the hole like marshall faulk with it
I put it in ya mouf - hoe can you talk with it
Im off tha chain right
And if you red and big fine then you wayne tight
Yea and weezy ya fuck friends boy ain't right
And yall like a lil pussy put u give brain right
Right she-she ain't never had a sqad boy slash a hot boy
Plus tha numba bitch im stunta son
And i just wanna see you hustle ta tha floor
And i dont wanna see you back that azz up that shit old
Im like oh oh oh in ya mouf and when i bust a nut i halla ahhhh

(hook - [lil wayne])
Im from tha sqad hoe
Im from tha sqad bitch
She like the sqad though
She love the sqad shit
And if you lookin fa her
Ykno where she be
With s-q-a-d

[Kidd Kidd]
Na hold on - lemme git my chain cuz it hang so long
Ain't so grown - but the game so strong
Hoe lemme fuck cuz my thang so long
But as soon as she give me brain so long
Dont let the game zone then the skank go home
Anyways you stankin up my ozone
You see me on tha 'Zant every all day
Pass all the halfway oh and pleez back ya dame up off me
F'aol - get it man introducing ya bitch ta nut a fuck up ya wedding plans
Im a veteran yall laggin
Yall niggas rookies in this game me and my dawgs all madden
Yall niggas acting like yall action
We all pack mac-10s that a give ya whole damn back in
We leave the club i pull up ya hoe walk back and
Fall it thats what i call mackin understand it

(hook - [lil wayne])
Im from tha sqad hoe
Im from tha sqad bitch
She like the sqad though
She love the sqad shit
And if you lookin fa her
Ykno where she be
With s-q-a-d

[Lil' Wayne]
I got a suite with a hoe inside
A suite with some dro inside
A bottle with momo inside
Its time na go inside
Its sqad up - throw it high
And i like ta take a reefer on with silence
Myflow jus died
Shh and im so damn fly
No mam i - dont hold hands i
Just git that throat and ride
See i quickly fuck a bitch and forget her
Yea baby - a higher empire like no limit records
And im not a minute man but i can fuck you fa so many seconds
And with the seconds i split in a split seconds
You just git impressive
I like it when you thick with big breastes
I like it when you quik ta git breakfast
And i just wanna see you pop it my way
You not a independent women
Bitch you not beyonce
And this mami do me or she wanna do is chew me
And when i bust a nut i halla oh wee

(hook - [lil wayne])
Im from tha sqad hoe
Im from tha sqad bitch
She like the sqad though
She love the sqad shit
And if you lookin fa her
Ykno where she be
With s-q-a-d-