[Hook: BJ the Chicago Kid]
You fine as hell, you know you are
You shine just like a shining star
On a nighttime, on a daytime
In the city you go to, they say you fine
You know you are, you cold as ice
If you broke my heart, you only got twice
Cause just like you i'm a cold nigga
I only fuck with centerfolds nigga

[Bridge: BJ the Chicago Kid & Freddie Gibbs]
You know you are
You know you are (x3)

When you see me pull up in a rover
Then you know it's time for you to bend over

This for my bad bitch, bad bitch
Super bad, perfect ass, got you on baby get your cash
Bad bitch, my bad bitch
Super bad, perfect ass, got you on baby get your cash

[Verse 1: Freddie Gibbs]
Girl I ain't tripping if you give it on the first night
Cause really I was down to fucking you at first sight
I see your head, nails, shoes and your purse, right
So get upon this dick and ride it like a dirtbike
Frontseat, the backseat we zoom-zoom
Hit it while we [?] and vroom-vroom
Twisting up a doobie, inhale the kush fumes
Head game stupid, ya pussy a damn fool
So I ran upon  that ass another day
I got a condo out in Cali you can go and stay
I was leaving other bitches like a throw-away
I'm try'na keep you on my team, let you know the play
Baby you fine as hell (You know you are)
That's cold in them draws, when they closed her up
My homie told me that I shouldn't let it go too far
The last nigga that you was with, you probably broke his heart, cause you

[Hook]

[Bridge]

[Outro: x7]
(Cause that nigga ain't me)That nigga ain't me