[Thoughts from MauSe]

[Hook]
If tonight is my last night, please don't cry
Just remember the good times of my life

[Verse 1]
Listen to the maestro, maestro
MauSe is a pyro
Sellebrate life yo, Psycho for a night show
Mudd club, paradise
Give me a drink and a pair of dice
And a hot girl that'll rock my world
Before I go to the after life
I ain't there yet
Don't care if I gotta year left
Just care if there's more beer left
That I can take to the head like a hair net
I been everywhere on a leer jet
I just need a girl I can stare at
Put my hands at, where her rear at
You hear that? I don't fear death
I scare death, so let's dance!

[Hook]
If tonight is my last night, please don't cry
Just remember the good times of my life
"Remember my life, my life, remember my life."
I'm gonna Sellebrate, Sellebrate
Whoaaa ooo ohhhh
Sellebrate!
Sellebrate, Sellebrate
Whoaaa ooo ohhhh
Sellebrate!

[Verse 2]
The night just started for me
Someone's daughters on me
Gave me a magic marker and asked can you start drawing on me?
Low life's in the spot
With Decepticons, no Auto-bots
Time to pose for a photo-op
Say cheese, this just what I need
My scene, this just what I mean
I'm free its just what I see
Living life, no regrets
But If I could turn no to yes
And turn water to wine, turn broke to checks
Turn over my soul, eternal rest
Wait my turn, no rush for me
I'm right where I want to be
Where you at though?

[Hook]
If tonight is my last night, please don't cry
"Enjoy the night, tonight, Enjoy the night, tonight."
Just remember the good times of my life
"Remember my life, my life, remember my life."
I'm gonna Sellebrate, Sellebrate
Whoaaa ooo ohhhh
Sellebrate
Sellebrate, Sellebrate
Whoaaa ooo ohhhh
Sellebrate!

[Verse 3]
Who wants to be mine tonight?
I'm tryna ride tonight
You know I can't drive tonight
I had too much wine tonight
That don't mean ima die tonight
But if I do, don't cry tonight
Remember me, everyday
After I die, Sellebrate!

[Bridge]
Its ok, its alright
Tonight is the night
Don't worry about tomorrow
We may never see a tomorrow
Let's dance till we see the sunshine!

[Hook]