Light caught the image frame on the iris
Molecules risen like Romans aurora
Took your ego advantage was minimizing fluorophore signal
First five hours were exquisite rest 24 ended the beginning
The real book of sinning medieval manuscript The Codex
Taking to the years of grimy scenes the thirty greed
Devastation of the German population another example of why Jesus rules the nations
Start of the orientation ready pissed off half these so called experts
Calming my words don’t rhyme
Pictures’ gritty
No expected effort
What I do with my beef I get it skinned
Finest leather
Looked for the map that contain the key to her sunken treasure
The splendor crowbar to her knees opened the dark cellar
Acted like a blacksmith smelted the hearts bathed in velvet
Body cold forgot the way of Luminescence
Shutting my eyes way deep for the evanescence
Me in my future? An undergraduate
Living better than my forgotten companions
No mansion but still getting medallions
Riding stallions with the same crew
Same old ragged shoes
T-shirt found at a garage sale
Pants always bought used
Sagged cause no belt
Hair shagged cause fuck brushing well
And everybody who claimed they understood me (well)

Disgust in the image
Eyes rolling with no craft kit to edit
No lens to keep privilege
Come to symbolize something old as the Sun, Moon Crescent
Textbooks became redundant
Pencils became weapons
And the trees became my heaven
Pyromaniac everything blended in splendid
No father figure responsibilities ended bended
All those other fuckas were relented
Searched for a better hope that’s when chunk became attended
Presented the same ideas plus he liked the way my style was (and my rapping)
Floe was the Supa Hoe getting girls like Black Bart did gold
Typing over getting hunches like burns only difference he’s known
And I’m still over working like how to get these shows (please)
And mother fuckas still look at us like we need time to adjust
No different film so start canning it
An MC not a candidate
Fuck your elections am badder than half these other rappers that opposing him
Primates with pencils ashamed that you even have apposing thumbs
Glad to make enemies in the game as for my slums
Slum in the chamber bullet corked in ready to bounce once I bring danger
So bring in the contestant that dares mess with this lone ranger
And ill slash, gut ‘em with just sheets of paper