[Intro]
Uh uh

[Verse 1]
Close my eyes before I cross the street
If a car about to hit me, then he ought to beep
Watching Dawson's Creek 'til I fall asleep
It's harder than it seems, I'm under water in my dreams
I'm in awe, this jigsaw, puzzles not complete
I'm just an idea, nothing concrete
Came to raise limits, get higher than plane engines
They tryna change with us, but come to the same difference
Shut your pie-hole, I'm dope and I know
My voice sound like it was a sample off a vinyl
I don't mind those hating on my style
I tend to take the high road, get stoned and fly low
I'm no God, I don't think that I'm a human, though cause I'm so odd
People selling drugs cause they can't find no job
Wonder if Christ made a million off selling the cross
Let bygones be bygones, my mind strong as pythons
The day that I die on will turn me to an icon
Search the world for Zion or a shoulder I can cry on
The best of all time, I'm Dylan, Dylan, Dylan, Dylan, (Dylan)

[Bridge]
Somebody do something (Somebody do something)
Somebody do something (Somebody do something)
Somebody do something (Somebody do something)
Somebody do something
Yeah, yeah, yeah
Somebody move something
Yeah, yeah
Somebody move something
Yeah, yeah
Somebody move something
Yeah, yeah, yeah
Somebody move something

Yeah

It ain't no party like aristocratic parties
Yeah, yo, yo, yo, oh
Said, ain't no party like aristocratic parties
Yeah, yo

[Verse 2]
Sipping Jameson like I was majored in whiskey flavouring
When I'm drunk, I'll cut your head off and leave it dangling
FlyLo's still tryna put me on to Ableton
Asian women love me, I look like David Duchovny
In kindergarten, used to put some condoms in my cubby
In case one of these hoes was tryna fuck me
I ain't nobody, and neither are you
Been contemplating if I even still believe in the truth
I'm so stubborn, I'd rather write my own history book
Where the world don't give a fuck 'bout how you physically look
All your songs are sixteen's and a hook
We're here to reinvent music, it's time for the revolution
I'm dying for the movement, trying not to lose it
Jewish Buddhist consuming the views of Christianity
Wonder if Hindus like to eat fish soup
If it's true, they should hit Alaska in a igloo
I hear the fish biting nice right now
I can't figure out life and feel right right now
Boo, if I think it, I should say it, there's a reason that I write it down
Spit the shit that leave a diaper brown, poo

[Outro]
Somebody do something (Somebody do something)
Yeah, yeah, yeah
Somebody do something (Somebody do something)
Somebody do something (Somebody do something)
Yeah, yeah, yeah
Somebody do something
And...
Somebody move something
Yeah, yeah, yeah
Somebody move something
You right there...
Somebody move something (Somebody move something)
Somebody move something
Yeah, yeah, yo, yo, yeah