[Intro]
Jezu, kolejny ranek, kolejna rozmowa o pracę
- Dzień dobry, Panu
- Dzień dobry, witam. Pana nazwisko?
- Nazywam się Rafał Szulc, mam dwadzieścia trzy lata, od pół roku bezskutecznie poszukuję pracy
- Hm, dobrze. A jakie są Pana kwalifikacje? Co Pan lubi i chciałby w życiu robić?
- Wie Pan, znaczy, to są dwie różne kwestie. Wpierw Pan chce usłyszeć co chcę robić, czy co lubię robić w życiu?
- Jedno i drugie. Niech Pan przedstawi swoje CV

Dzień dobry, jestem Rafał. Wiesz, to szło tak!

[Zwrotka 1]
Ty pytasz o nas, slogany ganić chciałbyś
Wchodzimy na majki, nosimy najki
Szukam poetek, ty idź po literatki
Lej po pół szklanki, ostatni nalej raz
Jak mówił Kaczmarski - "ja pójdę, bo już czas"
Pytasz o detoks? Jak Dre, średnio go znam
Mówią mi R do A, już to wiesz dobrze
Ja ponoć mam groupies, ty ponoć masz siostrę
To się zazębia, chodzi nam o jedno
Myślisz o czym innym, tak, czyli nie pierdol
Żyjemy lekko, bo ciężko jest trzeźwiej
Bo życie, jak techno, łupie w łeb codziennie
Szukam żony, coś mi mówi "to już było"
Użyję tu narządu, w końcu to chuj, nie miłość
To moje CV, krótko chcę wytłumaczyć
Mam dwadzieścia trzy lata, jestem Rafał, szukam pracy

[Beatbox: MAC]
Szukam pracy, lubię zamykać mordy
Taki on dobry, jak ten rap z Polski

[Zwrotka 2]
Nie jestem chamem, weź nalej mi rum z colą
Moje związki są stałe, bo stale się pierdolą
Zarobki, tysiąc, dzień grania, nie łam zasad
Za tysiąc miesięcznie mogę cię poobrażać
Nazwisko - Szulc, dalej, imię - Rafał
Jakieś znaki szczególne? Nie lubię wcale świata
I gram o wszystko, taki nawyk, tak wyszło
Że świat to hip hop, choć ten świat był tylko snem
Obudziliśmy się, jak zwykle, rano
Jak zwykle z kacem, jak zwykle jej nie znając
Tak to idzie, wie pan, lubię sarkazm
Złapię AIDS, aby wydymać farta
Chcę trzy tysiące na rękę, plus premię
Następnie mogę zostać szefem, żyć pięknie
Tak, i na to kładę nacisk
Mam dwadzieścia trzy lata, jestem Rafał, szukam pracy

[Beatbox: MAC]
Szukam pracy, lubię zamykać mordy
Taki on dobry, jak ten rap z Polski

[Zwrotka 3]
Nie po to gram ten rap, piszę pięć godzin dziennie
By rząd mnie pchał z jakimś Mezem, czy Mieszkiem
Chcę dużą pensję, jeszcze większą chatę
Bo plany mam największe, gdzieś je zmieszczę, łapiesz?
Mam proste CV, nie jestem w sumie inny
Doda też ma proste, ale ma duże cycki
Ośmiogodzinny tydzień pracy widzę
Te osiem mi pasuje, czyli osiem na tydzień?
Jedna nadgodzina, czy odwrotnie, jak to?
Tak powinno wyglądać nasze, Polskie państwo
Panie, jak Pan, zaraz sobie przypomnę
Od jutra mam pracę, jutro wziąłbym wolne
U wypił trochę póki mam wątrobę
Podtarł dupę CV, wydrukował nowe
Pamiętam, już nazwisko zapiszę
Jutro na siódmą, ta? To wszystko panie Fischer

[Beatbox: MAC]
Szukam pracy, lubię zamykać mordy
Taki on dobry, jak ten rap z Polski

[Tekst i adnotacje na Rap Genius Polska]