[Verse 1: Currensy]
Yeah - started out on the good side
And shooked to the hood side
'Cause that's where all the crooks reside
And wherever there is crooks, there is crime
Wherever there is crime, there is cash
And wherever there is cash, there is eye
Anywhere is eye, there is my guys
The society of people that are all fly
Bolt niggas and bitches only dance for the ritches
Any place that I walk in, I make a grant interest
Classic image, you've got to admit it:
There is no one that can get all the attention from all of the women
But these hoes slow down, so I make 'em steady dissin'
Sayin' tryin' to figure out - well keep my clock tickin'
Walking into the office meeting with my watch hittin'
Not because I am scared of getting robbed
But I don't wanna be offensive to the executives in here
I got more money then 'em, and they supposed to be the ones with good jobs
High spitter then that nigga, I'm a hood star
83 cut dough - that's my favorite hood call
Corner park it up time that was my favorite hood walk
Pass me the chopper, I show you what it’s good for

[Verse] (x2)
Cash rules everything around me - C.r.e.a.m
Get the money - Dollar dollar bill, yoo

[Verse 2: Remy Ma]
(Rem) x2
Cash rules everything around me
I heard motherfuckers telling niggas that they found me
But how is that possible when you ain't know where robby
? ya niggas hot - I tell ya stay the fuck from Remy
I be puffing purple, but sometimes I blow that brownie
Jay from Jamaica rolled in papers, smuggled in bouncy
I am 'bout to get money, bitch - dollar, dollar bill, yeah
I got a live crew that is dyin' to kill ya
Niggas feel my New York slang like they feel mob
Yeah, I mean, fuck outta here, son
That’s for ill ?
Go back to Hollywood ? that's where you got a chill guard
Never letting my nils ? I put that burner in your grill, Pa
Remy Ma, the queen of NY, she is so nice
A.k.a. the Bronx savior, Shesus Khryst
Whatever hater say - he or she don't like
May whatever they wish of me come back to them, Christ
Fuck your dead mother, bitch and your kid's a bastard
I am just here for Currensy, so tell me where the cash is
See - money controls all I seem: mass of confidence
Cash rules everything around me in other words

[Verse] (x4)
Cash rules everything around me - C.r.e.a.m
Get the money - Dollar dollar bill, yoo