[Verse 1: Curren$y]
Getting high with T-Y
My nigga up next
Whole lot of doja
That's my BFF
Started a No Limit soldier
Now I own a jet
Checks on top of checks
Yep I done that for myself
Now my rep is in the room
Before I take a step
Out of this thing
Red Corvette
I'm bakery fresh
I gained major respect
Stunting and snapping necks
I started a company
In my set I invest
Getting high with T-Y
My nigga up next
I told him keep his circle small
You gon' ball for sure
Cars and hoes come and go
Make sure you save your dough
Have a lawyer close
In case you gotta fight them folks
Make sure your jewelry yellow-gold
And stay valuable
Avoid these traps that they set
But still trap to death
Stack it to the sky
A million dollars high
Dollar signs in our eyes
Billion dollar minds
And when they said I'm lucky
Truth tell them
Ain't never lied

[Verse 2: TY]
And lately I been feeling like a man
Riding round in my own shit
Niggas stealing styles
Need to get they own shit
Made my mama proud
Came home with the grip
Get your head bust
But that's only if you slip
Told lil homie don't you trip
One day you gon hit your lick
Come through shining on these niggas
Pulling on all of these bitches
And we got diamonds that's bigger
Cars with hella work in them
Blue 100s all in my denim
If you don't know I'm that nigga
Smoked the Monte with a bitch
Who love to wear my shit
I had to leave her
Cause she start to make my nerves click
When I'm in that get money mode
It's hard to get me out
Niggas better follow the rules
Or get checked out
I lay my game down
Show them I ain't fucking round
Kept it G the whole time
Now look at me now
Get it through your head
This the corporation that never die
And when we say that we the truth
Just know we never lie