[Intro] [Answering machine]:
You have...one old message. Wednesday, 6:04AM. "Hi, this is Vicky please leave a message. Thank you bye."

[Sample]:
You were my first sweet love
My love, love love love
And set my child like dreams
Like kings and I'll be a queen
Don't tell my face it's never too late to love

[Hook]:
You were my first sweet love
My love, love love love

[Verse One]:
Before I even knew what love was you loved me for me
I was conceived from love, you believed Jesus sent me from thee above
Doc said you couldn't conceive kids, but did you believe the scrub?
Nah, you beat the odds didn't cease to dream, not even once
Pictures I would see of us, even when it was just the three of us
Without dad, saying she's with none eatin' crumbs
Dad left, came back, left again
He wasn't seein' us
You let us know it's not because he didn't love either of us
Kept no secrets from us
That's why we respected her so much when we were just young
She was me and my sister's air, couldn't breath it enough
Now memories of her love is all we have to breath in our lungs
If I could only hear her voice say "Petey" just once...
Shit, I'm kidding myself, that still wouldn't be enough
I feel like Heaven's not nice enough a place, wiping off my face
Cause you're not here to brighten up my days
When we were here together
You used to warn me that you won't be here forever
That mere thought brought me fear and terror
And now I'm just here dealing with whatever the weather delivers
Whether I'm bitter, I'm never a quitter
And though I can't hand deliver this letter
Me reading it out loud helps me handle this better
But now your spirit is free
Your memory will forever be in the lyrics of me
Anyone who hears it will see that

[Hook]:
You were my first sweet love
My love, love love love

[Verse Two]:
Had her funeral in a borrowed shirt
Borrowed shoes, borrowed tie
Wearing a borrowed watch cause we livin' off borrowed time
My sister called me early on May 6th
With bad news and my world has been gray since
Took the blue pill and got hurled in The Matrix
You've been on my mind every day since
Life hasn't made sense
I try to stay calm, think light but I stay tense
It's like I can't mom, I stick right in that same mess
I get good news and wanna call, forget your gone
By the time I dial the first two digits, I miss you mom
You got me talkin' to the air
Hopin' that you hear
Come haunt me if you dare
Respond to me from there
See I know better, I just want my mom to be aware
Honestly, I'll probably never be prepared
For you to ever leave from here
But Heaven needs you there, you're forever in my prayers
Till that one day I meet you in the air
Amen ma

[Hook]:
You were my first sweet love
My love, love love love

[Outro]:
Dedicated to my heart, my whole soul...Vicky Lee Nelson. Love you ma

Rest in peace ma