[Intro]
Ask me what my life is
Tell them bitches: "bitch my life is 'bout them vices" yeah
Said they ask me what my life is
I tell them bitches: "bitch my life is 'bout them vices" yeah
Yeah...yeah...
Yeah

[Hook]
Posted with the homies, smoking dope blunts (dope blunts)
Soda in my hand, you know its poured up (poured up)
Function got bracking when we showed up (showed up)
This my shit, nigga, tell the DJ hold up (hold up)
Posted with the homies, smoking dope blunts (dope blunts)
Soda in my hand, you know its poured up (poured up)
Function got bracking when we showed up (showed up)
This my shit, nigga, tell the DJ hold up (hold up)

[Verse 1]
Bitch, I'm D-A-DOLLA, coming from the 201
With my son, please don't start the drama
Heard he got a gun and bitches run
When they see me in the spot, burning pot
No, I'm what you're not
I pour fo's in a yola colored drop, Dolla
Daddy grab grass, throat burn from that Cognac
Red bone and her ass fat, got a backwood of that thrax pack
Said I made it here, I ain't going back
Getting paid off of fucking rap
Said I made it here, I ain't going back
Getting paid off of fucking rap
And I ride with my niggas
Go hit the lick, and get high with my niggas
Worse come to worse, then I die with my niggas
Shit, see that's the rules, know how I do
Eighth Letter Crew, look where we rule
You niggas food, we making moves, act like you knew, shit
And them hoes is steady asking what my life is
I tell them bitches "bitch, my life about them vices, nigga"
And them hoes is steady asking what my life is
I tell them bitches "bitch, my life about them vices" yeah

[Hook]
Posted with the homies, smoking dope blunts (dope blunts)
Soda in my hand, you know its poured up (poured up)
Function got bracking when we showed up (showed up)
This my shit, nigga, tell the DJ hold up (hold up)
Posted with the homies, smoking dope blunts (dope blunts)
Soda in my hand, you know its poured up (poured up)
Function got bracking when we showed up (showed up)
This my shit, nigga, tell the DJ hold up (hold up)

[Verse 2]
And now I'm driving drunk, the women say I'm tripping
All of them bars I took is fucking with my vision
PCH in front the steering wheel I'm gripping
The only thing that's on my mind
I hope the boys don't catch me slipping, yikes
Three of them think they straight
Other two, I think they dikes
Prolly only know 'em for the night
Couple weeks if I do fuck 'em right
Never die, just like my name is Christ
Swear to god, I love my fucking life
Wrote me a kite, and then I sent it to Maverick
He wrote me back and told me "let these niggas have it"
Raps turn into cabbage
Tabs under my tongue sent me on trips without the baggage
Psychedelic savage, doing damage
Jacket from a rhino, still fuck the five'o
Driving still, eyes low
Minds moving fast but I rhyme slow
I kiss the model, then dead the bottle, Hz, nigga