[Intro]
You remember what happened last time
When we brought the casket on stage
You know what really happens?
We told you you was gonna die
We came on stage, looked you in your face and said
You gon' die

[Hook]
Left the devil on the back roads
In search of heaven on the path home
In the raft I go
Niggas wanna have my soul
Feeling like Django, right back in the rodeo
We did it. Juicy get em. (Flex)
Niggas start flexin', it's the Wesson (Flex)
On these streets men bleed
They respect it or they test it aim for the weak
Them cowboys, I brought killas with me
Them cowboys, I brought killas with me
Killas with me, killas with me, killas with me
You with them cowboys, I brought killas with me

[Verse 1: Fat Trel]
You a cowboy I got killas
I got animals and gorillas
I got silverbacks with them black macks
And this trap rap no backpack
Petty thieves in my rat trap
Never preyed on the weak
Last lay was on south beach and that bitch stay for a week
'Fore the white folk came
Guns got blown, bodies on the ground and the brains on the floor
Put the cash in the bag in the all black Jag
In the bag in the trunk, next to the pump - bang
Whether sun or rain
I'm out here police know my name
Neighbours hate when I'm stepping out
Cause they already know what my weapon 'bout
And that's murder - we killers
And all my killers got knowledge
And Loaded Lux is my teacher
So middle finger to your college
And ace's clip is my preachers
DC bought me dollars
And I named my first son Harlem
And my manager bought me commas
No drama, and I left

[Hook]

[Verse 2: Loaded Lux]
I seen wise men come, I seen wise men go
And in this violent lifestyle all they know
They die for all their dough
It's always a test the best gotta raise the rest
I pray that less less is for the king of death
Saved you flesh you guessing your brain suggest
The game success?
Think of it like a game of chess
You in a lyrical circle individual virtues
Get tested no question this feeling is personal
And really get hurtful when the killing concerns you
You learn to when there's no one to turn to
Envision the verbal mental build of a slaughter house
Slaughter all involved with the choice of doubt
Fought in bouts to kill what it's all about
The bill was real you fake gotta call you out
The hardest out
Party's 'bout to have all them out
Well food for thought what counts
Knowledge explained without pay
And I'm kangaroo with this k
Let them hold that
Loaded Lux make 'em pay, they owe that
Trilly Trel ring them bells, they know that
Flick it up with the fans that's kodak
Cause hell if I gotta go back

[Hook]

[Verse 3: Fat Trel]
Cowboys and we killas
We hunt, so we eat
Y'all bar the way, so y'all starve
Peasants don't mingle with gods
My body count a collage
9-11 my team
So you can either jump in this ring
Or get 'head get under my wing
Silencers with them beams
Loud cries and screams
Drug dealers and fiends
And every king need a queen

[Verse 3: Loaded Lux]
Me and my younger Trilly Trel goin' bonkers
The monster from DC boy no comment
We conscious and we be hoppin' out the tonkers
Hear me know my old niggers yonkers
Harlem up in this motherfucker I offer to offer the most
Awesome lyrics you lost in
Sales get enormous endorsements
Finna drop these kicks, Miguel at the concert
Niggas got to hold that
Loaded Lux make 'em pay they owe that
Trilly Trel ring them bells they know that
Flick it up with the fans thats kodak
Cause hell if I gotta go back

[Hook]