[Produced by Blended Babies]

[Hook: Ricky Hil]
Mom, I'm a rolling stone, I know I ain't been home
I'm better on my own, I'm grown, and I
I got some stupid addictions, but the young people listen, listen to me, yeah
Mom, the first time I tried, I felt so free, yeah yeah yeah yeah yeah
Mom, the first time I tried, I felt so free, yeah yeah yeah

[Verse 1: Ricky Hil]
Do you have anything to help me sleep, mom?
I've been going all week mom, and I wanna come down
Do you have anyone I could see mom?
I feel sick mom, and I won't come down
We got, we got what we wanted, now it's killing us
We got, we got what we wanted, now it's killing us
You wouldn't wanna see me like I am now
Because I'm getting higher, it's taking its toll on me now

[Hook]
Mom, I'm a rolling stone, I know I ain't been home
I'm better on my own, I'm grown, and I
I got some stupid addictions, but the young people listen, listen to me, yeah
Mom, the first time I tried, I felt so free, yeah yeah yeah yeah yeah
Mom, the first time I tried, I felt so free, yeah yeah yeah

[Verse 2: Fat Trel]
And I say mom, don't wait for me
Bless and heal then pray for me
Know I be with Ricky Hil faithfully
Try and turn an instrumental to an 8th a key
In Hollywood, with molly on deck
Bitches everywhere so it's bitches on my neck
She say I'm the shit, now I think I'm obsessed
But I'mma fuck her and I'mma leave her upset
But mamma raised an angel, streets raised a devil
Came with a bible, left with a Chevy (I'm a rebel)
I was killing them niggas, you really drilling them niggas, I wasn't feeling them niggas
Ask Ricky Hil how he feel, he told me he wasn't feeling them niggas
So we ride real slow, in the Lincoln, Seat low
All black, whatchu know, CT DC we go
Searching for drugs, searching for bitches and bitches searching for love
We just searching for highs, we just searching for God

[Hook]
Mom, I'm a rolling stone, I know I ain't been home
I'm better on my own, I'm grown, and I
I got some stupid addictions, but the young people listen, listen to me, yeah
Mom, the first time I tried, I felt so free, yeah yeah yeah yeah yeah
Mom, the first time I tried, I felt so free

[Outro]
I'm a, I'm a rolling stone
I'm better on my own
Listen to me