[Intro]
Ah, if I could get my hands on that 'sill
I could pull myself up, ah, uh

[Bridge 1]
D... E... M... O... N... S...

[Intro 2]
Damn, I think I'm going insane
I'm hearing voices echoing in my mind, I can't take this y'all

[Verse 1]
Look, I can feel the demons in my brain
Creeping through the dark parts
Got my tucking different handguns in my Carhartt's
Where the hood got the reaper hiding underneath, yo
Ever wonder why we rather die, then let the beef go?
Stay feelin' stress, greed, lust and jealousy
My people cope by using cess, speed, dust, and LSD
D, more than just a simple sickness
It's triple sixes, to haunt the Holy Temple scriptures
And got the lost souls playing false roads
They got 'em, once they get inside 'em, like crossbows
It's the demons, conjuring up images you dreaming
Or screaming, it's seems when you're semen they scheming
Got us paranoid, steppin' out very cautious
The same way we holding guns, nuns carry crosses
Forms of protection against the evil forces
Of course there's subjections, in your cerebral cortex, the demons

[Interlude]
Man, my palms feel sweaty, my skin's curling
Even my soul feel trapped man, I don't know what to do
Sometimes I wake up in the middle of the night, hearing whispers

[Hook]
You see, if you listen close, you can hear the song they sing
Between good and evil, you're just a puppet on a string
It could be the angel of death or the angel king
A pitchfork with horns or a halo with wings

[Verse 2]
If I broke the word down in acronyms, while usin part logic
A demon could mean, destroying every man off narcotics
Drug epidemics, measure obsession needles
Got dealers earning money overnight
Deceitful elections, monitor our nations
While devil's effected, music out now on your stations
Dirty, explicit, material, oozing negativity
Distorting, eardrums mentally
Overwhelming nonsense
Dysfuctional, educational, malfuctions, oppressed negroes
Death, equals murder, oxygen's neglected
Drama, extreme mayhem, owning a necklace
Diabetes enter many obese niggas
So, dreams eventually match, ordinary nightmares
Department, eviction, management office notices
Dreadful, evolved missiles operating nuclear, why is this new to you?

[Interlude 2]
I can't explain it dog, I get this chill in my spine
I just get the urge to do something real crazy man
Yo, I might be losin my mind

[Hook 2]
You see if you listen close, you can hear the song they sing
Between good and evil, you're just a puppet on a string singing

[Bridge 2]
D... Dark deception, deepest degree
E... Enhanced evil, extraordinary envy
M... Major malicious, miscellaneous mayhem
O... Overload off, obnoxious obscenities
N... Never nice nature, negative nemesis
S... Several strange souls symbolizing stress

[Outro]
Fuck! I can't take this shit dog
I'm seeing demons, I'm stressed the fuck out
Lord help me, I think I'm going insane, can't explain it

[Skit]
What do you see right now?
Do you see exactly and only what I choose to show you?
(What? Get out of my head) That is it

Yo, what the fuck? What you doin in bed with this nigga man? You got another nigga in my bed? (Yo, old up, hold on a second man, hold on a second man)
Yo, shut the fuck up man! Y'all gonna make me kill both of y'all motherfuckers! Nigga get the fuck down! You shut the fuck up! Fuck y'all niggas doin? Fuck this shit man, you about to die right and fuck y'all niggas man (You cannot do this, don't do this)