Jaylin man, dag man you 8 months dawg
I remember just thinking, what you was even gonna look like before you got here man
And I sat down to myself man, and I just began writing, the Lord put something on my spirit man
It was just a way of me speaking to you things I wanted to relate to you man

This is my, letter to Jalen
And I’m praying, when you get older you comprehend what I’m saying
Man I’m here for you, and I’m making it clear to you
That a Christ-like life is where I’ll be steering you

And I know it’s rough, and obstacles will come against you
But you ain’t got to, go through what your daddy’s been through
God has sent you, with the hand of His might
I demand you understand His whole plan for your life!

Please! Don’t abandon the light
Cause it may be years before you veer back from the land of the night
Understand what is right and let no man lead you
Be a leader, no matter what they feed you

And I’ma teach you, that you must crawl for your walk
If you fall it’s a start, proceed with all of your heart
It’s all a part of growing up, learn from mistakes that you make
So when you face em again, you know what’s up

And weigh out ya options, don’t dive in to things head first
Manage your money, spend when you breaking a little break a little bread first
Keep you a plan, and only do what you can
When you accept responsibility, your truly a man

*phone rings*

Hey Dawan this is Jason
Hey Jason, where you at?
Oh I’m just at the studio, I was just giving you a call to let you know that I love you, you know I love you right?
Yeah, I love you too
Okay, well I’ll be home a little bit later. I’ll see you when I get there
Jason, can we play the game when you get home?
Yeah that’s cool, we could play the game when I get there, aight? I’ll see you later
Alright, bye
DeJuan

DeJuan, your not my son biologically
You have a dad, but still you have a father in me
When we met, truly I was still lost in the streets
You were four years old, and stuttered as you were talking to me

I remember clearly, you hated smoking severely
I did it around you anyway, claimed that I loved you dearly
It all was a lie, and my heart was desperately wicked
Expect that from man, when his focus ain’t Christ centered

But, for your forgiveness is what I’m asking
I murdered the flesh, you see the old man lays in the casket
Life everlasting, I’m trying to tell you what real is
Hell is hot, it ain’t something you wanna deal with

The world will paint this picture about, money and fashion
Can’t take it with you, when your body returns to ashes
(What I’m trying to say), don’t do what I did, but do what I do now
See Christ lives in me, I really do love you now

I thank the Lord for bringing our relationship closer
Secluding us from danger, keeping anger from boiling over
And as you grow, throughout your life situations
I’m here for you the same but know Christ is your foundation

I Jason (I Jason), take ye LaWanda (take ye LaWanda), my wedded wife (my wedded wife), to have and to hold (to have and to hold), for this day forward (for this day forward), for better or for worse (for better or for worse), for richer or for poorer (for richer or for poorer), in sickness (in sickness), and in health (and in health), and to love (and to love), and to cherish (and to cherish), till death do us part (till death do us part), according to God’s holy ordinance (according to God’s holy ordinance)...

I thank God for my wife, the love of my life, my heart and my soul
Woman of Christ, more valuable than the price of gold
I pray that it shows through affection my deepest emotions
Keeping me open, your love flows deep as an ocean

You’re the shirt on my back, pants on my butt
You’re the twinkle in my eye, crutches that are standing me up
My love, you’re my wife, you’re my friend, my light when its dim
My smiles or my grins, its like your everything (from within?)

I love you, and put no one but the Lord before you
I’ll endure through the pain because I adore you
Virtuous woman, adorably stunning, your beautiful
You love me and you should know that the feeling is mutual

What more can I do for you, before I’m smothered in dirt?
Cause it’s only right for me to love you, like Christ loves the Church
And He died for us, so know I’ll do whatever it takes
Then He rose for us, so know through Him we never will break

Through heartaches, all the ups and downs, the smiles and frowns, whatever
Long as we stay focused on God we’ll be the glory together
Holy, matrimony, such a wonderful thing
With my beautiful queen, as we both serve a glorious King

I thank God, for what He’s done in my life
And I gotta give Him thanks for my son and my wife
My whole fam, I know it’s a blessing to have
Nikki, Jaylin, Duwan, through the good and the bad (X2)

I thank God