[Verse 1: Erick Arc Elliott]
The rhyme is so raw, most these rappers need a seminar
You copy the same schematics, you making the same songs
You thought that you were the only, but understand it's the physical
Artistry manifest, but no ideas original
Our sickest creation, no need for further analysis
Plus the beats bang prestige giving me calluses
Even if it's assumed, proving it all again
Selling out all the shows never selling out who I am
Mild temper venter, chronic keep me casual
Formally introduced to a journey into the natural
The three, two zeros then proceeded by one
Laced like your woven tennis shoes before you go run
Danger danger, Will Robinson
There's a crisis here, nappy ain't dirty
Racist man it's just a type of hair
Nightmares have just begun, there's no enticing him
Limbs relaxed, but your music pop like a Vicodin

[Hook: Eric Arc Elliott]
R.I.P. to the CD can't even play my hits
Cause new computers ship without the means to play the shit
We love the boosted speed
We love the memory
It got me feeling like we're nothing like we used to be
R.I.P. to the CD can't even play my hits
Cause new computers ship without the means to play the shit
We love to boost the speed
We love the memory
It got me feeling like we're nothing like we used to be

[Verse 2: Zombie Juice]
Smoke smoke drip sip sip sip
Eyes closed like I missed this
No forgiveness, just a sick bitch
Cause I'm under destruction what is this?
Just a young nigga ready to get this
If I fall on my face, you're my witness
Feast on my blood when I leave this
Dimension I'm starting to think that
This world is lost like a sea ship
Walking to hell with the demons
How can the heavens defeat them?
Sometimes I just wanna, leave 'em
This feeling is something, I can't run
I just wanna be where I came from
I'm never gon' see where I came from
Rest in peace to the game son
Brooklyn baby reborn
Tripping up, you lukewarm
This is like a warning Flatbush swarming Nike shoes on
Prove them critics wrong getting cream bitch I love it
And the fans hold us down, put nothing above it

[Hook: Eric Arc Elliott]
R.I.P. to the CD can't even play my hits
Cause new computer ship without the means to play the shit
We love the boosted speed
We love the memory
It got me feeling like we're nothing like we used to be used to be, used to be

[Verse 3: Meechy Darko]
The wickedest, man on fire the new Richard Pryor
The wicked lit, rubber on my dick
'Cause I don't want that Charlie Sheen shit
Please don't say you're the highest until you met your highness
I just, want the head like ISIS
Fuck her so precise her pussy gushing like a geyser
I'm Michael Myers with these grip pliers took off your eyelids
I sit in silence, speak in tongues and burned Bibles
So paletted to all of my rivals you will not vanquish my titles
My semi-automatic, will splatter a nigga like Jackson Pollock
Deranged since birth I was conceived in an insane asylum
I solemnly swear this evening to refrain from the violence
Young and wilding, psilocybin still my stylist
LSD drops in my iris, tire mark, police sirens
No guidance, the belly of the beast is where I reside in
Grimy and vibrant like Busta Rhymes, in the early 90's
Click boom, your head blew like you play for the Giants
Lyrical tyrant the way I be rhyming
I deserve all of the Pulitzer prizes my pistol be hiding I pull it surprise 'em
My voice can be hypnotizing every verse I deliver be vivid and visually striking
Been the highest since I arrived and the climate is rising
It's 'bout to get violent cover your eye
And take this lyrical dosage that Doctor Meechy Dark prescribed ya
I slide inside her I love her tight vagina no E-Z Widers
Back to the cypher I got chronic to light up pass me the lighter

[Hook: Eric Arc Elliott]
R.I.P. to the CD can't even play my hits
Cause new computers ship without the means to play the shit
We love the boosted speed
We love the memory
It got me feeling like we're nothing like we used to beused to be,used to be
R.I.P. to the CD can't even play my hits
Cause new computers ship without the means to play the shit
We love to boost the speed
We love the memory
It got me feeling like we're nothing like we used to be