[Hook]
(Classified)
Although (oh) there are (oh) oceans we must cross (we must cross)
And mountains that we must climb (ha, we still got a long way to go)
["I testify"]
I knoooooow (oh) every gain (oh) must have a loss
(Seems like anybody will buy into anything these days)
So pray that our loss is nothing but time
(It's funny but it's serious, listen)
Although

[Verse 1 - Classified]
Now this is all before the throwbacks, trucker hats, spinners and the
Platinum (yeah)
Fads come and go, y'all need to recognize what's happening (haha)
Far as I remember in 1982 (yeah)
There was no one hating you if you rocked the latest shoes (uh)
Styles change daily like everyone's opinion
Buy the latest fashion just so you can fit in
In '89, everybody had Hammer pants
And they was topped off nice (yeah) with a brand new Barney Franz (haha)
Everybody wore it, nowadays ain't a chance any of us sport it
And that's why I record this (yeah)
Wanted all the newest style but never could afford it (nah)
But did have a mullet (what?) in my elementary portrait (yeah)
Lesson learned, I look stupid as hell
But I can laugh at myself now cause kid I'm doing well (ha)
I just do it for myself, make sure my music's felt (yeah)
This is real life reality, play what you were dealt, come on

[Hook]
Although (oh) there are (oh) oceans we must cross (we must cross)
And mountains that we must climb (ha, we still got a long way to go)
["I testify"]
I knoooooow (oh) every gain (oh) must have a loss
(Seems like anybody will buy into anything these days)
So pray that our loss is nothing but time
(It's funny but it's serious, listen)
Although

[Verse 2 - Classified]
And look at sped-up samples, everybody's using it
I try to skip past but can't bring myself to it (nah)
If it sounds good it's good, keep it plain and simple
But pitch hit the vocals and slice a bitch instrumental (yeah)
Back to the '80's though, kids wearing bike shorts
Looking like they're idiots, so this is what I write for (haha)
Open your eyes, all these fads are fading out (yeah)
Like pullover Chicago Bull and L.A. Raider coats (ohhh)
Say it ain't so but all of it gets played though
Like sneakers with Velcro, I'm speakin what you all know
Preachin with a raw flow, tryin to make it easy (ha)
You don't need to buy these things just because it's on your TV
(Believe me), I did the same shit in highschool
I had the Doc Martens shoes and thought "Classified's cool"
But come on, that went out quicker than the British Knights (yeah)
So now I spit it right every time I hit the mic, what?

[Hook]
Although (oh) there are (oh) oceans we must cross (we must cross)
And mountains that we must climb (ha, we still got a long way to go)
["I testify"]
I knoooooow (oh) every gain (oh) must have a loss
(Seems like anybody will buy into anything these days)
So pray that our loss is nothing but time
(It's funny but it's serious, listen)
Although

[Verse 3 - Classified]
And I remember women with their haircut lookin a straight menace (ha)
With the bangs a foot in the air like Elaine Benes (haha)
These whack trendsetters get backed by pretenders
Leg warmers, mesh shirts, all that shit (I remember)
I'm sick of seein 'No Fear' (No Fear) on people's windshield
Cause everybody had it on their car or truck in Enfield (haha)
Remember fanny packs (the pouch), whatever you call it
Kids used to wear 'em with nothing in it and think they we're ballin
We all fell into it but yes this game is fresh
So I still try to improve it and pursue it
But if rap fails (yeah), I'm growin back my rattail
Moving back to Enfield and livin the simple life

[Hook]

[Outro]
Although there are oceans (Class) we must cross
And mountains that we must climb
I knoooooow every gain must have a loss
So pray that our loss is nothing but time
Although (*echo*)