She doesn't love me it's all for money
She comes around all new this day
I fall back in love but I feel something funny
So why would I throw my world away?

Leather coat
Backstroke
Diet coke
Antidote
Mute purse
Universe
OC episode
Actress
Mattress
Unison
Glasses
Rock star
Classes
Backstage passes

Thought I told you
Told you she would mold you
Mind she hold you
Hold you like crazy glue
No clue
Tofu
Tell me whatcha gonna do
See she run run
She run run

She doesn't love me it's all for money
She comes around all a winter's day
I fall back in love but then I feel something funny
So why would I throw a friend away?

Forget the money better run now
You're not what she jumps now
You gotta learn to have fun now
Yeah
Forget the money better run now
You're ain't what she jumps now
You gotta learn to have fun now

You thought you had it under control
He thought he as holdin' it down
But she was makin' rounds all around downtown now

It not all for the money
We look above on a winter's day
We fall back in love but we feel something funny
Why are we throwing our world awya?

Forget the money
Forget the money
I'd like to think i'm not in the money game