Uh-huh
We wolves baby, we wolves

[Verse 1: Krumbsnatcha]
A full moon make my blood curl
Got me stuck in opposition in the underworld
Savage beasts, like wolves when we roamin these streets
And work for least, fuck peace, go to war with police
Some call priest, there's a demon in ya hood schemin
Catch me out the six leanin, with the nine steamin
Aimed at your BM
The sound of the Glock sound like riots in Watts
I point a Ruger at'cha crew and give you somethin to watch
D.T.'s, Feds, and NARCS, exchanging shots
In broad day until the first one lay when he pop
And if I pull and you pull
The one to get it worst be the last to burst
ICU status, with the phattest nurse
Gat holders tucking them burners, with the fat pollers concealed
But quickly leave a veal through your widow's shield
Reckless, connect like a Nexus, for your necklace is on
Formin like Voltron and bomb

Chorus:
[Children] Y'all police best be ready!
[Snatcha]  If you tired of seein niggas gettin beat in the street
[Children] Y'all police best be ready!
[Snatcha]  For all my hungry ass thugs that be tryin to eat
[Children] Y'all police best be ready!
[Snatcha]  All my people in the ghetto, get up off of your feet
And let the wolves out! (Unh)
And let the wolves out! (What!)
And let the wolves out! (Unh)
Let the wolves out!

[Verse 2: Billy Danze]
Yo I been labelled a bad guy since birth (why's that)
I was put on a part of the earth where the turf
Is rugged neva smoove
(What have you got to lose!)
Not a damn thing
That's why I holler "Ante Up" when you holler "Bling Bling"
How do I survive? I strap up all my heat
I get out on the beat, I find a way to eat
See William never sleep, you think it's somethin sweet
And I will kindly li-li-li-li-lift yo' ass up off your feet
Shackle me in chains, tamper with my brain
Spit a ten digit number when you call me by my name
The system has been aimed
For every 211 and every 187, my niggas is to blame
What happened to Diallo is a motherfuckin shame
How 'bout if I spit 41 at you and end the game
ALL disrespect intended, to any lieutenant
Who feel offended, by the way I represented, BITCH!

[Hook]

[Verse 3: Lil' Fame]
I put it down, M.O.P. spit FIIYAHH!
Show 'em what we stand for, YES SIYYAAH!
All I need is my niggas, my guns and, my CD's
And I'mma ride, fuck N.Y.P.D
The STREET cops, patrollin them HEAT
Goons be holdin 'em but fuck it
We lay 'em down like linoleum
GHETTO WARFARE! brroom, buck! We grip eight on
The pop'll pop off, that's how we do in Brooknam
Let the wolves out! Huh, all day
For my niggas gettin money that hustle in hallways
Get'cha money mister (mister) it's a (it's a) new day
Don't be street illiterate, cuz you could get it two ways
Behind bars, or six feet deep
So be careful who you fuckin wit
Motherfuckin you fuckin with the UH, OH, UH, That's the truth
It's the B'Ville, deranged, gun poppers, salute!

[Hook]