[Hook]
I’m talking bout roots
I can’t hate where I’m from
'Cause where I’m from made me
I came from the bottom of the slums
But now I got me...me
That’s because of my roots (Yeah, Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots (Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots

[Verse 1]
Hey I can’t be mad at what got me ahead
I don’t regret my ghetto struggle due to my success
It ain’t that beautiful to write on overcoming stress
Top Ramen noodle soup, thank pappy for the fact I was fed
Look at me now but all before, "Hey Mr. Skid Row"
The dirty south ain’t just a name the way I’ve been poor
The projects brown and white, I call it gizmo
Went from a gremlin to them cars in Jigga's video
Can’t find a meal to a mil, only God know it
No record deal to a deal, I work hard for it
Can I live to I’m living like my Momma told it
Before you reap it, gotta sew it

[Hook]
I’m talking bout roots
I can’t hate where I’m from
'Cause where I’m from made me
I came from the bottom of the slums
But now I got me...me
That’s because of my roots (Yeah, Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots (Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots

[Verse 2]
Hey, still on my Kunta Kinte
Somebody had to bleed just for me to get away
My sister had to leave, I respect her staying safe
Oh yea I had to grieve but I’m stronger to this day
Pain, I can’t ignore it, you might say I’m ignorant
I’m mistaking for courage, victory so gorgeous
Make it through two Bush, I can make it through any forest
Hunger gave me the wish, but the bottom is so important
37 ave and 187 street, Miami, Carol City, now I’m part of a legacy
I’m thankful for the hood, what is love without jealousy
There’s only five letters really help me

[Hook]
I’m talking bout roots
I can’t hate where I’m from
'Cause where I’m from made me
I came from the bottom of the slums
But now I got me...me
That’s because of my roots (Yeah, Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots (Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots

[Verse 3]
Hey I know the seeds been planted
It’s damaging my soul but my dreams been granted
That triple life towards, much deeper than Earth's planet
What could I want more than redoing, I never panic
Gets no lower than the ground beneath your feet
A man will stand for nothing if he falls for defeat
A boulder in the hand better than all in the street
If you look beneath the sand then we all need a crease
Roots before the branches, roots before the mansions
Roots before your paper crazier than Marilyn Manson
Roots with your grandparents, roots under your canvas
Roots whether you black, white, or Spanish

[Hook]
I’m talking bout roots
I can’t hate where I’m from
'Cause where I’m from made me
I came from the bottom of the slums
But now I got me...me
That’s because of my roots (Yeah, Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots (Yeah, Yeah, Yeeeaaahh)
I’m talking 'bout roots