[Intro]
Nard & B
Bobby Kritical

[Hook]
Pull up to the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact
If I hit your baby mama I ain't sorry, that's a fact
Bought a Birkin now the bitch act like a Barbie, that's a fact
Ay, that's a fact, ay-ay that's a fact
Ay, that's a fact, ay-ay that's a fact
Pull up on the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact

[Verse 1]
Nigga thought I fell off, no bitch I'm back
Know I keep a bad bitch by my side, that's a fact
Plenty bitches popping pills, sucking dick, we on that
You gon' run off with the wave every time so don't act
I might hit up Magic throw some change and grab a play
I ain't worried bout no dance I fuck the waitress anyway
When I call her she gon' pull up with the pussy any day
I got money coming in, nigga every which way

[Hook]
Pull up to the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact
If I hit your baby mama I ain't sorry, that's a fact
Bought a Birkin now the bitch act like a Barbie, that's a fact
Ay, that's a fact, ay-ay that's a fact
Ay, that's a fact, ay-ay that's a fact
Pull up on the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact

[Verse 2]
Nigga wanted issues so I had to give him that
Bitch I came back to the city, brought that wave that's a fact
I'm in LA with the trapper blowing gas and shooting craps
Why these bitch keep acting petty, she just mad, I don't react
Flooded out the Rollie now I'm feeling just like Meech
I don't trap but these niggas still love me in these streets
Vintage shirt, couple chains, and some Yeezys on my feet
Put in work, I ain't change throwing ones up out the Jeep, ugh

[Hook]
Pull up to the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact
If I hit your baby mama I ain't sorry, that's a fact
Bought a Birkin now the bitch act like a Barbie, that's a fact
Ay, that's a fact, ay-ay that's a fact
Ay, that's a fact, ay-ay that's a fact
Pull up on the scene, red 'Rari that's a fact
Blow my top while I swerve, getting head that's a fact