[Intro]
Cannon, cannon
Nah, it's K-I
It's K-I
D, D, yeah, you know you know me
You know it's the, the money symbol at the end of that
Uh huh, look
And you know I just, I just, want you, want you to remember that
Yeah, look

[Verse]
I want the fame
And I been wanting this my whole life
And I don't want a bite unless I can get the whole slice
Short weekend, fast days, and short nights
My ambition has got me higher than four kites
High, and I'm never coming down
I'm running so fast, my feet barely hit the ground
And labels say I'm good, but they never come around
So if no one ever hear me will I ever make a sound?
Mhm, I don't know and I don't really care
I just keep ripping up these beats until there's nothing there
Life is just a game, and these rules ain't nothing fair
I been on the plane to success, I can take you there
Welcome you to flight school, show you how to make it here
If you got a chance, then don't let these haters take it, eh
And if you got a dream, then don't let these haters break it, eh
And if you got a plan, then don't halfway bake it, yeah
That shit ain't gon' make it here, people on they grind
And I been on mine since I first turned five
And I been on fire since my very first line
Y'all haters can't see me like the world's gone blind
Yeah, I swear that, art is suddy, yeah
And if you got a limit I'ma make it disappear
Yeah, I swear, the art is suddy, yeah
And if you got a limit I'ma make it disappear
This music thing, it's been ripping me apart lately
There's so much screaming dawg, you would think I'm part crazy
And I'm tryna keep it pumping, but my heart's lazy
And every time I look up, it seems the bar's raising
Hard to show yourself if ain't nobody seeing you
We all believe in you, but don't nobody see it through
And it seems everybody want a piece of me
There's only one left, and I don't know who to feed it to
Damn, 'cause no one give me a reason to
Don't get it confused, I ain't easy food
And I'ma get it hype, you be on your P's and Q's
Party harder than Jersey Shore, season two
Ha, and that's more shots than Ray Allen
But not for me, 'cause I can't stomach tequila
I feel like I got a lifetime fever
Bringing down the rain boy, Hurricane Katrina
Got a pocket full of leaves, spend it on my team
All about green, I should be the head of EPA
Girls on my hip like I'm a '94 beeper
And I kill so many tracks, beats call me the grim reaper

[Chorus]
Yeah
K.i.D is kicking it
I ain't even complain at all, I just want a little bit (Nah)
Only one night though (Yeah), and it's all livin it
So if you're drink is in the air, go and take a sip of it
Mr. Man, ooh damn
K.i.D, you know me
C Breezy, B Combo, you know
Yeah, go and take a sip of it
K.i.D is doing things, I'm just tryna live a bit
Only one night though, that is so living it
So if you're drink is in the air, go and take a sip of it
Uh, yeah
I got 'em, K.i.D, D
Fully laced, boy
You know, you know you know me
Yeah, money symbol at the end of that
So um, remember that