[Chorus: Smokepurpp]
Communicate with the money
Communicate with the money
Communicate with the money
Communicate with the money
Communicate with the money
Extraterrestrial
Communicate with the money
Extraterrestrial
Communi-
Communicate with the money
Communi-
Communicate with the money
Extraterrestrial
Communicate with the money
Extraterrestrial
Communi-

[Verse 1: Smokepurpp]
I hit that gas in the booth
I get that bitch out, to boot
I get a bitch and I fuck her
I get that bitch in the booth
I get that bitch off this dope
Top floor resident
I count my money, dead franks
Glock-17, extendie
Boy talk shit, two shots in him
Black flag on my head

[Verse 2: Yoppa Bam]
Little bitch on the molly, staying ten
Can't stop popping them xans
Big Yoppa get [?] like [?]
Looking at my bank, seeing new moves
Probably be looking like a funeral
Take a blue pill, I'm on Neptune
Baby suck me up in the green room
Communicate with the money
I speak in a tongue with the money
And my diamonds, they bright like the morning
Nigga hating, go get you some money

[Chorus: Smokepurpp]
Communicate with the money
Communicate with the money
Communicate with the money
Communicate with the money
Communicate with the money
Extraterrestrial
Communicate with the money
Extraterrestrial
Communi-
Communicate with the money
Communi-
Communicate with the money
Extraterrestrial
Communicate with the money
Extraterrestrial
Communi-