(Yea, yea, cle-cleveland style!)

[Verse 1: Kid Cudi]
84 Kid Mesc was born
On my own since they cut the umbilical cord
When I was born, witness to divorce and scorn
Ever since that happened, I was daily torn
Didn't understand nothing but I'm happy
Instead of being cool, my family kept on snapping
Cool out shit 12 a nigga was rapping
My father died, the pain is still
Look in the mirror man, I see real
Touch my reflection, feels what I feel
The letter is written: stamped and sealed
Intoxicated, spill for spill
And I ain't never seen a gang making deals for deals
Cover my mind and witness why
There's the time in the world and no time to die

[Hook]
I ain't trying to upset nobody
I'm just trying to be me

Everywhere I go man, people like "he's still rapping?
Yeah that's right man, you still gun clapping?
I'm on to bigger positive things
Trying to live out a dream
I'm the MVP, look at my ring
What y'all know about the street games, you're just
Dreaming em up. Not trying to make a come-up
Going to sleep at night praying to god
Wishing that you had that bad bitch in your arm
I'm that kid tryna make things happen
Up in the club, watching gangstas clapping
And I'm that kid that be steady rapping in the booth
Throw out my demo and that's a Hot 97 proof
And you don't wanna sign me, fuck are y'all on?
I go next to the next dude that wanna put me on
And that's real, cause I'm only me
The K-I-D, not trying to become the next OG

[Hook]

Relax daily [-]
Ya know what I mean, less acting
More me and me, less them
In the pool of magical ones, I will not swim
Not on the hottest day or the warmest night
I'm free like a bird nigga, I should take flight
Plain nigga, the one less hoes like
Even if I had jewels that could dim light
Off they would never look, rather read a book
Know I'm semi-wrong, got 'em shook
Now they know Scott, and they know I plot
Don't trust hoes, they just want the knot
Till I abuse it, baby I love music, not
Really ain't no question, just lessons
At confessions, never false preaching
Real recognize through deception and lies
So, keep it music, baby keep it going steady
It won't be long, my niggas, till everybody witness

[Hook]