[Verse: Ghostface Killah (Raekwon), Both]
Yo, up in the M.G.M. coked up, psych
Six niggas walked in flashing they gems peace (Aight
One dark skinned nigga fifty-six inch rope wrapped around twice)
Smash the Gilligan boat with ice
(They threw sign language, ordered hot coffee
Wit a danish
Relax, whispered they, "Rap entertainers"
(Had Lizzy on, two Japanese birds with furs look good kid)
Laid back handling hors d'ourves
(It's like round three) We too black for BET
You memorize the 1 to 40 (I'm at the 19th degree
If a civilized person doesn't perform his duty, what shall be done?
Pardon me God, that nigga got a gun
Bulging out his sweatpants, check out his stance
See the side of his grill? (Look like my cousin Lance
Left hand, rocky Guess watch) Yo I think I did his Clarks
He wanted crush bone leather with the strings dark
(Now I remember) He from Bear Mountain
He and Mitch Greene shot the fair one (Near the water fountain)
Seventh round, Chavez bleeding from his right ear
Yo keep your eye on that same nigga from right here
Popcorn spilling all on Liz Claiborne
Ghost had the fly Gucci mocks wit no socks on
Seen Deion Sanders in the back with the phat fur on)
Working them hoes with the fly Wu shirts on
Mixed drink session Dun (Pour me some more)
Chef leathered down blinking at Chanté Moore
(Tenth round Chavez tearing 'em down) Sweet Pea get ya shit off
(It's like blacks against the Germans) Getting hit off
(Smooth and them walked in) Brownsville representing
(They sent a bottle over, autograph blessing)
Chef, pull out the doo-doo, twist the dank - pink noodles
(Yo I'm bout to roll one) Matter fact twist two of those
(Yo they wound up stopping the fight
Steels took a point away from Chavez)
Rematch scheduled on October Ninth
Rematch scheduled on October Ninth