[Produced by Russ]

[Intro: Russ]
Ooooo-ah
Mmmmmm
Just keep it real with yourself one time

[Hook: Russ]
It’s 2 A.M. and you feel like calling
I know what you want by the tone that you talking
Just get to the point with a boss
I gotta' couple shots in me yea I’m gone
Imma' make you feel like we just robbed a bank
Imma' make you forget that you gotta' get up in the A.M., A.M

[Verse 1: Russ]
Imma' one of one, that’s why you came through
Cause you don’t want me fucking with someone who ain’t you
Imma' blow up and see what this fame do
If you fuck up Imma' bounce like a kangaroo
But I play it cool, slide through for the hot one
You need drugs you need advice yea I got some
This is far from the end and far from the beginning
This is somewhere in the middle
Hit my phone when you slipping
Damn

[Hook: Russ]
It’s 2 A.M. and you feel like calling
I know what you want by the tone that you talking
Just get to the point with a boss
I gotta' couple shots in me yea I’m gone
Imma' make you feel like we just robbed a bank
Imma' make you forget that you gotta' get up in the A.M., A.M

[Verse 2: Russ]
Yeah, pretty Puerto Rican
Snapping at the mouth
Liquor love and anger makes your accent come out
Better calm the fuck down with your attitude
Cause I can change your longitude
And your fucking latitude
Put you on a plane to a place you never been
I could have you out in Asia lookin fly spending Yen
Better back the fuck up with that rah rah hooblah
Breath in breath out
Wooosahhhhh

[Hook x2: Russ]
It’s 2 A.M. and you feel like calling
I know what you want by the tone that you talking
Just get to the point with a boss
I gotta' couple shots in me yea I’m gone
Imma' make you feel like we just robbed a bank
Imma' make you forget that you gotta' get up in the A.M., A.M

[Outro: Russ]
Ooooo-ah
Mmmmmm
Just keep it real with yourself one time