[Intro]
Mr. Sandman
Yes?
Bring us a dream
Give him a pair of eyes
With a come-hither gleam
Give him a lonely heart like Pagliacci
And lots of wavy hair like Liberace
Yeah
Straight from Limbo
Yeah

I'm lyin' in the jungle fuckin' cheetahs on the run
Burnin' reffa catchin' preachers
In the bleachers with the nuns
Fuck your features I'm the one
The sun is in my glow cup
Kissin' on the rum hope my levi fuckin' hoes up
Funds will make you blow up
Laugh because it's possible
My optical illusions as a student was an obstacle
Had to break the fuck out
Dropped an armored truck now
Fuck your corny teens
Those were only fiends
We're more like drug routes
Guess we got the plug now
Diamonds got the dope bitch
In it for the bread so your music always loaves bitch
Faith in my own shit
Took me out to Jupiter
Feelin' like I'm God know for size tellin' Lucifer my dreams
And I drew the first scheme a long time ago
Apeshit make-shift the basement chronicles
Chronologically a part of me the futures optimal
Overdosed on ego trips
Now I'm at the hospital
Layin' next to sanity, tellin' him to fuck off
Hand me all the candy weed, I can't believe I'm stuck off
Half a cup of crazy half the youth value shot like
Watchin' pregnant babies gettin' rabies on the block
Yellin' save me to the cops but
I don't need a gimmick all you rappers tryin act
This is rap find a clinic get your mind right
Fine time to kick it with yourself til' the rhymes tight
Life gave me lemons then I flipped it in the limelight