[Sean Price]
Yo, Sean P!
DJ Honda, Sean Price
Haha, P!
John Wayne couldn't even stand the reign of the tec
Feel the flame on your neck
Bang bang with a sket
Bob Backlund, New Jersey Drivin', I'm carjackin'
Crack slingin' and sneak thievin', and Pa rappin'
Jack of all trades, sell crack, smoke haze
Tote the gat, blow strays if you're actin' all strange
Slumbilical, testin' the slums, my gun killin' you
Unload a clip on you, gun-buttin' a bitch or two
Holy War Jihad, no kufi or durag
Weapon of mass destruction blastin' somethin'
Johnny Rambo, live off the land, Captain Commando
Leave you injured, Afro-American ninja
True champion, Boot Campian, smoke weed
Some fresh new Timbs, dirty ass fatigues, listen
Sean Price is the grape ape thug
With a few bitches that's trippin' off the date rape drug
I'm gone

[Hook]
Weed, Pills, Coke, E
Shrooms, Heroin, LSD
PCP, GHB, Crystal Meth
Yes, I'ma D-I-E

[Sean Price]
Listen
My 16 off the chain
My clip hold 16, take off your chain
This ain't a freestyle off the brain
This is a fee style, break off some change
I'm rappin' for dough, plus I sell crack in the snow
Rain, sleet, hail, whatever
Any kind of weather
If your rhyme is better I'll quit my job
Join Academy become a cop and get you robbed
Listen, top shotta, knot rocker I be
You hear the P! The blocka that's me
Goddamn, the North Carolina vagina finder
Remind ya, I don't just rhyme
I got 50s, 20s, and dimes, yup
Sean Price, DJ Honda what it do
Big gat at an IMAX theater near you
Fightin' for mine, motherfucker knife for a nine
Beat your ass quick fast like I'm Mike in his prime

[Hook]