[Chorus: Daz]
You's just a B-I-T-C-H
You just a B-I-T-C-H
You just a bitch (B-I-T-C-H)
You's just a bitch (B-I-T-C-H)

[Verse 1: Daz]
I met her way back when on tour, Days Inn
Had her bent over backwards, her and her best friend
I was doing her in, making me cum again
And again and again and again
Having a ball while baby ate my balls
Gobbled it all, dick all in her jaws
And you know after I nut
I gotta get the fuck up and hit the cut
Bitch, you always will be a hoe that I know
And it shows in your attitude and shows in your clothes
Look at her look cute in her Chanel leather boots
And her pussy got juicy than a Juicy Fruit
Dick gobbler, nut swallower
You know the bitch is a real top scholar
Off ecstasy, baby fuckin' the best of me
Beyonce is my destiny

[Chorus: Daz]
You's just a bitch
You's just a bitch (bitch)
You just a B-I-T-C-H
You just a B-I-T-C-H
You just a bitch

[Verse 2: Kurupt]
Since the perfect ball blower, I'ma fuck and get up
See, all you'll ever be is a bitch to Kurupt
Put it in perspective, all she wanna do is eat something
Put it in perspective, all I wanna feed something
Put it in perspective, all I wanna do is beat something
So before I beat it, you could eat it, bitch
These bitches nowadays ain't right
Instead of having a good time all they wanna do is fight
But I ain't got time for it, I'ma say it again
See, I ain't got time for it nor the money to spend
But you, bitch, let me tell you what you could do, bitch
And I'll you'll ever be to me and my crew, bitch
A dust bag, dirty than a muthafuckin' dirt rock
Hoodrat only good for hittin' from the back
Scandalous than a muthafuckin' fat bitch
Probably woulda ate the homie's dick if I ain't crack it so quick

[Chorus: Daz]
You's just a bitch (B-I-T-C-H)
You's just a bitch (B-I-T-C-H)
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a bitch

[Verse 3: Daz & Kurupt]
Can I get some pussy tonight?
An hour before my flight, is it alright?
Is it all cool? Can we pull in a drive-in
And fuck in the back of my Lexus truck, bitch?
Get my dick sucked in the back of the pool
Been fuckin' since pre-school, I'm a muthafuckin' fool
A bitch is a bitch (bitch)
And now can my dick play with your clit?
The bitch love that shit
And am I wrong for thinking like this
Hittin' Peanuts on Tuesday and leaving with two women to twist?
Just been chasing bitches since pre-school, I used to do that
But if they ain't older than me, homie, then it just ain't cool

[Chorus: Daz]
You's just a bitch
(Bitch got some big ass muthafuckin' lips)
You's just a bitch
(Ooh, and she know how to suck a dick)
You's just a bitch
(She was eating her homegirl pussy
Freakin' it out with a dildo in her ass)
You's just a bitch
(Yeah, Freak Mama Number 1 that nasty)
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a B-I-T-C-H
You's just a biatch...