[Intro: Dream Mclean]
What it do
What it do, easy

[Verse 1: Dream Mclean]
I'll make you do what it do, make you do what I do
Bad news cause I do it all, and if I do it
Then I'm doing a few, I'm doing you, true
Then you should be doing you too, just do you and be cool
Just be cool, you'll be cool, baby, I knew you'd be cool
You are too beautiful to be suing people
And I'm pretty sure you asked me to let you pull on that zoot
Then put something in your drink, and then throw you in the pool
Twenty skinny white women in the pool with you too
Looking like noodles in soup, oh what a beautiful view
Coming down, come around, do the hula and hoop
And hope you're gone before it's gone too, toodle-oo

[Hook: Dream Mclean]
You say you want it all now
Tell me, what would you do for this?
You think I'm going all out
To tell you the truth, I'm just
Doing what I do, doing what I do
Doing what I do in here
Doing what I do, doing what I do
Doing what I do in here

[Verse 2: Professor Green]
Oi Dream, I was in the pool canoodling too
If I'm a noodle, well, then you're a fucking poodle
Business as usual until the day that it's toodle-doo
Until that day, all I'm ever gonna be's brutal
I ain't a wasteman but me, I'm out getting wasted
My palette ain't selective, anything you've got, I'll take it
My love ain't in the money, waste it quicker than I make it
6am looking vacant as I wonder around naked
Feeling kinda saucy now that I've been on the condiments
Dick in my hand, holding my rod while I'm fishing for compliments
I'm on a mix of cocaine, marijuana and ketamine
In a strip club trying not to slip up and lose my wedding ring

[Hook: Dream Mclean]

[Verse 3: CAS]
You know what I do, cocaine, ket and the dizzle too
Model chick, 22, 23 on her shoes
She brought a friend, I brought a friend, hit them with some two on two
Friend's clocking, bang her too, brain too, that'll do
I do what I gotta do, then I tell them on their bike
On my bike, R6, one wheel, out of sight
Her figure's slight, hair's right, might let her stay the night
After hoovering that white, most of them become my type
Pushing keys sorta like when you type, all these niggas talking trap
But we know they talking tripe, I've been on it all my life
On my life, coke resi on my knife
Now I'm getting big racks, like the one that's on my wife

[Hook: Dream Mclean]