[Produced by Lex Luger]

[Verse]
Pocket full of that collard greens
I still don't know will I get enough
See muthafuckas on the corner hating
Pull up a .12 and the heads get chopped
Use chopper style to make them respect
My hustle, yeah, they can't knock it out
I'm clever even if I sound dumb
And if my rhy-mes don't rhyme at all
I know my way used to be hard as fuck
That made my victory taste like honey
I kill the beats with every word I rhyme
And for staying safe you better give me your money
My life's a bitch, and I fuck her harder
Than Bradley Pitt makes love with the A
Fuck safety, she will not be pregnant
Go find your love a safe place to stay
Cause when I arrive into the city of angels
All cunts be mine, no doubt, I think
When I get signed my mom will be proud
I be the only one from fam to succeed
I'm gonna find a lot of relatives who never seen me
Pretending that my cash will ride out to them
Fuck you, my checks are mine, I'ma give some to mommy
For raising me to who I am
I'm hardcore, I fucking show no love
To homos, fucks and the pussy cunts
I'm a good kid into a badass city
Whose catchphrase is "What the Fuck?"
My creed gives me a rule of life
"No trust, boy, you have been fucked"
This rap game dirts everybody
Who stepped inside, there's no way out
I knew a rapper who wanted to retire
And went to church, he was dumb as fuck
5 years later he came back with desire
Ironi-cally he fucked his rapping up
I'll do it to death, it's my 25 to life
But I am proud, it's not my fault
Thank you, Em, Dre, Eazy for making me loud
Da Game Is to Be Sold, Not to Be Told, I'm about to go H·A·M

[Hook]
Hard as a motherfucker
Let these motherfuckers know just who I am
I'm about to go H·A·M
Hard as a motherfucker
Let these motherfuckers know just who I am