[Trademark Da Skydiver]

I think I'm Trademark, Da Skydiver
Locked in a cockpit like a jet fighter
I'm rollin super doobies, pass me my lighter
Smokin sour every hour
I can't get no higher

I said im Trademark, Da Skydiver
Locked in a cockpit like a jetfighter
Im rollin super doobies, pass me my lighter
Paper planes every hour
I can't get no higher

Let us do our thang
It's Jets over everythang
We got the shit on lock like cell blocks and sing sing
Fly kicks, heavy bling
Im married to the game
The money is the wedding ring
Call me peter parker im in love with mary jane
Super doobies on deck, pass me the flame
Niggas jumpin ship they bitchin up and switching lanes
You know who you are I don't have to say yo name
Cold captain of this jacking not aloud on this plane
So get it right, homie, we are not the same
I live that Jet life, you just livin lame
I get the cash and bash word to my nigga Dame
Im on bubble like 'caine over an open flame
Jet set in the building, fuck who else came
The shots fired from a silencer im taking aim
And rappers out like im at the shooting range
Im like a stack of hundreds, you just some loose change
I think im Clark Kent or maybe Bruce Wayne
Nah. more like Harvey Dent or Dr. Strange
T.M.S the S.V. who gon stop my reign?

[Curren$y]
I think Im Cheech, I think Im Chong
I got my Weed, I got my Bong
Livin in the fog
Don't know what goin on
But I dont give a fuck
Long as my money long
I think I'm doughboy on my front post
63' Impala in my driveway Saints gold
Sittin low, though im higher up
Diggies cup, crispy chucks, spittin tough
Nigga what?? yo' records stuck
Bitches don't listen to yo stuff
They with the jets, we in the cut
Settling for less that ain't for us
Suppress the hate in yo blood, makin
Ya'll lookin like girls
Poodles can't eat with the pits, bitch it's just a doggy dog world
Too clean to be fucked with
Supreme like a Cutlass
MC Hammer, you can't touch it
Better use some gloves or somethin'
Far too potent to be smoked with
Them holsters I dont know them
Snickelfrits them bitches, not official Jets bitches
Im just sittin cool whippin
Twistin green treat
Christmas too so many sweet wrappers up ima need a couple feelings
Im bout my roof pealin
No tornado took my ceiling
Its in the trunk shang monk Belly best, C-Note