[Intro]
Time flies when you're a piece of shit
Uh-huh, yeah
Uh-huh, yeah
Uh-huh, yeah

[Hook]
I'm a piece of shit
Don't trust me, I be talking shit
I might go 'head and fuck your bitch
And leave her like she ain't shit
I'm a piece of shit
Don't trust me, I be talking shit
I might go 'head and fuck your bitch
And leave her like she ain't shit

[Verse 1: Left Brain]
I'm from where the little shorties kick push crack
Your work is incomplete get your shit pushed back
We be walking 'round loud with the kush pack
Bottle of scotch, bottle of Stoltz
Boom, bye bye, in a batty boy head
We will not promote no nasty boy dem haffi dead
I'm cutting off legs, arms, arms, legs
And fuck what you heard and fuck what they said
Polo sport rugby, you niggas can't touch me
And if you niggas touch me you get smoked like a dutchy
You get smoked like a druggy
You get smoked like a '87 Volkwagen buggy
I leave you niggas bloody like a pussy on its period
Is you niggas serious, you got me delirious
I'm jumping off the top row, Rey Mysterious
I meant Rey Mysterio
Turn up the stereo
Smoking on this diesel got me feeling aerial
About to take flight
First class LAX to London one night, nigga fuck with me

[Verse 2: GoDreamer]
Jumping out the plane, snakes on it man
I had to go and get the *ah*, that cocaine
And it sound white, free Gucci Mane
I'm the king of the hill when it comes to propane
Yeah I light a fire, bad motherfucker
And go and start a riot, boom shaka-laka
And remember that all pigs don't come in their uniforms
So you gotta stick out, use your unicorn
And go blast on it, I'm running fast on it
Gotta get that cash on it, gotta make it last in this bitch
Now you niggas mad in this bitch
Don't give a fuck nigga
I'm a goose you better duck duck nigga
You thought you ran off with the swag, you stuck stuck nigga
All the hating alcohol got you lit
Cause in the back of your mind you think I'm a piece of shit
Really, nigga

[Hook]
I'm a piece of shit
Don't trust me, I be talking shit
I might go 'head and fuck your bitch
And leave her like she ain't shit
I'm a piece of shit
Don't trust me, I be talking shit
I might go 'head and fuck your bitch
And leave her like she ain't shit