[Produced by Context US]

[Verse 1]
You would have thought I was infatuated with being underrated
Instead of renowned, got me feeling like King David before the crown
I too have my views like you
Look what I do to stand on stages in front of crowds
I need food but I'd rather smoke a Black and Mild
Get back in the booth and spill my heart 'til I bust a valve
And that's the truth, hand over my left titty
I had faith in hip hop before she met Biggie
Just take this shit a day at a time
I thought I was on after Day in the Life
But you know our shit get put on hold after reality strikes
You ain't know I knew how to bowl
How you eat when there ain't even a bowl?
My stomach sound like something in the jungle
My mind saying give it up, the people saying don't go
It's easier to leave when you ain't got no dough
Cheap champagne wishes and thirty ratchet hoes
All up in my videos 'til you niggas see the vision (I ain't playing)
Guess a nigga never checked out detention
In my second childhood making music from the soul
Just so you know, crack a backwood
Fill it with that good and take a toke

[Break]
On and on and on and

[Verse 2]
They think me and these other rappers
Have something in common, God bless them, all men
I ain't stressing, I'm all in
They in Lois Lane, I'm Clark Kent
Go back to what's happening
Jay Rock finna drop and walk you all around Watts
Kendrick keep getting chased by cameramen
And for the first time, you've seen a Hoover Crip on the charts
As for me, I'm still an amateur
Venting, looking for the right Canon
To capture your attention, I need honorable mention
Most of all I need to exist in the fourth dimension
But niggas say I sing better than I rap
Who gives a crap about all them damn metaphors and diction? (Fuck that)
Took a step back to reevaluate my steez
Went to friendzone alone and wrote a gang of trees
Labels calling for everybody except for me
Like I ain't got the recipe, like this ain't my destiny
You know how much my family expect from me?
Especially considering I'm literally chasing a dream
Told G-packs, I'mma slip through the crack
Get that cream, that's a fact, yo
Whoever thought I'd get to write for Dr. Dre?
He probably thought it was trash and threw that shit away
But it's a new day, new possibilities
My time'll come sooner enough
No hostility, that type of shit'll slow you up
Don't get caught up in all of the marketing to show you up
He from Top Dawg? He more like a pup
He ain't from the streets, where the fuck he come from?
Who co-signing him, don't believe the hype
You niggas can't see me, can't call me on Skype
I'm all bite, no bark, a Benz to a Go-kart
All I do is go as hard as adult film co-stars
So on and so on, never lag, never that... you can't see? Look
They told me to break a leg, so now I'm an amputee
Give me fifty feet like G-Unit's sneaks
Soul brother number two times whoever you bring
Mothafucka, T.D.U.D