[Intro: Ab-Soul]
All my life
All my life

[Bridge: Ab-Soul]
I say all my life, all my life
All my life I knew I was tight
I say all my life, all my life
All my life I knew I was sick
I say all my life, all my life
All my life I knew I was ill
I say all my life, all my life
All my life I knew I was I'll be here

[Verse 1: Ab-Soul]
I'll be there, everywhere, tell the truth you wouldn't dare
Cross me like the gold you wear
Soulo flow like the solar flare in the open air
So much smoke that I'm comatose, but I still want mo'
TDE generals, she ain't spiritual, but she still on Soul
God bless, God body, no fear in nobody, no thing
Can I proceed? Collect all of my proceeds?
Don't I flow like I don't bleed? Every cut is just dumb
After me there will be none
I told you there is only one (Soul!)
Yeah, and I just might be in your hood
Causin' havoc with my bros, and it's still all to the good
Horse and carriage when I roll, it's over, hope it's overstood
I'm in Hollywood, ‘cause I remember when
I had 50 cent up in da club
All my life I knew I was major, I don't need no major
I don't even write rhymes
I really shouldn't have to sign paper to dominate the
Game y'all praise on hand and knee
Just waited 'til it came to me
I just kept it real with y'all, keepin' it real with me

[Hook: Ab-Soul and JMSN]
‘Cause I ain't got no fear, under the atmosphere
Tryin' to stay high, as long as we down here
Listen closely, see what we 'bout here
Who really 'bout that, you'll see when the smoke clears
‘Cause we really out here! (We really out here!)
We really out here! (We really out here!)
We really out here! (We really out here! Yeah, yeah, yeah!)

[Verse 2: Ab-Soul]
Uh, and it might not be such a bad idea
If I never went home again
Fuck on the same hoes again
Bumpin' "Druggies Wit Hoes Again" with my bros again
No, I want the world chico and everything in it
Every beverage with codeine in it
How the fuck you say I sold my spirit?
I'm still takin' blows at the Senate
Claims of Illuminati, I'm just tryna illuminate
Praise to the most high; God, Jah, Allah, Yahweh
Selassie eye, and I'm proud to say
I never need a 9 by my waist
Niggas still respect my gangster, celestials respect my space
And I just might be in your hood
Causin' havoc with my bros, and it's still all to the good
Horse and carriage when I roll, it's over, ho, it's overstood
I was overlooked, I went overboard, now I'm overbooked
Ab-Soul-Lute just, my life is like an open book
Read between the lines, nigga
I did this shit legally blind, nigga
Yeah, Soulo, ho, Carson arson with Del Amo
Tell your folks I said hello, I ain't never scared, ‘cause…

[Hook: Ab-Soul and JMSN]
‘Cause I ain't got no fear, under the atmosphere
Tryin' to stay high, as long as we down here
Listen closely, see what we 'bout here
Who really 'bout that, you'll see when the smoke clears
‘Cause we really out here! (We really out here!)
We really out here! (We really out here!)
We really out here! (We really out here! Yeah, yeah, yeah!)

[Bridge: Ab-Soul]
I say all my life, all my life
All my life I knew I was tight
I say all my life, all my life
All my life I knew I was sick
I say all my life, all my life
All my life I knew I was ill
I say all my life, all my life
All my life I knew I was I'll be here

[Break: Ab-Soul (Interview)]
These days, at this point in my life, I kinda really wanna use music to help people get through their days instead of just staying in the dumps, just keep going. Bring light to the situation. Maybe, you know, try to find your own personal message in that incident, that experience, and try to move forward…

[Battle Verse 1: Ab-Soul]
Y'all got me? Everything good? Y'all can hear me?
Before we start, let me just say this, let me just say this
I'm datin' you, Day… wait, wait, pause, no gay shit
What's the difference between a date and a day anyway, Day? A date is a day that's marked
I'm smart, and just ‘cause I know you love 'em so much
I came with name flips for days, tailored just for Day
I'm expecting Day to base his verse on data based on turds
My database said Day the basehead that date a basehead
Is he dope? No. Who gave Day the base?
Ball is what we do best
Flock his projects; that's a home run
Day, the baseball is what we do best
Carpe diem, that's how you say "seize the day" in French
I stand behind these bars for the rest of my life
I will never see the light of Day again
Now witnessing this rare occasion
I bear fruits of my labor, this Grape is green
I gotta eat on the go, Day
I hope they told you that everything that Soul say don't go a long way—don't go a long way, what?
A ho in Chipotle, no, this is food for thought
From a dog on top
We been nuts, there was a fool who thought we was new to this, but who knew this would end up
A glow stick in a uterus; that's Lyt in a box
And that's light, that's light
But Lyt like to lick twat a lot, so that's right
That's what y'all call street?
No tales from the Crip this evenin'
He slip, seems he forgot what the C meant
It's your dumbass' fault that last part was so concrete
But I guess you'd have to be kin to get that bar, b
Pardon me, I bet right about now
You feelin' like Jordan down in the Jordan Downs
In fact it's crazy that you even play ball
To clear your thoughts before raw backwards
And that's cool, but for this round, save the bull
Before you let the Jordan Downs and Jordan down
Now, as for the crew
Well, uhh, the villain been itchin' to skin a dog
And this nigga bought
What, a hundred and three dalmatians?
It's safe to say your mob of dots won't make it
And I'm a fan first, but it won't take too many seconds
To leave you in a damn urn
You deserve this disservice
I put this man in ER's if he don't got no manners
Man, word, I'm expectin'
Some etiquette in your segment, kid
I brought you to the 'Stu to show how we do
So all them antics and funny shit you do for the cameras don't get aired here, they can't see you
Wave your title to this tidal wave, we do
And you don't appear to be a peer to me
For real, you should kneel to me or somethin'
Fuck it, to keep it hundred, you're nil to me, that's nothin'
Heard they been raisin' raisins down on Grape Street
That's crazy, right? That's what happens when you expose them Grapes to too much Daylyt
So your chances of standin'
Much smaller than my plan to defeat you
Wait, what, do I gotta put it in photosynthesis or somethin', son? Shed some light on Day? 'Til he's cropped out
No, not now, I won't need a plant to defeat you
The sequel, this movie, won't need to be continued
You finally encountered somethin' you can't counter
Coward, you're counterfeit
You ain't gotta be in a Walgreen's pharmacy
To see Quill drug over the counter
After your mother consumed you
You were the fruit of the womb
After you were born, I'm sure you wore Fruit of the Loom
Now I'm tryna figure out, is you from Grape Street, Crip
Or just another fruit in this room?
It's crucial, you choose
I'm sure you don't want me to assume
I should be against the law to run into
‘Cause we all know in L.A. I'm double you
All so true, today is the day I split Day in two
What the fuck has battle rap turned Day into?
Are you from Gotham or from Watts?
Are you Batman, Spawn, or Devone?
Did you really think "Paul Walker" was a dope song?
If so, you were wrong
But hold on, I got one more, and don't lie to me
Do you really have a Batmobile outside, my G?
Don't be so transparent, this nigga Lyt through
If you don't know what transparent means
Let me enlighten you
If it's transparent, that means that it lets the light through
So I should smack this trans' parents for lettin' Lyt through
Like, the nerve of this cat
Lyin' with a motionless emotion, this nigga Day all bitch
Somebody get Quill a quilt before Quill get killed
Do Quill got skill at all, homie?
It was some Braveheart shit; all I heard was nah's, homie
Did you really expect to last, Day?
You know Revelations say that we livin' in the last days
I mean, I see you skimmed through Genesis and Timothy
But did you get to that page? You got gats?
You think your little arm'll get in the way of Armageddon?
Forget it, Day! No, really, forget this day
If I had a time machine, I'd go back in time to see
Just how many people would say yes to Day
Nobody, fam, nobody, fam, that's why I'm ahead to Day
No, no body, fam, that's why I'm a head today
No, nobody fam, that's why I'm ahead of Day
Somebody check the clock, I think I'm ahead a day
Send him to the choppin' block, off with the head of Day
It's only right I be blunt to Lyt
I only gave Lyt a match to light a blunt
I see I should have used the lighter instead
Chill, Loc, we ain't smokin' no purple
We need the fire instead
When I think of daylight, I think of shit like… breakfast, morning, birds singin', kids playin'—see where I'm goin'?
That means you better break fast
Or I'll have your family mourning'
When that bird sings, kid, I ain't playin' and you know it
But you know what? Hold on, hold on
Let me get you right, we have this shit
Take this 500 before you clap this shit up
Say this, let me say this, let me just say this
These flashin' lights got Lyt flashin', nigga, for the glory
Your buzz lightyears from here
Quill, and you tellin' toy stories
You boys bore me, that's why I'm hoggin' all lanes
All your bars Häagen-Dazs, that's on everything
Day a dairy queen, Deluxe; bless, King!
Dearly beloved, all first verse, all first verse
You know I brought a hearst
For the sausage you brought worst
Dearly beloved, here lies this little light of mine
That tried to let it shine
And I hate that we have to hear lies
From this little light of mine that tried to let it shine
But I'm ill, you men ate when I finished Lyt
You get it, Lyt? That's how you ILL-u-min-ate
And finish Lyt, good night
Hold on, hold on, hold on
Let me get you right, you got that for me?
Brought you some complimentary TDE ski masks

[Battle Verse 2: Daylyt]
Question, you know how many copies The Matrix sold?
It don't matter, The Matrix's old
I double cats, I ask 'em if they seen the glitch
No, no, no, face it, I got it covered
Prevail, they say the sail was a thread to hell
The gravitational stitch, ‘cause some niggas seem down
They come up with this perfectly clean round
But I hope you not doin' this cause of fear
Of the pen, I'ma prove you pussy within
But I guess it's up to you to risk your career
I retire niggas, I'm the slow leak crew
I could OD too, and even the odds some
He thought he could least get a baby victory
But all he got was "Nah, son."
Check this out, he not ready
Either you fight back or I Ether you
Thought you could face what I hand you
Well, this is isn't peek-a-boo
Soon as I took a peek at you, you looked shocked
Peep it, you put everything at stake
Well done, this is beef, right?
Jesus, holy cow, cut the bull, Soul, before you get meatsliced
I'm from the third, I gotta try you
Guy, you play Ryu, lose a ken in a street fight
Nice slow guidance with both sirens
You still couldn't see Lyt
Division, I got it covered, I'm so eye lit
Pilot, fly, I be the goblin; we battle for a stack
In fact they had to get a cataract, ‘cause I be the problem
But it's useless, use less filler, excuse the excuses
But, but, but… these asscheek niggas dead
You said you would fry Day previously
But that's what the last weak nigga said
But, but, but keep cool, Joe, ‘cause dog crazy
Get down, we turn niggas vegetable if they don't let us up
He know the heat blowers like Daffy at the casino
Nigga, you better duck
But I tell them tails we never tuck, we gon' line that ass up
I from the Watts block for decision
My profession is stompin' squares the fuck out
We played hopscotch for a livin'
But that's def, that's just plain old def
It's funny how we're all in here but bro don't listen
Have a seat, picture this
Picture this photo, this a Soulo, is it?
Hold up, is it because he 'bout to get smoked?
Common roll the physics, so exquisite
Thought I was in here dolo
No, bro, somebody tell Soulo this not a solo mission
The deal closed, SoHo is it
Thought you could fuck with me, gal? I gotta Cotto-split him
Look at your girl dead in her eyes
And say "Fuck Dorothy, dog!"; I'm toto dissin'
But at this moment, everybody in the room should be scared as hell, as I release bars, they better bail
Objects that I process is parallel
Let's get this aligned, minus sinus
The stuff he knows flew overhead, it's cold, redemption
Stay still, as I apply DayQuil, ‘cause you look like you need medical attention, don't mind me
See where mind be is a mine, explosive, interior is inferior
This is a hobby probly, y'all see I got the drop on everybody
That's why I reign superior
Whether you like or not, it's Hell for you, ice plate
These blister niggas still can't overshadow a nice Day
Remember, you did say you would fry Day?
But you don't realize you're on the weak end to the streets
Preacher for they peeps, you asshole
You in the motion to grab toes, you're reachin' for defeat
I tell 'em I got the four in
Cut the sheep, it's all for the woolish
Game I play is death, get sword for the hoodish
Actin', it's Tinactin, it's all for the footage
I'm dope, I'm practical, crack to you
I need a lot of space; the galactic crew, the actors knew
You feel it it's Felix, see what the old cat could do
But you got the roots stirred up, gelatin dropped and slide
This game is stormchasin'
Based on whether you got the drive
Win rounds, destroy their whole city—will they get tore?
Nay, do you realize I still got a break, brother?
When I quake in action, think of blanket jackin'; take cover
That's lightwork, Soul
Cut your lights switch, see how the light works, Soul
I cut the light switch off and your light switch off, Soul
Somebody get this nigga help! I mean, like, Soul, assist him
Get him help, I'm sendin' this nigga out the solar system
I mean, it's simple, Aretha Franklin; you a Soul, sister
That's enough, man, I'ma have to throw one of these masks on, man, should I finish him off?
And I told you once, I gotta give 'em the Quill
And I gotta give 'em the skill
I be on my tip, like I tried to give him the bill
New approach, Bull coach; I tried to give 'em the feel
For Watts, starvin', gotta get us a meal
Bein' modest, this is modern astrology for the real
You can't back up defeat, but I try to get up the hill
Cold, rack up the heat, but I'm tired of niggas that grill
Chicago in my blood, but I used to be the shyest
Cat form, but now I'm back searchin' for the highest
Platform, see where I come from? It was sirens, blackboards
Eyelids see the violence, what is that for?
.44 shoot, they screamin', "Who's that guy?!"
Jesus, his face, they screamin', "Who's that?! God!"
We be on the top, careers gettin' too high
They knew I would get a million dollars, what I do buy
That pink kid in the cup, that Majin Buu fly
Tragic, twin maggots; I grew up too fly
They askin', "Who I?" in front of that triangle black
That's that guy that come with the side kangol hat
We take it back from slangin' packs to the stars mission
Older now, I'm in the Rover, but it's not a Mars mission
Settle down, one child, merry; feel like I'm Marge pimpin'
Bitches wanna eat my shorts; feel like I'm Bart Simpson
I feel this a full moon, chocolate, dreams puddin'
They be likin' everything I do, they're teen wolfin'
But you got it, you got it bad
2Pac, don't watch the world sad, come back
Two watches, that's pocket change
Dude coppin' that clock exchange
Credit good, I'ma pull the card out
Better be hyesterectomy, show 'em how to ball out
Cough, they can show that they're stomach so they fall out
Whip, double roof, dog barkin' in the dog house
And I gotta give 'em the light
My people in the struggle, I gotta give 'em a fight
Ain't no equal piece of puzzle, hope God'll give us the mic
Ain't no sequel to this puzzle, I gotta give us the life
Wow, they say the Bugatti went up in price
Wow, that's a million, I'm done

[Outro]
Ces jours-ci, je suis très concentré