[Ab-Soul]
More than a man, I had died and rose again, yeah
Fast life, slow motion
These days

[Jackson Browne]
Well I've been out walking
I don't do that much talking These Days

[Ab-Soul]
I gotta stop smoking cigarettes

[Jackson Browne]
These Days
These Days I seem to think a lot
About the things that I forgot to do for you
And all the times I had the chance to

[Ab-Soul]
Yo, how the fuck my new girl got me jealous of other girls
I think I live in another world

[Jackson Browne]
And I had a lover
But it's so hard to risk another
These Days

[Ab-Soul]
These Days

[Jackson Browne]
These Days

[Ab-Soul]
Yo, he wrote this shit when he was 16 he said
I'm 27, this is like my whole life
This -

[Jackson Browne]
Now if I seem to be afraid
To live the life that I have made in song

[Ab-Soul]
You know all I like to do is keep it real
Soulo - Ho

[Jackson Browne]
Well it's just that I have been losing

[Ab-Soul]
Can I win one time

[Jackson Browne]
So long

[Ab-Soul]
Yeah, its that pain you was talking about
Can I win one time?

[Verse 1: Ab-Soul ]
So many pills I should have slipped already
My lungs the same color as my lips already
Expensive clothes and sufficient funds
Me and my bros switching hoes just for fun
The money and bitches is all we care about
Very far from home if you worried about my whereabouts
Chasing the light at the end of the fucking tunnel
Pray for Sydney, send Tia a text, tell her I love you
The devil is a lie, never let him persevere
God took my angel, and left me here
It's heavy here

[Jackson Browne]
Well I will keep on moving, moving on
Things are bound to be improving These Days

[Ab-Soul]
It's long term, this shit real

[Jackson Browne]
I love These Days

[Ab-Soul]
It will all make sense one day my nigga
I even been on songs with Common
It's crazy

[Jackson Browne]
These Days I'll sit on corner stones

[Ab-Soul]
Can't stop me my nigga, yeah

[Jackson Browne]
And count the time in quarter tones to ten, my friend
Don't confront me with my failures

[Ab-Soul]
Can't achieve success without failure baby

[Jackson Browne]
I have not forgotten them

[Verse 2: Ab-Soul ]
Digging for gold in these Codeine bottles
Trying to picture potential in these Instagram models
Like, information racing around the internet
Before the iPad was invented, I had a pad of writtens
Smoking a cig on the side of the house trying to figure it out
The axe didn't cut it, moms told me cut it out
Clem told me always take pride in my work
I clutch the mic with blessed hands at all my concerts
Why his name Soulo? How is he so smart?
We can see his four footprints in the sand when he walk
I like to refer to myself in third person from the third person
Thats a out-of-body experience of self
So I can see me for me and no one else
Don't need to see a Emmy, award or no jail
I'm at them like a cell, I just want to be free
All this chatter from the chattel nigga
I don't speak sheep
This TDE and nothing beyond that
Told Du Dog I don't even need to read the contract
As if some legal documents can stop me
Legalize, legal lies, legal eyes so I see
I did it while you were sitting wishing
Ask my nigga DZA
All my verses hearses leaving churches
Not the cheap chicken
And I love the Beast Coast
But what about the best one
What's your life without a soul?
A dead one

Yeah Mac, you ain't got bars like that Mac