Pt. I: Wifey vs. WiFi

[Intro: Ab-Soul]
Man, I hate quotin' Jay Z, but cuz just too tight
Is he a Blood? Is he Crip? Is he that? Is he this?
Will he do it? You know, it!
Now every time I say "it" it's in reference to my dick
You can suck it if you want to
Every time I say "it" it's in reference to my dick
And you can suck it, motherfuckin' bitch!

[Verse 1: Ab-Soul]
Listen, bitch!
When it's in you the sentiment is incredible
Winter fresh even, I even undress your winter clothes
When it's out, instead of worryin' about where it's at
You'd rather rack your cap
About where it's goin' or where it's been
Where are we goin'? I'm beginning to see an end
Don't bring Larry King in this
Sniff the evidence on my clothes and go through my cell phone
And now I'm in jail for leavin' out a few details, oh well

[Chorus: Ab-Soul]
It's wifey or WiFi (Ayy!)
Wifey or WiFi (Ayy!) wifey or WiFi
Got some niggas in the pen that really gotta face time
She just bitching ‘cause I missed her FaceTime
It's wifey or WiFi (Ayy!)
Wifey or WiFi (Ayy!) wifey or WiFi
Got some niggas really havin' issues in the cell
She just bitching ‘cause them other bitches in my cell

[Post-Chorus: Ab-Soul]
Oh well, oh well
I guess she wanna go to war then
I guess we should warn the warden
Oh well, oh well

[Bridge: Ab-Soul]
Alright, I want you to tweet me right now
If you're using your third iPhone
It's wifey or WiFi, wifey or WiFi
Wifey or WiFi, hey, hey
It's wifey or WiFi, wifey or WiFi
Wifey or WiFi, oh well, oh well
Oh well, oh well
Oh, I hit you with the hash back

[Verse 2: Ab-Soul]
Ayy, my nigga lil' Riley got into it with his mommy
They be fightin' all the time, so I ain't pay it no mind
He said: "God, she could really be the Devil," I said "Chill!"
He smacked his teeth
And shook his head and said "No, for real!
You know I love her, but she could really be a pain in the ass
Matter fact, fuck that! Pull out your jack real fast!
Real shit, my nigga, now glance at the keypad
This that mind-bogglin' shit you like to throw in your raps
And this might be your best yet; notice how every number
Represents three letters of the alphabet
Like, 2 is A-B-C, 3 is D-E-F
4 is G-H-I," I said: "I get it, alright!"
He said: "Now trip off this, listen to me, Soul
I know you off the shits, but I'ma need you to get a grip."
I said: "Be serious," he said "Dial M-O-M."
What a hella coincidence! It was 6-6-

Pt. II:  P.M.S

[Chorus: BR3]
All because of this penitentiary mind state, is it my fate?
For God's sakes, why did I have to lose the case?
I kept it real, and I ain't never been fake
I'm feelin' like Biggie when he lost Faith
See, this penitentiary mind state, is it my fate?
For God's sakes, why did I have to lose the case?
I kept it real, and I ain't never been fake
I'm feelin' like Biggie when he lost Faith

[Verse 3: BR3]
Look, there's sixty seconds left, I'ma have to get back later
Your boy chasin' this penitentiary paper
Tell my momma stay on point
Your phone hit her on three-way
Then, fuck it, I'ma hit her on that other joint
First term, nigga, but I did it like a vet
Hung up the phone, and when I asked: "Who had next?"
It was one of the lifers, all nest with no neck
Gotta stay with my striker, no nigga is no threat
I swipe my knife on the under
But I can still hear it in my head
When he said: "That's right, youngster
Just stay focused, sleep with your hands open
Beat 'em with a long-handled spoon
When you deal with smokers."
I sag low when I walk the yard, hold my head high
Yaddada to them Bay niggas; me, I'm from the Westside
Lookin' for a gram to steal, ‘cause I'm tryin' to get high
Thinkin' about my fake-ass bitch on the outside
Out of sight, out of mind, shit, I don't mind
Long as a nigga make the paper when he doin' time
Right, look… fuck it, I'm lyin', I'm just really tryin' to hold out
Thought of some trick runnin' dick in my bitch mouth

[Chorus: BR3]
My penitentiary mind state, is it my fate?
For God's sakes, why did I have to lose the case?
I kept it real, and I ain't never been fake
I'm feelin' like Biggie when he lost Faith
Look, look, hold up, hold up!