[Intro\Hook]
Don't you act up, 'cuz you ain't crazy
Niggas in the hood like, fuck you pay me
We grind daily, through the background
Suckas talking tough, 'till somebody got shot down

[Verse 1 - Johaz]
Top of the world, top of the pile
Become one with the universe on top of the clouds
Niggas talking like they king, we 'gon stomp on their crown
Is there a doctor in the house, 'cuz its an officer down
Jeweler the (?), gotta get cash
Get my hands up on this paper, 'fore the economy crash
Oh you a thug life actor with a sodomy past
Making rappers think (?) in a (?) bag
Savage the land, damage the surface i mean
Beheading these devils, and battling serpents it seems
You cry in the night, but nobody hears 'ya screams
You're reaching for God, but devils done cursed your dreams
You feel the pain like an Advil, and wipe the blood of your hands, and then your mans kill

[Bridge]
And right before you say goodnight, i pray that he has mercy on your soul

[Hook x2]

[Verse 2 - M.E.D]
Dollar bill, drug dealer, slums, hate build here
Big gum, thrust your four-wheelers in the windmills
Miller beer cheers, and the veal only fears jail-
And late bills, oh, (?) finger nail
Hair done, check from the county should of been here
Attitude- just write it from my living room view
Music's like a therapy group, troubled youth
(?) conspiracies, and audio boost
Move crowd with a (?)
Cash rules, who think not-
Pop screws loose in your (?)
Ox the city, not the bebe shot
If any problems, I poke 'em like, (?)
Cost ya my honesty, but they know
He just a remix in the same song, play slow
Oh, yea
Before you go-

[Bridge]

[Hook x2]

[Verse 3 - Rass Kass]
Niggas coming at me sideways just to rap on their beat
But they ain't holla at the kid when i was flat on the street
No tip, no whips, I was trapping in heat
But got the nerve to get mad 'cuz i ain't rapping for free?
Now- you on some (?) shit, tryna guilt me on some
"We can bring the west back" shit
But i remember you, got Hollywood as fuck
Popping bottles in the club, and way too good to say "Whadup?"
Yo, so i left it at that
And i ain't never been a hater I was thinking congrats
But if a nigga want beef, homie speak with the gat
Dangerous , sign language leave you leaking your (?)
Fuck eating with rats, and snakes I'm speaking the facts
I'm like black lumber jacks, the way i creep with the axe
On Exile tracks

[Bridge]

[Hook x2]