(Hook: Lil Wyte)

M.E.M.P.H.I.S I've held it down I run this town
M.E.M.P.H.I.S Thumbs up till I hit the ground
M.E.M.P.H.I.S my city is cold blooded homie
M.E.M.P.H.I.S watch your own homies, homie (2X)

(Verse 1: Lil Wyte)

Yeah Yeah

Welcome to Memphis, Tennessee I am the white man that runs this ho
If I could give you a tourist tip I hope you brought a gun in this ho
Not a too much money though a little bit of dough
Don't ride too clean don't put on no show
If you got a bad bitch better leave her at home
Cause a Memphen gonna take what it wants
If that means your car, or even your wife
Better watch A&E these first 48 boys will take your life first 48 boys will take your life
Maybe its something in the water that makes us lose our marbles
Then we hit Bill Street, Wet Willie's and loose em even farther
We got no sense but stack dollars uneducated we get brain from scholars
I was lucky and I had my father grew up in Fraiser and wasn't bothered
You know what my fucking name is I ain't saying in this rap
I'm the only motherfucking white boy in the city to even stand up and speak of it
And put it on the damn map its true

(Hook)

(Verse 2: Miscellaneous)

Yeah

They say my city filled with young dropouts
Ridin around with they Glocks out
That tough shit get your ass knocked out
Glock in your mouth watch your whole brain pop out
From the side of town where they banging, nigga
Mob shit where they claiming, nigga
AKs what they aiming, nigga
Even bitches got nuts and they hanging, nigga
From the side of town where they known to hate
But that known hate only motivate my whole city made first 48
From South Memphis back to the bay
Orange mound they lay you down
Gun ya down for a half a pound
Them Jack Boys they riding round do the same thing in any fucking town
Ain't no peace in these streets I know real Bs out in the east
GDs in Pelpatri, Tulane and BHZ
Miscellaneous ain't scared B back on the fed shit
It's the rapping Leslie Ballin just got signed to the rapping Fred Smith
Yeah, bitch!

(Hook)

(Verse 3: Al Kapone)

Yeah, its Al Kapone

M.E.M.P.H.T.N. yeah bitch its me again
I tried to walk away from rap but fuck it I got my second wind
God Father status yeah my city built a savage out here
I help created this Memphis shit ain't no way you can have it
Yeah I'm raging rage war on all you fucking cockroaches
Gives us our fucking props we was first and all you bitches know it
Al Kapizzy yeah that's me, Mississippi, Tennessee
Arkansas they riding with us that's that holy Trinity
I almost said the hell with this now I feel the love again
Rejuvenated motivated riding till the fucking end
Yeah I'm rapping with a bands
Sometimes a symphony I said it on Lyrical Drive by
Ain't too many that can fuck with me

(Hook)