[Intro: Tech N9ne]
No, you ain't supposed to put on your devil suit
When you come up in the church, young mayne, hehehehehe
Now they ain't about to think you a rebel
You 'bout to make them think you birthed from flames
La la la-di-da-da
Wanna be on TV just to show out for mi mama
But breakin' into colored houses, admit
That it's a bitch when you sick like this

[Verse 1: Tech N9ne]
Puttin' all the face paint I can put on
Put my black jeans and black hood on
That's your TV I just stood on
With a faded habit this brother swerves when I sip vodka
I'm the latest rabbit; in other words, I'm a hip hopper
You disc jockers never played me, you said my shit stopped ya
2001, I mixed opera now every clique's got the
Sick caca with lots of rippin' about they chips, oughta
Listen to this quick chopper flippin' and poppin'
With the spirit of Pac and Big Poppa!
Ya! This for your motherfuckin' rap quotes
My shit is surprising and shocking like Barack votes
The traps broke when I rapped with Tunechi and Stacks though
OG Muggs said I'm gonna be the first rapper to cross over to black folk

[Pre-Hook: Tech N9ne]
Yah, I'm breakin' into colored houses
Polo boots and hella dark-colored outfits
Yah, I'm breakin' into colored houses
Fellas better put a chastity belt on your spouses

[Hook: T-Pain]
Hey!
Man, it must suck to be you niggas cause it don't suck to be this rich
If you not fuckin' with me, brethren, you can suck upon this dick
Man I just get it how we get it where I live
Somebody better call 911 (call 911) I'm breakin' in these niggas' cribs
Yeah, we out here workin'
One thing for sure, two things for certain
I'm for real, that's how I live
Somebody better call 911 (call 911) I'm breakin' in these niggas cribs

[Verse 2: Tech N9ne]
Since 2001 my people dodged me like Durango
Now at my shows I see more N-words than Django
(From Missouri) like Nelly, Chingy, and Chain Hang Low
But Kansas City somewhere over the rainbow
I'm in yo' house baby, I'm in yo' living room
Lookin' down yo' blouse lady, and everybody is in tune
To Tech Nina, sex fiend a threat to his and whom
They got a beautiful woman and givin' poon
They want it cause I'm 'bout to be big and BOOM!!
Breakin' into colored houses is hard, mayne
Cause everybody got (guards)
And they got (dogs) and they got bars mane
But I'm comin' through that TV
And all the ghetto is gon' see me
Sippin' the KC Tea
Now you know Tech N9ne now everybody want a freebie!

[Pre-Hook: Tech N9ne]
Damn, I'm breakin' into colored houses
Polo boots and hella dark-colored outfits
Yah, I'm breakin' into colored houses
Fellas better put a chastity belt on your spouses

[Hook: T-Pain]
Hey!
Man, it must suck to be you niggas cause it don't suck to be this rich
If you not fuckin' with me, brethren, you can suck upon this dick
Man I just get it how we get it where I live
Somebody better call 911 (call 911) I'm breakin' in these niggas' cribs
Yeah, we out here workin'
One thing for sure, two things for certain
I'm for real, that's how I live
Somebody better call 911 (call 911) I'm breakin' in these niggas cribs

[Verse 3: Tech N9ne]
My people missin' me, like Diana Ross
No this ain't MMG, but I am a boss
Although I'm wicked see, I'm fly and I floss
So why am I lost? Like my jam is off?
Yes you a day late, better late than never, I'm a veteran
My cheddar been truly silly like Stevie J face (haha)
Every last one of these evil haters they see me vacate
Dip to the crib, turn on the television and see my face like, "Hey, wait..."

[Hook: T-Pain]
Hey!
Man, it must suck to be you niggas cause it don't suck to be this rich
If you not fuckin' with me, brethren, you can suck upon this dick
Man I just get it how we get it where I live
Somebody better call 911 (call 911) I'm breakin' in these niggas' cribs
Yeah, we out here workin'
One thing for sure, two things for certain
I'm for real, that's how I live
Somebody better call 911 (call 911) I'm breakin' in these niggas cribs