[Verse 1]
I was down on my luck, out of my bucks
Growlin' my gut while in a rut
How I was smilin' when falice was callin' on uh
I was proud and I bust loud and enough to rally them up
My style as a child it was roudy and ruff
Such as life, when the dope ain't sellin'
The soap ain't smellin'
Ripe dough ain't swellin', no hope but nope I ain't failing tonight
And entered a contest with nothin' in my palm just
A microphone and god next to Tech to bless and I'm set
I won, the people voted for me to take the pay
Was fate the way it happened the show fell on
My graduation day, so I chose the show
To go open for EPMD and Gaume that's how it was suppose to go
I didn't know that I was chosen never
Expected it but these people saw while the other
Haters rejected it, I tore through the hardest part
Of this art when most neglected it, I poured out
My soul on to the paper and you accepted it

[Hook]
You are my heart, you are my soul
I thank you for all you done for me
You are my art, you are my flow
My fans made it for everyone to see
You are my heart, you are my soul
I thank you for all you done for me
You are my art, you are my flow
My fans made it for everyone to see
(Forever Accepting N9ne's Soul)

[Verse 2]
In Kansas City, a lot of fans is with me
Started doing shows with crazy flows and it expanded quickly
Tech Nina's band of hippies ran the shit we handed strictly
I landed scripts that damaged emcees, ripped these calamitously
And I ain't have nothin', not a cent to my name, man
I just had bussin' I just vent through my brain
When I went through the rain, y'all invented my lane
Cause you went to the strange events to see strength in my pain
You saved my life, damn, you made my life, grand
I love these times with you all even though it made my wife
Scram cause all the time I spent I grind for thine and
Rhyme again I sign your skin and bind a friend tonight different kinds of kin
Technicians, Juggalos, Juggalettes, Kottonmouth Kings, and Queens
Gangbangers, College Kids, Metal Heads they all seen the dream
Of me being the King this almost brings a string
Of tears meaning I sing to all of you that's been on my team

[Hook]

[Verse 3]
You took me over seas to Germany and Sweden
Australia, Switzerland, Amsterdam, and Paris I'm seeing
Fans in red clothes in Norway and Spain in Monaco
We honor those that rep the strange lane
Couldn't ask for a better life or better fam, yeah
My fans they set us right so they get a jam and
All of my heart and soul and confusion ready to start
The pollution bring my art from allusion to me rulin'
And I will never let you down, I swear to you
Industry be aware the clown is up in here to scare a few
And stare at you with a glare that shoos the square that's not aware of Tech
And caribou but all hail the fans up forever there for you
I didn't know that I was chosen never
Expected it but these people saw while the other
Haters rejected it, I tore through the hardest part
Of this art when most neglected it, I poured out
My soul on to the paper and you accepted it

[Hook]