[Intro: Brother KT]
Praise God, my brother, forgive me father right now
As I'm asking great blessings in favor right now
For this man of God, Lord, you know the direction that your taking his life
Holy spirit Lord and you have a covering over his life
Continue to bless him, Lord, let him know that his best is yet to come
And Lord, let him know when the wickedness of his enemies try to destroy him
To bring him down, all he has to do is just call on you
Now Lord, come bring favor into his life, favor into his music Lord
Let him know that his best is yet to come
As long as he can continue to put you first

[Verse 1: Tech N9ne]
Drama, used to be my middle name, with ecstasy
Sex and technically set me for a little fame, it gets to me
When the people I used to know switch and change, regretfully
I'm gonna say I don't wanna see none of them again, they stressing me
When they think cause of my absence I'm playing games
When really I just work in strain to let everybody else feel my pain
And respectfully I gotta say buzz off you and Tech Nina's thangs in jeopardy
Cause I need angels around me, that's your claim, but you'll never be
Strange Lane I feel this deep in my veins like Leprosy
You attacking my nerves and mess with my brain, it's vexing me
Ain't a angel inside you distrusting vain is your recipe
To complain is necessity, you're to blame so I reckon we
No longer straight that's why I never came when you beckoned me
I need peace in my life, but with you need gangs and weaponry
I'm too busy to have these lousy lames come question me
Man I really do need more angels blessing me

[Hook: Irv Da Phenom]
You see we've all done our dirt
God knows that I have
And I know I can't take that back
But I can say today I'm makin' a change
I'mma leave the drama in my past
So if you tryin' to bring me down
Don't you ever come around
I got no space in my life for negative, I said I need
I need more angels around me

[Verse 2: Tech N9ne]
Need somebody to bring me a brighter day
Not somebody that when I see 'em comin' I gotta hide away
Like these losers leavin' messages ain't gon' try to say
I went Hollywood when I don't answer so you know I push delete right away
I need the drama gone like I'm at my mama home
Your persona's piranha beyond the haters trauma, holmes
So if you wanna get on us you get the llama chrome
I know that you hear me even though I'm speaking mono tone
That's to the demons who's callin' leaving me death threats
Been a couple of years and my spirit ain't even left yet
Yellin' 'bout when I come to your town I'm liable to get wet
Tech said maybe angels but dump you can bet that
We don't need evil seeds making us get dummy
Wanna breathe the weight of succeed, get from me
Devil breed ain't no need for we to get chummy
Deny your creed and proceed to get money


[Hook: Irv Da Phenom]
You see we've all done our dirt
God knows that I have
And I know I can't take that back
But I can say today I'm makin' a change
I'mma leave the drama in my past
So if you tryin' to bring me down
Don't you ever come around
I got no space in my life for negative, I said I need
I need more angels around me

[Verse 3: Tech N9ne]
Need sun rays, not a dark cloud
That's why they still lookin' for me like, "Where art thou?"
Oh brother, they so cluddered and hearts' foul
Ain't never returned they call and they 'bout to start now
Need angel wings, not gargoyles
You bring that beef to me get ready to get charbroiled
I treated them so nice in the past these people are spoiled
Reject them demons and get them all off of our soil
And when the smoke clears in your retina
Who cleaned it up? You gots to give it up to slegna
The black boots and red strings come to bless ya
Let's ya mesh mess and threds bash your ex-o
Dus, yes that's us but my angle
Is to break news to these webs that's so tangled
Such a shame, your name remains painful so change your games
Cause we were stained but became angels


[Hook: Irv Da Phenom]
You see we've all done our dirt
God knows that I have
And I know I can't take that back
But I can say today I'm makin' a change
I'mma leave the drama in my past
So if you tryin' to bring me down
Don't you ever come around
I got no space in my life for negative, I said I need
I need more angels around me

[Outro: Brother KT]
Now, Lord guide and keep him
Lord give him strength and favor
And Jesus end my prayer, amen
My brother I love you, stay encoraged man
And just know what God has for you Tech, is for you
Can always count on me, alright?
Much love from Brother KT