[Blaq Poet]
Five in the morning, I'm just yawning
One time banging on the door with the warrant
I got the gat, I got some cracks about four floors up
Something in my mind saying, "No Po', don't jump"
I can already see me broke up in them cuffs
Police be laughing as they eat their donuts
I rather shoot it out with them niggas like "what"
Front page daily news, "Black Nigga Goes Nuts"
But they ain't even trying to raid the crib
I think it's a warrant for some bullshit I did
So I ignored them niggas
Light up a blunt, read The Source, I'm on tour with niggas, fuck it
I do what I do, about an hour go passed
I creep through the peephole, I still see the brass
Looked under the door, an eye looking at me
Then I hear a voice "Yeah, he's in there, chief"
What a fucked up situation
They're waiting like I'm a terrorist nation
Damn, I go to the window, I see the blue van
Cell phone ring, pick it up, "Hoo han"
"Yo they're running 'round with pictures
And they're scooping niggas up, I hope they don't get you"
"Say word, they're banging on my door right now"
"Just don't open it; they can't knock it down"
"Alright yo, yo where the fuck you at?"
"I'll call you when I see you nigga, don't call back"
Click
Ah shit, niggas is shooked
They're handing out secret indictments on all crooks
Hell no, I ain't going outside
Spend the whole day playing Madden Live, fuck that
They're locking niggas up
All the hoes and the fiends, all my thuns throwing things
I just got to play it smooth
Soon as they bounce, make my move
Tick, tock, tick, tock
Time to call the cab, tell them meet me by the block
The coast is clear, I thought it was cool
I see niggas lined up, kids coming from school
Niggas getting stripsearched
On the hill, on the ave, on the corner by the church
The hood is on fire
It's like the scene from The Wire, got my balls in the pliers
Every few years, the boys come around
They call themselves "trying to clean up the whole town"
But they don't understand the struggle
How to live in the jungle and stay out of trouble
Niggas overcrowding the system
Sent up for years, their family missed them
And the fiends still smoking that shit
From a new nigga coming up playing the strip
S.O.S., the same old shit
The block is hot, got rocks to chop nigga
S.O.S., the same old shit
Niggas pumping, gats busting, always into something
S.O.S., the same old shit
Tryna rock the spot, you better watch who cop nigga