[Intro: Jake La Furia & Gué Pequeno, Gué Pequeno, Jake La Furia]
D.O.G.O
Dance Dance Dance
Portami dove ballano la dance

[Strofa 1: Jake La Furia]
Imbottigliato in circonvalla sulla Seat Ibiza
Penso a voi che state a galla, che siete a Ibiza
Per il cachet da miliardario come Erick Morillo
Mi resta il mega-miliardario al bar Murillo
Nel mio quartiere non vanno a Ibiza davvero
Hanno l'impianto del pascià nella jeep di Carmelo
In testa cassa dritta dai tempi di Carbonero
Gli piace il mondo rap ma pensano che c'è poco pelo
Io voglio andare dove ballano la dance
Coi cachet della dance, e le tipe con gli Hot pants
Ricordo in disco quattro piste con le cubiste
Mo già da fuori per le liste ci sono gli hipster
Quando finisco i concerti sono tutto sudato
Voglio svoltare le serate solo col serato
Voglio viaggiare in prima classe tutto spesato
Da questa parte del mondo e dall'altro lato

[Ritornello: Don Joe]
Voglio andare dove ballano la dance
Con i DJ della dance
E le tipe della dance, dance, dance
Voglio andare dove suonano la dance
Nelle disco della dance
Con i soldi della dance, dance, dance

[Bridge: Jake La Furia & Gué Pequeno]
Io voglio andare dove ballano la dance
Coi cachet della dance
E le tipe con gli Hot pants
Io voglio andare dove ballano la dance
Coi cachet della dance
E le tipe con gli Hot pants

[Strofa 2: Gué Pequeno]
Io voglio andare dove ballano la dance
Sex, Love, Mercedes-Benz
E svegliarmi sulla spiaggia di Cancun
Senza bum, bum cha, solo tunz, tunz, tunz
Fare tanto grano come Tiësto
Senza la giornalista che mi stressa per il testo
La cassa dritta, frà, ha sempre ragione
E invece che in Italia vado in tour in Giappone
Io voglio andare dove ballano la dance
Coi cachet della dance e le tipe con gli Hot pants
D.O.G.O. nel business yo, la gente fa: "Ooh"
Io faccio "Yes, yes yo!"
Voglio stare alla console che sul palco
Salto da una parte all'altra e rischio l'infarto
Il DJ pompa non c'è niente da capire
Sai che sbatti, per me, scrivere 'ste rime

[Ritornello: Don Joe]
Voglio andare dove ballano la dance
Con i DJ della dance
E le tipe della dance, dance, dance
Voglio andare dove suonano la dance
Nelle disco della dance
Con i soldi della dance, dance, dance

[Bridge: Jake La Furia & Gué Pequeno]
Uh, uh devi farmi entrare dal retro
DJ manda questo disco indietro
Uh, uh devi farmi entrare dal retro
Don manda questo disco indietro

[Ritornello: Don Joe]
Voglio andare dove ballano la dance
Con i DJ della dance
E le tipe della dance, dance, dance
Voglio andare dove suonano la dance
Nelle disco della dance
Con i soldi della dance, dance, dance