[Intro: Kato]
I just got my G.E.D
So there ain't shit you can say to me
(x3)

Yeah, Kato
Jarren, Benton
4, Ize
Waddup?
You ever try to suck your own dick?
That shit never works do it?
I just got my G.E.D. nigga!
Finna style on these niggas

[Verse 1: Jarren Benton]
Every day I wake up (yawn)
Tryna get this cake up
Smack a bitch so hard, I knock off all her make-up
Stomach rumbling, fucking rappers 'bout to get ate up
Y'all a bunch of queers, they cheering for team Jacob
Josephine Baker, blowing green acres
Bully niggas for lunch money, I need paper
Fuck with me, is bump 50 with clean razors
And I stand the fuck out like new shorts and pink gators
Torpedo on my arm
Bitch I'm not the norm'
And I'm posted at the bar all day like I'm Norm
Clueless like a Blood in a blue uniform
And the shit I'm smoking got me seeing blue unicorns (woo)
Stunting on these niggas like I just hit the lottery
Dick in your bitch ass, like a colonoscopy
Got my GED, but I majored in philosophy
Got a minor in psychology, who's fucking hot as me?
Niggas think it's a game, cause Jarren's a monopoly
Sawed off shotgun, to break you off properly
Stand between me and my paper, like apostrophe
Give niggas lobotomies, they shittin' out colostomies
Bitches used to diss me, they ain't wanna talk to me
Jock's shoved me in the lockers cause I act awkwardly
Now I'm getting pussy like I study gynecology
The dopest nigga from the bottom, yeah bitch, I got him here

[Verse 2: 4ize]
Uh-huh, I said yeah bitch I gotta be
Blessed like the Dalai Lama
Your mama honour me
Probably, it's certified, guaranteed
Kato, Jarren B, 4ize apparently
The illest motherfuckers like 3, the hard ways
So I freestyle, getting off at freedom parkway
Okay? Is y'all pissed off yet?
Cut the check, my money long as Chris Bosh neck
With paid salary in Eric 9's art gallery
I'm a beast, with the vampire immortality
In the pale moonlight, dancing
I'm dancing, romancing fine bitches like Scarlett Johansson
Freaky sluts and tramps with these hoes
I'll show 'em what they pussy made for
Black, white, Indian, Italian, Asians and Puerto Ricans
Fucking every colour in the rainbow
My fire, flame, oh
I'm smoking on the best for a living
And sex is a given if I'm next to a pigeon
Chicken head, hood rat, googoo with a monkey
The ambassador, I do it for my country
Do it for the haters, I do it for hip-hop
Ain't nothin peewee up under my big top
I'm hard headed like a boner
Stupid like Homer (d'oh!)
With a general education diploma

[Verse 3: Laws]
Castlevanian mansion
Ring, Brady and Manson
Ballerina in the attic and the lady's dancing
80 phantoms, maybe I'm inhaling branson
And maybe I'm Bronson
Super sperm, break the condom
A hundred kids walk around with my physical structure
My older son drank 'till he made his liver rupture
My second oldest like Moses
'Cept he took two of every creature, put 'em in his freezer and he froze 'em
My brain half dead, pledge allegiance to the chosen
These hookers want my kids, caught 'em leaving with the trojan
Try and empty it with legs open
I clotheslined her in the Days Inn parking lot and now she choking
I'm laughing at the moon while I'm rapping to this tune
I will make an ass out of you if you ever assume
Configure me cause I'm using simplicity
I will fucking stab you next month, and turn the future to history
People think I'm a prophet cause I'm dressing like Socrates
Easy access, has always been my philosophy
I don't even flow, my words sit on top of the beat
Kathy Bates style, use a clock to prop up your feet
Down with the sledge hammer, call me 5-0
Dead rappers, I don't turn heads, I give neck fractures
And split heads after
Call me Jack the Rapper
You motherfuckers pitch crack, I attack the battle

[Outro: Kato]
I just got my G.E.D
So there ain't shit you can say to me
(x3)