[Intro: Shy Glizzy]
Bitch I don't need NO I.D. I'm with twenty-one
UGH!
Too trill... Nigga!

[Chorus: Shy Glizzy]
I got my dollars up and now I'm going dumb
Bitches got some followers and now they acting dumb
Bitch I don't need NO I.D. I'm with twenty-one
It's just us and twenty bitches think we on to something
I'm going dumb
I'm going dumb
Bitch I don't NO I.D. I'm with twenty-one
I'm going dumb
I'm going dumb
I told my partners grab the choppers think we on to something

[Verse 1: 21 Savage]
I left my glizzy at the house cause I was with the glizzys
Slaughter gang throw bullets around like a fucking frisbee
She got some followers but savage still not on her titty
I'm from the streets you just a rapper with a fucking image
I'm whipping a brick bitch
I pull up with sticks bitch
I pull up and bop, bop
I pull up and hit shit
I pull up in Phantoms and Ghost
I pull up and fuck on yo hoe
I pull up and kick in yo door
I still scrape the sides of the bowl
Young savage I got to get dough
I got to go get me some more
I used to pour up a latetle deuce
Now I might pour up a four
Matter fact pour up some more
Load the sticks [?] he gone
Got my dollars right [?] went dumb
Percocets and backwoods I'm gone

[Chorus: Shy Glizzy]
I got my dollars up and now I'm going dumb
Bitches got some followers and now they acting dumb
Bitch I don't need NO I.D. I'm with twenty-one
It's just us and twenty bitches think we on to something
I'm going dumb
I'm going dumb
Bitch I don't NO I.D. I'm with twenty-one
I'm going dumb
I'm going dumb
I told my partners grab the choppers think we on to something

[Verse 2: Shy Glizzy]
My niggas right behind me they got twenty guns
If a nigga play with jefe they going to hear something
I'm with a nigga baby moms we in something foreign
Bitch wasn't nothing I won't even give her twenty-one
It's getting lit told my niggas that it's time to slide
What you going to do if a nigga ask you, you going to ride
Right in your eyes, are you a G or you a lie?
Bop, bop somebody died here come homicide
Gang leader
I'm drinking lean out the liter
Posted up with my heater in a white beater
Glizzy gang, slaughter gang, we'll come through squeezing
See you on a Instagram well I already cheated

[Chorus: Shy Glizzy]
I got my dollars up and now I'm going dumb
Bitches got some followers and now they acting dumb
Bitch I don't need NO I.D. I'm with twenty-one
It's just us and twenty bitches think we on to something
I'm going dumb
I'm going dumb
Bitch I don't NO I.D. I'm with twenty-one
I'm going dumb
I'm going dumb
I told my partners grab the choppers think we on to something