[Verse 1: Johnny Venus]
A'ight ho, that's your cue to go
That ass is fat and we love that but this the studio
You be walkin' past them knobs, booty fuckin' up them lows
Plus they gotta hear that bass so they won't play me in the eight

[Hook: Johnny Venus]
Like wah-wa-la-la, that pussy feelin' great
I ain't never been to L.A. anyway, where them freakers stay?
She said, "Allah, now don't lead me astray"
Everything just look so crazy up here baby
Wait, wait, wait, wait, wait, wait

[Verse 2: Doctur Dot]
Mom's at the crib performing spiritual Tae Bo
Holy Billy Blanks, let's karate chop and breathe
I'ma prolly start the D, having honest conversations
With God, regardless if he give a fuck 'bout what I say
Before you shrug your shoulders, wait, 'cause I know you don't care
I know you thinking, "Why this nigga feel the need to go there?"
Is it because my nerd eye turned a third eye or eleventh, twelfth?
I guess whatever sounds the best
I bet Lisa Left Eye knew while leaving Best Buy
The camera she purchased would be capturing her last night
What about me? What if I died? Leave the booth tonight
Drunk driver don't even notice my headlights
Damn, damn, damn, damn, damn, damn, damn, damn, damn
Just thinkin' about it'd make me shake
And I pray that ain't the case but if occasion turns to fate
Maybe you silly niggas'll listen to what I say
Die and become a legend, a legend is where you stay in the cerebellum of niggas
Steady bumpin' your tape in rotation with Marvin Sapp, Zapp & Roger, Marvin Gaye
Gaze into the eyes of Satan and she told me it's okay
And presented me with the option to talk or just walk away
And I left and ever since she been textin' me everyday and it's cool
But Lord protect me when the temperature change
The temptation and palpitation in my heart is insane
I tried to sit and calculate how many "no's'" it would take
Before my nose was wide open and I'm all in her face
Yeah I struck out swingin', but I'm all in your base
With ghostman on third, like nobody would play

[Hook: Johnny Venus]
Like wah-wa-la-la, that pussy feelin' great
I ain't never been to L.A. anyway, where them freakers stay?
She said, "Allah, now don't lead me astray"
Everything just look so crazy up here baby
Wait, wait, wait, wait, wait, wait

[Verse 2: Johnny Venus]
When every record that you put out, got them throwin' they tush out
Pray they play it at cookouts, got the whole city shook now
People talkin' like, "Look now, I told you that they gon' make it"
Them same niggas that hated got you all up in they playlist
'Cause the world concentratin', the crucial contemplation
You two-steppin' with these heffers, I'm receiving revelations
You twirlin' in girls, I'm swimming in women who curl up like curls
Body remind me of some thoroughs that I used to ride back in Seaside
She know I'm tryna quit, but see she my bad habit
Nice to meet you I had it
We got features, y'all got snips
Bought casinos, y'all bought chips
Y'all ain't seen nothin' like this
I dip my paint brush in a bucket like fuck it and get some mo'
See all I know is the foreman, yeah he from Campbellton Road
I know y'all ain't been told
I made it, waited, weighed it flew this shit in from the '80s
Distribution conducted by all of my lovely ladies
I promise I ain't budgin'
I promise I ain't make it 'til I'm rakin' in a 100k a month and that ain't nothin'
Half of that stashed into something I ain't touchin'
After that smashed into somethin' I ain't lovin'
After my first meal, "What you buyin?", I say, "Nothin'"
Relocate into the jungle, paradise in the bungalow
I finally got some diamonds in my wrist
My nigga Yoda finally got some ice off in this bitch
Finally I might even get off this hype of ghetto trip
Syringe steel stickin' out my Benz, still picking out my friends
Speed datin' with my ends, it's a cinch
You'd think they huntin' DAs they way we hopped up off the fuckin' bench
I heard one is from the S.W.A.T.S., you know the other one is too
It's crazy how all the shit we say start to come true
Countryside with my boo, hoppin' out that ooh
Searchin' for our papers, man I pray they let us through
We got babies waitin' mouths to feed, that teacher too
You can call it what you want, I just call the shit the truth
Never steppin' in the booth unless it's for the right quota
These be desperate measures take it right back to the coder

[Hook: Johnny Venus]
Like wah-wa-la-la, that pussy feelin' great
I ain't never been to L.A. anyway, where them freakers stay?
She said, "Allah, now don't lead me astray"
Everything just look so crazy up here baby
Wait, wait, wait, wait, wait, wait

[Outro]
I'm on molly, I can handle anything