[Hook: French Montana & Fabolous]
Money make the rules, Bad bitches get to choosin'
Talk about that money, All my niggas make a movie
Bitch I seen them tricks before, Fuck outta here
Nigga I seen yo type before, Fuck outta here
Them niggas said we can't what? Fuck outta here
Them bitches said they don't what? Fuck Outta here
Bust it(5x), Wide open
Bust it(7x), Wide open

Money make the rules, Money money make the rules
Fuck Outta here(2x)

[Verse 1: Fabolous]
You don't make no money you don't make no rules either
Real niggas gettin' money that's the fools beefin'
Rule number one never tell a chick you need her
Number two she should never bite the dick that feed her
Don't make me introduce ya bitch to this fly shit
Have her callin' yo shit my shit
Give her dick, And maybe somethin' nice
The head off the chain, Jesus Christ
My company is loyal, Hoes is bad for business
My lil' homie bust the 40 like Cain in Menace
Never mind a hater, Hater on my mind never
Stop flexin' nigga you was hot in 97

[Hook]

[Verse 2:French Montana]
Money make the rules, All my niggas make the movies
Once them bitches choose she bust it open like a uzi
Shoes 2 thou a pair,And that clearport I'm there
You won't get none of this money, But these hot shells I share
And I live by them houses, That's right by them mountains
I just caught that lick, took me 3 days to count it
Them bitches they love it, Bunch of young niggas thuggin'
I don't be askin' no questions, I just tell her go bust it
Like wide open, All my niggas gettin' high smokin'
If you hatin' eat a dick wit yo eyes open
Montana Oscar Rob nigga
That's like 2.5 in that garage nigga

[Hook]